### ISSUE TITLE
BBC Three Programs

### ISSUE THREAD

**Issue by websteth** [Ascoware/get-iplayer-automator#10]
Has anyone else had an issue searching or setting PVR for BBC Three programs? It seems that the only way to really download these is using the "Use Current Webpage" option and sometimes that doesn't seem to capture it. Just curious. Thanks to everyone who has contributed.

**Comment by botchla** [comment]
Because it uses the BBC schedule to know what to download, BBC Three is excluded - I have the same issue and use the current webpage option.

**Comment by websteth** [comment]
Makes total sense. I thought it might be something like that.

**Comment by skovatch** [comment]
Correct, there is no longer a way to get just the BBC3 listings since the channel is online only.
