### ISSUE TITLE
Downloading Autodescribed Versions from BBC - how do I stop it?

### ISSUE THREAD

**Issue by darfielddx** [Ascoware/get-iplayer-automator#101]
I am using GiA 1.9.13 and MacOSX 10.13.2

I have been download McMafia from the BBC and when I go to watch it, it is the auto-described version. I have not ticked this option in preferences. Is there any way I can avoid getting this version as I find it really annoying!

Any help or advice would be appreciated.
---------------

**Comment by skovatch** [comment]
You could try resetting the preferences back to the defaults.

**Comment by jchhenderson** [comment]
Hi darfielddx - I also don't have this issue when downloading McMafia.  I did have to totally uninstall and re-install the app because of other issues (all of which went away after doing so).

**Comment by skovatch** [comment]
Closing as not reproducible. If you see it with another show let me know and I'll try to catch it again.
