### ISSUE TITLE
Enhancement Request - Remove Programmes from PVR or Add TV Programmes to History

### ISSUE THREAD

**Issue by jasowt** [Ascoware/get-iplayer-automator#103]
The problem is most annoying when downloading Match of the Day. Currently have "Match of the Day: Series 2017-2018: 23/12/17"; "Match of the Day: Series 2017-2018: 26/12/17"; "Match of the Day: Series 2017-2018: 30/12/17" all sitting in download queue. Won't download as they were on a long time ago and no way to remove them permanently from PVR without deleting Match of the Day itself.

Also, it'd be nice if Match of the Day only came on the PVR when it was actually available. Saturday's entry on iPlayer comes up on Saturday night but only is available from Monday morning. Same situation with MoTD 2 coming online Tuesday. Not a massive problem, but it'd be nice to iron out.

Using latest GiA on latest OS X.

**Comment by jchhenderson** [comment]
I also have this problem where some episodes (not MOTD) appear in the download queue when the are not actually available on BBCi.  The BBCi website is always correct - if it shows up there, it really exists and can be downloaded.

Conversely, some episodes show in the BBC website as available to download but do not show in the queue - so I have to recheck everything manually and then use the <cmd><g> function to force it into the queue (so as not to miss an episode in a series).

using latest GiA 1.9.14 and OSX 10.13.2, but think the problem was in v1.9.12 (I only downloaded the latest release yesterday so need to check if problem persists or not).

**Comment by jchhenderson** [comment]
...I should add that this app is fantastic - thanks for making it happen! :-)

**Comment by WilliamOfGaunt** [comment]
My own experience is that episodes can appear in the download queue when they 
aren't available on iPlayer, but only when I do a Force Cache Update while the 
programme is still being broadcast. I just have to remember to wait!

**Comment by jchhenderson** [comment]
OK, yes, this still happens in v1.9.12

In this case "Dragons - Race to the edge - 11.  A Time to Skrill" (aka Dragons s04e11) which was on TV yesterday, is in the BBCi Player but not in the download queue (and not in my history).

will try the Force Cache Update - thanks, William!

**Comment by jasowt** [comment]
Thanks for the tip @WilliamOfGaunt, although doesn't appear to work for MoTD. Still coming up in download queue. Still get http://www.bbc.co.uk/programmes/b09kpg6t for example, even though not on iPlayer.

**Comment by WilliamOfGaunt** [comment]
@jasowt - Using "--PID=b09kpg6t" also doesn't find a programme in the Windows version of get_iplayer (admittedly a slightly old version, which I should update!). This suggests that the issue lies with get_iplayer rather than GIA.

**Comment by jchhenderson** [comment]
@jasowt - As I am on a Mac like you, I tried MOTD 23/12/17 after forcing a cache update - didn't work for me either (cmd-g did force it into the queue though).

**Comment by sleaux-meaux** [comment]
Use the "Permanently Skip Selected Series-Link Entries" button to force unavailable programmes into the download history so they don't get re-queued.

**Comment by jasowt** [comment]
Maybe I’m being stupid but I can’t see this on GiA?

**Comment by jasowt** [comment]
Yes, I was being stupid! Just seen at bottom!!

**Comment by jchhenderson** [comment]
you've closed this but what you have is a workaround.

...Isn't the problem of the download queue mismatching the BBCi website is still there?

**Comment by sleaux-meaux** [comment]
The get_iplayer documentation warns you that a few unavailable programmes may show up in search results because they expire sooner than 30 days, but get_iplayer can't discover that during indexing. What goes for get_iplayer goes for GiA.

**Comment by jchhenderson** [comment]
@sleaux-meaux - got it thanks.

I just need to confirm that cache-updates fixes the reverse-problem then.

cheers.

**Comment by jasowt** [comment]
@jchhenderson I initially only wanted a workaround (I just hadn't seen that button), as @sleaux-meaux says - underlying problem seems to be with get_iPlayer rather than GiA itself so can't be fixed.

Unsure on GitHub etiquette (first time), shall I reopen the post? Actual enhancement request in post was already included in GiA.

**Comment by jchhenderson** [comment]
@jasowt no need to re-open (thanks for asking).  I'll shout if the problem persists & will cross-reference with get_iplayer first and post there if necessary.

**Comment by jchhenderson** [comment]
yup, doing a force-cache-update fixes this for me.
