### ISSUE TITLE
PVR getting deleted - Queue.automatorqueue

### ISSUE THREAD

**Issue by jefro108** [Ascoware/get-iplayer-automator#104]
[Queue.automatorqueue.txt](https://github.com/Ascoware/get-iplayer-automator/files/1665053/Queue.automatorqueue.txt)
It appears that when a crash is intercepted by MacOS High Sierra and if I allow the program to crash and send a message to Apple that the PVR gets deleted - the file Queue.automatorqueue in the Get iPlayer Automator folder in Application Support.

I've been trying with Time Machine to restore the settings to a time before the crash (and replace the download_history so that I don't download programmes twice, but each time I have done so and start up GIA the PVR gets deleted again.

I've solved similar problems in the past by 'going back in Time' but it's a mystery why it's not working this time.

Attaching a copy of the PVR file.

**Comment by sheepworrier** [comment]
Same issue here.  My PVR queue has been deleted.  I added it manually and restarted the app and it was empty again.

**Comment by the-saint** [comment]
This has been happening to me for weeks. It starts with a specific episode of an ITV programme that won’t download and produces an unable to download file error message. When this occurs, the next time I open GiA, my PVR programmes are gone. I tried restoring the file from Time Machine but that didn’t work.

**Comment by jchhenderson** [comment]
Yes, I has this too.  It went away after I uninstalled/re-installed and remade the queue.

...I tried restoring first - didn't help.  I tried restoring after a re-installed, also didn't help.  Only a fresh install worked.

**Comment by jchhenderson** [comment]
...just happened to me again last night (has been a while).  This time restoring Queue.automatorqueue did work...

**Comment by skovatch** [comment]
What is going on that causing the app to crash? If I fix that then you shouldn't need to restore from a backup.

**Comment by the-saint** [comment]
I attempted to download a programme from ITV. The particular episode wouldn’t download. I got a generic error message, and if I’m not mistaken, the log said there was no format selected. Other episodes of that programme downloaded without incident, but no matter how many times I tried to download that episode, it wouldn’t download. The aftermath was that the next time I opened GiA, my PVR list was gone. This happened every time I ran into this particular problem. It occurred on two or three occasions, always precipitated by a single episode of an ITV programme that refused to download.

**Comment by skovatch** [comment]
Okay, I think I see the problem... bad Obj-C technique on the part of my predecessor :-) I will post a new version in the next day or two.

**Comment by the-saint** [comment]
Curse the pumpkin. : )

**Comment by the-saint** [comment]
Shite. It just happened again.

**Comment by skovatch** [comment]
Fixed in v1.10.0

**Comment by the-saint** [comment]
It is fixed. But why are the programmes failing to download?

Get iPlayer Automator 1.10.0 Initialized.


INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used
GetITVShows: ITV Cache Update Starting 
AppController: Updating Programme Index Feeds...

GetITVShows (Info): Merge complete B/F Programmes: 1382 C/F Programmes: 1357 Today Programmes: 160 
AppController: Index Updated.
GetITVShows: Update Finished


INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used
AppController: Starting Downloads


Downloading Show 1/2:

ITV Download (ID=2/4269/0010#002): Downloading Marcella - Series 2 - Episode 2 - 2/4269/0010#002
INFO: Preparing Request for Auth Info
INFO: Requesting Metadata.
ITV Download (ID=2/4269/0010#002): ERROR: None of the modes in your download format list are available for this show. Try adding more modes if possible.

Downloading Show 2/2:

ITV Download (ID=2/4037/0016#001): Downloading The Cruise - Series 3 - Episode 4 - 2/4037/0016#001
INFO: Preparing Request for Auth Info
INFO: Requesting Metadata.
ITV Download (ID=2/4037/0016#001): ERROR: None of the modes in your download format list are available for this show. Try adding more modes if possible.
AppController: Downloads Finished

**Comment by hugofalkman** [comment]
@the-saint For both downloads that’s issue #95.
