### ISSUE TITLE
program type '' not recognised

### ISSUE THREAD

**Issue by rbnpi** [Ascoware/get-iplayer-automator#105]
using Mac OS 10.11.6 with gia 1.9.14
get following log entry

Downloading Show 1/1:

BBC Download (ID=b09kp6xr): Downloading New Year's Day Concert - Live from Vienna 2018
ERROR: Programme type '' does not exist
BBC Download (ID=b09kp6xr): Unknown: PID Not Found Failed
AppController: Downloads Finished

Same for other pids eg

INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used

Downloading Show 1/1:

BBC Download (ID=p05pkszd): Downloading McMafia - Series 1: Episode 1
ERROR: Programme type '' does not exist
BBC Download (ID=p05pkszd): Unknown: PID Not Found Failed
AppController: Downloads Finished

**Comment by skovatch** [comment]
Two suggestions, easy one first: try clicking "Restore Defaults.." from the preferences screen, then download something again.

That should make things better, but if that doesn't help, quit the application, and go to "~/Library/Application Support" in the Finder. Look for a folder named "Get iPlayer Automator". Rename it to something like "old Get iPlayer Automator", then run the application again. It will rebuild your cache.

**Comment by rbnpi** [comment]
Thanks a lot
All sorted when I deleted the Application Support Get iplayer folder.
Your fast response much appreciated.
