### ISSUE TITLE
Return of Invalid Page message

### ISSUE THREAD

**Issue by MacMuser** [Ascoware/get-iplayer-automator#108]
Since 22/2/2018 unable to add individual BBC radio programmes to the Download Queue by opening iPlayer in Safari or Chrome and clicking on a radio show. It results in the usual Invalid Page dialogue box, "Please ensure the frontmost browser tab is open to an iPlayer episode page or ITV Hub episode page." Using the PVR still works but only for programmes or series that have been or have started being aired.

*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*
Open GiA, open BBC iPlayer in Safari
Select (for example) Radio 4 or Radio 4+
Select one of today's radio shows and open its page in Safari
Click on Use Current Webpage in GiA

*What is the expected output? What do you see instead?*
Programme's name added to download queue
Result is Invalid Page dialogue box, "Please ensure the frontmost browser tab is open to an iPlayer episode page or ITV Hub episode page."

*What version of GiA are you using? On what version of OS X?*
Version 1.9.14 (20180115003)
10.13.3 (17D102)

*Are you using a web proxy? DNS proxy? VPN? VPS?*
no

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *
https://www.bbc.co.uk/programmes/b00r32wz
Falco Iron Hand of Mars episode 5

*Please provide any additional information below.*

This is occurring on two Macs running same Sytem and version of GiA

**Comment by sleaux-meaux** [comment]
As a workaround, load the "http:" version of the URL instead of the "https:" version. It looks like GiA needs to be updated to handle both versions for BBC radio programmes.

**Comment by MacMuser** [comment]
Hi sleaux-meaux

Thanks, that’s a good tip. Have passed it onwards.

BTW I used to drink Friary Meaux bitter in years gone by. No relation presumably, just like I don’t have with Tennents brewery.

Mark

**Comment by MacMuser** [comment]
Thanks that's a good tip which I have passed onward.
