### ISSUE TITLE
Downloads being incorrectly labelled as failed

### ISSUE THREAD

**Issue by JeremyCavanagh** [Ascoware/get-iplayer-automator#11]
[GIA-partial-log.txt](https://github.com/Ascoware/get-iplayer-automator/files/986856/GIA-partial-log.txt)

What steps will reproduce the problem? Be specific, and provide as much detail as possible.

Just select program from the iplayer using "Use Current Webpage"

What is the expected output?

At the moment, with fingers crossed and a following wind, a successful download. 

What do you see instead?

What happens is a successful download, but, every time the file is marked "failed" and a notification indicates the same.

What version of GiA are you using? On what version of OS X?

GiA : Version 1.9b2 (1821)
OS X : 10.11.6

Are you using a web proxy? DNS proxy? VPN? VPS?

DNS : Smart DNS Proxy

What programme are you attempting to download (full title, series and episode)? **Provide only ONE programme as an example. DO NOT list multiple programmes.**

Hetty Feather - Friends and Enemies Forever: Series Preview

I have included the relevant portion of the log file as an attachment. Although, I may have cocked it up and added twice. Apologies if I have.

**Comment by skovatch** [comment]
Thanks for the log... I'll try with this show and see what happens. Looks like get_iplayer takes a different path when it completes this show.

**Comment by JeremyCavanagh** [comment]
This problem appears to be solved. However, there is now a new problem, I shall open a new issue.
