### ISSUE TITLE
RETRIEVE CHANNEL 4 PROGRAMS?

### ISSUE THREAD

**Issue by mark-gaucher** [Ascoware/get-iplayer-automator#117]
I am aware that it was once possible to retrieve C4 programs many moons ago.  I wonder if anything has changed at channel 4 to enable programs to be downloaded once more?

**Comment by skovatch** [comment]
As much as I would like to support it, since I like Countdown now and then, this won't happen. Channel 4 uses digital rights management on its shows, so it's not possible.

**Comment by mark-gaucher** [comment]
Thanks for your time.



Mark

On 9 Mar 2018 04:48, Scott Kovatch <notifications@github.com> wrote:

As much as I would like to support it, since I like Countdown now and then, this won't happen. Channel 4 uses digital rights management on its shows, so it's not possible.
