### ISSUE TITLE
"Use Kodi (XBMC) Naming:" not removing underscores

### ISSUE THREAD

**Issue by Duffledorf** [Ascoware/get-iplayer-automator#12]
**What steps will reproduce the problem?** 
I have run the same show through twice with the "Use Kodi (XBMC) Naming:" option off and then on;
both options produce filenames with underscores in folders with underscores.

**What is the expected output?** 
Previous versions of GiA removed the underscores

**What version of GiA are you using? On what version of OS X?**
GiA - 1.9b2 on macOS Sierra V:10.12.4

**Are you using a web proxy? DNS proxy? VPN? VPS?**
No; No; No; No

**Log of example download:**

**_With Kodi Naming off:_**

[naming off.txt](https://github.com/Ascoware/get-iplayer-automator/files/989557/naming.off.txt)

**_With Kodi Naming on:_**

[naming on.txt](https://github.com/Ascoware/get-iplayer-automator/files/989558/naming.on.txt)

**Comment by Duffledorf** [comment]
This issue was also noted by @nigelbb (in 1.9b1 app download link in here #1) while @Themanwithoutaplan reported it working correctly for him.

**Comment by mutantcamel** [comment]
Think this means that the --whitespace option needs to be added to the get_iplayer script.

**Comment by skovatch** [comment]
get_iplayer now requires an extra argument '--whitespace' to prevent it from changing whitespace to underscores. I'll add that back to match what it was before.

I suspect the other report is either in error or he's using it from Terminal.

**Comment by skovatch** [comment]
Fixed in 1.9b3
