### ISSUE TITLE
No ITV download

### ISSUE THREAD

**Issue by nrj53** [Ascoware/get-iplayer-automator#122]
GIA 1.10.1 would not let me import the open page from the browser.
GIA 1.10.2 will import the page but then goes back to the problem where I get download failure that states I do not have a relevant format entered, although I have all 4 of the available ITV formats in preferences.  Same as the problem just before 1.10.0 started to crash on opening.  I have been trying to download the latest episode of Endeavour from the March 11th. using a Mac.  Everything had been perfect until the past 8-10 days, suggesting ITV are doing something with ITV player.

**Comment by hugofalkman** [comment]
Please close this as duplicate of issue #95.

You are causing Scott extra work by opening duplicate issues of known problems.

You are also spamming all of our input baskets.

**Comment by nrj53** [comment]
Sorry.  Obviously not intended to annoy.
Just to let people know that it continues with GIA 1.10.2, which would not be known from the issue#95 entires.
