### ISSUE TITLE
BBC iPlayer says "invalid page" when using 'use current webpage'

### ISSUE THREAD

**Issue by whitedb** [Ascoware/get-iplayer-automator#123]
Having experienced the crashes reported previously, I am using version 1.10.2 and am located in the UK using a normal connection.  Issue seen under Sierra and El Capitan.

When I select "Use Current Webpage" on an iPlayer page I get the invalid page error and Please ensure the frontmost browser tab is open to an iPlayer episode page or programme clip page.

         Invalid Page: https://www.bbc.co.uk/programmes/b009szrh/episodes/player

Interestingly, the page reported is not the one I am on.  If I select the PID from the page I want and manually enter it then the program is found and the download works.

I have seen recent reports of this problem for iTV but not for BBC.  The problem occurred with Radio and TV programs.

**Comment by whitedb** [comment]
Umm, carried on working on this and tried quitting safari and re-launching.  GIA now seems to work....

**Comment by skovatch** [comment]
This will happen if you have multiple BBC show pages open in different tabs, or have a BBC show page open but not in the front most tab. I suppose it could be cleaner by checking just the frontmost tab of the frontmost window, but I'm not sure you can get that information from the code that scans tabs.

**Comment by makpufterpup** [comment]
I'm getting this now, though it has previously been working.
For example, Versailles episode 10 The Legacy
`Invalid Page: https://www.bbc.co.uk/programmes/b0bfk71y`

**Comment by makpufterpup** [comment]
Other things I've found.

This only shows an error when trying to add the program from the programs page website, example: https://www.bbc.co.uk/programmes/b04fqq62

But not from the iPlayer website: https://www.bbc.co.uk/iplayer/episode/b04fqq62/cuckoo-series-2-4-funeral

It used to add it from the Programs page.

The feautre works and adds the pids fine from the ITV website.

**Comment by skovatch** [comment]
I'm guessing that the format of the program page or URL changed. Thanks for the non-iPlayer URL; I see those URLs in the code but couldn't figure out where they came from. I'm rewriting the getCurrentWebpage code so that it walks through the frontmost tab of the windows, front to back, so I should be able to fix both issues.

**Comment by skovatch** [comment]
Fixed in v1.13.14.
