### ISSUE TITLE
Use get_iplayer's call-through to AtomicParsley

### ISSUE THREAD

**Issue by skovatch** [Ascoware/get-iplayer-automator#127]
get_iplayer supports tagging of BBC radio and TV programs via AtomicParsley. GiA can also tag radio and TV shows, but there's no need for it to happen with BBC content. We should just let get_iplayer do it.

This doesn't apply to ITV content, of course. But I can simplify the code a bit by using what's already in place.

**Comment by sleaux-meaux** [comment]
It already works that way for BBC programmes. GiA has never tagged BBC downloads directly, at least not in the 5+ years I have used it. All that post-processing in Download.m is only used for ITV.

**Comment by skovatch** [comment]
Okay, I see that now with the verbose mode flagged. I may add some of the arguments to the ITV processing for completion, in that case.
