### ISSUE TITLE
Be great to have srt subtitles on ITV programmes

### ISSUE THREAD

**Issue by jefro108** [Ascoware/get-iplayer-automator#128]
Be great to have an option for srt subtitles on ITV programmes

youtube-dl can automatically convert the vtt subtitles to srt with the `--convert-subs=srt` option and ffpmeg converts with `ffmpeg -i CwmtkFPYXsg.en.vtt CwmtkFPYXsg.srt`

Thanks so much for fixing all the ITV download problems!

**Comment by skovatch** [comment]
That's helpful, thanks! We can us that instead of the ttml2srt script.

**Comment by skovatch** [comment]
Fixed in 1.11.1.
