### ISSUE TITLE
GiA 1.11: ITV HLS download mechanism slow and produces poor output

### ISSUE THREAD

**Issue by sleaux-meaux** [Ascoware/get-iplayer-automator#129]
The ffmpeg command introduced in GiA 1.11 to download ITV HLS streams forces the media to be transcoded using default parameters. This is slower and more CPU-intensive than remuxing (which is all that is needed) and results in a file of lower bit rate and video quality than the original.

**Comment by skovatch** [comment]
If you have better parameters to pass to ffmpeg for downloading please submit a pull request or post them here.

**Comment by jefro108** [comment]
eg `ffmpeg -i itvprog.flv -codec copy itvprog.mp4` see https://askubuntu.com/questions/50433/how-to-convert-mkv-file-into-mp4-file-losslessly?answertab=active#tab-top

I just downloaded the Marcella episodes that hadn't been possible with GiA previously and although the flv files are downloaded which are the best quality files I believe I ended up with rather poor quality results.

**Comment by jefro108** [comment]
Actually that's not correct for HLS stream - see https://stackoverflow.com/questions/33108105/converting-an-hls-m3u8-to-mp4?answertab=active#tab-top

`ffmpeg -i in.m3u8 -acodec copy -bsf:a aac_adtstoasc -vcodec copy out.mp4`

**Comment by jefro108** [comment]
Just downloaded Marcella s02e04 https://www.itv.com/hub/marcella/2a4269a0012 with version 1.10.2  and it first downloads the flv file before converting to mp4 and produces a decent quality file of 534.2MB with a video Bit rate | 1 443 kb/s

Version 1.11.0 produces a file only of 167MB  with a Bit rate | 350 kb/s

**Comment by rabrowne** [comment]
Mmmm, I agree, just successfully downloaded Marcella s02e05 with Version 1.11.0 and resulting file is 164MB instead of the usual 500+ MB!

**Comment by sleaux-meaux** [comment]
You'll need to wait until 1.11.1 is actually released. It looks like he forgot to upload the new build (see #131). I've built it myself and I can verify that the ffmpeg command has been fixed and the video quality of the media stream is preserved.

**Comment by sleaux-meaux** [comment]
I should also add that you may not get quite the same quality as before. From what I can see, ffmpeg picks out a variant with the larger of two video resolutions available, but not the highest bitrate for that resolution, so the resulting file won't be quite the same as what you could have gotten in previous releases.

**Comment by skovatch** [comment]
Oops. I basically fell asleep after I built and tagged it last night. It's updated now.

**Comment by jchhenderson** [comment]
no worries!!  ...we truly appreciate everything you are doing! :-)
