### ISSUE TITLE
GiA 1.11: ITV WebVTT subtitles deleted after download

### ISSUE THREAD

**Issue by sleaux-meaux** [Ascoware/get-iplayer-automator#130]
GiA 1.11 processes ITV WebVTT subtitles through the TTML->SRT conversion script (which of course results in an empty .srt file), then deletes the original file, leaving no subtitles for playback. I tried the March 14,16,19 episodes of Coronation Street, and this behaviour was consistent. The logic in Download. subtitlesSavedTo() appears to need updating so the converSubtitles() isn't called for a .webvtt file (or a conversion implemented). A potential remedy was suggested in #128. Failing that, it would help to just retain the WebVTT file unconditionally.

In the interim, anyone having the same problem can retain the WebVTT subtitles by setting an item in GiA's preferences from the command line:

    defaults write com.ascoware.getiPlayerAutomator ITV_KeepRawSubtitles -bool true

I deduced this from reading the relevant bits of code, so not an obvious approach, but it seems to work. You still get an empty .srt file.

**Comment by skovatch** [comment]
Fixed in v1.11.1.
