### ISSUE TITLE
1.11.0 crashes after updating ITV indexes

### ISSUE THREAD

**Issue by jchhenderson** [Ascoware/get-iplayer-automator#131]
HI Guys

I **really** appreciate everything that is going on right now and all the effort going into address ITV, but having updated to v1.11.0, I get a crash immediately after updating the ITV indexes with the following message:
> Application Specific Information:
> *** Terminating app due to uncaught exception 'NSGenericException', reason: '-[NSAlert runModal] may only be invoked from the main thread. Behavior on other threads is undefined.'
> terminating with uncaught exception of type NSException
> abort() called

I can see that there is a 1.11.1 bug fix release, but not sure whether it addresses this particular issue and I am unable to update to it as it fails fails with the message:
> An error occurred in retrieving update information. Please try again later.
...perhaps this is because I can never get past the indexing though?

There appears to be no .zip link on Git to download v1.11.1 either.

thanks!

**Comment by skovatch** [comment]
Yeah, I think that's the problem. I updated the branch that tracks the releases, but forgot to actually attach the binary.

**Comment by skovatch** [comment]
I suspect the NSAlert problem wasn't fixed, though. I'll have a look at that soon -- it's likely because the app wasn't able to get to ITV.com for whatever reason.

**Comment by jchhenderson** [comment]
Hi Scott - I can confirm both problems (update and crash) are fixed in v1.11.1 - awesome!

**Comment by skovatch** [comment]
Huh -- I didn't specifically try to fix the crash, so it's probably still lurking in there somewhere. Was there a backtrace or crash log?

**Comment by jchhenderson** [comment]
Scott - I closed this before reading your reply re NSAlert as the crash no longer occurs in v1.11.1 - Are you OK with that?

**Comment by jchhenderson** [comment]
I cannot see any logs in \library\logs or \library\Application Support\Get iPlayer Automator.

Where can I find them?

**Comment by skovatch** [comment]
Look in /Library/Logs/DiagnosticReports. It's slightly easier to use Console.app, but you can use Terminal, too.

**Comment by jchhenderson** [comment]
done.

**Comment by jchhenderson** [comment]
v1.11.2 crashes as well
> Application Specific Information:
> *** Terminating app due to uncaught exception 'NSGenericException', reason: '-[NSAlert runModal] may only be invoked from the main thread. Behavior on other threads is undefined.'
> terminating with uncaught exception of type NSException
> abort() called

[Get iPlayer Automator_2018-03-21-084509_James-MacBook-Pro.crash.txt](https://github.com/Ascoware/get-iplayer-automator/files/1832494/Get.iPlayer.Automator_2018-03-21-084509_James-MacBook-Pro.crash.txt)

**Comment by jchhenderson** [comment]
interestingly, going back to v1.11.1 does not solve this (it worked last time).

J.

**Comment by jchhenderson** [comment]
..but going back to 1.10.2 and then updating directly tho 1.11.2 overcame it - but I suspect the underlying cause is still there...

**Comment by jchhenderson** [comment]
nope - it came back again.  ...nothing after 1.10.2 works for me.

**Comment by jefro108** [comment]
I renamed the Get iPlayer Automator folder in Application Support and opened 1.11.2 which created a new Get iPlayer Automator folder. I copied in the `download_history` and the `Queue.automatorqueue` (which contains the PVR details) files and all is now well. No more crashes! 😊

**Comment by jchhenderson** [comment]
I uninstalled/re-installed having copied the `download_history` and the `Queue.automatorqueue`first which I then copied back.

...I think your way was more intelligent! :-)

**Comment by compulsivebuyer** [comment]
jefro108 this worked form me, thanks very much

**Comment by skovatch** [comment]
v1.12 calls NSAlert if needed on the right thread. Hopefully it isn't necessary anymore.
