### ISSUE TITLE
ITV more compressed

### ISSUE THREAD

**Issue by enkidus** [Ascoware/get-iplayer-automator#132]
Firstly, thanks for all your hard work keeping this running.

Since updating to your latest release (1.11.1) I've finally managed to download the last episode of the 5th series of Endeavour (5:6 Icarus) which is great.  However I noticed that this has far more compression artefacts than the other 5 episodes in the series and is 2/3rds its size ~600MB instead of typically 900MB for the others.  After re-downloading one of the others in this series (5:5 Quartet), using the HD option as the only one available, I found that it also came in now at ~600MB and is noticeably poorer in quality than the original download from a month ago.
Is this something ITV have changed or is Get-ipayer-automator now using a harder compression algorithm?

Thanks again for your continued hard work keeping this going

**Comment by sleaux-meaux** [comment]
You're not getting the file with the highest bit rate available. To be brief, ffmpeg has some limitations as an HLS downloader. GiA would need further improvements to parse out the various HLS streams and provide a way to specify the best available. get_iplayer already does that for BBC programmes, so this is purely an ITV-related issue.

If it's important to you, you can use youtube-dl as a workaround to get a higher bit rate download. Turn on verbose mode in GiA and when downloading begins for an ITV programme you will see the HLS playlist URL in the line marked with "ffmpeg args". Stop your download and copy that URL for use with youtube-dl. It will also utilise ffmpeg, but will feed it the stream with the highest bit rate in the playlist. I suggest using `-o example.mp4 `to give the output file a more readable name and `--external-downloader-args='-loglevel error'` to avoid a load of warnings from ffmpeg being printed.

**Comment by skovatch** [comment]
I noticed that the JSON response after getting the streamable playlist has provisions for multiple URLs for the video content but in my testing never saw a show with more than one option. I'll try with Endeavour; maybe it has more choices.

On the plus side, it might provide a way to get the ITV show quality working again. I really don't want to implement both types of download (RTMPDump and HLS streaming)

**Comment by sleaux-meaux** [comment]
For all the programmes I've looked at, the variant playlist for each one had 5 video streams and 1 audio-only stream available. The best video quality I've seen is 896x504 and around 1500kbps. They may have better quality for IPTV services, but I don't have any way to check that.

**Comment by enkidus** [comment]
The original ITV downloads of Endeavour were 896×504 at ~1400kbps whereas they are now coming in at 896×504 at ~870kbps.
Hope this helps...

**Comment by skovatch** [comment]
Based on what youtube-dl is doing, I don't know if I can do anything else here. While youtube-dl can tell you all of the available streams, it ends up passing the main m3u8 URL off to ffmpeg.

**Comment by sleaux-meaux** [comment]
Not true. Run youtube-dl with --verbose  and you will see it is doing more than that.

**Comment by jchhenderson** [comment]
...not sure if this helpful, but if you run Downie with post-processing set to "none" (my default was "convert to .mp4") - you still get an .mp4 but with a higher bitrate than iPlayer does (or did).

**Comment by skovatch** [comment]
Fixed with v1.12, which uses youtube-dl as its ITV engine.
