### ISSUE TITLE
v1.11.2 - "ITV Player" is now "ITV Hub"?

### ISSUE THREAD

**Issue by jchhenderson** [Ascoware/get-iplayer-automator#135]
This may not be a bug, but people might like to know...

I noticed that some TV is no longer being added from the PVR.  So I removed / re-added one (Lewis) and realised that the _TV Network_ is now called "ITV Hub" (was "ITV Player").

It then worked, but my download history was lost (I guess because it works by matching both _TV Network_ and _Show_. 

...re: #131, I removed/re-installed GiA from scratch and then recovered download_history + Queue.automatorqueue to try to overcome the crash.

**Comment by skovatch** [comment]
Rolled it back just to be safe in v1.12, though eventually it shouldn't matter.
