### ISSUE TITLE
Possible to download highest quality ITV programme version?

### ISSUE THREAD

**Issue by jefro108** [Ascoware/get-iplayer-automator#136]
Some of ITV programmes still have FLV versions that can be downloaded with youtube-dl, which are higher quality than the HLS streams. 

Is it possible for GiA to find these and download them (and remux them as mp4) in preference to the HLS streams of the latest version (ie go back to the old way of downloading for those programmes)?

**Comment by skovatch** [comment]
I was really trying to avoid having to support two download paths, but given that I don't really have time right now to parse out m3u playlists that might be easier.

**Comment by jefro108** [comment]
Have you considered using youtube-dl to do all the donkey work of downloading?

**Comment by skovatch** [comment]
Hmm... At first I wasn't thrilled about that, but then again this app is already dependent on get_iplayer. Also, the licensing on youtube-dl is friendly enough that I think it will be okay, even though GiA is GPL-licensed.

Let me think about it. I suspect it would be easier to integrate that pick apart streaming manifests.

**Comment by skovatch** [comment]
Fixed in v1.12.0. Youtube-dl is now the engine for ITV downloads.
