### ISSUE TITLE
Unknown: PID Not Found

### ISSUE THREAD

**Issue by bevanting** [Ascoware/get-iplayer-automator#139]
I am using 1.11.2 and am encountering a strange problem:

I clicked "Use Current Webpage" and the show I wanted is added to the queue. However, after I clicked "Process PID", the show name episode name is changed to "Unknown: PID Not Found". 
The show was downloaded successfully though. 
Is anyone else encountering this problem? I've tried with a few shows and all of them giving me this issue.

**Comment by jchhenderson** [comment]
yes, has happened to me also - only for me it would not download.  I had to remove all Gia settings in library/application support (except `download_history` and the `Queue.automatorqueue`).  My aim was to remove the caches, but I basically restarted from scratch and the problem went away.  Time will tell if it comes back.

**Comment by hugofalkman** [comment]
Please close as duplicate of #138. Bypass is to force cache update.

**Comment by bevanting** [comment]
Yes forced cache update fixed it. Sorry for the duplication. Didn't think it was related.
