### ISSUE TITLE
App crashes on launch

### ISSUE THREAD

**Issue by goobertron** [Ascoware/get-iplayer-automator#14]
I hope I'm reporting this correctly. The wiki is currently empty so all links to the wiki are broken. I can't find any other channel for support with individual problems rather than reporting bugs - I assume this isn't a bug in the code as no one else is reporting it.

I'm running OS 10.7.5 and have just downloaded GiA 1.9b2. Each time I try to launch the app, it crashes instantly. I've downloaded the app three times and tried launching each download numerous times just in case something changed, but the result was the same with each attempt.

I've pasted the crash report (which was exactly the same for each launch attempt) in to a gist: https://gist.github.com/goobertron/c7a7e44c7aea47764a7cfdd0b29243da

Any help much appreciated! And by the way, thanks so much for forking GiA and getting development back on track.

**Comment by skovatch** [comment]
I restored the deployment target to 10.7. We'll see how long I can continue to do that; I want to modernize the code at some point.

**Comment by Westy2017** [comment]
Morning everyone

I'm having the same crash on launch problem (also running 10.7.5) and have tried to attach the crash report.  (I'm new to Github so please forgive newbie errors!)

To echo what the previous poster said, sincere thanks for your time and effort spent getting this back up and running - it's a great app and I've really missed being able to use it of late.  

Fingers crossed you'll be able to offer some wise words to get me back up and running.

Thanks in advance
W

**Comment by Westy2017** [comment]
Morning everyone

I'm having the same crash on launch problem (also running 10.7.5) and have tried to attach the crash report. (I'm new to Github so please forgive newbie errors!)

To echo what the previous poster said, sincere thanks for your time and effort spent getting this back up and running - it's a great app and I've really missed being able to use it of late.

Fingers crossed you'll be able to offer some wise words to get me back up and running.

Thanks in advance
W
[Crash report.txt](https://github.com/Ascoware/get-iplayer-automator/files/992589/Crash.report.txt)

**Comment by goobertron** [comment]
Thank you, @skovatch. It looks like you're releasing every few days, so I'll keep an eye out for the next update.

**Comment by skovatch** [comment]
Fixed in [1.9b3](https://github.com/Ascoware/get-iplayer-automator/releases/tag/1.9b3)

**Comment by goobertron** [comment]
Many thanks indeed. App now launches. Am having other problems but will look at other issues for those.
