### ISSUE TITLE
Possible to add progress to ITV downloads?

### ISSUE THREAD

**Issue by jefro108** [Ascoware/get-iplayer-automator#145]
Is it possible to add a progress bar to the interface? See https://askubuntu.com/questions/635504/youtube-dl-file-download-progress-with-zenity-progress-bar

**Comment by skovatch** [comment]
I don't understand the question... the progress bar is already being updated in ITV downloads. However, GiA relies on youtube-dl to dump out the show duration at the beginning, and if it doesn't do that we can't generate a progress bar.

That said, it could at least show how much has been downloaded.

**Comment by skovatch** [comment]
There is no equivalent to Zenity on macOS, if that's what you're asking about.

**Comment by skovatch** [comment]
Fixed the output parsing to get the duration on ITV shows, and added more info in the progress bar. (v.1.12.1)

**Comment by jefro108** [comment]
That's brilliant. Thanks! 😊
