### ISSUE TITLE
BBC Programs  not downloading 

### ISSUE THREAD

**Issue by Grimfool** [Ascoware/get-iplayer-automator#147]
For the last 2 days I have bee unable to download any BBC programmes. 
They all say download failed
The verbose log is attached
[Verbose log.pdf](https://github.com/Ascoware/get-iplayer-automator/files/1856496/Verbose.log.pdf)

**Comment by hugofalkman** [comment]
Error 403 forbidden in your verbose log means BBC is blocking your VPN/DNS service. This can happen also  when the streaming of the same program is working -- GiA uses get_iplayer to download BBC programs, and get_iplayer uses a different access method to download than is used for streaming.

**Comment by skovatch** [comment]
Closing. No support is given for getting GiA to work due to VPN or location issues.
