### ISSUE TITLE
ITV downloads often stop halfway with no error message

### ISSUE THREAD

**Issue by robincm** [Ascoware/get-iplayer-automator#148]
Just wondering if anyone else is having this problem. 
Many thanks to all who are keeping GiA alive.

*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*

Attempt to download ITV programme

*What is the expected output? What do you see instead?*

Download often just freezes - no warnings, no error messages

*What version of GiA are you using? On what version of OS X?*

1.12.2 MacOS 10.13.3

*Are you using a web proxy? DNS proxy? VPN? VPS?*

No

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *

Vera Thur Mar 22 and others

*Please provide any additional information below.*

Download just stops partway through. Sometimes it's ok when I try again, at other times it just stops at another place. It always starts again at the beginning.

[Verbose log.pdf](https://github.com/Ascoware/get-iplayer-automator/files/1863190/Verbose.log.pdf)

**Comment by skovatch** [comment]
youtube-dl is supposed to resume downloads when it can; I don't know if ITV downloads are resumable. I recognize that's frustrating, though. I'm trying it myself to see if youtube-dl is silently giving up or something else is wrong.

**Comment by skovatch** [comment]
For comparison, can you try Downie or youtube-dl? I suspect it's not something in GiA's control but we'll have to test other apps to know for sure.

**Comment by jefro108** [comment]
There's also a GUI for youtube-dl https://forum.videohelp.com/threads/384566-youtube-dl-GUI-for-Apple-Macs if the command line isn't your thing 😊

**Comment by sleaux-meaux** [comment]
Downloads are not resumable when they get delegated to ffmpeg, as happens for ITV when crypto support is not installed.

**Comment by robincm** [comment]
Thanks for the suggestions.
I have just successfully downloaded 2 episodes of Vera with youtube-dl with no problems (but also anther episode with GiA also with no problems!)
So I guess the problem may just be intermittent.

**Comment by skovatch** [comment]
Looks like I can include pycrypto and get resumable ITV downloads as a result. I need to do some more testing on parsing the output, but it's looking good.

**Comment by skovatch** [comment]
With the addition of pycrypto to allow youtube-dl to resume ITV downloads, I'm going to mark this as fixed. I can't really do much about the timeouts, since it's out of my control, but now you can at least pick up where you left off when your network is behaving better.

**Comment by robincm** [comment]
@skovatch Thank you so much.
Robin

**Comment by jefro108** [comment]
I just tried to resume a download of https://www.itv.com/hub/the-good-karma-hospital/2a4663a0009. I stopped the download because I wanted to edit the Download History for something else I wanted to add. Normally with BBC programmes they just resume where they stopped. I assumed this would now be the case for the ITV programme, but it appeared to go back to the beginning and lost the progress bar as well.

See 

```
Downloading Show 1/10:

ITV Download (ID=2a4663a0009): Downloading The Good Karma Hospital - Sun Apr 01
INFO: Preparing Request for Auth Info
INFO: Requesting Metadata.
DEBUG: Metadata response status code: 200
INFO: Metadata processed.
DEBUG: youtube-dl args:["https://www.itv.com/hub/the-good-karma-hospital/2a4663a0009", "-f", "mp4", "--external-downloader-args", "-hide_banner", "-o", "/Volumes/media/Downloads/TV Shows/The Good Karma Hospital/The Good Karma Hospital.s02e03.Episode 3.mp4", "--write-sub"]
DEBUG: youtube-dl environment: ["PATH": "/Applications/Get iPlayer Automator.app/Contents/MacOS:/usr/bin"]
[ITV] 2a4663a0009: Downloading webpage

[ITV] 2a4663a0009: Downloading XML

[ITV] 2a4663a0009: Downloading JSON metadata

[ITV] 2a4663a0009: Downloading m3u8 information

ITV Download (ID=2a4663a0009): Subtitle path = /Volumes/media/Downloads/TV Shows/The Good Karma Hospital/The Good Karma Hospital.s02e03.Episode 3.en.vtt
[download] Destination: /Volumes/media/Downloads/TV Shows/The Good Karma Hospital/The Good Karma Hospital.s02e03.Episode 3.mp4

Input #0, hls,applehttp, from 'https://itvpnpdotcom-a.akamaihd.net/2-4663-0009-001/18/1/VAR012/2-4663-0009-001_18_1_VAR012.ism/2-4663-0009-001_18_1_VAR012-audio=128000-video=1418931.m3u8':
  Duration: 
frame=  600 fps=191 q=-1.0 size=    4608kB time=00:00:23.97 bitrate=1574.3kbits/s speed=7.63x    
frame=  900 fps=189 q=-1.0 size=    7168kB time=00:00:35.98 bitrate=1631.6kbits/s speed=7.56x    
frame= 1109 fps=192 q=-1.0 size=    8704kB time=00:00:44.28 bitrate=1610.3kbits/s speed=7.67x    
frame= 1421 fps=192 q=-1.0 size=   11008kB time=00:00:56.80 bitrate=1587.6kbits/s speed=7.69x    

frame=68133 fps=193 q=-1.0 size=  508928kB time=00:45:25.28 bitrate=1529.8kbits/s speed=7.74x    
frame=68433 fps=193 q=-1.0 size=  510976kB time=00:45:37.28 bitrate=1529.2kbits/s speed=7.74x    
frame=68745 fps=193 q=-1.0 size=  513280kB time=00:45:49.76 bitrate=1529.1kbits/s speed=7.74x    
frame=69940 fps=195 q=-1.0 Lsize=  520309kB time=00:46:37.54 bitrate=1523.6kbits/s speed= 7.8x    
video:484502kB audio:32816kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.578182%


[download] 100% of 508.11MiB in 06:00


[download] 100% of 508.11MiB in 06:00

ITV Download (ID=2a4663a0009): youtube-dl finished downloading
INFO: Downloading thumbnail
INFO: Thumbnail Download Completed
INFO: Beginning AtomicParsley Tagging.
INFO: AtomicParsley Tagging finished.
INFO: Converting Subtitles...
INFO: Converting to SubRip: /Volumes/media/Downloads/TV Shows/The Good Karma Hospital/The Good Karma Hospital.s02e03.Episode 3.en.vtt
INFO: Conversion to SubRip complete: /Volumes/media/Downloads/TV Shows/The Good Karma Hospital/The Good Karma Hospital.s02e03.Episode 3.srt
```

**Comment by sleaux-meaux** [comment]
youtube-dl is still delegating to ffmpeg, so no resumable downloads. Even though the necessary crypto support is now bundled in GiA, it appears that it doesn't actually use it. The runtime environment for youtube-dl doesn't appear to be properly configured.

**Comment by skovatch** [comment]
Oops, when I developed this feature I had pycrypto in my Python libraries, so when I ran it here of course it worked fine. I need to figure out how to modify the python path so it looks in the Resources directory of the app.

You can install pycrypto yourself from https://pypi.python.org/pypi/pycrypto, though that is definitely a workaround. You shouldn't need to install third party stuff via the command line to use GiA.

**Comment by skovatch** [comment]
Please follow the new bug I just created instead of adding to this one, since this is closed.
