### ISSUE TITLE
Radio programmes: modes not available through app, but can download OK using command line

### ISSUE THREAD

**Issue by gingerbeardman** [Ascoware/get-iplayer-automator#15]
```
Get iPlayer Automator 1.9b2 Initialized.

AppController: Updating Programme Index Feeds...

INFO: Getting radio Index Feeds (this may take a few minutes)
INFO: Using sequential indexing
AppController: Index Updated.

INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used

AppController: Starting Downloads

Downloading Show 1/1:

BBC Download (ID=b08p1b3d): Downloading Radcliffe and Maconie - Ellie Gibson
INFO: encodinglocale = UTF-8
INFO: encodinglocalefs = UTF-8
INFO: encodingconsoleout = UTF-8
INFO: encodingconsolein = UTF-8
INFO: ${^UNICODE} = 39
INFO: User prefs dir: /Users/matt/Library/Application Support/Get iPlayer Automator
INFO: System options dir: /etc/get_iplayer/options
	versionlist = default
INFO: Search args: ''
INFO: ffmpeg version string = 3.0.1
INFO: ffmpeg version number = 3.0
INFO: Will try prog types: tv
INFO: Loaded history for first check.
INFO: Loading recordings history
INFO: Programme not in history
INFO: No file cache exists for tv
INFO: Getting page http://www.bbc.co.uk/programmes/b08p1b3d.json
INFO: Episode PID detected
INFO: Trying pid: b08p1b3d using type: tv
INFO: Trying to download PID using type tv
INFO: pid not found in tv cache
INFO: Cleaning pid Old: 'b08p1b3d',  New: 'b08p1b3d'
INFO: 1 Matching Programmes
INFO: Loaded history for first check.
INFO: Loading recordings history
INFO: Programme not in history
INFO: Programme metadata URL = http://www.bbc.co.uk/programmes/b08p1b3d.json
INFO: Getting page http://www.bbc.co.uk/programmes/b08p1b3d.json
INFO: Getting page http://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/pc/vpid/b08p1b2h/transferformat/dash?cb=70560
INFO: Getting page http://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/apple-ipad-hls/vpid/b08p1b2h/transferformat/hls?cb=75770
INFO: Getting page http://aod-hls-uk-live.akamaized.net/usp/auth/vod/piff_abr_full_audio/e3d696-b08p1b2h/vf_b08p1b2h_4456aff3-143b-4342-a1a2-2dc4a635b362.ism/vf_b08p1b2h_4456aff3-143b-4342-a1a2-2dc4a635b362.m3u8?__gda__=1494522474_c8d145619233556aac6230234850c94d
INFO: Getting page http://aod-hls-uk-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_audio/e3d696-b08p1b2h/vf_b08p1b2h_4456aff3-143b-4342-a1a2-2dc4a635b362.ism/vf_b08p1b2h_4456aff3-143b-4342-a1a2-2dc4a635b362.m3u8?s=1494479274&e=1494522474&h=69f4d7708d93a06f482cfb3ee0412ea2
INFO: Getting page http://cp401492-vh.akamaihd.net/i/prod_af_mp4_aaclc_128/iplayerstream/l2o/b08p1b2h_bdfe7957-ed53-4310-a8a0-1e3b3d1d7dac.mp4/master.m3u8?hdnea=st=1494500874~exp=1494522474~acl=/*b08p1b2h_bdfe7957-ed53-4310-a8a0-1e3b3d1d7dac.mp4*~hmac=1d3d448137507b4c7390aa3d1155e5c1304e4bfe8bc50675f28d170595367730
INFO: Getting page http://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/apple-iphone4-ipad-hls-3g/vpid/b08p1b2h/transferformat/hls?cb=25082
INFO: Getting page http://cp401492-vh.akamaihd.net/i/prod_af_mp4_heaacv1_48/iplayerstream/l2o/b08p1b2h_ac89353d-b6e8-42fe-bc2e-ac31fee2f204.mp4/master.m3u8?hdnea=st=1494500875~exp=1494522475~acl=/*b08p1b2h_ac89353d-b6e8-42fe-bc2e-ac31fee2f204.mp4*~hmac=a32f9a9241a7781fd3d099ca15e3f935c4590932210f1094d9bbed1074b16276
INFO: Found mode hafhigh1: (gip_haf_iplayer_340) hls aac 340kbps stream (CDN: af_limelight_uk_hls/2)
INFO: Found mode hafhigh2: (gip_haf_iplayer_340) hls aac 340kbps stream (CDN: af_akamai_uk_hls/1)
INFO: Found mode hafstd1: (gip_haf_iplayer_136) hls aac 136kbps stream (CDN: af_limelight_uk_hls/2)
INFO: Found mode hafstd2: (gip_haf_iplayer_136) hls aac 136kbps stream (CDN: af_akamai_uk_hls/1)
INFO: Found mode hafmed1: (gip_haf_iplayer_102) hls aac 102kbps stream (CDN: af_limelight_uk_hls/2)
INFO: Found mode hafmed2: (gip_haf_iplayer_102) hls aac 102kbps stream (CDN: af_akamai_uk_hls/1)
INFO: Found mode haflow1: (gip_haf_iplayer_51) hls aac 51kbps stream (CDN: af_limelight_uk_hls/2)
INFO: Found mode haflow2: (gip_haf_iplayer_51) hls aac 51kbps stream (CDN: af_akamai_uk_hls/1)
INFO: Found mode hlsaacstd1: (gip_hlsaac_iplayer_128) hls aac 128kbps stream (CDN: akamai_hls_open/10)
INFO: Found mode hlsaaclow1: (gip_hlsaac_iplayer_47) hls aac 47kbps stream (CDN: akamai_hls_open/10)
INFO: Loaded history for first check.
INFO: Loading recordings history
INFO: Programme not in history
INFO: Will search for versions: original
INFO: Mode list: dafhigh,dafstd,daflow,hlshd,hlsvhigh
INFO: Checking existence of original version
INFO: Version = original
INFO: No specified modes (dafhigh,dafstd,daflow,hlshd,hlsvhigh) available for this programme with version 'original'
INFO: Try using --modes=hafmed,hafstd,haflow,hafhigh,hlsaaclow,hlsaacstd
ERROR: Failed to record 'Radcliffe and Maconie - Ellie Gibson (b08p1b3d)'
REASON FOR FAILURE: None of the modes in your download format list are available for this self.show.
Try adding more modes.
BBC Download (ID=b08p1b3d): Radcliffe and Maconie - Ellie Gibson Failed

AppController: Downloads Finished
```

**Comment by MacMuser** [comment]
I have been getting similar messages this morning (GMT+1) and even with radio programmes I downloaded yesterday. It isn't unusual, however, and usually someone at the BBC notices and makes a change. Unless the BBC have done it deliberately to thwart GiPA… I'm back to recording live via my Elgato TV tuner.

**Comment by gingerbeardman** [comment]
But I can downloaded it on the command line just fine:

it seems that the mode `hafhigh1` is used on the command line but that mode isn't associated with radio shows in the app.

```
matt$ get_iplayer --type radio --pid b08p1b3d
get_iplayer 3.01-homebrew.0, Copyright (C) 2008-2010 Phil Lewis
  This program comes with ABSOLUTELY NO WARRANTY; for details use --warranty.
  This is free software, and you are welcome to redistribute it under certain
  conditions; use --conditions for details.

  NOTE: A UK TV licence is required to legally access BBC iPlayer TV content

INFO: Episode PID detected
INFO: Trying pid: b08p1b3d using type: radio
INFO: Trying to download PID using type radio
INFO: pid not found in radio cache
Matches:

INFO: 1 Matching Programmes
INFO: Checking existence of original version
INFO: hafhigh1,hafhigh2,hafstd1,hafstd2,hlsaacstd1,hafmed1,hafmed2,haflow1,haflow2,hlsaaclow1 modes will be tried for version original
INFO: Trying hafhigh1 mode to record radio: Radcliffe and Maconie - Ellie Gibson
INFO: File name prefix = Radcliffe_and_Maconie_-_Ellie_Gibson_b08p1b3d_original                 
INFO: Begin recording file: /Users/matt/Radcliffe_and_Maconie_-_Ellie_Gibson_b08p1b3d_original.audio.ts
INFO: Begin recording at: 0.00 MiB (00:00:00) [1]
INFO: Recorded: 434.64 MiB (03:01:20) [1700] in 00:02:03 at 28.27 Mibit/s       
INFO: Saved HLS audio file: /Users/matt/Radcliffe_and_Maconie_-_Ellie_Gibson_b08p1b3d_original.hls.ts
INFO: Begin converting audio file: /Users/matt/Radcliffe_and_Maconie_-_Ellie_Gibson_b08p1b3d_original.hls.ts
size=  426995kB time=03:01:19.97 bitrate= 321.5kbits/s speed=1.23e+03x    
INFO: Converted to file: /Users/matt/Radcliffe_and_Maconie_-_Ellie_Gibson_b08p1b3d_original.partial.m4a
INFO: Recorded file: /Users/matt/Radcliffe_and_Maconie_-_Ellie_Gibson_b08p1b3d_original.m4a

INFO: Begin tagging file: /Users/matt/Radcliffe_and_Maconie_-_Ellie_Gibson_b08p1b3d_original.m4a

 Started writing to temp file.
 Progress: =================================================> 89% ------|
 Finished writing to temp file.
INFO: Tagged file: /Users/matt/Radcliffe_and_Maconie_-_Ellie_Gibson_b08p1b3d_original.m4a
matt$ 
```

**Comment by Beechy11** [comment]
I Have the same issue - looks like its trying to find video formats to download when its a radio show - see log
BBC Download (ID=b016z6pf): Downloading The Navy Lark - The Redundancy Drive
INFO: Episode PID detected
INFO: Trying pid: b016z6pf using type: tv
INFO: Trying to download PID using type tv
INFO: pid not found in tv cache
INFO: 1 Matching Programmes
INFO: Checking existence of original version
INFO: No specified modes (dafhigh,dafstd,daflow,hlshd,hlsvhigh,hlsstd) available for this programme with version 'original'
INFO: Try using --modes=hafstd,haflow,hafmed,hafhigh,hlsaaclow,hlsaacstd
ERROR: Failed to record 'The Navy Lark - The Redundancy Drive (b016z6pf)'
REASON FOR FAILURE: None of the modes in your download format list are available for this self.show.
Try adding more modes.
BBC Download (ID=b016z6pf): The Navy Lark - The Redundancy Drive Failed

**Comment by Duffledorf** [comment]
Likewise, I have been trying various radio shows throughout the day with no luck, despite this working yesterday. Can only conclude something else changed at the BBC, but it isn't affecting video downloads on GiA or any downloads using get_iplayer.

INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used

AppController: Starting Downloads

Downloading Show 1/1:

BBC Download (ID=b08p4mmj): Downloading Radio 2 Playlists - Radio 2's Jazz Playlist
INFO: Episode PID detected
INFO: Trying pid: b08p4mmj using type: tv
INFO: Trying to download PID using type tv
INFO: pid not found in tv cache
INFO: 1 Matching Programmes
INFO: Checking existence of original version
INFO: No specified modes (dafstd,dafhigh,daflow,hlshd,hlsvhigh) available for this programme with version 'original'
INFO: Try using --modes=hafhigh,hafstd,hafmed,haflow,hlsaacstd,hlsaaclow
ERROR: Failed to record 'Radio 2 Playlists - Radio 2's Jazz Playlist (b08p4mmj)'
REASON FOR FAILURE: None of the modes in your download format list are available for this self.show.
Try adding more modes.
BBC Download (ID=b08p4mmj): Radio 2 Playlists - Radio 2's Jazz Playlist Failed

AppController: Downloads Finished

**Comment by skovatch** [comment]
The underlying get_iplayer changed some of its options for fetching audio, since there are now different formats from the BBC. I think I'm going to simplify the UI and just have 'best, very good, good', etc and use the generic values and let get_iplayer figure out what to use.

**Comment by Vangelis66** [comment]
@Duffledorf wrote: 

> Likewise, I have been trying various radio shows throughout the day with no luck, 
> despite this working yesterday. Can only conclude something else changed at the BBC,

Your gut feeling is right; the BBC made some changes that broke DASH radio streams (daf modes).
This is documented on Known Issue 2 over at the get_iplayer wiki: 

[Issue no.2](https://github.com/get-iplayer/get_iplayer/wiki/issues#2-2017-05-11-dash-streams-unavailable-for-radio-programmes)

**Comment by skovatch** [comment]
Fixed in [1.9b3](https://github.com/Ascoware/get-iplayer-automator/releases/tag/1.9b3)

**Comment by goobertron** [comment]
I'm afraid I'm getting the exact same error using v1.9b3 (Mac OS 10.7.5). I've tried various radio and TV programmes, and none will download. The radio error is as above, where it appears to be downloading it from the TV feeds:

> BBC Download (ID=b08nf0km): Downloading Late Junction: Late Junction Sessions - North Atlantic Flux
> WARNING: Please download and run latest installer or install the JSON::PP Perl module for more accurate programme metadata.
> WARNING: Could not determine PID type. Trying to record PID directly.
> INFO: Trying pid: b08nf0km using type: tv
> INFO: Trying to download PID using type tv
> INFO: pid not found in tv cache
> INFO: 1 Matching Programmes
> WARNING: Please download and run latest installer or install the JSON::PP Perl module for more accurate programme metadata.
> WARNING: No programmes are available for this PID with version(s): default (available versions: original)
> BBC Download (ID=b08nf0km): Late Junction: Late Junction Sessions - North Atlantic Flux Failed

For a TV programme, the error message was slightly different:

> BBC Download (ID=b065y1dx): Downloading Storyville - Atomic, Living in Dread and Promise
> INFO: pid found in cache
> INFO: 1 Matching Programmes
> WARNING: Please download and run latest installer or install the JSON::PP Perl module for more accurate programme metadata.
> WARNING: No programmes are available for this PID with version(s): default (available versions: editorial)
> BBC Download (ID=b065y1dx): Storyville - Atomic, Living in Dread and Promise Failed

Should I open a new issue?

**Comment by skovatch** [comment]
@goobertron you are running into #3. You'll need to update Perl and get the required library so get_iplayer can do its job.

**Comment by neeklamy** [comment]
I just came across the same problem, downloading using the built in Perl program worked just fine (`get_iplayer.pl --type radio --pid b08pmsmp`).

Using OS X 10.11.6.

```
Get iPlayer Automator 1.9b6 Initialized.

AppController: Updating Programme Index Feeds...

AppController: Index was Up-To-Date.

INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used

AppController: Starting Downloads

Downloading Show 1/1:

BBC Download (ID=b08pmsmp): Downloading How Does That Make You Feel?, Series 8 Omnibus
ERROR: Programe Type '' does not exist. Try using --refresh
BBC Download (ID=b08pmsmp): Unknown: PID Not Found Failed

AppController: Downloads Finished
```

**Comment by gingerbeardman** [comment]
FWIW I just downloaded that programme fine using the app @neeklamy

**Comment by neeklamy** [comment]
Like I said though, I managed to cd into the Get iPlayer Automator bundle and use the `get_iplayer.pl` program to download that episode, so presumably it’s nothing to do with either the Perl installation or its dependencies (I haven’t monkeyed with any of that either).

**Comment by neeklamy** [comment]
Curiously, I just tried this again and it worked.

All I did was restore the preferences defaults, then enabled BBC Radio caching, and finally forced the cache to update.

Previously to this I:
- Disabled General ▸ Items to Cache ▸ BBC TV & ITV TV;
- Disabled New Programmes ▸ BBC One, Two, and Four, BBC Radio 1, 2, and 3; and
- Disabled ‘Ignore all radio programmes with "news" in the title’.
