### ISSUE TITLE
Option to save BBC Radio downloads as a Podcast / Audiobook

### ISSUE THREAD

**Issue by jasowt** [Ascoware/get-iplayer-automator#153]
Hi all,

Love the app. I would just like to request that an enhancement is made to it so that users have the option of saving BBC Radio downloads as podcasts or audiobooks, to make management easier than having it go in with the music.

Cheers!

**Comment by sleaux-meaux** [comment]
Until a better solution presents itself, you can do this via the back door by setting options for get_iplayer from a command prompt:

    PERL5LIB="/Applications/Get iPlayer Automator.app/Contents/Resources/perl5" "/Applications/Get iPlayer Automator.app/Contents/Resources/get_iplayer" --profile-dir="$HOME/Library/Application Support/Get iPlayer Automator" --prefs-add --tag-podcast-radio

To switch it off, change `--prefs-add` to `--prefs-del` in the above command. Assumes you installed GiA in /Applications.

**Comment by skovatch** [comment]
That's a reasonable thing to add, and something I can see using myself, now that I see the get_iplayer option for it.

**Comment by skovatch** [comment]
Implemented in 1.13.4.
