### ISSUE TITLE
PID/connection issues

### ISSUE THREAD

**Issue by Fisheri** [Ascoware/get-iplayer-automator#154]
---------------

*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*
Using VPN
*What is the expected output? What do you see instead?*
"WARNING: Failed to download JSON PID info: http://www.bbc.co.uk/programmes/b09yswj5.json
WARNING: Could not determine PID type (b09yswj5). Trying to record PID directly.
ERROR: Failed to get version PID metadata from iPlayer site (JSON)"
*What version of GiA are you using? On what version of OS X?*
1.12.2 OS 10.12.6
*Are you using a web proxy? DNS proxy? VPN? VPS?*
Express VPN (which has worked well before today)
*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *
Ordeal by Innocence: Series 1: Episode 1 PID b09yswj5
*Please provide any additional information below.*
LONG time to fill in Status from BBC, as far as showing either "Available" or "Available:None"
BBC issues or is it me?

**Comment by mutantcamel** [comment]
Can you upgrade to v1.13 and try again?  I downloaded this last night with a VPN (I'm in Beijing) and it worked fine.

**Comment by Fisheri** [comment]
All Good now! Thanks!!
