### ISSUE TITLE
Missing Cookies?

### ISSUE THREAD

**Issue by Fisheri** [Ascoware/get-iplayer-automator#156]
---------------

*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*
Still working, but an error shows up in the Log. Should I worry?
*What is the expected output? What do you see instead?*
"/Users/fisheri/Library/Application Support/Get iPlayer Automator/cookies.desktop does not seem to contain cookies at /System/Library/Perl/Extras/5.18/HTTP/Cookies.pm line 432.
*What version of GiA are you using? On what version of OS X?*
Gia:1.13 OS:10.12.6
*Are you using a web proxy? DNS proxy? VPN? VPS?*
VPN
*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *
The Lancaster: Britain's Flying Past PID b04bwhk8
*Please provide any additional information below.*

**Comment by skovatch** [comment]
What's actually in that file? Here I see `#LWP-Cookies-1.0`
If it's not that I think you can delete it and not worry about it.

**Comment by Fisheri** [comment]
Thanks!
