### ISSUE TITLE
Mrs Mandela BBC download fails

### ISSUE THREAD

**Issue by jefro108** [Ascoware/get-iplayer-automator#157]
Mrs Mandela https://www.bbc.co.uk/iplayer/episode/b00qbyhn/mrs-mandela fails to download. I end up with three files in the Mrs Mandela folder

Mrs Mandela.dash.m4a
Mrs Mandela.video.m4v
Mrs Mandela.video.txt

```
Downloading Show 1/15:

BBC Download (ID=b00qbyhn): Downloading Mrs Mandela - Mrs Mandela
INFO: encodinglocale = UTF-8
INFO: encodinglocalefs = UTF-8
INFO: encodingconsoleout = UTF-8
INFO: encodingconsolein = UTF-8
INFO: ${^UNICODE} = 39
INFO: Profile dir: /Users/user/Library/Application Support/Get iPlayer Automator
INFO: User options file: /Users/user/Library/Application Support/Get iPlayer Automator/options
INFO: System options file: /etc/get_iplayer/options
INFO: Search args: ''
INFO: Got 1375 file cache entries for itv
INFO: Got 6461 file cache entries for tv
INFO: Got 13439 file cache entries for radio
INFO: Cleaning PID - old: 'b00qbyhn' new: 'b00qbyhn'
INFO: Getting URL: http://www.bbc.co.uk/programmes/b00qbyhn.json
INFO: tv episode PID detected (b00qbyhn)
INFO: 1 total programmes
INFO: Loaded history for first check.
INFO: Loading recordings history
INFO: Programme not in history
INFO: Getting URL: http://www.bbc.co.uk/programmes/b00qbyhn.json
INFO: Getting URL: http://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/pc/vpid/p0067znk?cb=23220
INFO: Getting URL: http://vod-dash-uk-live.akamaized.net/usp/auth/vod/piff_abr_full_sd_ad/f00598-b00qbyd7/vf_b00qbyd7_51809088-3419-40eb-b7a9-102ae9c8e4e1.ism/pc_hd_abr_v2_dash_master.mpd?__gda__=1522902615_2b7632d4e19056fad340997dfa6c8bf2
INFO: Getting URL: http://vod-dash-uk-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_sd_ad/f00598-b00qbyd7/vf_b00qbyd7_51809088-3419-40eb-b7a9-102ae9c8e4e1.ism/pc_hd_abr_v2_dash_master.mpd?s=1522859415&e=1522902615&h=b4f1ad2c4fbecd41fc9563fc934c1780
INFO: Getting URL: http://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/iptv-all/vpid/p0067znk?cb=80463
INFO: Getting URL: http://vod-hls-uk-live.akamaized.net/usp/auth/vod/piff_abr_full_sd_ad/f00598-b00qbyd7/vf_b00qbyd7_51809088-3419-40eb-b7a9-102ae9c8e4e1.ism.hlsv2.ism/vf_b00qbyd7_51809088-3419-40eb-b7a9-102ae9c8e4e1.ism.hlsv2.m3u8?__gda__=1522902615_e8605a00078b45dabde9861fe8949394
INFO: Getting URL: http://vod-hls-uk-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_sd_ad/f00598-b00qbyd7/vf_b00qbyd7_51809088-3419-40eb-b7a9-102ae9c8e4e1.ism.hlsv2.ism/vf_b00qbyd7_51809088-3419-40eb-b7a9-102ae9c8e4e1.ism.hlsv2.m3u8?s=1522859415&e=1522902615&h=9ed1c2a492841762ef623764dae1ffc8
INFO: Getting URL: http://mm.bidi.bbc.co.uk/vod-hls-uk-live/usp/auth/vod/piff_abr_full_sd_ad/f00598-b00qbyd7/vf_b00qbyd7_51809088-3419-40eb-b7a9-102ae9c8e4e1.ism.hlsv2.ism/vf_b00qbyd7_51809088-3419-40eb-b7a9-102ae9c8e4e1.ism.hlsv2.m3u8?at=jRgDVveQf3525a9b59013b3720d53098dd5b0fdf5978a7505690d5def2bc0
INFO: Found mode    dvfxsd1:   gip_dvf_iplayer_1604 dash h264   960x540 25fps 1604kbps mf_limelight_uk_dash/2
INFO: Found mode    dvfxsd2:   gip_dvf_iplayer_1604 dash h264   960x540 25fps 1604kbps mf_akamai_uk_dash/1
INFO: Found mode  dvfxhigh1:    gip_dvf_iplayer_827 dash h264   704x396 25fps  827kbps mf_limelight_uk_dash/2
INFO: Found mode  dvfxhigh2:    gip_dvf_iplayer_827 dash h264   704x396 25fps  827kbps mf_akamai_uk_dash/1
INFO: Found mode    dvflow1:    gip_dvf_iplayer_437 dash h264   512x288 25fps  437kbps mf_limelight_uk_dash/2
INFO: Found mode    dvflow2:    gip_dvf_iplayer_437 dash h264   512x288 25fps  437kbps mf_akamai_uk_dash/1
INFO: Found mode    hvfxsd1:   gip_hvf_iplayer_1836  hls h264   960x540 25fps 1836kbps mf_bidi_uk_hls/3
INFO: Found mode    hvfxsd2:   gip_hvf_iplayer_1836  hls h264   960x540 25fps 1836kbps mf_limelight_uk_hls/1
INFO: Found mode    hvfxsd3:   gip_hvf_iplayer_1836  hls h264   960x540 25fps 1836kbps mf_akamai_uk_hls/1
INFO: Found mode   hvfhigh1:   gip_hvf_iplayer_1800  hls h264   704x396 50fps 1800kbps mf_bidi_uk_hls/3
INFO: Found mode   hvfhigh2:   gip_hvf_iplayer_1800  hls h264   704x396 50fps 1800kbps mf_limelight_uk_hls/1
INFO: Found mode   hvfhigh3:   gip_hvf_iplayer_1800  hls h264   704x396 50fps 1800kbps mf_akamai_uk_hls/1
INFO: Found mode  hvfxhigh1:   gip_hvf_iplayer_1013  hls h264   704x396 25fps 1013kbps mf_bidi_uk_hls/3
INFO: Found mode  hvfxhigh2:   gip_hvf_iplayer_1013  hls h264   704x396 25fps 1013kbps mf_limelight_uk_hls/1
INFO: Found mode  hvfxhigh3:   gip_hvf_iplayer_1013  hls h264   704x396 25fps 1013kbps mf_akamai_uk_hls/1
INFO: Found mode    hvfstd1:    gip_hvf_iplayer_865  hls h264   640x360 25fps  865kbps mf_bidi_uk_hls/3
INFO: Found mode    hvfstd2:    gip_hvf_iplayer_865  hls h264   640x360 25fps  865kbps mf_limelight_uk_hls/1
INFO: Found mode    hvfstd3:    gip_hvf_iplayer_865  hls h264   640x360 25fps  865kbps mf_akamai_uk_hls/1
INFO: Found mode    hvflow1:    gip_hvf_iplayer_599  hls h264   512x288 25fps  599kbps mf_bidi_uk_hls/3
INFO: Found mode    hvflow2:    gip_hvf_iplayer_599  hls h264   512x288 25fps  599kbps mf_limelight_uk_hls/1
INFO: Found mode    hvflow3:    gip_hvf_iplayer_599  hls h264   512x288 25fps  599kbps mf_akamai_uk_hls/1
INFO: Getting URL: http://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/pc/vpid/b00qbyd7?cb=75163
INFO: Getting URL: http://vod-dash-uk-live.akamaized.net/usp/auth/vod/piff_abr_full_hd/f00598-b00qbyd7/vf_b00qbyd7_4bd662cd-63ea-4c18-a7b9-d1eca8e953e8.ism/pc_hd_abr_v2_dash_master.mpd?__gda__=1522902616_24f55c25d2c9cddafe8afc97891738f8
INFO: Getting URL: http://vod-dash-uk-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_hd/f00598-b00qbyd7/vf_b00qbyd7_4bd662cd-63ea-4c18-a7b9-d1eca8e953e8.ism/pc_hd_abr_v2_dash_master.mpd?s=1522859416&e=1522902616&h=de42d9536ac2ef56fe854015f896e5fa
INFO: Getting URL: http://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/iptv-all/vpid/b00qbyd7?cb=79438
INFO: Found mode     dvfhd1:   gip_dvf_iplayer_5070 dash h264  1280x720 50fps 5070kbps mf_limelight_uk_dash/2
INFO: Found mode     dvfhd2:   gip_dvf_iplayer_5070 dash h264  1280x720 50fps 5070kbps mf_akamai_uk_dash/1
INFO: Found mode     dvfsd1:   gip_dvf_iplayer_2812 dash h264   960x540 50fps 2812kbps mf_limelight_uk_dash/2
INFO: Found mode     dvfsd2:   gip_dvf_iplayer_2812 dash h264   960x540 50fps 2812kbps mf_akamai_uk_dash/1
INFO: Found mode    dvfxsd1:   gip_dvf_iplayer_1604 dash h264   960x540 25fps 1604kbps mf_limelight_uk_dash/2
INFO: Found mode    dvfxsd2:   gip_dvf_iplayer_1604 dash h264   960x540 25fps 1604kbps mf_akamai_uk_dash/1
INFO: Found mode  dvfxhigh1:    gip_dvf_iplayer_827 dash h264   704x396 25fps  827kbps mf_limelight_uk_dash/2
INFO: Found mode  dvfxhigh2:    gip_dvf_iplayer_827 dash h264   704x396 25fps  827kbps mf_akamai_uk_dash/1
INFO: Found mode    dvflow1:    gip_dvf_iplayer_437 dash h264   512x288 25fps  437kbps mf_limelight_uk_dash/2
INFO: Found mode    dvflow2:    gip_dvf_iplayer_437 dash h264   512x288 25fps  437kbps mf_akamai_uk_dash/1
INFO: Found mode subtitles1:               captions http  N/A       N/A   N/A      N/A mf_limelight_uk_plain/20
INFO: Found mode subtitles2:               captions http  N/A       N/A   N/A      N/A sis/10
INFO: Found mode subtitles3:               captions http  N/A       N/A   N/A      N/A mf_akamai_uk_plain/10
INFO: Programme not in history
INFO: Searching for versions: original
WARNING: A UK TV licence is required to access BBC iPlayer TV content legally
INFO: Mode list: radiobest,radiobetter,radiovgood,hlshd,hvfxsd,dvfxsd,hlsvhigh,hvfxhigh,dvfxhigh,hvfstd,hlsstd,hlsxstd,hvflow,dvflow,hvfxsd,dvfxsd,hlsvhigh,hvfxhigh,dvfxhigh,hvfstd,hlsstd,hlsxstd,hvflow,dvflow,hlsvhigh,hvfxhigh,dvfxhigh,hvfstd,hlsstd,hlsxstd,hvflow,dvflow
INFO: Searching for version: 'original'
INFO: Found version: 'original'
INFO: Modes to try for 'original' version: dvfxsd1,dvfxsd2,dvfxhigh1,dvfxhigh2,dvflow1,dvflow2,dvfxsd1,dvfxsd2,dvfxhigh1,dvfxhigh2,dvflow1,dvflow2,dvfxhigh1,dvfxhigh2,dvflow1,dvflow2
INFO: Downloading tv: 'Mrs Mandela - - (b00qbyhn) [original]'
INFO: Trying 'dvfxsd1' mode: attempt 1 / 5
INFO: ffmpeg version string = 3.4.2-tessus
INFO: ffmpeg version number = 3.4
INFO: Creating subdirectory /Volumes/media/Downloads/TV Shows/Mrs Mandela for programme
INFO: File name prefix = Mrs Mandela
INFO: Creating dir '/Volumes/media/Downloads/TV Shows/Mrs Mandela'
INFO: Begin downloading at: 0.00 MB (00:00:00) [1]
  1.0%     0.65 MB / ~65.17 MB (00:00:57 / 01:30:33) [   15 / 1415] @   2.6 Mb/s ETA: 00:03:17 (dvfxsd1/ll) [audio]
  2.0%     1.31 MB / ~65.17 MB (00:01:51 / 01:30:33) [   29 / 1415] @   3.5 Mb/s ETA: 00:02:26 (dvfxsd1/ll) [audio]
--truncated--
 98.1%    63.97 MB / ~65.17 MB (01:29:12 / 01:30:33) [ 1394 / 1415] @   5.1 Mb/s ETA: 00:00:01 (dvfxsd1/ll) [audio]
 99.1%    64.62 MB / ~65.17 MB (01:30:06 / 01:30:33) [ 1408 / 1415] @   5.1 Mb/s ETA: 00:00:00 (dvfxsd1/ll) [audio]
INFO: Downloaded: 64.95 MB (01:30:33) [1415] in 00:01:42 @ 5.09 Mb/s (dvfxsd1/ll) [audio]
INFO: Finished downloading to file: /Volumes/media/Downloads/TV Shows/Mrs Mandela/Mrs Mandela.audio.m4a
INFO: Begin downloading at: 0.00 MB (00:00:00) [1]
BBC Download (ID=b00qbyhn): Mrs Mandela - Mrs Mandela Failed
```
[Mrs Mandela.video.txt](https://github.com/Ascoware/get-iplayer-automator/files/1878019/Mrs.Mandela.video.txt)

**Comment by skovatch** [comment]
I can't debug this any further because I'm being told there are only audiodescribed and signed versions available.

Oh... I also noticed that it insists on me being signed in to watch it in a web browser. This could be bad news.

**Comment by jefro108** [comment]
It comes up with that message if the force HLS streams for get_iplayer is set. Otherwise it downloads  audio but when it comes to the video the progress isn't visible even though it's downloading the .m4v file. 
Preferring the 50fps stream seems to solve the problem of the download failing though.

**Comment by jefro108** [comment]
I notice though that GiA is processing the video with FFMPEG with the command  `"/Applications/Get iPlayer Automator.app/Contents/MacOS/ffmpeg" "-loglevel" "fatal" "-stats" "-y" "-i" "/Volumes/media/Downloads/TV Shows/Mrs Mandela/Mrs Mandela.dash.m4a" "-i" "/Volumes/media/Downloads/TV Shows/Mrs Mandela/Mrs Mandela.dash.m4v" "-c:v" "libx264" "-c:a" "copy" "-preset" "ultrafast" "-movflags" "+faststart" "-map" "0:a:0" "-map" "1:v:0" "/Volumes/media/Downloads/TV Shows/Mrs Mandela/Mrs Mandela.partial.mp4"` - I'm wondering why FFMPEG needs to convert the video with libx264 rather than `-c:v copy` when the source is already H264. 

However I notice that the video is unplayable in Quicktime Player although it works fine in 5KPlayer when I remux the m4v and m4a files using FFMPEG via [remux](https://www.macupdate.com/app/mac/35968/remux)

**Comment by hugofalkman** [comment]
Downie downloads Mrs Mandela including subtitles without problems.

**Comment by jefro108** [comment]
GiA downloads Mrs Mandela including subtitles without problems when 'Prefer 50 FPS streams if available' is checked and 'force get_iplayer to fetch HLS video' is not checked in the Preferences.

**Comment by sleaux-meaux** [comment]
There are several things going on here:

There is a bug in GiA such that it ignores the progress output when downloading a DASH video stream, so it isn't clear from the log what happened, though you can see it in the .txt file you posted. I also think GiA discards some get_iplayer output that might help identify the failure. I had no problem downloading this programme with GiA. Also, the HD streams are clearly listed as 50fps options in the log you posted. I had no problem downloading HD either. You could test just the download process outside of GiA to see if any more useful information appears:

    PERL5LIB="/Applications/Get iPlayer Automator.app/Contents/Resources/perl5" "/Applications/Get iPlayer Automator.app/Contents/Resources/get_iplayer" --profile-dir="$HOME/Library/Application Support/Get iPlayer Automator"  --output="$HOME/Movies/TV Shows/test" --pid b00qbyhn --subdir --force --raw --verbose

The `--raw` option skips transcoding and tagging.

The "No versions of this programme were selected" message seen when "Force get_iplayer to fetch HLS video" is selected in preferences may be misleading. It is accurate for the non-audiodescribed version of this programme, but may cause problems elsewhere, such as with the audiodescribed version. That preference setting actually excludes most of the HLS streams that may be available. I presume that is a bug. Still, it wouldn't help for this particular programme since only DASH streams are available for the non-audiodescribed version.

The version of get_iplayer embedded in GiA was changed a while back to transcode the output files from DASH streams so they can be used in iTunes/QuickTime (other media players work OK with a simple remux, which is what get_iplayer itself does). Search the repository for "dash" to find the related issues. Whether or not that is a good idea depends on how much you want to cater to iTunes/QuickTime and/or shield users from the realities of streaming media. Even if you fix the above problem with forcing HLS, you will still find the occasional programme like this one that is only available via DASH. I had no problem playing the transcoded output in iTunes/QuickTime, so that isn't a universal problem.

**Comment by Vangelis66** [comment]
@skovatch 

> Oh... I also noticed that it insists on me being signed in 
> to watch it in a web browser. 

The mandatory sign-in requirement for UK iPlayer users, for radio+tv content alike, has been imposed since last autumn 2017, nothing new here (international iPlayer users can still enjoy radio content (in reduced bitrates) and limited video content without being prompted to sign-in; that could change, though...).

> This could be bad news.

It could certainly be, starting from mid-May of this year; see my recent tracker post [here](https://github.com/Ascoware/get-iplayer-automator/issues/124#issuecomment-377820975) :wink:

**Comment by sleaux-meaux** [comment]
I see what you mean. It looks like no HLS streams for this programme were included in the IPTV mediaselector for the "original" version, and those in the iPad mediaselector are now ignored. I presume they are normally duplicates. That seems like a one-off mistake by the BBC to me, though. I think many connected TVs use HLS. I'll have to check on my TV tonight.

**Comment by Vangelis66** [comment]
> It looks like no HLS streams for this programme were included in the IPTV mediaselector 
> for the "original" version, and those in the iPad mediaselector are now ignored. 
> I presume **they are normally duplicates**.

I wouldn't generalise this; `iptv-all` and `apple-ipad-hls` mediaselectors **normally** produce different playlists; e.g. for pid=p061mwjm => vpid=p061mwtw, for the Ak CDN over HTTP: 

`http://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/apple-ipad-hls/transferformat/hls/vpid/p061mwtw` => 
`http://vod-hls-uk-live.akamaized.net/usp/auth/vod/piff_abr_full_hd/746223-p061mwtw/vf_p061mwtw_c82d88ec-782a-416e-80f5-43f85c653d65.ism/mobile_wifi_main_sd_abr_v2_hls_master.m3u8?__gda__=1522964392_207230e377eae1634dffc678d7e8b95f` => best video = 960x540p25@1802k, best audio = 96kbps (HE-AAC)

whereas 

`http://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/iptv-all/transferformat/hls/vpid/p061mwtw` =>
`http://vod-hls-uk-live.akamaized.net/usp/auth/vod/piff_abr_full_hd/746223-p061mwtw/vf_p061mwtw_c82d88ec-782a-416e-80f5-43f85c653d65.ism.hlsv2.ism/iptv_hd_abr_v1_hls_master.m3u8?__gda__=1522964748_9a87b398b4e1bf3e4543db82360b1938`
 => best video = 1280x720p50@5510k, best audio = 128kbps (AAC LC)

>That seems like a one-off mistake by the BBC to me, though.

Be that as it may (the beeb failing to provide HLS streams for `iptv-all` mediaset), the fact that latest GiP (hence GiA) can't identify **any** HLS streams for the `original` version of `pid=b00qbyhn` is a direct consequence of code change inside GiP 3.13, a change that, IMHO, results in this bugged behaviour; as such, I still insist on someone reporting this issue to the GiP dev; let's see what _he_ has to say...

> "Force get_iplayer to fetch HLS video" still wouldn't work in this case 
> due to the problem noted earlier.

Apologies for being thick here... Are you saying that even if GiP were to successfully identify the existing HLS streams for the `original` version of `pid=b00qbyhn` (the ones produced by the `apple-ipad-hls` mediaselector), GiA would still fail with the "Force get_iplayer to fetch HLS video" setting?

**Comment by sleaux-meaux** [comment]
> I wouldn't generalise this; iptv-all and apple-ipad-hls mediaselectors normally produce different playlists

You need to compare the playlists get_iplayer uses, not the ones in the mediaselector file. I've rolled back to 3.12 and checked your example, and they contain the same streams. But re-incorporating the duplicates would certainly help in cases like this.

> Apologies for being thick here... Are you saying that even if GiP were to successfully identify the existing HLS streams for the original version of pid=b00qbyhn (the ones produced by the apple-ipad-hls mediaselector), GiA would still fail with the "Force get_iplayer to fetch HLS video" setting?

For this particular programme, yes. Select "Force get_iplayer to fetch HLS video" and "Audio Described versions" in preferences and try to download this programme. It's the same issue.

**Comment by hugofalkman** [comment]
This screenshot shows the alternatives Downie finds -- no HLS streams.

<img width="724" alt="screen shot 2018-04-05 at 22 42 23" src="https://user-images.githubusercontent.com/10969068/38391003-481122b6-3923-11e8-86e4-dbee04d834fe.png">

**Comment by skovatch** [comment]
Closing as the program was downloaded. You may have issues with get_iplayer here; I don't see a GiA bug.
