### ISSUE TITLE
Failed: No Specified Modes

### ISSUE THREAD

**Issue by jchhenderson** [Ascoware/get-iplayer-automator#160]
**What steps will reproduce the problem? Be specific, and provide as much detail as possible.**
Tru to download "Ordeal by Innocence s01e02" either by queue or by direct add from webpage

**What is the expected output? What do you see instead?**
Download to start after pressing <start>

**What version of GiA are you using? On what version of OS X?**
11.13.1 and 1.13.2 (I updated incase that was the issue)

**Are you using a web proxy? DNS proxy? VPN? VPS?**
No.

**What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.**
"Ordeal by Innocence s01e02"

**Please provide any additional information below.**
...other BBC shows work OK, so I understand this may not be GiA

**Comment by sleaux-meaux** [comment]
If you have "Force get_iplayer to fetch HLS video" selected, deselect it. That setting actually prevents you from downloading most HLS streams. The streams it selects may be being phased out by the BBC, but it is too soon to know for sure. This is the same bug I mentioned here: https://github.com/Ascoware/get-iplayer-automator/issues/157#issuecomment-378898681.

**Comment by jchhenderson** [comment]
yes, that fixed it - thanks, @sleaux-meaux !

...sorry for not spotting it in #157 myself.
