### ISSUE TITLE
1.13.2 fails with Lethal Weapons s2e10-11

### ISSUE THREAD

**Issue by hugofalkman** [Ascoware/get-iplayer-automator#161]
GiA 1.13.2 fails with diagnosis Problem Unknown, leaving items still in download queue with status downloading. ttml and part files in download folder. Attaching log file.

[log.txt](https://github.com/Ascoware/get-iplayer-automator/files/1889330/log.txt)

**Comment by sleaux-meaux** [comment]
From the UK, youtube-dl doesn't find any available streams for episode 10. Episode 11 downloads OK, but is only available in FLV format, which might be a problem for VPN users. Because it is FLV, be forewarned that GiA now makes youtube-dl put it through a wasteful and unnecessary transcoding after download. A simple remux would suffice. OTOH, this probably won't apply to most ITV programmes since I doubt very many are FLV-only.

**Comment by skovatch** [comment]
What do you mean by "unnecessary transcoding" after download? iTunes can't import the .flv format.

**Comment by skovatch** [comment]
If you have a patch or better suggestion for the youtube-dl command line arguments that would be more helpful.

**Comment by skovatch** [comment]
> As to how you do it, you'll find the necessary clue immediately beneath --recode-video in the youtube-dl readme.
Are you referring to -postprocessor-args for ffmpeg? Please be specific.

**Comment by sleaux-meaux** [comment]
Bingo

**Comment by skovatch** [comment]
After an rtmpdump the code used to call ffmpeg with "-i <download path> -vcodec copy -acodec copy". I'll have to see if I can coax youtube-dl into doing that. If youtube-dl can get an mp4 directly this step isn't necessary. I would have to detect when youtube-dl had to fall back to the old flv stream.

**Comment by sleaux-meaux** [comment]
You should be able to use the more modern "-c copy". And you shouldn't need to do any detection. You're already forcing the use of HLS if present; RTMP would only ever be the last resort. youtube-dl will skip transcoding via --recode-video if the desired output format already exists. You can already see that in action with an episode of Coronation Street, which has both HLS and RTMP streams. By default, youtube-dl would flag an RTMP stream as "best", but you're already overriding that.

**Comment by hugofalkman** [comment]
Redid log file with verbose mode. @sleaux-meaux  what I can see GiA treats episodes 10 and 11 identically, both fail with same behavior/diagnosis. Only difference between the two is that episode 11 leaves a ttml and a part file in the download directory, whereas episode 10 leaves no trace there.

[log.txt](https://github.com/Ascoware/get-iplayer-automator/files/1891448/log.txt)

**Comment by sleaux-meaux** [comment]
@hugofalkman - youtube-dl probably can't find subtitles for episode 10. It wouldn't make much sense to have subtitles without associated video. I don't have Windows available to check if subtitles  are available online. Subtitles are downloaded before media, so .ttml file is left behind when episode 11 download fails. There isn't enough info in the logs to tell what is going on. youtube-dl error messages are apparently being discarded by GiA, so if you run youtube-dl outside GiA you might see some more useful information. My uneducated guess is that you're not able to establish an RTMP connection for episode 11.

**Comment by hugofalkman** [comment]
@sleaux-meaux Thought the part file had nothing to do with subtitles? Would it show up if an RTMP session hadn't been established?

**Comment by hugofalkman** [comment]
@sleaux-meaux You are right -- the episode 11 .part file is zero bytes long.

**Comment by sleaux-meaux** [comment]
That strongly suggests that rtmpdump either cannot connect (VPN issue) or is denied access (CDN geo-block).

**Comment by jefro108** [comment]
I'm surprised anyone can get any download of Lethal Weapon since I believe it is an encrypted stream now. All I get in the log is the following:

```
Downloading Show 1/3:

ITV Download (ID=2a4808a0028): Downloading Lethal Weapon - Fri Mar 16
INFO: Preparing Request for Auth Info
INFO: Requesting Metadata.
DEBUG: Metadata response status code: 200
INFO: Metadata processed.
DEBUG: youtube-dl args:["https://www.itv.com/hub/lethal-weapon/2a4808a0028", "-f", "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best", "--recode-video", "mp4", "-o", "/Volumes/media/Downloads/TV Shows/Lethal Weapon/Lethal Weapon.s02e10.Wreck The Halls", "--write-sub", "--verbose"]
DEBUG: youtube-dl environment: ["PYTHONPATH": "/Applications/Get iPlayer Automator.app/Contents/Resources", "PATH": "/Applications/Get iPlayer Automator.app/Contents/MacOS:/usr/bin"]
[ITV] 2a4808a0028: Downloading webpage

[ITV] 2a4808a0028: Downloading XML

[ITV] 2a4808a0028: Downloading JSON metadata

ITV Download (ID=2a4808a0028): youtube-dl finished downloading

Downloading Show 2/3:

ITV Download (ID=2a4808a0029): Downloading Lethal Weapon - Fri Apr 06
INFO: Preparing Request for Auth Info
INFO: Requesting Metadata.
DEBUG: Metadata response status code: 200
INFO: Metadata processed.
DEBUG: youtube-dl args:["https://www.itv.com/hub/lethal-weapon/2a4808a0029", "-f", "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best", "--recode-video", "mp4", "-o", "/Volumes/media/Downloads/TV Shows/Lethal Weapon/Lethal Weapon.s02e11.Funny Money", "--write-sub", "--verbose"]
DEBUG: youtube-dl environment: ["PYTHONPATH": "/Applications/Get iPlayer Automator.app/Contents/Resources", "PATH": "/Applications/Get iPlayer Automator.app/Contents/MacOS:/usr/bin"]
[ITV] 2a4808a0029: Downloading webpage

[ITV] 2a4808a0029: Downloading XML

[ITV] 2a4808a0029: Downloading JSON metadata

ITV Download (ID=2a4808a0029): Subtitle path = /Volumes/media/Downloads/TV Shows/Lethal Weapon/Lethal Weapon.s02e11.en.ttml
[download] Destination: /Volumes/media/Downloads/TV Shows/Lethal Weapon/Lethal Weapon.s02e11.Funny Money

ITV Download (ID=2a4808a0029): youtube-dl finished downloading
```

**Comment by sleaux-meaux** [comment]
@jefro108: Again, without a full log from youtube-dl running outside GiA, there is no way to see what is going on. Perhaps Episode 11 is a fluke. Let's see what happens with future episodes.

**Comment by skovatch** [comment]
Fixed, although the 3/16 show just isn't available for download.
