### ISSUE TITLE
ITV Download Cause Python Crash while using _AES.so plug-in

### ISSUE THREAD

**Issue by steps39** [Ascoware/get-iplayer-automator#162]
*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*
Select an ITV program or programs using the search function in GiA - add to queue
Hit start
The first ITV program will change status to Downloading then download failed message comes up
The program stays in the downloading status and the next program appears to start downloading
Download will Trying download any ITV program

*What is the expected output? *
I expected to see the ITV program being download.
In my download location, in the "Action Team" directory:
Action Team.s01e06.Episode 6.mp4

*What do you see instead?*
Program stays in Downloading status, but the download reports failed and the next program appears to start downloading
The GiA log shows:
"AppController: Starting Downloads
Downloading Show 1/43:
ITV Download (ID=2a5066a0006): Downloading Action Team - Mon Apr 02
INFO: Preparing Request for Auth Info
INFO: Metadata processed.
ITV Download (ID=2a5066a0006): youtube-dl finished downloading"
Message displayed: "Python quit unexpectedly while using the _AES.so plug-in - with Ignore / Report / Reopen options.
In my download location, in the "Action Team" directory:
Action Team.s01e06.Episode 6.part
Action Team.s01e06.Episode 6.ytdl
Action Team.s01e06.Episode 6.part-Frag0

*What version of GiA are you using? On what version of OS X?*
GiA 1.13.2 - OS X 10.11.6

*Are you using a web proxy? DNS proxy? VPN? VPS?*
No

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *
Action Team - Mon Apr 02 2a5066a0006

*Please provide any additional information below.*
GiA verbose log:
[180409GetiPlayerCrashLog.txt](https://github.com/Ascoware/get-iplayer-automator/files/1889594/180409GetiPlayerCrashLog.txt)
Problem details and system configuration -
[180409GetiPlayerCrash.txt](https://github.com/Ascoware/get-iplayer-automator/files/1889521/180409GetiPlayerCrash.txt)
Process:               Python [1874]
Path:                  /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
Identifier:            Python
Version:               2.7.10 (2.7.10)
Code Type:             X86-64 (Native)
Parent Process:        Get iPlayer Automator [1756]
Responsible:           Python [1874]
User ID:               502

PlugIn Path:             /Applications/Get iPlayer Automator.app/Contents/Resources/Crypto/Cipher/_AES.so
PlugIn Identifier:       _AES.so
PlugIn Version:          ??? (0)
Date/Time:             2018-04-09 07:11:07.488 +0100
OS Version:            Mac OS X 10.11.6 (15G18013)

**Comment by steps39** [comment]
I used find on my Mac Pro to find another application using _AES.so and renamed existing /Applications/Get iPlayer Automator.app/Contents/Resources/Crypto/Cipher/_AES.so and copied _AES.so from calibre.app.

I am now able to download ITV programs, but am left with the mp4 file and mp4.jpg which has not been integrated into the mp4 file.  Looking at log below - tagging failed:

ITV Download (ID=2a5066a0005): Downloading Action Team - Mon Mar 26
INFO: Preparing Request for Auth Info
INFO: Requesting Metadata.
DEBUG: Metadata response status code: 200
INFO: Metadata processed.
DEBUG: youtube-dl args:["https://www.itv.com/hub/action-team/2a5066a0005", "-f", "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best", "--recode-video", "mp4", "-o", "/Volumes/Macintosh HG/Action Team/Action Team.s01e05.Episode 5", "--verbose"]
DEBUG: youtube-dl environment: ["PYTHONPATH": "/Applications/Get iPlayer Automator.app/Contents/Resources", "PATH": "/Applications/Get iPlayer Automator.app/Contents/MacOS:/usr/bin"]
[ITV] 2a5066a0005: Downloading webpage
[ITV] 2a5066a0005: Downloading XML
[ITV] 2a5066a0005: Downloading JSON metadata
[ITV] 2a5066a0005: Downloading m3u8 information
[download] Destination: /Volumes/Macintosh HG/Action Team/Action Team.s01e05.Episode 5


[download]   0.8% of ~282.47MiB at Unknown speed ETA Unknown ETA
............
[download] 100% of 268.07MiB in 02:47

ITV Download (ID=2a5066a0005): youtube-dl finished downloading
INFO: Downloading thumbnail
INFO: Thumbnail Download Completed
INFO: Beginning AtomicParsley Tagging.
INFO: Tagging failed.
AppController: Downloads Finished

**Comment by skovatch** [comment]
Hopefully this is fixed in v1.13.3. I wasn't able to reproduce it, but I did use a newer version of PyCrypto.

**Comment by steps39** [comment]
@pmhird from Issuse #277 I see you running GiA on El Capitan.
I am still having to replace _AES..so plug.in with every GiA update are you also doing this?
I running on a Mac Pro 1.1, so the kernel is patched to allow it to run and this may be my issue.

**Comment by pmhird** [comment]
I did exactly what was in the steps mentioned I’m afraid. I’m not that technical so didn’t do anything extra!
