### ISSUE TITLE
BBC Download Fails - None of download modes available

### ISSUE THREAD

**Issue by sxmpete** [Ascoware/get-iplayer-automator#163]
GIA v1.13.2 (bbc download formats best, better, very good selected) on Mac El Capitan. Not using proxy.
attempted to load Ordeal by Innocence Episode 2 (however, episode 1 d'ld ok).
log messages follow:
_b09zg9dd: Ordeal by Innocence - Series 1: Episode 2: Retrieving Metadata For PID

INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used

Downloading Show 1/1:

BBC Download (ID=b09zg9dd): Downloading Ordeal by Innocence - Series 1: Episode 2
INFO: 1 total programmes
WARNING: A UK TV licence is required to access BBC iPlayer TV content legally
INFO: Downloading tv: 'Ordeal by Innocence: Series 1 - 2. Episode 2 (b09zg9dd) [editorial]'
INFO: No specified modes (radiobest,radiobetter,radiovgood,hlshd,hlsvhigh,hlsstd,hlsxstd,hlsvhigh,hlsstd,hlsxstd,hlsvhigh,hlsstd,hlsxstd) available for this programme with version 'editorial'
INFO: Available modes: hvfhd,hvfsd,hvfxsd,hvfhigh,hvfxhigh,hvfstd,hvflow
REASON FOR FAILURE: None of the modes in your download format list are available for this show.
Try adding more modes.
BBC Download (ID=b09zg9dd): Ordeal by Innocence: Series 1: Episode 2 Failed
AppController: Downloads Finished

This sounds like the issue with ITV a few weeks ago...

**Comment by jeanpaulz85** [comment]
in download formats section uncheck "Force get-iplayer to fetch HLS video, it will work after that

**Comment by skovatch** [comment]
Fixed in v1.13.3
