### ISSUE TITLE
Converting Takes Too Long... (Needs full encode?)

### ISSUE THREAD

**Issue by TimelordCardiff** [Ascoware/get-iplayer-automator#164]
Let me first say I am not a programer ... more of a hacker (old def..)

It seems since last update (Version 1.13.2 (20180408001)), GiA is now doing a full encode of the video (supposedly FLV->MP4), which of course takes forever.

I stop GiA and manually used ffmpeg using this command... 

     ffmpeg -i file.flv -c copy file.mp4

or in the case of GiA...   file.flv is just the "file" with no ext.  ie: American Dad!.s12e19.Garfield and Friends

... and seems to work just fine and at the speed GiA used to do the job.

also of note..  noticed when I let GiA encode the file it is about half the size of the original file and from what I can tell from VLC around half the bit rate of the original.  

Also on the converted file it drops off the 3rd part of the file name...  ie:  
American Dad!.s12e19.Garfield and Friends  ->  American Dad!.s12e19.mp4

I understand the "ITV download improvements" and they are Great!... Just not sure about the full encoding with the bitrate change from the original preset in prefs.

Thanks for any help...

**Comment by skovatch** [comment]
Yeah, I know.... youtube-dl is actually doing the conversion. It doesn't know that a copy is sufficient to put it into an mp4 container. I am investigating what options will get it to do the right thing.

**Comment by sleaux-meaux** [comment]
Encoding issue already discussed in #161

**Comment by TimelordCardiff** [comment]
More info...  
GiA doing the full Download and Converting  on Media Inspector

General
Complete name                     : /Family Guy/Family Guy.s16e13.mp4
Format                                   : MPEG-4
Format profile                        : Base Media
Codec ID                                 : isom
File size                                : 95.3 MiB
Duration                                 : 20mn 38s
Overall bit rate                         : 646 Kbps
Collection                               : Family Guy
Season                                   : 16
Part                                     : 13
Track name                               : Family Guy - Veteran Guy - 2a4259a0310
Performer                                : ITV Player
ContentType                              : TV Show
Description                              : Peter and the gang are forced to join the Coast Guard.
Recorded date                            : 2018-04-09T20:00+0000
Encoded date                             : UTC 1904-01-01 00:00:00
Tagged date                              : UTC 2018-04-10 19:07:46
Writing application                      : Lavf57.83.100
Cover                                    : Yes
Lyrics                                   : Peter and the gang are forced to join the Coast Guard.
Comment                                  : Peter and the gang are forced to join the Coast Guard.
TVNetworkName                            : ITV Player
Part_ID                                  : Veteran Guy
LongDescription                          : Peter and the gang are forced to join the Coast Guard.

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L3.1
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 20mn 38s
Bit rate                                 : 511 Kbps
Width                                    : 896 pixels
Height                                   : 504 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 25.000 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.045
Stream size                              : 75.5 MiB (79%)
Writing library                          : x264 core 152
Encoding settings                        : cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=3 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=25 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=crf / mbtree=1 / crf=23.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00
Encoded date                             : UTC 1904-01-01 00:00:00
Tagged date                              : UTC 1904-01-01 00:00:00

Audio
ID                                       : 2
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : 40
Duration                                 : 20mn 38s
Bit rate mode                            : Constant
Bit rate                                 : 128 Kbps
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 KHz
Compression mode                         : Lossy
Stream size                              : 18.9 MiB (20%)
Encoded date                             : UTC 1904-01-01 00:00:00
Tagged date                              : UTC 1904-01-01 00:00:00

My Conversion using (ffmpeg -i file.flv -c copy file.mp4)

General
Complete name                            : /Family Guy/Family Guy.s16e13.Veteran Guy.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom
File size                                : 188 MiB
Duration                                 : 20mn 38s
Overall bit rate                         : 1 276 Kbps
Encoded date                             : UTC 1904-01-01 00:00:00
Tagged date                              : UTC 1904-01-01 00:00:00
Writing application                      : Lavf57.71.100

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L3.1
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 6 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 20mn 38s
Bit rate                                 : 1 174 Kbps
Nominal bit rate                         : 1 704 Kbps
Width                                    : 896 pixels
Height                                   : 504 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 25.000 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.104
Stream size                              : 173 MiB (92%)
Writing library                          : x264 core 138
Encoding settings                        : cabac=1 / ref=6 / deblock=1:-1:-1 / analyse=0x3:0x113 / me=umh / subme=8 / psy=1 / psy_rd=0.60:1.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-4 / threads=8 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=0 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=150 / keyint_min=15 / scenecut=0 / intra_refresh=0 / rc_lookahead=60 / rc=cbr / mbtree=1 / bitrate=1704 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / vbv_maxrate=1704 / vbv_bufsize=1278 / nal_hrd=none / filler=0 / ip_ratio=1.40 / aq=1:1.40
Encoded date                             : UTC 1904-01-01 00:00:00
Tagged date                              : UTC 1904-01-01 00:00:00

Audio
ID                                       : 2
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : 40
Duration                                 : 20mn 38s
Bit rate mode                            : Constant
Bit rate                                 : 96.0 Kbps
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 KHz
Compression mode                         : Lossy
Stream size                              : 14.2 MiB (8%)
Encoded date                             : UTC 1904-01-01 00:00:00
Tagged date                              : UTC 1904-01-01 00:00:00
