### ISSUE TITLE
ITV Only Downloading SD vs Available HD Versions...

### ISSUE THREAD

**Issue by Mimpy** [Ascoware/get-iplayer-automator#167]
I've searched the issues and I don't see this anywhere. ITV shows, for me at least, only download in SD resolution instead of the requested HD. All shows, so not show specific. Is there an option I'm missing? I have all of my formats set to HD/very high/high for ITV. BBC is fine. 

I'm only getting 896X504 for all shows. If this has been discussed elsewhere, my apologies in advance. Kindly direct me to the location and I'll close this out. Otherwise, is this an issue being addressed already?

*What version of GiA are you using? Version 1.13.3 (20180411001) on macOS 10.13.5 Beta (17F35e)

*Are you using a web proxy? DNS proxy? VPN? VPS?* NO

*What program are you attempting to download (full title, series and episode)? Plebs

**Comment by sleaux-meaux** [comment]
That is the best available from ITV. Also, the ITV format setting is now ignored.

**Comment by Mimpy** [comment]
Thanks for the info.
