### ISSUE TITLE
ITV downloads failing

### ISSUE THREAD

**Issue by thornbank** [Ascoware/get-iplayer-automator#168]
*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*

Attempting to download yesterday's James Martin program

*What is the expected output? What do you see instead?*

The program would be downloaded and added to iTunes

*What version of GiA are you using? On what version of OS X?*

Version 1.13.3 (20180411001)

10.13.5

*Are you using a web proxy? DNS proxy? VPN? VPS?*

No

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *

ownloading Show 1/4:

ITV Download (ID=2a5159a0034): Downloading James Martin's Saturday Morning - Sat Apr 21
INFO: Preparing Request for Auth Info
INFO: Requesting Metadata.
DEBUG: Metadata response status code: 200
INFO: Metadata processed.
DEBUG: youtube-dl args:["https://www.itv.com/hub/james-martins-saturday-morning/2a5159a0034", "-f", "mp4/best", "-o", "/Volumes/Videos/Videos/James Martin\'s Saturday Morning/James Martin\'s Saturday Morning.s01e34.Episode 34.%(ext)s", "--verbose"]
DEBUG: youtube-dl environment: ["PYTHONPATH": "/Users/paul/Desktop/Get iPlayer Automator.app/Contents/Resources", "PATH": "/Users/paul/Desktop/Get iPlayer Automator.app/Contents/MacOS:/usr/bin"]
[debug] System config: []

[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.itv.com/hub/james-martins-saturday-morning/2a5159a0034', u'-f', u'mp4/best', u'-o', u"/Volumes/Videos/Videos/James Martin's Saturday Morning/James Martin's Saturday Morning.s01e34.Episode 34.%(ext)s", u'--verbose']

[debug] Encodings: locale US-ASCII, fs utf-8, out None, pref US-ASCII

[debug] youtube-dl version 2018.04.09

[debug] Python version 2.7.10 (CPython) - Darwin-17.6.0-x86_64-i386-64bit

[debug] exe versions: ffmpeg 3.4.2-tessus, ffprobe N-90346-g86c7d8df95, rtmpdump 2.4-102-ga3a600d-get_iplayer

[debug] Proxy map: {}

[debug] Using fake IP 25.78.169.157 (GB) as X-Forwarded-For.

[ITV] 2a5159a0034: Downloading webpage

[ITV] 2a5159a0034: Downloading XML

ERROR: ITV said: No match found for production id: 2/5159/0034#001

Traceback (most recent call last):
  File "/Users/paul/Desktop/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/YoutubeDL.py", line 789, in extract_info
    ie_result = ie.extract(url)
  File "/Users/paul/Desktop/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/extractor/common.py", line 440, in extract
    ie_result = self._real_extract(url)
  File "/Users/paul/Desktop/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/extractor/itv.py", line 132, in _real_extract
    '%s said: %s' % (self.IE_NAME, fault_string), expected=True)
ExtractorError: ITV said: No match found for production id: 2/5159/0034#001

ITV Download (ID=2a5159a0034): youtube-dl finished downloading

*Please provide any additional information below.*

**Comment by Vangelis66** [comment]
I can reproduce with latest `yt-dl` on Windows, so have created a new [bug report](https://github.com/rg3/youtube-dl/issues/16253) over at the yt-dl tracker 😄 

With so many **open** issues there, the fact it may apply to only few ITV shows so far (if more are discovered with the same error message, please report them here/there) and the fact the yt-dl dev team is understaffed, one can only hope this will eventually attract the attention it deserves...

**Comment by zugernaut** [comment]
Same problem with Harry Hill's Alien Fun Capsule Series 2 - Episode 2

**Comment by Mimpy** [comment]
I've also been getting this over the past 3 days, an issue where ITV goes through the motion of downloading but immediately errors out without downloading. Here is this morning's latest log;

Get iPlayer Automator 1.13.3 Initialized.
GetITVShows: ITV Cache Update Starting 
AppController: Updating Programme Index Feeds...

GetITVShows (Info): Episodes: 1344 Today Programmes: 184 
AppController: Index Updated.
GetITVShows: Update Finished


INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used
AppController: Starting Downloads


Downloading Show 1/2:

ITV Download (ID=2a4263a0029): Downloading American Dad! - Tue Apr 24
INFO: Preparing Request for Auth Info
INFO: Metadata processed.
ITV Download (ID=2a4263a0029): youtube-dl finished downloading

Downloading Show 2/2:

ITV Download (ID=2a2898a0024): Downloading Who's Doing the Dishes - Wed Apr 25
INFO: Preparing Request for Auth Info
INFO: Metadata processed.
ITV Download (ID=2a2898a0024): youtube-dl finished downloading
AppController: Downloads Finished

You can add in American Dad to the list also. BBC, so far, is fine. 

Although this log shows downloads finished, it is not even starting to download.... just goes through the motions and then the Failed Download Solutions window pops up and states "Problem Unknown, please submit a bug report..."

So, I'm not sure if this is a different problem to the original above or an entirely new issue. Thought I should say something.

**Comment by skovatch** [comment]
In this case, it's ITV that is returning the error:

```
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
	<s:Body>
		<GetPlaylistResponse xmlns="http://tempuri.org/">
			<GetPlaylistResult>
				<Fault xmlns="">
					<faultcode>InvalidVodcrid</faultcode>
					<faultstring>No match found for production id: 2/4156/0019#001</faultstring>
				</Fault>
			</GetPlaylistResult>
		</GetPlaylistResponse>
	</s:Body>
</s:Envelope>
```

Updating to the latest youtube-dl doesn't fix it, either.

**Comment by skovatch** [comment]
Fixed in v1.13.4

**Comment by Vangelis66** [comment]
@PhoolR 

Many thanks for posting a verbose log; line 

`ExtractorError: ITV said: No match found for production id: 2/4156/0019#001`

_does indicate_ your failure is indeed covered by this GiA issue; which, as posted, 
is a [bug](https://github.com/rg3/youtube-dl/issues/16253) of the helper utility youtube-dl (a python script) used by GiA for ITV fetches 
(posting this explanation for those that want to learn more - please disregard otherwise) :smile:

> UPDATE:
> Ah... youtube-dl 05.01.2018 fixes this. I will merge that in and post an update.

GitHub doesn't notify by e-mail when an existing comment has been edited; when I came here to post about developments, I saw you found https://github.com/rg3/youtube-dl/commit/c18142da6e0e99a7b4c9ab488ddb285ad1e8dad9 :wink:

> Fixed in v1.13.4

Much obliged, and I think I speak on the behalf of many... 👍 

Regarding `yt-dl` and GiA's dependence on it, I can safely say we were lucky enough the issue was fixed by the Russian dev (one of only 3 active devs currently) only 9 days after original submission; and I don't want to take any credit, but I humbly feel additional input by yours truly made things easier for him (all credit should go to the **get_flash_videos** dev for detecting what had been changed by ITV 👍). 
Unlike `get_iplayer`, specialised in BBC iPlayer, `yt-dl` has a much broader target of supported sites, an eventual new issue relating to its itv extractor may stay in the backlog for quite long, while the devs are busy fixing other, more popular/urgent issues; I guess this is the drawback of relying on third party code...

Best wishes

**Comment by WilliamOfGaunt** [comment]
Good luck with the retina(s) – I can sympathize from personal experience.

**Comment by Vangelis66** [comment]
> as I am recovering from a retina re-attachment yesterday.

> Good luck with the retina(s) – I can sympathize from personal experience. 

... speedy recovery wishes from me, too...
