### ISSUE TITLE
Series-Link entries found despite already being in history

### ISSUE THREAD

**Issue by Murfur** [Ascoware/get-iplayer-automator#17]
**What steps will reproduce the problem?**
Start app or check for cache update, recent episodes in PVR list will be found and added to the queue, despite having been downloaded previously and in the history.

**What is the expected output?**
Only new episodes that have not been downloaded previously

**What do you see instead?**
New episodes that have not been downloaded previously PLUS episodes that have already been downloaded

**What version of GiA are you using? On what version of OS X?**
1.9b1 (1814) on Mac OS X Sierra 10.12.4

**Are you using a web proxy? DNS proxy? VPN? VPS?**
No, no, no, no.

**What programme are you attempting to download (full title, series and episode)?**
The Graham Norton Show, Series 21, episode 5

**Please provide any additional information below.**
Please see attached screen shot of queue and download history
![screen shot 2017-05-11 at 17 05 37](https://cloud.githubusercontent.com/assets/2332206/25959801/ce7a26c8-366c-11e7-937f-0c9d2fd7db23.png)

**Comment by hugofalkman** [comment]
This was fixed in 1.9b2, see closed issue #1

**Comment by Murfur** [comment]
Sincere apologies - my poor excuse for a search of previous issues did not reveal that. Many thanks.
