### ISSUE TITLE
ITV Downloads failing without starting after reporting youtube-dl downloaded successfully.

### ISSUE THREAD

**Issue by Mimpy** [Ascoware/get-iplayer-automator#170]
*What version of GiA are you using? Version 1.13.3 (20180411001) On what version of OS X? 10.13.5
For the last 3 days & after attempting to download 4 different and available shows, getting Failed Download Solutions window popping up stating "Problem unknown, please submit a bug report..."

I just downloaded these shows yesterday and nothing has changed on my end.

INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used
AppController: Starting Downloads

Downloading Show 1/2:

ITV Download (ID=2a4263a0029): Downloading American Dad! - Tue Apr 24
INFO: Preparing Request for Auth Info
INFO: Metadata processed.
ITV Download (ID=2a4263a0029): youtube-dl finished downloading

Downloading Show 2/2:

ITV Download (ID=2a2898a0024): Downloading Who's Doing the Dishes - Wed Apr 25
INFO: Preparing Request for Auth Info
INFO: Metadata processed.
ITV Download (ID=2a2898a0024): youtube-dl finished downloading
AppController: Downloads Finished

Even though the youtube-dl shows finished, it isn't even beginning to start downloading. 

Another show is Last Laugh in Vegas.
Ideas?

**Comment by Mimpy** [comment]
Benidorm just downloaded fine but none of the other shows mentioned above would today at all. So I'm not sure what ITV is doing. Just an FYI.

**Comment by Lordsnooty05** [comment]
Mimpy, just to let you know, "Last Laugh In Vegas" just downloaded for me using the latest version of GIA Version 1.13.3 (20180411001). I'll try Who's Doing the Dishes and let you know how I get on

**Comment by Lordsnooty05** [comment]
Mimpy those shows downloaded no problem what I did notice is that the dates you gave where wrong American Dad! - Tue Apr 24....it should have been the 23 April......I don't know if that is the cause or whether you need to update GIA but it's working perfectly for me

**Comment by Mimpy** [comment]
Thanks Lord.. Good to know it's working for you. The date is what pulled from the cache update so I'm at a loss. Checked my system date and it's fine. And as mentioned, Benidorm downloaded no problem. I'm on the latest GIA. Regarding Last Laugh in Vegas, the finale downloaded no problem as did episode 1 and 2, but not 3....it gave the error above.  Very bizarre. Should I keep this open? Is ITV diddling with the ID directories? I can use the ITV Hub or Downie, so it's not a massive problem. Should I keep this open?

**Comment by Lordsnooty05** [comment]
I don't know if you should keep it open, you would have to take that up with Scott. I tend to think that you should keep it open because it's not working for you and there may be others who it isn't working for. As you say it's not a massive problem if you have Downie which I also use as a backup .....but mainly for YouTube type videos.

**Comment by Vangelis66** [comment]
Hi @Mimpy :smile: 
Are you inside the UK or using some means to geo-spoof?

>  Very bizarre. Should I keep this open?

 With the two shows mentioned in your initial post, using standalone `youtube-dl` produces
```
youtube-dl -F "https://www.itv.com/hub/american-dad/2a4263a0229" =>

[ITV] 2a4263a0229: Downloading webpage
[ITV] 2a4263a0229: Downloading XML
ERROR: ITV said: No match found for production id: 2/4263/0229#001
```
.... so this is definitely another case of #168 (and should've been added there 😉 )
```
youtube-dl -F "https://www.itv.com/hub/whos-doing-the-dishes/2a2898a0024" => 

[ITV] 2a2898a0024: Downloading webpage
[ITV] 2a2898a0024: Downloading XML
ERROR: ITV said: The requested content is not available to this platform
```
 This produces a different error; it is rather cryptic, but one safe guess is there are no RTMPE/HLS streams available (yet) for yt-dl to grab; I tried ITVHub with Mozilla Firefox (52.7.3ESR) and it does play there with DRM'd MPEG-DASH streams (WidevineCDM is required); so it's not a case of "**IE11 on Win10**" only (Microsoft's _PlayReady_ DRM).
I would wait for a couple of more days, either you'll get downloadable HLS streams or ends up being yet another case of #168...

> Regarding Last Laugh in Vegas, the finale downloaded no problem
> as did episode 1 and 2, but not 3....it gave the error above. Very bizarre.

```
youtube-dl -F "https://www.itv.com/hub/last-laugh-in-vegas/2a5081a0003" => 

[ITV] 2a5081a0003: Downloading webpage
[ITV] 2a5081a0003: Downloading XML
[ITV] 2a5081a0003: Downloading JSON metadata
[ITV] 2a5081a0003: Downloading m3u8 information
[info] Available formats for 2a5081a0003:
format code  extension  resolution note
hls-136      mp4        audio only  136k , mp4a.40.2@128k
hls-599      mp4        512x288     599k , avc1.64001F@ 436k, 25.0fps, mp4a.40.2
@128k
hls-792      mp4        512x288     792k , avc1.64001F@ 618k, 25.0fps, mp4a.40.2
@128k
hls-1113     mp4        896x504    1113k , avc1.64001F@ 921k, 25.0fps, mp4a.40.2
@128k
hls-1411     mp4        896x504    1411k , avc1.64001F@1203k, 25.0fps, mp4a.40.2
@128k
hls-1700     mp4        896x504    1700k , avc1.64001F@1475k, 25.0fps, mp4a.40.2
@128k (best)
```
which demonstrates HLS streams are available (now?) for Ep03, so you should be able to fetch 
(NB: these are geo-fenced streams!).

**Comment by Mimpy** [comment]
Thanks Vangelis66. No geo-spoofing on my end. Still unable to download Last Laugh in Vegas along with last night’s American Dad..same error. Too early to check Who’s doing the dishes. 

Thanks for your input.

**Comment by Mimpy** [comment]
Vangelis66, you would have lost some teeth had you spoken to me this way in person. Not everyone who uses this tool knows the intricate workings of it like you do. I have enabled verbose mode and will watch for errors from GIA as you so "respectfully" directed. In the future I will not be participating in reporting anything for fear it being useless information or "whining". Go eff yourself.
