### ISSUE TITLE
is 1.13.4 downloading at a lower image size?

### ISSUE THREAD

**Issue by jchhenderson** [Ascoware/get-iplayer-automator#171]
*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*
nothing special - just downloading a TV series but with v1.13.4 now

*What is the expected output? What do you see instead?*
I normally get 1280x720 video, but now I am getting 960x540 video with no changes in any settings

*What version of GiA are you using? On what version of OS X?*
GiA: 1.13.4
OSX: 10.13.4

*Are you using a web proxy? DNS proxy? VPN? VPS?*
no.

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *
Dragons: Riders of Berk - We are Family, Part 2

*Please provide any additional information below.*

**Comment by jchhenderson** [comment]
hmm - now I am not so sure.  I just checked an earlier episode that I downloaded on 27/Apr and it was also 960x540 so now not entirely sure when the resolution changed...

**Comment by sleaux-meaux** [comment]
Select 50 FPS. Files will be twice the size (~2 Gb per hour of video), but it's the only way to get HD for recent BBC programmes. This has occurred because the BBC is no longer producing HD 25 FPS streams, though some older stuff is still available in 25 FPS. Open the episode info popup for an episode to check. The popup itself is partially broken, but the necessary info will appear in the log window if you have verbose mode selected. If the line beginning "modes:" contains an "hlshd1" entry, the programme is still available in 25 FPS HD.

**Comment by jchhenderson** [comment]
thanks, @sleaux-meaux!

I was trying to avoid 50fps as I understand that every 2nd frame is a repeat frame (and so is 50% wasted space).

What/where is the "episode info popup" that you mention? ...is this in GiA

**Comment by Vangelis66** [comment]
> I understand that every 2nd frame is a repeat frame (and so is 50% wasted space).

Hello :smiley:
Actually, this does not cover all 720p50 encodes offered currently by BBC iPlayer; 
some material has been shot originally in 50fps framerate (in 1080p resolution, maybe higher?), 
that material is offered in iPlayer as true 720p50fps encodes (i.e. a second's worth of video consists of 50 distinct frames). 
You can test a video's frames by using a (software) player capable of frame-by-frame slow-motion; 
the [Live Lounge videos](https://www.bbc.co.uk/iplayer/episodes/p01029mq) are a perfect example of true 50fps encodes (shot "in-house" by a BBC camera crew); other cases involve sports coverage, which  benefits the most from 50fps shooting (as rapid motion during sports is better captured...). 

But, as a general rule of thumb, your understanding does indeed describe the majority of iPlayer content 
(frame duplication to achieve 50fps) :wink: The perfectly sized, legacy, 720p25 encodes will be sorely missed... 😞 

Best regards

**Comment by jchhenderson** [comment]
@Vangelis66 that's good to know - thanks!
