### ISSUE TITLE
Last Broadcast date inaccurate for Radio 4 programmes

### ISSUE THREAD

**Issue by BruceGoatly** [Ascoware/get-iplayer-automator#172]
This is a minor issue only, but it confused me at first, before coffee.

*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*

Searching on 'In our time'

*What is the expected output? What do you see instead?*

A list of In Our Time programmes on Radio 4 with dates of transmission. Instead I see a list with all dates in January (for example today's broadcast is listed as 3 Jan. 2018; last month's are also listed as from January).

*What version of GiA are you using? On what version of OS X?*

GiA 1.13.4; Mac OS 10.13.4.

*Are you using a web proxy? DNS proxy? VPN? VPS?*

None of the above.

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *

In Our Time - The Almoravid Empire

*Please provide any additional information below.*

Screen shot attached.

![screen shot 2018-05-03 at 11 08 01](https://user-images.githubusercontent.com/9452777/39572585-9811d95e-4ec7-11e8-8b32-7f6f81669d57.png)

**Comment by sleaux-meaux** [comment]
Check the date format in your system: 

System Preferences -> Language & Region -> (Select preferred language if multiple entries) -> Advanced -> Dates -> Medium

Did somebody hard-code "Jan." in the format?

**Comment by BruceGoatly** [comment]
Well, you're right - thanks! Bizarrely, it's hard-coded. That's not something I've ever done (and it was working properly last time I checked in GiA), so yesterday's update to OS X must have done it. Not a GiA problem then, but how do I un-hard-code it? There's no drop-down menu for that element!

**Comment by BruceGoatly** [comment]
Sorry - I didn't intend to close the issue, but I will if the query is deemed irrelevant.

**Comment by BruceGoatly** [comment]
That's magic - thanks! I had no idea one could do that with the elements - pretty unintuitive, if you ask me. I'll re-close the issue.

**Comment by skovatch** [comment]
Excellent, thanks for handling this before I even woke up.
