### ISSUE TITLE
GiA hangs retrieving metadata from ITV

### ISSUE THREAD

**Issue by hugofalkman** [Ascoware/get-iplayer-automator#173]
GiA 1.13.4 MacOS 10.13.4

GiA hangs downloading The Americans S06E05 already when retrieving metadata.

Downie downloads successfully HLS stream at 896x504 1584 kbit. (Downie doesn't support metadata.)

Log:
Get iPlayer Automator 1.13.4 Initialized.
GetITVShows: ITV Cache Update Starting 
<AppController: 0x7ff96ad2d380>: Updating Programme Index Feeds...

GetITVShows (Info): Episodes: 1457 Today Programmes: 177 
<AppController: 0x7ff96ad2d380>: Index Updated.
GetITVShows: Update Finished

INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used
AppController: Starting Downloads

Downloading Show 1/1:
ITV Download (ID=2a2471a0070): Downloading The Americans - Series 6 - Episode 5 - 2a2471a0070
INFO: Preparing Request for Auth Info
INFO: Requesting Metadata.

**Comment by skovatch** [comment]
I have no problems downloading this in 1.13.4. Can you turn on verbose and see if you get any other information?

**Comment by hugofalkman** [comment]
That IS the verbose log!

It's now working for me too so ITV must have fixed their metadata. Maybe there should be a timeout on the metadata request.

**Comment by skovatch** [comment]
Hmm... the first verbose message would have been the one notifying you of the metadata request result. There already is a 10 second timeout on the metadata request.

**Comment by hugofalkman** [comment]
Well, in this case the timeout didn't trigger.
