### ISSUE TITLE
Enhancement Request: Added by Series-Link - Last Broadcast

### ISSUE THREAD

**Issue by karelVD** [Ascoware/get-iplayer-automator#174]
Hi all!

I've noticed that when episodes are added by 'Series-Link' the 'Last Broadcast' doesn't show, so I can't order them by broadcast date accordingly. However, when the same episodes are added by 'Add to Queue', the last broadcast date does show up.

Is it just my Get iPlayer automator that does this? If not, then I'd like to suggest this feature for a future enhancement, if possible, please. 

Thanks for the great work!

**Comment by skovatch** [comment]
Fixed with v1.13.9.
