### ISSUE TITLE
GiA not reliably getting 720p version from BBC

### ISSUE THREAD

**Issue by drdmb** [Ascoware/get-iplayer-automator#175]
In the last week or so GiA has been downloading the 960 x 540 version of programmes rather than the 1280 x 720 versions when "HD" is supposedly available.  I do not have the "prefer 50 fps" box checked because those versions are double the size of the 25 fps files.

For example, I downloaded "Live at the Apollo", series 13, episode 4, with GiA and got the 960 x 540 version.  As a check, I used Downie, also.  Downie got a 1280 x 720 version, however it was at 50 fps. 

It is possible that the BBC is not always generating 1280 x 720 at 25 fps, and GiA is getting the best 25 fps version.  Or it may be that this is an indexing issue.

**Comment by sleaux-meaux** [comment]
Already covered in #171
