### ISSUE TITLE
BBC shows not available for download

### ISSUE THREAD

**Issue by damndingo** [Ascoware/get-iplayer-automator#178]
Any BBC show refuse to download since today. Yesterday was fine still.

For example:
BBC Download (ID=b0b0b6ph): Downloading The Bridge: Series 4 - Episode 3
INFO: 1 total programmes
WARNING: No media streams found for requested programme versions and recording modes.
WARNING: The programme may no longer be available - check the iPlayer site.
BBC Download (ID=b0b0b6ph): The Bridge: Series 4 - Episode 3 Failed
AppController: Downloads Finished

*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*
The result is the same, if i use PVR or added by "use current webpage"
The shows are playing in the browser though.

*What is the expected output? What do you see instead?*
See example above.

*What version of GiA are you using? On what version of OS X?*
Version 1.13.4

*Are you using a web proxy? DNS proxy? VPN? VPS?*
I am using Unlocator.com

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *
The Bridge: Series 4 - Episode 3

*Please provide any additional information below.*

**Comment by mutantcamel** [comment]
This is an intermittent network issue with Unlocator, please be aware that the BBC (or their CDN) is actively and aggressively  blocking IPs that are used by VPN services and SmartDNS services like the service you are using.  There's nothing we can do about from the GiA end.

**Comment by stevenfld** [comment]
I don't think your response to the question is correct. I am also using Unlocator and am getting the same error with GIA. However I can play any program on my Mac from BBC Iplayer and I can download programs using BBC Iplayer Downloads. So this would mean that the issue would appear to be with GIA and not Unlocator or BBC blocking Unlocator.

**Comment by skovatch** [comment]
Unlocator appears to be a smart DNS system, so it's not clear what might be causing the problem.

Generally speaking, I don't provide support for getting VPN or smart DNS solutions working with GiA. You may want to describe your issue with the service provider to see if they have any suggestions.

**Comment by rg3rbick** [comment]
The exact same thing has happened to me at the same time.  I can download or watch shows on BBC's website or app but when I try to do the same with get iplayer automator (or using get iplayer that I also have installed) it says that it has determined I am not in the UK.  I am using Nord VPN and using all the latest builds.  It worked fine the morning of may 26th but not the afternoon and not since.

**Comment by skovatch** [comment]
get_iplayer 3.14 is out, and one of its changes is that it now uses https for all of its connections. There are some other changes related to 50 FPS streams being the default, so I will need to make some UI adjustments too, but so far it seems to be working fine.

Give me a day to catch up from Memorial Day weekend and I will push an update.

**Comment by stevenfld** [comment]
Hey Scott:
No worries! I hope you had a great Memorial Day weekend, and thanks so much for keeping GIA on the go.


Sent from Yahoo Mail for iPhone


On Tuesday, May 29, 2018, 2:37 AM, Scott Kovatch <notifications@github.com> wrote:


get_iplayer 3.14 is out, and one of its changes is that it now uses https for all of its connections. There are some other changes related to 50 FPS streams being the default, so I will need to make some UI adjustments too, but so far it seems to be working fine.

Give me a day to catch up from Memorial Day weekend and I will push an update.

**Comment by sleaux-meaux** [comment]
@mutantcamel  is spot on. It doesn't matter that you can access the iPlayer site in your browser. get_iplayer doesn't work that way, so it can be blocked even if you still have access to the iPlayer site. This has always been true for get_iplayer, and it should not come as a surprise to anyone that the Beeb and its CDNs block VPNs. Upgrading get_iplayer will not make any difference, nor will using https. Only your VPN provider can  restore access. It's a cat-and-mouse situation - sometimes your VPN is the cat, sometimes it is the mouse.

**Comment by skovatch** [comment]
The best way to settle this would be to install get_iplayer 3.14 and see if you can download via the command line. If it's still broken then your issue is with Unlocator. If it works then the lack of https is the issue. That said, I think get_iplayer is already using https for all of the actual fetching of video, so it may not help _in this case_. 

All that said, I don't believe GiA is at fault here. I am using smartdnsproxy.com and having no issues, so I'm closing this bug. 

I seem to recall (maybe from someone here?) that BBC is now requiring https connections. That's why get_iplayer had to update recently, and why I suggested that as a reason.

**Comment by sleaux-meaux** [comment]
That won't have any diagnostic value. GiA is already set up for https. You would see different errors if it wasn't.

**Comment by hugofalkman** [comment]
Anyway also Downie stopped working with Unlocator so get_iplayer isn't the problem. I also doubt it's BBC catching up as both streaming and BBC downloads still work. Far more probable it's Unlocator introducing a new bug in a new release of it's offering.

My experience is it's hopeless convincing these services that downloads with some more or less esoteric software no longer works when they can see BBC streaming and BBC's own downloads still work.  Even if they finally comprehend what you complain about, their normal reaction is: "we don't support THAT, we only support BBC streaming and downloads".

So whenever this happens, I just move on to a new service, this time another one with a name starting with "Un" (and ending in "Us"). Works fine with both GiA and Downie.

**Comment by skovatch** [comment]
> Anyway also Downie stopped working with Unlocator so get_iplayer isn't the problem.
Excellent, that's what I was hoping/expecting to hear. And your advice is spot on -- find another one and keep going. I'll just add: don't pay for a year of service up front! You never know when this will happen.

**Comment by stevenfld** [comment]
![screen shot 2018-06-01 at 4 25 01 pm](https://user-images.githubusercontent.com/39712913/40860319-87a02f30-65bf-11e8-93c9-811795b34cb6.png)

Hi there. So changed VPN and problem is solved, almost. Per above screen shot files are downloading as audio under status and GIA is freezing at 99% an not completing the transfer into iTunes. Any ideas?
