### ISSUE TITLE
Coming from 1.8.8pre5, version 1.9b2 reset preferences to default

### ISSUE THREAD

**Issue by hugofalkman** [Ascoware/get-iplayer-automator#18]
Have now tested 1.9b2 on my 10.12.4 Sierra system. Downloading TV shows works fine for both BBC and ITV, both via Search and via the Use Current Webpage button. Downloading subtitles work correctly.

What remains is fixing preferences. We are used to that upgrading to a new release keeps the preferences intact. 1.9b2 reset preferences to default compared to the preferences set in my earlier release 1.8.8pre5. This for instance meant the new advanced option Use Alternative ITV Cache Refresh was deselected, which I think implies that ITV search won't work. Also by default the advanced option Include Downloaded Shows in Search Result was selected. Subtitles were deselected etc, etc.

So my statement everything is working properly, is dependent on my first having restored the preferences to those used in 1.8.8pre5.

ps Under the Download Formats tab in preferences, for BBC TV show formats, in 1.8.8pre5 there were 5 choices: HD, Very High, High, Standard, and Low. In 1.9b2 High is missing so there are only four choices: HD, Very High, Standard, and Low.

**Comment by robincm** [comment]
#hugofalkman: that is strange because they are the ONLY choices I have! 
I did however "transit" from 1.8.8pre5 through 1.9b1.

**Comment by raythw** [comment]
Following on from this, would it be possible to also let users select 720/50fps HVF HD or DVF HDD streams, as supported in GetiPlayer? These formats employ very large files, but they give an exceptionally good picture, with the added bonus of much improved sound.
Many thanks for the work done on this project!

**Comment by skovatch** [comment]
I suspect there are a couple of things at play here... one, there was an issue where the application support folder was being created incorrectly, so preferences might have gotten out of whack. I am reworking this part of the code -- for BBC there will only be Best, Better, Very Good, Good, Worse, and Worst, to be consistent with get_iplayer. ITV has separate fetching logic, so its preferences won't change.

@raythw I will look into adding the 50fps preference flag. That sounds like a reasonable thing to add.

**Comment by skovatch** [comment]
I'm closing this because I'm not going to migrate preferences from version to version. You may need to reset your preferences to get the download formats you want.
