### ISSUE TITLE
1.13.5 fails for ITV (since updating)

### ISSUE THREAD

**Issue by jchhenderson** [Ascoware/get-iplayer-automator#180]
*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*
-> Nothing has changed.  The TV shows are in the PVR.
-> I have changed no settings since upgrading
-> Download formats are default

*What is the expected output? What do you see instead?*
-> successful download

*What version of GiA are you using? On what version of OS X?*
-> 1.13.5

*Are you using a web proxy? DNS proxy? VPN? VPS?*
-> no.

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *
-> Vera

*Please provide any additional information below.*
-> Failure occurs mid download (not at start).
**-> *does* work when "prefer 25 FPS streams if available" is checked.  ...but surely this does not need to be checked if 25FPS is the only stream available??**

**Comment by skovatch** [comment]
"Prefer 25 FPS streams" won't apply -- that option isn't even read for ITV. It may be a coincidence. Which episode of Vera were you trying? I see 3 of them, and 2 for May 24th. Also, try with a verbose log and paste in just the start of the download so I can see what options are being sent to youtube-dl.

**Comment by jchhenderson** [comment]
Hi,

It was 1a7314a0001

I am trying again with verbose on - will let you know.

Thanks!
J.

**Comment by jchhenderson** [comment]
OK, it worked just fine - but Endeavour failed (which was the other one that failed).

J.


Get iPlayer Automator 1.13.5 Initialized.
GetITVShows: ITV Cache Update Starting 
<AppController: 0x7fc261c2a8e0>: Updating Programme Index Feeds...

GetITVShows (Info): Episodes: 1394 Today Programmes: 185 
<AppController: 0x7fc261c2a8e0>: Index Updated.
GetITVShows: Update Finished


INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used
AppController: Starting Downloads


Downloading Show 1/1:

ITV Download (ID=1a7314a0001): Downloading Vera - Sun Jun 03
INFO: Preparing Request for Auth Info
INFO: Requesting Metadata.
DEBUG: Metadata response status code: 200
INFO: Metadata processed.
DEBUG: youtube-dl args:["https://www.itv.com/hub/vera/1a7314a0001", "-f", "mp4/best", "-o", "/Users/jameshenderson/Downloads/GiA/Vera/Vera.s01e01.Hidden Depths.%(ext)s", "--write-sub", "--verbose"]
DEBUG: youtube-dl environment: ["PYTHONPATH": "/Applications/Get iPlayer Automator.app/Contents/Resources", "PATH": "/Applications/Get iPlayer Automator.app/Contents/MacOS:/usr/bin"]
[debug] System config: []

[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.itv.com/hub/vera/1a7314a0001', u'-f', u'mp4/best', u'-o', u'/Users/jameshenderson/Downloads/GiA/Vera/Vera.s01e01.Hidden Depths.%(ext)s', u'--write-sub', u'--verbose']

[debug] Encodings: locale US-ASCII, fs utf-8, out None, pref US-ASCII

[debug] youtube-dl version 2018.05.01

[debug] Python version 2.7.10 (CPython) - Darwin-17.6.0-x86_64-i386-64bit

[debug] exe versions: ffmpeg 3.4.2-tessus, ffprobe N-90346-g86c7d8df95, rtmpdump 2.4-102-ga3a600d-get_iplayer

[debug] Proxy map: {}

[debug] Using fake IP 25.210.10.255 (GB) as X-Forwarded-For.

[ITV] 1a7314a0001: Downloading webpage

**Comment by skovatch** [comment]
One last question for now, since I'm not able to reproduce this. What was the last message you got when it failed? 

I was able to download Endeavour and s1e1 of Vera without problems, so this sounds like a network hiccup on your end. I can't offer any suggestions beyond that unfortunately.

**Comment by jchhenderson** [comment]
The status was "download failed".

...I am with you - I think it is some network issue on my end.

Thanks for the rapid response though :-)
