### ISSUE TITLE
Enhancement: Way for GiA to recognise "BBC iPlayer only" shows

### ISSUE THREAD

**Issue by jchhenderson** [Ascoware/get-iplayer-automator#181]
Some BBC iPlayer shows are not on BBC 1, 2 etc but just on the iPlayer.

I can download these with `<cmd><g>` manually, but is there a way to get them to be seen in the PVR (using "*" as the TV Network doesn't work).

**Comment by skovatch** [comment]
This is something get_iplayer would need to add. The PVR has to look for programs in the cache to do its job, but get_iplayer needs a starting point so it knows where to scrape the HTML to find the program data.

**Comment by skovatch** [comment]
I suspect, though, that they won't do it. The documentation on searching makes it clear that they "only search for programmes that were scheduled for broadcast on BBC linear services within the previous 30 days, even if some are available for more than 30 days on the iPlayer site. BBC Three programmes, iPlayer exclusives, and BBC podcasts are not searchable. Old programmes that are still available after 30 days must be located on the iPlayer site and downloaded directly via PID or URL."

I will change the "Get Current Webpage" so it doesn't obliterate the metadata we did find.

**Comment by jchhenderson** [comment]
closed against #182
