### ISSUE TITLE
v1.13.7. "ignore dash streams" is still there

### ISSUE THREAD

**Issue by jchhenderson** [Ascoware/get-iplayer-automator#184]
**What steps will reproduce the problem? Be specific, and provide as much detail as possible.**
Update to 1.13.7
Go to preferences > Download formats

**What is the expected output? What do you see instead?**
"Force get-player to ignore DASH video" is still there
..it should have gone in this version

**What version of GiA are you using? On what version of OS X?**
1.13.7
OSX 10.13.5

**Please provide any additional information below.**
release notes say this was removed

**Comment by skovatch** [comment]
Whoops! You're right -- I built and tested it all locally and then forgot to regenerate the release archive afterwards. I'll post a new version later this morning.

**Comment by jchhenderson** [comment]
👍

**Comment by skovatch** [comment]
It's later than 'this morning', but fixed in 1.13.8.
