### ISSUE TITLE
Very Large Files

### ISSUE THREAD

**Issue by Lordsnooty05** [Ascoware/get-iplayer-automator#185]
I downloaded last night one episode of the BBC’s excellent drama “A Very English Scandal” and it was a massive 2  GBs whereas the previous episodes were an average 750mbs (large enough). I store these files/episodes on my very large NAS but at this rate I will need another NAS.

**Comment by Lordsnooty05** [comment]
Thanks for that. I did uncheck the higher quality and it had little or no change on the file size. I will do what you say and reduce the 50 FPS to 25 FPS.....it must be that is giving the large file sizes. I don’t remember ever having to adjust that feature....maybe that is a new update that I hadn’t seen before. Thanks again, for drawing my attention to it. I will try it later on today and report back

**Comment by mutantcamel** [comment]
If you have Handbrake installed, you can open the large files in that and it will tell you if you're at 50 or 25 fps.  I have the 25 fps version of these episodes and the largest file is 814MB.  
![a_very_english_scandal_series_1_-_3__episode_3___hvfxsd___mp4](https://user-images.githubusercontent.com/28098325/41189774-a155ac24-6c05-11e8-8fc7-cc9e28fc2006.png)

**Comment by skovatch** [comment]
A recent change in get_iplayer 3.14 is causing this. 50 FPS video is now the default, and it will produce much larger video. See the [release notes](https://github.com/get-iplayer/get_iplayer/wiki/release310to319#release314). I did call this out in the release notes for 1.13.7, but I can't fault you for not noticing it in the upgrade notification.

Note that using 25 FPS means you won't get HD-quality video, except for some reruns broadcast before April 2018. See https://github.com/get-iplayer/get_iplayer/wiki/modes for more information about that.

**Comment by Lordsnooty05** [comment]
Scott thanks. I don't normally look at the changes you have made to each build but these files are very large and quickly fill up my NAS. Obviously I do like a quality recording but and it would have been good if they had been HD quality but beggars can't be choosers .....I'm sure at 25fps will be fine. Thanks
