### ISSUE TITLE
question about "prefer 25 frame video"

### ISSUE THREAD

**Issue by jchhenderson** [Ascoware/get-iplayer-automator#186]
Hi,

If I have quality set to "best" and have checked "prefer 25 frame video if available" can I assume that the 25 frame video will have the same resolution as the 50 frame video (I only want 25 frames if resolution is not lost).

thanks,
James.

**Comment by skovatch** [comment]
Short answer: no. In 'best' mode at 25 fps the highest resolution is 960x540, while at 50 fps it's 1280x720. There are some situations where you can get HD resolution at 25 FPS, but that's mainly for older shows.

I would recommend you check out https://github.com/get-iplayer/get_iplayer/wiki/modes which describes all of the modes and the resolutions they return. With the exception of the --prefs-add, the options shown are exactly what GiA sends to get_iplayer when you request a show. It's very well done, and I learned quite a bit myself.

Trying to turn that myriad of command-line options into a good UI is a difficult problem. You won't be able to do perform all of the fallback logic described in that document in GiA, but maybe with sone UX assistance we could come up with something in the future.
