### ISSUE TITLE
Internal Error 

### ISSUE THREAD

**Issue by JeremyCavanagh** [Ascoware/get-iplayer-automator#19]
[crash-details.txt](https://github.com/Ascoware/get-iplayer-automator/files/996139/crash-details.txt)
[GiA-partial-log.txt](https://github.com/Ascoware/get-iplayer-automator/files/996138/GiA-partial-log.txt)
![output-detail](https://cloud.githubusercontent.com/assets/5337880/25998605/2127f5ca-3722-11e7-9c81-5195f9dce17a.png)
![screenshot](https://cloud.githubusercontent.com/assets/5337880/25998606/2130bed0-3722-11e7-8a5c-6d4542ccd158.png)

What steps will reproduce the problem? Be specific, and provide as much detail as possible.

Just download any programme from iplayer or itvhub

What is the expected output? 

The usual, a successful download.

What do you see instead?

A successful download (no incorrect labeling - I closed my previous issue), but, an internal error is thrown and downloading stops until the continue button is clicked.

What version of GiA are you using? On what version of OS X?

Version 1.9b2 (1821)

Are you using a web proxy? DNS proxy? VPN? VPS?

DNS : Smart DNS Proxy

What programme are you attempting to download (full title, series and episode)? 

BRDC Formula 3 Championship Highlights - Episode 1 

Please provide any additional information below.

I have included a copy of the error details, a partial log file for the programme and a couple of screen shots as illustration.

P.S., You are doing a brilliant job thanks for all your hard work.

**Comment by skovatch** [comment]
Please check with the latest build ([1.9b6](https://github.com/Ascoware/get-iplayer-automator/releases/tag/1.9b6))

**Comment by jefro108** [comment]
I get the same as this even on Version 1.9b7 (1840)

Crash details at https://gist.github.com/jefro108/d5a157d0a2bd2edc61c09f9be91df16d#file-gistfile1-txt

**Comment by skovatch** [comment]
Is this still an issue in v1.9.7? I haven't come across this in any testing.

**Comment by JeremyCavanagh** [comment]
Hi skovatch,
I cured pretty much all of the problems I had by doing a complete clean out of all files and folders associated with GiA and then a fresh install. My current version is Version 1.9 (1841).

There is one area that doesn't seem to perform quite so well (I am on a very slow internet though 2Mbps-the price one pays for living in the French countryside) and that is the program cache which takes an age to update, but I can live with that. The only irritation with it is that GiA does a cache update every 
time I start the app even if that is a few minutes after a previous startup. In its previous existence there was a quick caching facility so GiA was ready for download action within a couple a minutes. Maybe a timestamp associated with the cache file could prevent this full reload. 

Having said all that I am incredibly grateful for all your efforts this is, and always has been a great application.

Regards

Jeremy Cavanagh

**Comment by skovatch** [comment]
Closing this... Please file an enhancement request regarding the caching delay for ITV.
