### ISSUE TITLE
BBC won't download, but iTV does

### ISSUE THREAD

**Issue by Hottsy-Tottsy** [Ascoware/get-iplayer-automator#198]
Second day now where I get "Error Unknown.  Please submit bug..."  

Running version 1.13.12 on Mac 10.13.6

BBC Download (ID=b0bgy739): Downloading The Repair Shop: Series 3 - Episode 10
INFO: 1 total programmes
ERROR: Failed to download URL (3/3): https://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/iptv-all/vpid/b0bgy2vk?cb=52831
ERROR: Response: 403 Forbidden
ERROR: Failed to download URL (3/3): https://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/pc/vpid/b0bgy2vk?cb=80299
ERROR: Response: 403 Forbidden
ERROR: Failed to download URL (3/3): https://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/apple-ipad-hls/vpid/b0bgy2vk?cb=42910
ERROR: Response: 403 Forbidden
WARNING: No media streams found for requested programme versions and recording modes.
WARNING: The programme may no longer be available - check the iPlayer site.
WARNING: If you are outside the UK, check with the provider to find out if your VPN/VPS/Smart DNS/web proxy has been blocked.
BBC Download (ID=b0bgy739): The Repair Shop: Series 3 - Episode 10 Failed
AppController: Downloads Finished
GetITVShows: ITV Cache Update Starting 
<AppController: 0x7fb9ab609240>: Updating Programme Index Feeds...

**Comment by skovatch** [comment]
What are your download format settings? I get 403 errors as well, but am able to download shows. I'm using 'Prefer 25 FPS streams if available', and I start with 'Better' to minimize download size.

**Comment by Vangelis66** [comment]
... Maybe a dupe of #99, that was started by the same person back in January? 

> VPN is working fine

It might well be that his VPN has been, again, blacklisted, as suggested by the log: 

> ERROR: Failed to download URL (3/3): https://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/iptv-all/vpid/b0bgy2vk?cb=52831
ERROR: Response: 403 Forbidden

All 3 `mediaselector/5 API` URLs are **403**, consistent with an **overseas** or a **blacklisted** UK IP address; 
those URLs are the ones generating stream data needed by GiP for BBC TV fetches... 

@Hottsy-Tottsy 
What do you get when you try 
`https://open.live.bbc.co.uk/mediaselector/5/select/version/2.0/mediaset/iptv-all/vpid/b0bgy2vk` 
in a browser? My bet is on a **geolocation** error: 
```xml
<mediaSelection><error id="geolocation"/></mediaSelection>
```
As prompted by GiP, 
> WARNING: If you are outside the UK, check with the provider to find out if your VPN/VPS/Smart DNS/web proxy has been blocked.

 The BBC have been mass blacklisting, in a blanket fashion, the IP pools of all known commercial UK VPS providers in the UK and elsewhere (brands like Amazon, Digital Ocean, Linode, OVH SAS, Rackspace, ArubaCloud, iomart and many others), so services hosted on such servers cease to "work" with BBC iPlayer... 

> but iTV does

Irrelevant; they maintain different IP blacklists, generally more relaxed (at least presently)... 😉

**Comment by Hottsy-Tottsy** [comment]
Not a "dupe" 66, but thanks for your help #99.  I will try your suggestion.  Thank you!!

**Comment by Hottsy-Tottsy** [comment]
Thank you both for your suggestions.  I will give them a try.  

Kind regards

**Comment by Hottsy-Tottsy** [comment]
Today it's working fine without any intervention.  Who knows?  That's why I initially waited for a couple days to report.  Auntie Beeb keeping me on my toes.
