### ISSUE TITLE
Download Failed

### ISSUE THREAD

**Issue by JeremyCavanagh** [Ascoware/get-iplayer-automator#20]
[GiA-partial-log.txt](https://github.com/Ascoware/get-iplayer-automator/files/996216/GiA-partial-log.txt)
![output-screenshot](https://cloud.githubusercontent.com/assets/5337880/25999451/73afcc2a-3725-11e7-8666-2d9e78218719.png)

What steps will reproduce the problem? Be specific, and provide as much detail as possible.

This is a little difficult to say, this happens erratically. It has occurred only occasionally
with less than a dozen files.

What is the expected output? 

The usual successful download.

What do you see instead?

Download Failed. The difference between these files and successful downloads is that the file type being downloaded has a ".ts" extension, whereas, a successful download has a ".flv" extension prior to the conversion to an mp4 file.

What version of GiA are you using? On what version of OS X?

Version 1.9b2 (1821)

Are you using a web proxy? DNS proxy? VPN? VPS?

DNS : Smart DNS Proxy

What programme are you attempting to download (full title, series and episode)? **Provide only ONE programme as an example. DO NOT list multiple programmes.**

The Brits who Built the Modern World - 3. The Politics of Power

Please provide any additional information below.

I have included a partial log file for this download and a partial screenshot of the download folder.

**Comment by approtech** [comment]
I've had the same issue with a number of programmes. Consistently fails to complete the 'Best' quality version, and instead falls back to the 'Better' quality - even if only 'Best' is selected in Preferences > Download Formats > BBC

Example log attached for another episode in the same series noted above; however, in my case Episode 3 did successfully download the 'hlshd' (Best) version.

[GiA Log2.txt](https://github.com/Ascoware/get-iplayer-automator/files/998058/GiA.Log2.txt)

**Comment by JMMheypresto** [comment]
Exactly the same problem. Starts to download 'Best' then switches to 'Better' halfway through. Then either complete or more usually give failed message (even though the lower quality version has downloaded).

**Comment by reded247** [comment]
I am having problems with BBC Three programs, i have been using, Use Current Webpage. The Download starts get to about 2% then fails. I tried to downloading other BBC Three programs using Terminal. But had the same problems as JeremyCavanagh. It would just got to .ts file. 

Have shown the same problems.

![screen shot 2017-05-13 at 13 32 14](https://cloud.githubusercontent.com/assets/28192718/26025481/b56ce25e-37e0-11e7-8391-1e6114fbc59a.png)

**Comment by skovatch** [comment]
Please see the get_iplayer project for more information. This isn't anything that can be helped by GiA.

https://github.com/get-iplayer/get_iplayer/wiki/issues
