### ISSUE TITLE
De-selected cache, now app crashes immediately.

### ISSUE THREAD

**Issue by robincm** [Ascoware/get-iplayer-automator#204]
I inadvertently unticked all boxes in the "items to cache" and now the app (1.13.15) crashes immediately on startup.
I have a working version on another Mac and wonder if someone could point me to where the "prefs" file is kept so I can copy it and insert it onto the failing app? 
Thanks.

**Comment by skovatch** [comment]
Okay, that's bad... I'll try to look at it in the next day or so. The preferences are in
`~/Library/Preferences/com.ascoware.getiPlayerAutomator.plist`

If you have Xcode you can open that file and change the CacheITV_TV or CacheBBC_TV properties to YES and then save the file.

**Comment by robincm** [comment]
Brilliant - @skovatch thankyou very much. All sorted!
And many many thanks for all the work and effort you put in to keep everything up to date & working.
