### ISSUE TITLE
ITV blockng  programmes

### ISSUE THREAD

**Issue by msg362** [Ascoware/get-iplayer-automator#206]
**

**Delete the instructions above before submitting your ticket.**

---------------

*What steps will reproduce the problem? Be specific, and provide as much detail as possible.* Using a UK VPN, iTV has recently stopped working, BBC still works. I posted this on another thread but the OP asked me to start a new thread

*What is the expected output? What do you see instead?*
![untitled](https://user-images.githubusercontent.com/44188098/46997767-c3596180-d14a-11e8-9e76-caa4914cdc6b.jpg)

*What version of GiA are you using? On what version of OS X?* Version GIT version 1.13.15 .    OSX High Sierra 10.13.6

*Are you using a web proxy? DNS proxy? VPN? VPS?* Yes a VPN UK based
*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *  
Butterfly' on ITV

*Please provide any additional information below.* Switched off firewall but still can't ownload. No AV installed

**Comment by skovatch** [comment]
If the issue is with a VPN, get_iplayer or GiA cannot fix the problem. Please refer to the disclaimer in the bug report template.

**Comment by msg362** [comment]
Now have ITV working using  smart DNS , when I load the programme into GIT
it initially appears and identifies the programme (in this case
'Butterfly') but then drops and says Unkown PID, see screen shot.

 Mike
 Sankamphaeng
 Chiang Mai
 Thailand

**Comment by msg362** [comment]
Get iPlayer Automator 1.13.16 Initialized.
<AppController: 0x7fd8e7f42d40>: Updating Programme Index Feeds...

<AppController: 0x7fd8e7f42d40>: Index was Up-To-Date.


INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used
AppController: Starting Downloads


Downloading Show 1/1:

BBC Download (ID=2a5387a0001): Downloading Unknown: PID Not Found
ERROR: Could not extract a valid PID from 2a5387a0001
INFO: 0 total programmes
BBC Download (ID=2a5387a0001): Unknown: PID Not Found Failed
AppController: Downloads Finished

This is the log I get when trying to download from ITV, BBC works fine

**Comment by skovatch** [comment]
How are you getting that program ID into the application? That's an ITV program ID, not a BBC ID.
Search for the name of the show you want to download and then click Add To Queue.

**Comment by msg362** [comment]
I open the programme in the ITV player, it runs there,I stop it and then I
tell GIA to 'Use current webpage',  I get the PID to appear (2a5387a0001)
if I use 'current webpage' and then 'Unknown: PID not found' appears. If I
search for  the programme (in this case 'Butterfly but it happens with
others too),it does not appear


 Mike
 Sankamphaeng
 Chiang Mai
 Thailand

**Comment by skovatch** [comment]
Are you caching ITV shows? If not, turn it on. That's a known bug unfortunately.

**Comment by msg362** [comment]
Scott, thanks, it works when I  cache ITV. So two issues resolved. First,
ITV doesn't like my VPN but accepts a smart DNS connection and then second,
the caching issue.
 Thanks again for your time

 Mike
 Sankamphaeng
 Chiang Mai
 Thailand
