### ISSUE TITLE
New design of iPlayer radio web page - Get Current Webpage broken

### ISSUE THREAD

**Issue by nigelbb** [Ascoware/get-iplayer-automator#207]
The BBC just rolled out a completely new design for the iPlayer radio web pages so that Get Current Webpage no longer works. It used to grab the PID from the URL but it's no longer contained there but must be in the page source somewhere. Clicking on Get Current Webpage gets an error "Programme Page Not Found Please ensure the frontmost browser tab is open to an iPlayer episode page or ITV Hub episode page."

As an example browsing for Sherlock Holmes I get a page https://www.bbc.co.uk/programmes/b0bn94fg for "The Empty House Sherlock HolmesSherlock Holmes with Carleton Hobbs - Series 3  Episode 1 of 7" but evidently this is the series page & clicking on "Listen Live" (which appears instead of Play now) another page is loaded https://www.bbc.co.uk/sounds/play/live:bbc_radio_four_extra with the audio player embedded in the page.

The same problem occurs with Safari & Chrome. MacOS Mojave.

I'm surprised that nobody else has encountered this. Surely I'm not the only person to use Get Current Webpage?

**Comment by nigelbb** [comment]
Here is another example. An episode of "In Our Time" https://www.bbc.co.uk/programmes/m0000nd9 When I have this page open in Chrome or Safari (depending on setting in Preferences) then use Get Current Webpage I get the error 

Series Page Found https://www.bbc.co.uk/programmes/m0000nd9
Please ensure the frontmost browser tab is open to an iPlayer episode page or programme clip page. Get iPlayer Automator doesn't support downloading all available shows from a series.

If I drag that URL into "Quick URL Record" dock icon (from get_iplayer distribution) then the programme is downloaded correctly so it seems that the PID m0000nd9 is correct but that GIA is not parsing the URL correctly.

Unfortunately my main use of GIA is to browse round the iPlayer Radio pages then hit <CTRL>G when I find an interesting looking programme. Get Current Webpage with GIA is by far the simplest way of downloading.

**Comment by skovatch** [comment]
So noted. The BBC must have changed this over the weekend, so I'll have to revisit the page-scraping code. Thanks for the report!

**Comment by nigelbb** [comment]
Thanks for the prompt response. Many thanks for your work on GIA too. You enhance the life of millions:-)

**Comment by naq59** [comment]
Yes, I noticed this but assumed it was maybe just a temporary glitch. I´ve resorted to copy and pasting the URL into GIA for the time being. 
Also many thanks for all the hard work, Skovatch. It´s really appreciated.

**Comment by nigelbb** [comment]
>  I´ve resorted to copy and pasting the URL into GIA for the time being.
How do you do that? I've tried dragging the URL to the Dock icon & to the GIA window but it doesn't work. Where exactly do I paste the URL?

**Comment by hugofalkman** [comment]
@naq59 Seems to work for BBC but not for ITV. From the log (the same PID works when added to queue from search results):

INFO: Got 1747 file cache entries for itv
INFO: Got 7753 file cache entries for tv
INFO: No file cache exists for radio
INFO: Cleaning PID - old: 'https://www.itv.com/hub/action-team/2a5066a0003'
ERROR: Could not extract a valid PID from https://www.itv.com/hub/action-team/2a5066a0003
INFO: 0 total programmes
BBC Download (ID=https://www.itv.com/hub/action-team/2a5066a0003): Unknown: PID Not Found Failed

**Comment by skovatch** [comment]
This particular issue is fixed in 1.13.16. If you find something new please file a new bug.

**Comment by nigelbb** [comment]
> First, click on the URL and copy it. Then click on "+" in GIA, bottom left corner. Double click under PID on the dark blue line and paste URL. Click on "Process PID". Once "available" click on "Start".

Thanks. Good to know if Get Current Webpage stops working the next time the BBC change the webpage layout.
