### ISSUE TITLE
BBC iPlayer Radio moved to BBC Sounds, unable to download programmes

### ISSUE THREAD

**Issue by mgoeppl** [Ascoware/get-iplayer-automator#209]
What steps will reproduce the problem? Be specific, and provide as much detail as possible.
I can't download BBC Sounds programmes.

What is the expected output? What do you see instead?
It returns the infamous "Programme Page Not Found" error.

What version of GiA are you using? On what version of OS X?
GiA 1.13.16 (20181016001)
macOS 10.14.1 Beta (18B57c)

Are you using a web proxy? DNS proxy? VPN? VPS?
VPN, yes. But downloading shows does work like a charm.

What programme are you attempting to download (full title, series and episode)?
https://www.bbc.co.uk/sounds/play/p06pbbdm

**Comment by PC-Thai** [comment]
I have the same problem - cannot use 'Get Current Webpage' on individual shows from BBC Sounds. If they appear in the cache then its fine but if its older than the cache file then you cannot download them...
