### ISSUE TITLE
As some player radio files migrate to the BBC sounds website, the 'Use Current Webpage' button fails

### ISSUE THREAD

**Issue by Cameron999** [Ascoware/get-iplayer-automator#215]
*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*

I browse to a BBC Radio page (eg https://www.bbc.co.uk/programmes/m0001h2l) and then in get-player, click on the Use Current Webpage button and all is well (Both Chrome and Safari).  The BBC is currently moving many things eg Audio Books and some comedy and much music to BBC Sounds (eg https://www.bbc.co.uk/sounds/play/b0br5d8k) which as you can see is at a different URL root.  Now when I press the Use Current Webpage button it gives me the error show below.  Looking at the source code in "GetCurrentWebpage.swift" it is clear that the extract meta data function (?) only looks at iplayer and itv URLs, and not et new Sounds one. 
*What is the expected output? What do you see instead?*
The expected output is that the file for the page I select in sounds now appears in the download list - what actually happens is the menu Programme Page not Found and "Please ensure the frontmost browser tab is open to an iPlayer episode page or ITV Hub episode page." pops up - I suggest this is because it is a Sounds page.
*What version of GiA are you using? On what version of OS X?*
GIA Version 1.13.18 (20181125001), OSX Mojave 10.14.1 (18B75)
*Are you using a web proxy? DNS proxy? VPN? VPS?*
No
*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *
https://www.bbc.co.uk/sounds/play/b0br5d8k
*Please provide any additional information below.*
This may also be the issue reported in Issue hash 209

**Comment by Radiolistener** [comment]
I have the identical experience to that of Cameron999.

**Comment by cgareth** [comment]
There's a work-around:

1. Click the + bottom left to add a blank entry to the download queue
2. Double click on that entry under 'PID'; this opens up a field...
3. ...into which you copy/paste/type the code of the prgramme you want, in the above case 'b0br5d8k'
4. Press enter. Download.

**Comment by Cameron999** [comment]
Thank you cgareth, that works perfectly - it also shows me that I don't know how to use the program.

**Comment by skovatch** [comment]
What @cgareth describes is a good workaround, so thanks for that. That said, a Sounds page is a valid program page, so Get Current Webpage should be able to handle it. I just need to add /sounds/ as a valid root for searching for the metadata.

**Comment by naq59** [comment]
I can load the page now directly without error messages but it still doesn´t download. 1.13.10 is for me the only version working even if it means entering the URLs by hand.

**Comment by skovatch** [comment]
> I can load the page now directly without error messages but it still doesn't download.
This is a problem with your DNS/VPN service and not GiA or GiP. Please see https://github.com/Ascoware/get-iplayer-automator/issues/211#issuecomment-449799373
