### ISSUE TITLE
BBC Subtitles Not Downloading Since Update

### ISSUE THREAD

**Issue by GarthRanzz** [Ascoware/get-iplayer-automator#219]
Since the latest update subtitles have not been downloading for BBC shows. The first time, with yesterday's Luther, I assumed it was a case of the subtitle not being available. But it happened with the latest episode as well. When I tested two programs I had grabbed prior to the update that had subtitles, they did not download again. I've toggled the option off, tried with the embedding option off, toggled back on; no luck.

**Comment by skovatch** [comment]
Oops, looks like `--subtitles` is no longer implied when you use `--subsembed`. You have to supply both arguments now according to the release notes.

Just `--subtitles` should work, however... are you not getting a .srt file if you just use 'Download subtitles'?

**Comment by skovatch** [comment]
I will post a new release sometime today, after I recover from getting back from vacation.

**Comment by GarthRanzz** [comment]
I did and still didn't get an .srt file. Trying another show right now with a fresh install, only 'Download subtitles' checked. I'll let you know if that works.

**Comment by skovatch** [comment]
Fixed in 1.14.2
