### ISSUE TITLE
1.9b3 fails to open

### ISSUE THREAD

**Issue by approtech** [Ascoware/get-iplayer-automator#22]
*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*

Downloaded 1.9b3 and unzipped it. On running, it 'bounces' in the dock for some considerable time (around 2 minutes), then when it stops no windows have opened. At this point, right-clicking on its icon reveals 'Application Not Responding'. Using Force Quit after waiting a few minutes produces the following in CrashReporter:

Filename:
Get iPlayer Automator_D204BCF7-BAF2-52FB-B691-C56764E8958F
File content:
bplist00—]ForceQuitDate3Aæ∆$…Ñ@"

I had renamed the Get iPlayer Automator folder in Application Support first, and it didn't create a new one. I then ran 1.9b2 again, which opened immediately, and created a new folder.

I then ran 1.9b3 again in case having an existing folder in Application Support would make any difference. It still took 2 minutes (actually exactly 2 minutes, so presumably it's hit a Mac OS timeout?) to stop bouncing in the dock, and on Force Quitting it, the Crash Reporter file had almost the same content (presumably that's just the datestamp encoded).

*What is the expected output? What do you see instead?*

Expected GiA main window to open and menu to appear; instead no windows open and menu bar remains focused on Finder.

*What version of GiA are you using? On what version of OS X?*

GiA 1.9b3 / OS X 10.9.5

*Are you using a web proxy? DNS proxy? VPN? VPS?*

No, No, No, No

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *

n/a

*Please provide any additional information below.*
Crash log attached as .txt

[CoreServicesUIAgent_2017-05-12-182028_MMI.crash.txt](https://github.com/Ascoware/get-iplayer-automator/files/997492/CoreServicesUIAgent_2017-05-12-182028_MMI.crash.txt)

**Comment by skovatch** [comment]
This appears to be a bug on Apple's part in 10.9 and signed applications. Look for a new build shortly that should fix it.

**Comment by skovatch** [comment]
Should be fixed in 1.9b4. I don't have 10.9 for testing, though.

**Comment by approtech** [comment]
Excellent! Problem solved on 10.9, opened immediately and works fine.
More importantly, it has resolved the issue I've had all week with downloads failing. that said, it now tags everything as 'Download Failed' even though they succeed, but I'll check other issues for that.

**Comment by skovatch** [comment]
Please open a new issue for that, as I have read/seen that but haven't been able to reproduce it.
