### ISSUE TITLE
Unable to download ITV films

### ISSUE THREAD

**Issue by jefro108** [Ascoware/get-iplayer-automator#220]
I'm unable to download Torvill and Dean https://www.itv.com/hub/torvill-dean/2a5718a0001 and other films from ITV Hub - I get told PID not found.

It's the same with other films like Goodbye Mr Chips https://www.itv.com/hub/goodbye-mr-chips/IND0228a0001

Using the latest version of GiA on High Sierra

**Comment by skovatch** [comment]
For whatever reason, the movies aren't being picked up for the cache, even though they show up in the ITV Hub shows page. I'll have to figure out what's going on.

**Comment by hugofalkman** [comment]
@skovatch For what it's worth, the option Refresh cache every X hours doesn't work for people like me that keep the GiA window open 7/24 in a separate desktop window. At least not for ITV. So I routinely force an update of the cache before I search it.

**Comment by BritTVfan** [comment]
@skovatch First, let me start by thanking you for helping me get my favorite British shows. If Get iPlayer Automator never works for me again, I'll still be grateful for all the shows I have been able to see. That said, is there a reason why I keep having download failures? This has happened for the last few weeks, and it doesn't matter whether I'm trying to download shows on ITV or BBC. I have the latest software update. Any suggestions on what I should do?

**Comment by skovatch** [comment]
@BritTVfan I won't be able to do much based just on your description. Can you make a new bug and attach a log? I can probably suggest something from that.

**Comment by skovatch** [comment]
Also, closing this bug, as it was fixed in 1.14.3.

**Comment by BritTVfan** [comment]
@skovatch Thank you for your prompt reply. I'm not sure how to submit a bug report. But here is the Log: Get iPlayer Automator 1.14.3 Initialized.
GetITVShows: ITV Cache Update Starting 
<AppController: 0x7fc714d41990>: Updating Programme Index Feeds...

GetITVShows (Info): Episodes: 1538 Today Programmes: 168 
<AppController: 0x7fc714d41990>: Index Updated.
GetITVShows: Update Finished
/Applications/Get iPlayer Automator.app/Contents/Resources/get_iplayer
--nocopyright
-e60480000000000000
--type=tv,itv
--listformat=SearchResult|<pid>|<available>|<type>|<name>|<episode>|<channel>|<seriesnum>|<episodenum>|<desc>|<thumbnail>|<web>|<available>
--long
--nopurge
--search
endeavour
--profile-dir=/Users/sheilaburke/Library/Application Support/Get iPlayer Automator


INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used
AppController: Starting Downloads


Downloading Show 1/1:

ITV Download (ID=2a1229a0024): Downloading Endeavour - Sun Feb 10
INFO: Preparing Request for Auth Info
INFO: Metadata processed.
ITV Download (ID=2a1229a0024): youtube-dl finished downloading
AppController: Downloads Finished

**Comment by skovatch** [comment]
At the top right of this page, just click on "New Issue" and fill out the information requested.

This looks like it was a successful download.
