### ISSUE TITLE
no download formats available BBC

### ISSUE THREAD

**Issue by msg362** [Ascoware/get-iplayer-automator#229]
<<<Edited for clarity>>>

**Comment by msg362** [comment]
GIA 1.14.3 VPN from Thailand to UK
Mojave
Tried to download two BBC programmes ( one- Death in Paradise 8,  earlier episodes successful) another test programme also failed.
got 'none of dowload formats available for this show, ' but I have opened all formats 


Get iPlayer Automator 1.14.3 Initialized.
<AppController: 0x7f879ef18fe0>: Updating Programme Index Feeds...

<AppController: 0x7f879ef18fe0>: Index was Up-To-Date.


INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used
AppController: Starting Downloads


Downloading Show 1/1:

BBC Download (ID=m0002vlg): Downloading Death in Paradise: Series 8 - Episode 8
INFO: 1 total programmes
ERROR: Failed to download URL (3/3): https://vod-hls-uk-live.akamaized.net/usp/auth/vod/piff_abr_full_sd_ad/db58a8-m0002vlf/vf_m0002vlf_91882bba-1ab3-4729-ae7c-f3ad8a4864a7.ism.hlsv2.ism/vf_m0002vlf_91882bba-1ab3-4729-ae7c-f3ad8a4864a7.ism.hlsv2.m3u8?__gda__=1551512998_67c14a06e45bb9c64b7bd8f47b65605c
ERROR: Response: 403 Forbidden
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): https://vod-hls-uk-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_sd_ad/db58a8-m0002vlf/vf_m0002vlf_91882bba-1ab3-4729-ae7c-f3ad8a4864a7.ism.hlsv2.ism/vf_m0002vlf_91882bba-1ab3-4729-ae7c-f3ad8a4864a7.ism.hlsv2.m3u8?s=1551469798&e=1551512998&h=dfabe2d659372c94b5a4d8ebf17b6b22
ERROR: Response: 403 Forbidden
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): https://vod-dash-uk-live.akamaized.net/usp/auth/vod/piff_abr_full_sd_ad/db58a8-m0002vlf/vf_m0002vlf_91882bba-1ab3-4729-ae7c-f3ad8a4864a7.ism.hlsv2.ism/iptv_hd_abr_v1_dash_master.mpd?__gda__=1551512998_33214c58130c83a8f13896f5f35c01d6
ERROR: Response: 403 Forbidden
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): https://vod-dash-uk-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_sd_ad/db58a8-m0002vlf/vf_m0002vlf_91882bba-1ab3-4729-ae7c-f3ad8a4864a7.ism.hlsv2.ism/iptv_hd_abr_v1_dash_master.mpd?s=1551469798&e=1551512998&h=ed6aed9d2a17644a0883bd171580bcce
ERROR: Response: 403 Forbidden
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): https://mm.bidi.bbc.co.uk/vod-hls-uk-live/usp/auth/vod/piff_abr_full_sd_ad/db58a8-m0002vlf/vf_m0002vlf_91882bba-1ab3-4729-ae7c-f3ad8a4864a7.ism.hlsv2.ism/vf_m0002vlf_91882bba-1ab3-4729-ae7c-f3ad8a4864a7.ism.hlsv2.m3u8?at=ryumF_na65aa3f105cab4340749e17c025843a10d3c24c4d58312bda65d80
ERROR: Response: 403 Forbidden
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): https://vod-dash-uk-live.akamaized.net/usp/auth/vod/piff_abr_full_sd_ad/db58a8-m0002vlf/vf_m0002vlf_91882bba-1ab3-4729-ae7c-f3ad8a4864a7.ism/pc_hd_abr_v2_dash_master.mpd?__gda__=1551513015_09135d5b09eb7bd0c59be5494a29c98c
ERROR: Response: 403 Forbidden
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): https://vod-dash-uk-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_sd_ad/db58a8-m0002vlf/vf_m0002vlf_91882bba-1ab3-4729-ae7c-f3ad8a4864a7.ism/pc_hd_abr_v2_dash_master.mpd?s=1551469815&e=1551513015&h=8cabe9b0ea47ba59ea448c3c41037701
ERROR: Response: 403 Forbidden
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): http://vod-hls-uk-live.akamaized.net/usp/auth/vod/piff_abr_full_sd_ad/db58a8-m0002vlf/vf_m0002vlf_91882bba-1ab3-4729-ae7c-f3ad8a4864a7.ism/vf_m0002vlf_91882bba-1ab3-4729-ae7c-f3ad8a4864a7.m3u8?__gda__=1551513019_770306c39bef451435c96770b417e634
ERROR: Response: 403 Forbidden
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): http://vod-hls-uk-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_sd_ad/db58a8-m0002vlf/vf_m0002vlf_91882bba-1ab3-4729-ae7c-f3ad8a4864a7.ism/vf_m0002vlf_91882bba-1ab3-4729-ae7c-f3ad8a4864a7.m3u8?s=1551469819&e=1551513019&h=9f2291ed5f73ee44476baeb98723a086
ERROR: Response: 403 Forbidden
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): http://mm.bidi.bbc.co.uk/vod-hls-uk-live/usp/auth/vod/piff_abr_full_sd_ad/db58a8-m0002vlf/vf_m0002vlf_91882bba-1ab3-4729-ae7c-f3ad8a4864a7.ism/vf_m0002vlf_91882bba-1ab3-4729-ae7c-f3ad8a4864a7.m3u8?at=Usgp5QZgbb15b0773c77735bab1ec3031891c74dce5c8a2b58312bee6ccc0
ERROR: Response: 403 Forbidden
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): https://vod-hls-uk-live.akamaized.net/usp/auth/vod/piff_abr_full_hd/db58a8-m0002vlf/vf_m0002vlf_a22a5170-05e3-4b92-b3fd-bea08c21a6e5.ism.hlsv2.ism/vf_m0002vlf_a22a5170-05e3-4b92-b3fd-bea08c21a6e5.ism.hlsv2.m3u8?__gda__=1551513026_a20d5fce58e9829e2ace88309e0731d6
ERROR: Response: 403 Forbidden
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): https://vod-dash-uk-live.akamaized.net/usp/auth/vod/piff_abr_full_hd/db58a8-m0002vlf/vf_m0002vlf_a22a5170-05e3-4b92-b3fd-bea08c21a6e5.ism.hlsv2.ism/iptv_hd_abr_v1_dash_master.mpd?__gda__=1551513026_ba1d1eb2512b1e9b2f4ad261252ff97e
ERROR: Response: 403 Forbidden
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): https://vod-dash-uk-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_hd/db58a8-m0002vlf/vf_m0002vlf_a22a5170-05e3-4b92-b3fd-bea08c21a6e5.ism.hlsv2.ism/iptv_hd_abr_v1_dash_master.mpd?s=1551469826&e=1551513026&h=1df247912137ddbd7655741712f5c914
ERROR: Response: 403 Forbidden
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): https://vod-hls-uk-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_hd/db58a8-m0002vlf/vf_m0002vlf_a22a5170-05e3-4b92-b3fd-bea08c21a6e5.ism.hlsv2.ism/vf_m0002vlf_a22a5170-05e3-4b92-b3fd-bea08c21a6e5.ism.hlsv2.m3u8?s=1551469826&e=1551513026&h=908a89a6744fa26da2c53a1a3a2cae61
ERROR: Response: 403 Forbidden
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): https://mm.bidi.bbc.co.uk/vod-hls-uk-live/usp/auth/vod/piff_abr_full_hd/db58a8-m0002vlf/vf_m0002vlf_a22a5170-05e3-4b92-b3fd-bea08c21a6e5.ism.hlsv2.ism/vf_m0002vlf_a22a5170-05e3-4b92-b3fd-bea08c21a6e5.ism.hlsv2.m3u8?at=9njy9qGk8f589ece32b1bd9f10b65573a955484ba3ca6aed58312bf519c80
ERROR: Response: 403 Forbidden
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): https://vod-dash-uk-live.akamaized.net/usp/auth/vod/piff_abr_full_hd/db58a8-m0002vlf/vf_m0002vlf_a22a5170-05e3-4b92-b3fd-bea08c21a6e5.ism/pc_hd_abr_v2_dash_master.mpd?__gda__=1551513043_0aa12259980cfd850ebc314aa6a19d1d
ERROR: Response: 403 Forbidden
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): https://vod-dash-uk-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_hd/db58a8-m0002vlf/vf_m0002vlf_a22a5170-05e3-4b92-b3fd-bea08c21a6e5.ism/pc_hd_abr_v2_dash_master.mpd?s=1551469843&e=1551513043&h=ee07397dfd95b40240fa861e2aa2eef8
ERROR: Response: 403 Forbidden
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): http://vod-hls-uk-live.akamaized.net/usp/auth/vod/piff_abr_full_hd/db58a8-m0002vlf/vf_m0002vlf_a22a5170-05e3-4b92-b3fd-bea08c21a6e5.ism/vf_m0002vlf_a22a5170-05e3-4b92-b3fd-bea08c21a6e5.m3u8?__gda__=1551513047_4d0714f7b3a3d9808535335431c44d86
ERROR: Response: 403 Forbidden
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): http://vod-hls-uk-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_hd/db58a8-m0002vlf/vf_m0002vlf_a22a5170-05e3-4b92-b3fd-bea08c21a6e5.ism/vf_m0002vlf_a22a5170-05e3-4b92-b3fd-bea08c21a6e5.m3u8?s=1551469847&e=1551513047&h=4de372af129d18e091007cd04cfa407f
ERROR: Response: 403 Forbidden
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): http://mm.bidi.bbc.co.uk/vod-hls-uk-live/usp/auth/vod/piff_abr_full_hd/db58a8-m0002vlf/vf_m0002vlf_a22a5170-05e3-4b92-b3fd-bea08c21a6e5.ism/vf_m0002vlf_a22a5170-05e3-4b92-b3fd-bea08c21a6e5.m3u8?at=8Cn02CSV6e9f91a081ca1e15ac2443258b1eb1b870e03f1c58312c0920bc0
ERROR: Response: 403 Forbidden
ERROR: Ignore this error if programme download is successful
WARNING: A UK TV licence is required to access BBC iPlayer TV content legally
INFO: Downloading tv: 'Death in Paradise: Series 8 - 08. Episode 8 (m0002vlg) [original]'
INFO: No specified modes (radiobetter,hvfhd,dvfhd,hvfsd,dvfsd,hvfxsd,dvfxsd,hvfhigh,dvfhigh,hvfxhigh,dvfxhigh,hvflow,dvflow) available for this programme with version 'original'
INFO: No other modes are available
INFO: The programme may no longer be available - check the iPlayer site
INFO: The programme may only be available in an unsupported format (e.g., Flash) - check the iPlayer site
INFO: If you use a VPN/VPS/Smart DNS/web proxy, check with the provider to find out if it has been blocked
REASON FOR FAILURE: None of the modes in your download format list are available for this show.
Try adding more modes.
BBC Download (ID=m0002vlg): Death in Paradise: Series 8 - Episode 8 Failed
AppController: Downloads Finished










Get iPlayer Automator 1.14.3 Initialized.
<AppController: 0x7f879ef18fe0>: Updating Programme Index Feeds...

<AppController: 0x7f879ef18fe0>: Index was Up-To-Date.


INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used
AppController: Starting Downloads


Downloading Show 1/1:

BBC Download (ID=m0002vlg): Downloading Death in Paradise: Series 8 - Episode 8
INFO: 1 total programmes
ERROR: Failed to download URL (3/3): https://vod-hls-uk-live.akamaized.net/usp/auth/vod/piff_abr_full_sd_ad/db58a8-m0002vlf/vf_m0002vlf_91882bba-1ab3-4729-ae7c-f3ad8a4864a7.ism.hlsv2.ism/vf_m0002vlf_91882bba-1ab3-4729-ae7c-f3ad8a4864a7.ism.hlsv2.m3u8?__gda__=1551512998_67c14a06e45bb9c64b7bd8f47b65605c
ERROR: Response: 403 Forbidden
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): https://vod-hls-uk-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_sd_ad/db58a8-m0002vlf/vf_m0002vlf_91882bba-1ab3-4729-ae7c-f3ad8a4864a7.ism.hlsv2.ism/vf_m0002vlf_91882bba-1ab3-4729-ae7c-f3ad8a4864a7.ism.hlsv2.m3u8?s=1551469798&e=1551512998&h=dfabe2d659372c94b5a4d8ebf17b6b22
ERROR: Response: 403 Forbidden
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): https://vod-dash-uk-live.akamaized.net/usp/auth/vod/piff_abr_full_sd_ad/db58a8-m0002vlf/vf_m0002vlf_91882bba-1ab3-4729-ae7c-f3ad8a4864a7.ism.hlsv2.ism/iptv_hd_abr_v1_dash_master.mpd?__gda__=1551512998_33214c58130c83a8f13896f5f35c01d6
ERROR: Response: 403 Forbidden
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): https://vod-dash-uk-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_sd_ad/db58a8-m0002vlf/vf_m0002vlf_91882bba-1ab3-4729-ae7c-f3ad8a4864a7.ism.hlsv2.ism/iptv_hd_abr_v1_dash_master.mpd?s=1551469798&e=1551512998&h=ed6aed9d2a17644a0883bd171580bcce
ERROR: Response: 403 Forbidden
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): https://mm.bidi.bbc.co.uk/vod-hls-uk-live/usp/auth/vod/piff_abr_full_sd_ad/db58a8-m0002vlf/vf_m0002vlf_91882bba-1ab3-4729-ae7c-f3ad8a4864a7.ism.hlsv2.ism/vf_m0002vlf_91882bba-1ab3-4729-ae7c-f3ad8a4864a7.ism.hlsv2.m3u8?at=ryumF_na65aa3f105cab4340749e17c025843a10d3c24c4d58312bda65d80
ERROR: Response: 403 Forbidden
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): https://vod-dash-uk-live.akamaized.net/usp/auth/vod/piff_abr_full_sd_ad/db58a8-m0002vlf/vf_m0002vlf_91882bba-1ab3-4729-ae7c-f3ad8a4864a7.ism/pc_hd_abr_v2_dash_master.mpd?__gda__=1551513015_09135d5b09eb7bd0c59be5494a29c98c
ERROR: Response: 403 Forbidden
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): https://vod-dash-uk-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_sd_ad/db58a8-m0002vlf/vf_m0002vlf_91882bba-1ab3-4729-ae7c-f3ad8a4864a7.ism/pc_hd_abr_v2_dash_master.mpd?s=1551469815&e=1551513015&h=8cabe9b0ea47ba59ea448c3c41037701
ERROR: Response: 403 Forbidden
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): http://vod-hls-uk-live.akamaized.net/usp/auth/vod/piff_abr_full_sd_ad/db58a8-m0002vlf/vf_m0002vlf_91882bba-1ab3-4729-ae7c-f3ad8a4864a7.ism/vf_m0002vlf_91882bba-1ab3-4729-ae7c-f3ad8a4864a7.m3u8?__gda__=1551513019_770306c39bef451435c96770b417e634
ERROR: Response: 403 Forbidden
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): http://vod-hls-uk-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_sd_ad/db58a8-m0002vlf/vf_m0002vlf_91882bba-1ab3-4729-ae7c-f3ad8a4864a7.ism/vf_m0002vlf_91882bba-1ab3-4729-ae7c-f3ad8a4864a7.m3u8?s=1551469819&e=1551513019&h=9f2291ed5f73ee44476baeb98723a086
ERROR: Response: 403 Forbidden
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): http://mm.bidi.bbc.co.uk/vod-hls-uk-live/usp/auth/vod/piff_abr_full_sd_ad/db58a8-m0002vlf/vf_m0002vlf_91882bba-1ab3-4729-ae7c-f3ad8a4864a7.ism/vf_m0002vlf_91882bba-1ab3-4729-ae7c-f3ad8a4864a7.m3u8?at=Usgp5QZgbb15b0773c77735bab1ec3031891c74dce5c8a2b58312bee6ccc0
ERROR: Response: 403 Forbidden
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): https://vod-hls-uk-live.akamaized.net/usp/auth/vod/piff_abr_full_hd/db58a8-m0002vlf/vf_m0002vlf_a22a5170-05e3-4b92-b3fd-bea08c21a6e5.ism.hlsv2.ism/vf_m0002vlf_a22a5170-05e3-4b92-b3fd-bea08c21a6e5.ism.hlsv2.m3u8?__gda__=1551513026_a20d5fce58e9829e2ace88309e0731d6
ERROR: Response: 403 Forbidden
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): https://vod-dash-uk-live.akamaized.net/usp/auth/vod/piff_abr_full_hd/db58a8-m0002vlf/vf_m0002vlf_a22a5170-05e3-4b92-b3fd-bea08c21a6e5.ism.hlsv2.ism/iptv_hd_abr_v1_dash_master.mpd?__gda__=1551513026_ba1d1eb2512b1e9b2f4ad261252ff97e
ERROR: Response: 403 Forbidden
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): https://vod-dash-uk-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_hd/db58a8-m0002vlf/vf_m0002vlf_a22a5170-05e3-4b92-b3fd-bea08c21a6e5.ism.hlsv2.ism/iptv_hd_abr_v1_dash_master.mpd?s=1551469826&e=1551513026&h=1df247912137ddbd7655741712f5c914
ERROR: Response: 403 Forbidden
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): https://vod-hls-uk-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_hd/db58a8-m0002vlf/vf_m0002vlf_a22a5170-05e3-4b92-b3fd-bea08c21a6e5.ism.hlsv2.ism/vf_m0002vlf_a22a5170-05e3-4b92-b3fd-bea08c21a6e5.ism.hlsv2.m3u8?s=1551469826&e=1551513026&h=908a89a6744fa26da2c53a1a3a2cae61
ERROR: Response: 403 Forbidden
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): https://mm.bidi.bbc.co.uk/vod-hls-uk-live/usp/auth/vod/piff_abr_full_hd/db58a8-m0002vlf/vf_m0002vlf_a22a5170-05e3-4b92-b3fd-bea08c21a6e5.ism.hlsv2.ism/vf_m0002vlf_a22a5170-05e3-4b92-b3fd-bea08c21a6e5.ism.hlsv2.m3u8?at=9njy9qGk8f589ece32b1bd9f10b65573a955484ba3ca6aed58312bf519c80
ERROR: Response: 403 Forbidden
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): https://vod-dash-uk-live.akamaized.net/usp/auth/vod/piff_abr_full_hd/db58a8-m0002vlf/vf_m0002vlf_a22a5170-05e3-4b92-b3fd-bea08c21a6e5.ism/pc_hd_abr_v2_dash_master.mpd?__gda__=1551513043_0aa12259980cfd850ebc314aa6a19d1d
ERROR: Response: 403 Forbidden
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): https://vod-dash-uk-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_hd/db58a8-m0002vlf/vf_m0002vlf_a22a5170-05e3-4b92-b3fd-bea08c21a6e5.ism/pc_hd_abr_v2_dash_master.mpd?s=1551469843&e=1551513043&h=ee07397dfd95b40240fa861e2aa2eef8
ERROR: Response: 403 Forbidden
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): http://vod-hls-uk-live.akamaized.net/usp/auth/vod/piff_abr_full_hd/db58a8-m0002vlf/vf_m0002vlf_a22a5170-05e3-4b92-b3fd-bea08c21a6e5.ism/vf_m0002vlf_a22a5170-05e3-4b92-b3fd-bea08c21a6e5.m3u8?__gda__=1551513047_4d0714f7b3a3d9808535335431c44d86
ERROR: Response: 403 Forbidden
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): http://vod-hls-uk-live.bbcfmt.hs.llnwd.net/usp/auth/vod/piff_abr_full_hd/db58a8-m0002vlf/vf_m0002vlf_a22a5170-05e3-4b92-b3fd-bea08c21a6e5.ism/vf_m0002vlf_a22a5170-05e3-4b92-b3fd-bea08c21a6e5.m3u8?s=1551469847&e=1551513047&h=4de372af129d18e091007cd04cfa407f
ERROR: Response: 403 Forbidden
ERROR: Ignore this error if programme download is successful
ERROR: Failed to download URL (3/3): http://mm.bidi.bbc.co.uk/vod-hls-uk-live/usp/auth/vod/piff_abr_full_hd/db58a8-m0002vlf/vf_m0002vlf_a22a5170-05e3-4b92-b3fd-bea08c21a6e5.ism/vf_m0002vlf_a22a5170-05e3-4b92-b3fd-bea08c21a6e5.m3u8?at=8Cn02CSV6e9f91a081ca1e15ac2443258b1eb1b870e03f1c58312c0920bc0
ERROR: Response: 403 Forbidden
ERROR: Ignore this error if programme download is successful
WARNING: A UK TV licence is required to access BBC iPlayer TV content legally
INFO: Downloading tv: 'Death in Paradise: Series 8 - 08. Episode 8 (m0002vlg) [original]'
INFO: No specified modes (radiobetter,hvfhd,dvfhd,hvfsd,dvfsd,hvfxsd,dvfxsd,hvfhigh,dvfhigh,hvfxhigh,dvfxhigh,hvflow,dvflow) available for this programme with version 'original'
INFO: No other modes are available
INFO: The programme may no longer be available - check the iPlayer site
INFO: The programme may only be available in an unsupported format (e.g., Flash) - check the iPlayer site
INFO: If you use a VPN/VPS/Smart DNS/web proxy, check with the provider to find out if it has been blocked

**Comment by skovatch** [comment]
This is not a GiA or get_iplayer error. The 403 errors means that either your VPN has stopped working or the BBC is now blocking your VPN provider.

**Comment by msg362** [comment]
Thnk you, it sems that the VPN ( HideIPVPN) uk servers (6) are blocked but
their smart DNS works.
Cheers

 Mike
 Sankamphaeng
 Chiang Mai
 Thailand
