### ISSUE TITLE
Downloads falsely tagged as failed

### ISSUE THREAD

**Issue by approtech** [Ascoware/get-iplayer-automator#23]
*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*

Download any BBC programme; the main window list and status bar count up the %age downloaded so far as normal. After 99% it changes to 'Converting..'. The '.partial.mp4' file grows in size as normal. As soon as it's complete and the '.ts' file disappears, notification pops up to say 'download failed' and the status column says 'Download Failed'. The programme is complete and plays correctly, so the 'failed' message is spurious.

Note: ITV programmes correctly show 'Download Complete'.

*What is the expected output? What do you see instead?*

Expect 'Download Complete'; instead get 'Download Failed'.

*What version of GiA are you using? On what version of OS X?*

1.9b4 / OS X 10.9.5

*Are you using a web proxy? DNS proxy? VPN? VPS?*

No

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *

A1: Britain's Longest Road: Series 1: Episode 6
(eventual filename "A1 Britains Longest Road Series 1 - 6. Episode 6 ((hlshd)).mp4")

*Please provide any additional information below.*

Log attached.
[GiA Log1.txt](https://github.com/Ascoware/get-iplayer-automator/files/997983/GiA.Log1.txt)

Other info: I do not add completed downloads to iTunes.

**Comment by skovatch** [comment]
> Other info: I do not add completed downloads to iTunes.
Do you have 'Tag Downloaded Programs with Metadata' on?

**Comment by approtech** [comment]
No, I didn't. Having set it, after 'Converting' the status is then 'Processing Download' followed by 'Download Complete'. (I only turned it off earlier while trying to diagnose another issue.)

**Comment by skovatch** [comment]
Fixed in 1.9b5.
