### ISSUE TITLE
BBC Scotland

### ISSUE THREAD

**Issue by GarthRanzz** [Ascoware/get-iplayer-automator#230]
Will you be adding BBC Scotland as a choice for downloading programmes? Right now none of the available shows appear in a search and you cannot add the channel under preferences. You can download them using with the "Use Current Webpage" function but I'd like to add them to my scheduled downloads.

Thanks!

**Comment by skovatch** [comment]
You should be able to see BBC Scotland in a search by name -- make sure you are running the latest Get iPlayer Automator, which has the get_iplayer with BBC Scotland support. 

I can update the channel selection page for BBC Scotland. I'll have to see if that preference pane needs other cleanup as well.

**Comment by GarthRanzz** [comment]
I'm running 1.15.0 which says it is the latest and greatest. But when I search specifically for Still Game (which just started series 9) I only get a hit on BBC Radio Scotland. And when searching in PVR, nothing comes up. I removed the first two episodes from my download history, just in  case they were what was causing the show not to appear but I still get no results for it in either search.

**Comment by skovatch** [comment]
Is this still an issue for you? I'm seeing all of the episodes of Still Game when I search for it.

**Comment by GarthRanzz** [comment]
I was actually able to see it and other BBC Scotland shows in the search. I first noticed them on Thursday. Prior to that, the previous Thursday, it still wasn't working. But all looks good now.
