### ISSUE TITLE
Issues with Chrome

### ISSUE THREAD

**Issue by abcaster** [Ascoware/get-iplayer-automator#234]
*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*
Problem 1: Attempt to add programme via shortcut Cmd-G fails.
Problem 2: Select GiA->About GiA->Project Homepage produces box: Programme "Google Chrome.app" is no longer open.

*What is the expected output? What do you see instead?*
For 1: Programme added to Queue
For 2: This page opening in Chrome.

*What version of GiA are you using? On what version of OS X?*
GiA: 1.15.0 (20190302001)
OSX: 10.14.3

*Are you using a web proxy? DNS proxy? VPN? VPS?*
No

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *

Adventures in the Big Apple
Composer of the WeekAstor Piazzolla (1921-1992)  Episode 1 of 5
(m0003dbn)

**Comment by skovatch** [comment]
For problem 1, in Mojave you need to give Get iPlayer Automator permission to control Chrome. You can check if it does by selecting System Preferences -> Security & Privacy -> Privacy tab -> Automation section. It will tell you if Get iPlayer Automator.app has permission to control Google Chrome.

That _might_ fix problem 2 as well, but clicking that link should just open your default browser, and I don't think the security settings apply in that case.

**Comment by abcaster** [comment]
It's already switched on, and problem 2 persists.

**Comment by abcaster** [comment]
Everything seems to function normally as of now.
