### ISSUE TITLE
Beachballing on start up

### ISSUE THREAD

**Issue by arijitsadhu** [Ascoware/get-iplayer-automator#24]
On "Updating programme Indexes: 0 Matching Programmes" GIA 1.9b4 hangs with beachball.
Running on 10.9.5.

**Comment by latenightlizzie** [comment]
Same result as @arijitsadhu.  Running on 10.11.6.

**Comment by arijitsadhu** [comment]
Seems that #25 is a duplicate and the fix seems 10.11. Even on 10.11 the updating indexes seem to take a very long time, even if it doesn't beachball.

**Comment by arijitsadhu** [comment]
Seems to be fixed on 1.9b6

**Comment by skovatch** [comment]
This is now fixed since 1.9.3, with the correct configuration of Perl 5.
