### ISSUE TITLE
Proxy user and password not being used with youtube-dl

### ISSUE THREAD

**Issue by devmichaelross** [Ascoware/get-iplayer-automator#241]
When using a proxy with user:pass these details are not passed to youtube-dl resulting in "Authentication Required" from proxy server.

**Comment by skovatch** [comment]
I think I have a fix for this, but I don't use a proxy server so I can't test it. If I post a test build can you please try it before I release it?

**Comment by devmichaelross** [comment]
Yeah of course. No problem at all.

**Comment by skovatch** [comment]
Please download https://github.com/Ascoware/get-iplayer-automator/releases/tag/v1.15.2-beta and let me know how it works.

**Comment by devmichaelross** [comment]
Works perfectly.
[debug] Command-line args: // u'--verbose', u'--proxy', u'user:pass@host:port']

Much appreciated mate.

**Comment by skovatch** [comment]
Thanks! I'll post an official release, probably tomorrow.
