### ISSUE TITLE
Unable to download certain BBC Podcasts

### ISSUE THREAD

**Issue by Radar68** [Ascoware/get-iplayer-automator#248]
*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*
Select Podcast from BBC Sounds app and use GiA to try and download using 'Use Current Webpage' option

*What is the expected output? What do you see instead?*
Expected Podcast to download but received message of failure.  Download is available, starts but then fails.

*What version of GiA are you using? On what version of OS X?*
1.15.2 on OSX 10.13.6

*Are you using a web proxy? DNS proxy? VPN? VPS?*
No

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *
13 Minutes To The Moon.
All episodes are OK EXCEPT 01,05 and 06.

*Please provide any additional information below.*
Get iPlayer Automator 1.15.2 Initialized.
GetITVShows: ITV Cache Update Starting 
<AppController: 0x7fbe3872bec0>: Updating Programme Index Feeds...

INFO: Indexing tv programmes (concurrent)
GetITVShows (Info): Episodes: 1583 Today Programmes: 184 
GetITVShows: Update Finished
INFO: Added 0 tv programmes to cache
<AppController: 0x7fbe3872bec0>: Index Updated.

INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used
AppController: Starting Downloads

Downloading Show 1/3:

BBC Download (ID=w3csz4dj): Downloading 13 Minutes to the Moon: Ep.01 ‘We choose to go’
INFO: 1 total programmes
INFO: No versions of this programme were selected (available versions: podcast2)
BBC Download (ID=w3csz4dj): 13 Minutes to the Moon: Ep.01 ‘We choose to go’ Failed

Downloading Show 2/3:

BBC Download (ID=w3csz4dn): Downloading 13 Minutes to the Moon: Ep.05 The fourth astronaut
INFO: 1 total programmes
INFO: No versions of this programme were selected (available versions: podcast2)
BBC Download (ID=w3csz4dn): 13 Minutes to the Moon: Ep.05 The fourth astronaut Failed

Downloading Show 3/3:

BBC Download (ID=w3csz4dp): Downloading 13 Minutes to the Moon: Ep.06 Saving 1968
INFO: 1 total programmes
INFO: No versions of this programme were selected (available versions: podcast2)
BBC Download (ID=w3csz4dp): 13 Minutes to the Moon: Ep.06 Saving 1968 Failed
AppController: Downloads Finished

**Comment by Vangelis66** [comment]
Hello :smile: 
From your log: 
```
INFO: No versions of this programme were selected (available versions: podcast2)
BBC Download (ID=w3csz4dj): 13 Minutes to the Moon: Ep.01 ‘We choose to go’ Failed
(snip)
INFO: No versions of this programme were selected (available versions: podcast2)
BBC Download (ID=w3csz4dn): 13 Minutes to the Moon: Ep.05 The fourth astronaut Failed
(snip)
INFO: No versions of this programme were selected (available versions: podcast2)
BBC Download (ID=w3csz4dp): 13 Minutes to the Moon: Ep.06 Saving 1968 Failed
```
... Your predicament is due to a fault inside get_iplayer (but down the line it's more of a BBC c*ck up 😞 ), the perl script inside GiA which handles beeb fetches... More precisely, programme version `podcast2` is NOT included inside GiP's default version list, so that version is not tried by the script in an automated fashion; but it can be explicitly requested by the user... 

Please read related entries in the get_iplayer support forum (which isn't open for GiA users, though...): 

https://forums.squarepenguin.co.uk/thread-2024-post-8578.html#pid8578 (and following posts inside that thread...)
https://forums.squarepenguin.co.uk/showthread.php?tid=2018

Best regards

**Comment by skovatch** [comment]
Addressed in a later version of get_iplayer, and incorporated in 1.17.
