### ISSUE TITLE
How to download Box Sets

### ISSUE THREAD

**Issue by stek1961** [Ascoware/get-iplayer-automator#249]
I've tried --pid-recursive, but I only get the first episode, also when I search I don't see the Box Sets listed (command line)

In fact, nothing in box sets seems to come up in searches...

**Comment by skovatch** [comment]
I think this will have to be a new feature. I can’t think of how you would do this in the current UI.

It may be some time before I can look into this; We are moving to San Jose, CA, in the next two weeks so packing and logistics will consume my time for the next month or so.

**Comment by stek1961** [comment]
Your life is more important this this, don't worry! No effort to click all individually but a nice to have for the future...

**Comment by robincm** [comment]
If you are trying to download Box Sets from the BBC try loading bbc.co.uk/iplayer and navigating to the relevant Series. Then open up the page for each individual episode and use "use Current Webpage" before moving on to the next episode.
A bit long winded method but it works for me!!

PS @skovatch good luck with the move!

**Comment by stek1961** [comment]
That's what I do normally - just I was fancying downloading Doctor Who series 1-11 box set, must be about 100 pages to open and click on!

**Comment by hugofalkman** [comment]
Downie supports BBC Box sets. Here is a screen shot. (After selecting the box set you also have to click on More Episodes -- View All, to get the URL to paste into Downie.)

<img width="707" alt="Screenshot 2019-07-11 at 17 03 17" src="https://user-images.githubusercontent.com/10969068/61062313-4b307b80-a3fe-11e9-9822-988575ad3858.png">

**Comment by stek1961** [comment]
Oh! I have Setapp and Downie is on that - never knew it did iPlayer - I'll give it a shot - Cheers!

**Comment by hugofalkman** [comment]
Of course Downie doesn't read the metadata to automatically add it to the right series in iTunes, you have to modify the TV Programme Info manually. You can however modify all episodes at once, by choosing TV Programme Info from the Unknown Programmes thumbnail.

Also Downie doesn't add subtitles automatically to the mp4 file, so after adding a series, you would still have to use Subler to merge in the .srt file for each episode.

**Comment by stek1961** [comment]
Just trying it now - I don't want subbies so that's ok, doesn't seem to grab the whole 11 series though - only one series at a time. Still, quicker than the old method....

**Comment by stek1961** [comment]
Just trying it now - I don't want subbies so that's ok, doesn't seem to grab the whole 11 series though - only one series at a time. Still, quicker than the old method....

**Comment by hugofalkman** [comment]
Yes the Downie support is general, not just for iPlayer. It grabs all links it finds in one URL, and in iPlayer under View All, you only display one series at a time.

**Comment by stek1961** [comment]
And it does Channel 4 too - great! Haven't tried Channel 5 yet....

**Comment by hugofalkman** [comment]
No Channel 4 is all encrypted, Downie will give you an error message when processing.

**Comment by stek1961** [comment]
Ahhh, never mind....

**Comment by skovatch** [comment]
This should be fixed in 1.24.3. Get Current Webpage will use --pid-recursive-list to gather all IDs on a page.
