### ISSUE TITLE
seems to hang on updating programme indexes OSX 10.7.5

### ISSUE THREAD

**Issue by edjonesy** [Ascoware/get-iplayer-automator#25]
*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*
Launch the app and it never gets past the 'Updating Programme Indexes: Using Sequential Indexing...     Updating ITV Indexes'

*What is the expected output? What do you see instead?*
N/A

*What version of GiA are you using? On what version of OS X?*
get-inlayer-automor Version 1.9b4 (1828) Mac OSX 10.7.5

*Are you using a web proxy? DNS proxy? VPN? VPS?*
No

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *
N/A

*Please provide any additional information below.*
When I laugh Version 1.9b4 (1828) on my Mac Pro 1.1 Server Machine running 10.7.5 it doesn't get past the message 'Updating Programme Indexes: Using Sequential Indexing...     Updating ITV Indexes' it has been updating for 3 hours now...

I have tried deleting the get player folder from the application support folder in library but this made no difference, I have installed the same version on my MBP 2013 running 10.12.4 and it launches with no problem.

The app doesn't crash, I can use command Q to quit it, I then get a warning that it is updating the caches.

**Comment by Radar68** [comment]
I believe that GiA relies on the underlying utility get_iplayer, which is a command line (terminal) 'app' that allows the downloading of BBC apps.  GiA is the graphical UI interface to get_iplayer as I understand it.
I also believe that very recently get_iplayer has dropped support for versions of OSX below 10.10.
Given that the issue you (and I) are having on 10.7 relates to the indexing of download data, and thus presumably the underlying get_iplayer, I'd assume that it is not ever going to work.
This seems to be borne out by the fact that your 10.12 machine does work.
Happy to be corrected by the new GiA developers and also happy to have GiA working on 10.7 if possible.  I have however dealt with Dinky over on the get_iplayer forums re get_iplayer on 10.7 and support has sadly, but understandably, been dropped.

**Comment by skovatch** [comment]
If it is the case that 10.10 is now the minimum version for get_iplayer, then I will have no choice but to to do the same for GiA. I don't have the time or resources to maintain backwards compatibility.

I would recommend looking at the Mac wiki page for get_iplayer for more information.

https://github.com/get-iplayer/get_iplayer/wiki/osx
