### ISSUE TITLE
Need help installing

### ISSUE THREAD

**Issue by SpaceOddities** [Ascoware/get-iplayer-automator#250]
I'm a novice so please bear with me!  I have downloaded the latest version as a zip file, I unzip the file and I get a folder called Contents with seemingly the contents of the app.  But what do I now?  I've tried changing the folder to a .app but that won't launch, I can't find any kind of giu executable to launch the software and I've hunted high and low for installation instructions but found nothing.  Can someone help with an idiots guide please?

Many thanks

**Comment by Lordsnooty05** [comment]
I take it you are trying to install it on a Mac and not a Windows computer or laptop?

**Comment by SpaceOddities** [comment]
Yes I'm on a mac and yes I have downloaded the file 'Get.iPlayer.Automator.v1.15.2.b20190425001.zip' from https://github.com/Ascoware/get-iplayer-automator/releases   It unzips to a contents folder, like the package contents of an app but I can't do anything with it.

**Comment by hugofalkman** [comment]
Try downloading the zip file again, using Safari. It should automatically unzip and leave just the app file, that you can then move into the Applications folder.

**Comment by SpaceOddities** [comment]
Brilliant!  That has worked perfectly - I also think that perhaps one of my compressed file utilites was causing an issue too.  Thank you so much!
