### ISSUE TITLE
Integration with YV app under MacOS Catalina

### ISSUE THREAD

**Issue by thornbank** [Ascoware/get-iplayer-automator#251]
[removed boilerplate - skovatch]

**Comment by thornbank** [comment]
GIA runs under Catalina but, as iTunes has been removed is unable to add it to the new TV app. Are there any plans to facilitate this, or will I have to manually add the new downloads ?

Thanks

**Comment by skovatch** [comment]
I definitely plan to upgrade GiA to support Catalina. I don't have spare hardware that I can install the betas on right now, though, and I don't like installing Apple beta OS's on my day-to-day equipment, so it may be some time before I can investigate. Plus, I just moved, so unpacking and doing renovations will take up my weekends for the next month or two at least. 

If someone else has the bandwidth to do some investigation I'm happy to review any changes.

**Comment by skovatch** [comment]
Reopened, as this is definitely a needed thing, and I will want an issue against which I can track any changes.

**Comment by skovatch** [comment]
This was addressed in 1.16.1. TV shows will go to the TV app in Catalina, and iTunes in previous versions.
