### ISSUE TITLE
Cache updates broken due to BBC changes

### ISSUE THREAD

**Issue by skovatch** [Ascoware/get-iplayer-automator#255]
Starting 19-August-2019, or thereabouts, cache updates are not working. The log reports these errors, one for each BBC channel:

WARNING: Got 0 programmes for BBC News schedule page (JSON): https://www.bbc.co.uk/schedules/p00fzl6g/2019/w34

WARNING: Got 0 programmes for BBC Four schedule page (JSON): https://www.bbc.co.uk/schedules/p00fzl6b/2019/w34

WARNING: Got 0 programmes for BBC One Cambridgeshire schedule page (JSON): https://www.bbc.co.uk/schedules/p00fzl6h/2019/w34

etc.

This is due to changes on the BBC's end. A newer get_iplayer is needed. v3.22 was quickly released to address this, and GiA needs to incorporate it.

_Originally posted by @TonyMc589 in https://github.com/Ascoware/get-iplayer-automator/issues/252#issuecomment-522959246_

**Comment by TonyMc589** [comment]
Thanks for the quick response @skovatch

**Comment by Beechside** [comment]
Indeed, thank you @skovatch and for your invaluable ongoing support.  Very much appreciated...

**Comment by skovatch** [comment]
Fixed in v1.16
