### ISSUE TITLE
Download hangs on 'Waiting' status

### ISSUE THREAD

**Issue by winqang** [Ascoware/get-iplayer-automator#257]
*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*
- Open GiA
- Search "Strictly Come Dancing"
- Select "Add to queue"
- Click "Start" 
- Observe

*What is the expected output? What do you see instead?*
- Programme starts downloading

*Actual*
- Programme stays in 'Waiting' status indefinitely

*What version of GiA are you using? On what version of OS X?*
- GiA v1.16
- OS 10.14.6

*Are you using a web proxy? DNS proxy? VPN? VPS?*
- Nope

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *
- Strictly Come Dancing

**Comment by skovatch** [comment]
I was able to download this yesterday with no problems. Can you provide a verbose log showing what's going on while it's in the 'waiting' state?

**Comment by winqang** [comment]
Hey, thanks for replying. Since then I've reverted back to using get_iplayer via my Windows laptop instead. Thanks for looking into anyway.

**Comment by gingerbeardman** [comment]
Friend of mine just got this. Will investigate why when I see them next

**Comment by gingerbeardman** [comment]
So the issue was solved by one/all of:

- moving the app to /Applications folder
- opening using right click menu
- updating to latest version

I suspect it was falling foul of Application Translocation security feature of macOS by trying to run the app from the Downloads foler.
