### ISSUE TITLE
Unable to download radio 3 programmes

### ISSUE THREAD

**Issue by SimonD1000** [Ascoware/get-iplayer-automator#26]
*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*
Find Programme on R3 website, open GiA and choose use current web page. Click Start.
*What is the expected output? What do you see instead?*
Expect programme to download. Get error message saying programme cannot be found.
*What version of GiA are you using? On what version of OS X?*
V 1.8.7 on OSX Sierra 10.12.4
*Are you using a web proxy? DNS proxy? VPN? VPS?*
No
*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *
BBC Radio 3 Record Review (but applies to ANY BBC R3 programme within iPlayer time limits
*Please provide any additional information below.*
Log:
Get iPlayer Automator 1.8.7 Initialized.

Updating Program Index Feeds from Server...
AppController: Index was Up-To-Date.

INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used

AppController: Starting Downloads

Downloading Show 1/1:

BBC Download (ID=b08n1mr1): Downloading Record Review, Andrew McGregor with William Mival and Kate Molleson
WARNING: rdf URL contained no data
WARNING: PID URL contained no RDF data. Trying to record PID directly.
INFO: Trying pid: b08n1mr1 using type: tv
INFO: Trying to stream pid using type tv
INFO: pid not found in tv cache
INFO: 1 Matching Programmes
WARNING: Could not download programme metadata from http://www.bbc.co.uk/programmes/b08n1mr1.xml
ERROR: Failed to get version pid metadata from iplayer site
BBC Download (ID=b08n1mr1): Record Review, Andrew McGregor with William Mival and Kate Molleson Failed

AppController: Downloads Finished

**Comment by nrj53** [comment]
I have a slightly different problem with Radio 3.  Using 1.9.1b2, the programs are cached and I can find them easily, and transfer them to the download window.  But the download fails because  its states that "none of the download formats I specified are available for the show".  I have all three levels of AAC in the preferences, but I have no idea what other format I should specify, or how it can be entered since the "add" tab only brings up the same three AAC options.

**Comment by skovatch** [comment]
@nrj53 you should download a newer build, and then double-check your download preferences. Radio formats are now more generic, and you should be able to download radio in whatever format is available.

**Comment by SimonD1000** [comment]
I have found the beta 1.9 version (version 1.9b4 (1828) and that seems to be working so I guess it is just an update issue. I had tried to update but the Check for updates .. did not work. Will keep a watch for final V1.9

**Comment by nrj53** [comment]
Thanks to both.  Downloaded 1.9.1b6, the latest update.  It found the program and downloaded it perfectly with the format being MPEG-4.  No need to do anything with preferences.

**Comment by gingerbeardman** [comment]
Works for me also.

Vote to close.

**Comment by SimonD1000** [comment]
Yup, looks like it's solved by updating. 1.9.1b6 appears to be the latest available.
