### ISSUE TITLE
macOS Catalina

### ISSUE THREAD

**Issue by Sparkey65** [Ascoware/get-iplayer-automator#260]
Following upgrading to Mac OS Catalina (10.15) get-iPlayer-automator will not work with Safari (Version13.0.2 (15608.2.30.1.1) It still works with Chrome (Version 77.0.3865.90). The attached message is displayed.
<img width="450" alt="Screenshot 2019-10-12 at 20 23 12" src="https://user-images.githubusercontent.com/56488057/66706787-5a8dd080-ed2f-11e9-92d0-c22a6cc01ea4.png">

**Comment by skovatch** [comment]
In the Security and Privacy control panel, scroll down to Automation, click it, and then check for Get iPlayer Automator.app in the list. Is Safari listed below it, and is it checked?

The first time you use GiA to get the frontmost Safari page data macOS should ask you if you want to allow GiA to control Safari.app. But if you clicked "No" at some point, it won't ask you again.

**Comment by Sparkey65** [comment]
Hi Scott

Thanks for your assistance with this. 

Safari as well as Chrome were both selected. However I deselected Safari, shut the apps down, then added Safari back in. Started Safari and Get iPlayer Automator and all is now working.

Regards

Wayne

**Comment by skovatch** [comment]
Great! This is one of those not-well-documented parts of macOS, and the UI for resetting things is not clear at all.

Closing.
