### ISSUE TITLE
Unable to use Safari to download programmes.

### ISSUE THREAD

**Issue by dtw1970** [Ascoware/get-iplayer-automator#261]
I'm using Get iPlayer Automator Version 1.16.1 (20191008001) on macOS Catalina.
I can use the 'USE CURRENT WEB PAGE' option to download programmes using Chrome as my default browser but unable to download this way using Safari as the default browser.
I'm not very technical minded so will try and describe as best I can.
A while ago I updated GiA and an option appeared on screen (which I can vaguely remember). It was something to do with allowing GiA to control Safari and I had to select 'Allow' or 'Do Not Allow'. I meant to select 'Allow' but I was rushing and clicked 'Do Not Allow' by mistake. I'm assuming this is now stopping me download programmes via the 'USE CURRENT WEBPAGE' option through Safari.
Each time I update the app the option to 'Allow' or 'Do Not Allow' control of Safari never reappears.
Is there a way to correct this problem?
Sorry if this sounds confusing.

**Comment by skovatch** [comment]
No worries -- this is a surprisingly common problem. In System Preferences, select Security & Privacy and then the Privacy tab. Scroll down to Automation, and then look for Get iPlayer Automator in the right column. You should see Safari below it, unchecked. Click on it so it's checked again and you should be able to use the feature again.

**Comment by dtw1970** [comment]
Many, many, many thanks for your solution. It worked! The problem I had bugged me for a long time and now you've fixed it for me. Hooray!

**Comment by skovatch** [comment]
Great! I'll close this.
