### ISSUE TITLE
Truncated Subtitles in ITV's Scott & Bailey

### ISSUE THREAD

**Issue by raythw** [Ascoware/get-iplayer-automator#262]
*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*

I successfully downloaded Series 5 of 'Scott & Bailey' from ITV, but several episodes, including 2 and 4 had truncated subtitles at around 22 minutes, apart from episode 7, which appears to be OK. This could be an ITV problem, I suppose, but if anyone could confirm this behaviour it would be appreciated...

*What version of GiA are you using? On what version of OS X?*
Version 1.16.1 (20191008001) and Catalina version 10.15.1 (19B88)

*Are you using a web proxy? DNS proxy? VPN? VPS?*
None of the above

**Comment by hugofalkman** [comment]
There are only 3 episodes in Series 5 of Scott & Bailey https://en.wikipedia.org/wiki/Scott_%26_Bailey#Episodes

**Comment by raythw** [comment]
Oops, I meant series 4, currently available!

**Comment by raythw** [comment]
OK. I repeated the downloads today. I got these results:
S04E05: Ends at 00:22:32 (truncated)
S04E06: Ends at 00:22:08 (truncated)
S04E07: Ends at 00:45:01 (normal)
This could be an ITV fault, of course, but I've no way of proving this one way or t'other!

**Comment by hugofalkman** [comment]
Downloaded S&B S05E01 today -- no subtitles. Checking the streaming version on ITV hub, it didn't have any subtitles either. ITV are very sloppy about subtitles for their reruns, and they don't correct their mistakes after a while either.

**Comment by raythw** [comment]
Thanks for your comments, hugofalkman. Viewing online the other episodes also have their subtitles in a mess, so have to conclude this is ITV's failing...
