### ISSUE TITLE
Radio shows being imported into TV.app not Music.app

### ISSUE THREAD

**Issue by NotHereForever** [Ascoware/get-iplayer-automator#263]
Since updating to MacOS 10.15.1 Catalina from Mojave Get iPlayer Automator (on version 1.16.1 latest) attempts to load a downloaded radio show into the TV/film program TV.app Obviously it should try to import audio files into Music.app. 

Back in the day both went into iTunes of course.

**Comment by NotHereForever** [comment]
As a Workaround it is possible to manually import the files from '/Users/Ms.NotHereForever/Movies/TV Shows' into Music.app

**Comment by TheDunxter** [comment]
I have the same problem with version 1.17 (Catalina 10.15.2). However, if switch back to Safari, then move on to the next episode page and keep Safari as the foreground application GiA loads the radio program to an App it chooses Music rather than TV.

**Comment by NotHereForever** [comment]
Tried that just having Best, in BBC Radio Format. Didn't work for me.

**Comment by TheDunxter** [comment]
I have had success after updating the cache, but even then some older programmes are still considered to be TV programmes. I suspect that the app defaults to TV if the programme isn't in the cache.

**Comment by skovatch** [comment]
I think I have a handle on this... when you are capturing show info from a web page I need to determine if it's a BBC Radio or BBC Sounds page, and set a flag as appropriate. Shows from the cache should be marked correctly, since get_iplayer knows what program feed it used to cache it.

**Comment by skovatch** [comment]
I'm pretty confident this was first fixed in v1.19, so closing this.
