### ISSUE TITLE
GIA 18.1 Crashes

### ISSUE THREAD

**Issue by sxmpete** [Ascoware/get-iplayer-automator#280]
Using Gia 18.1 under MacOS 10.14.6 Mojave, with a VPN.
Attempted download That's My Boy from ITV.
Download appeared ok, but GIA crashed right after downloading thumbnail and just before/as tagging was about to begin. Crash eliminated the GIA log, so attaching Mac Crash Report instead. (FYI, attempted same download with Gia 17, worked fine)
[GIA Crash Log.pdf](https://github.com/Ascoware/get-iplayer-automator/files/4219740/GIA.Crash.Log.pdf)

sxmpete

**Comment by Lordsnooty05** [comment]
Yes, I am having the same problem. I just downloaded the new software and tried to download an episode of "Vera" and it Crashed and then tried it again and it immediately crashed. In the meantime can I download the previous version of Get-iplayer until this one is fixed as I had no problems with the previous version?
Thanks again Scott for all your hard work...it is much appreciated

**Comment by howyallare** [comment]
This bug only affects ITV downloads, so probably best to avoid those until a fix is available. Another option is to temporarily disable metadata tagging in preferences when downloading an ITV programme, but then you would have to re-tag them yourself later.

**Comment by Lordsnooty05** [comment]
I agree but I have moved back to the previous version and it is working without any problems. I have downloaded ITV programmes and BBC without any problems (but then again I don't need subtitles which seems to be the main reason why the software was upgraded)

**Comment by skovatch** [comment]
Oh, I think I know what happened... ffmpeg and AtomicParsley moved to a new location within the application bundle with the new layout of get_iplayer. ITV downloads still use AtomicParsley, but the code wasn't updated to find it in the new location. 

I'll fix this evening. I can't do anything while I'm at work.

**Comment by skovatch** [comment]
Fixed in v1.18.2
