### ISSUE TITLE
Failure to download BBC, multiple shows

### ISSUE THREAD

**Issue by mteller2** [Ascoware/get-iplayer-automator#281]
*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*
Just running GiA

*What is the expected output? What do you see instead?*
Expct download; not failure

*What version of GiA are you using? On what version of OS X?*
1.18.2 on 10.15.3

*Are you using a web proxy? DNS proxy? VPN? VPS?*
VPN

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *
Death in Paradise s9e8

*Please provide any additional information below.*
Verbose log attached for session.
[DiP-fail.pdf](https://github.com/Ascoware/get-iplayer-automator/files/4272466/DiP-fail.pdf)

**Comment by skovatch** [comment]
This is a failure of your VPN service, not GiA. Contact your provider or investigate alternatives.

**Comment by mteller2** [comment]
I thought so and filed a troublw ticket with them. Thanks for confirming…...

Marc Teller ￼￼￼￼
mteller@mjtc.com (MBk)

**Comment by mteller2** [comment]
Scott,
	I follow up question: iPlayer works just fine (with occasional buffering). Is there a significant difference in the way iPlayer and GiA stream that would explain why one works, but the other fails.

Thank you very much for your support,
Marc

Marc Teller ￼￼￼￼
mteller@mjtc.com (MBk)

**Comment by mteller2** [comment]
Scott,
	Sorry to bother you, but quick question. Do you use just the DNS service or both DNS and VPN from smartDNS? I am planning to try them out. Just the DNS does not seem to work (although it could be a setup problem)…

Thanks, in advance,
Marc

Marc Teller ￼￼￼￼
mteller@mjtc.com (MBk)

**Comment by skovatch** [comment]
I don't use smartDNS anymore. They haven't worked for some time. Try [this](https://www.dns4me.net) instead.

**Comment by mteller2** [comment]
Scott,
	Sorry to bother you again. Before I reach out to the service you suggested; I thought you might have some insight. I signed up for the trial, the 2 channels supported are selected, the 2 system checks passed, but I fail to get going. I have attached the GiA log.

	Any insights? I will open a service ticket if no….



Marc Teller ￼￼￼￼
mteller@mjtc.com (MBk)
