### ISSUE TITLE
Cannot differentiate between Series 1 and Series 12

### ISSUE THREAD

**Issue by jchhenderson** [Ascoware/get-iplayer-automator#283]
Hi,

I am trying to download "New tricks: Season 1" (it may never happen, but I have it in my PVR) but it keeps trying to download Season 12 (which I already have).

Obviously, not a massive issue, but certain REGEX codes work, but some seem not to.

**Works:**
`^` works (start of string)
`\` works (escape)

**Does not work:**
`$` does not work (end of string)

**Examples**
`^Noughts \+ Crosses: Series 1` **finds all 3 episodes**
`^Noughts \+ Crosses: Series 1$` **finds nothing**

My real case is:
`New tricks: Series 1$` to get season1, but not season 12

Am I simply using the wrong character for "end of string" or does it simply not work?

**Comment by howyallare** [comment]
The string being searched contains more than just the series title, so constrain your match to a word boundary instead of end of string.

**Comment by jchhenderson** [comment]
thanks.  do you mean with `\>` - that didn't work for me.

**Comment by howyallare** [comment]
Only Perl regular expressions can be used.

**Comment by jchhenderson** [comment]
cheers.
