### ISSUE TITLE
GiA hangs on Retrieving Programme Metadata for many but not all ITV downloads

### ISSUE THREAD

**Issue by hugofalkman** [Ascoware/get-iplayer-automator#286]
This is ITV only, BBC works ok.
I have waited an hour to verify it's really hanging. 
Sometimes it helps restarting GiA.
Downie works fine for all ITV downloads.
GiA 1.18.2 MacOS Catalina 1.15.4.

Here is an example log:
Get iPlayer Automator 1.18.2 Initialized.
GetITVShows: ITV Cache Update Starting 
<AppController: 0x7fd33573fa90>: Updating Programme Index Feeds...

/Applications/Get iPlayer Automator.app/Contents/Resources/get_iplayer/perl-darwin-2level/bin/get_iplayer
-e14400
--type=tv
--refresh
--nopurge
--profile-dir=/Users/zilla/Library/Application Support/Get iPlayer Automator
.*
INFO: Indexing tv programmes (concurrent)
INFO: Added 6 tv programmes to cache
GetITVListings (Error(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSErrorFailingURLStringKey=https://www.itv.com/hub/tonight/1a2803, NSErrorFailingURLKey=https://www.itv.com/hub/tonight/1a2803, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2103, NSLocalizedDescription=The request timed out.})): Unable to retreive programme episodes for https://www.itv.com/hub/tonight/1a2803
GetITVShows (Info): Episodes: 1765 Today Programmes: 209 
<AppController: 0x7fd33573fa90>: Index Updated.
GetITVShows: Update Finished
/Applications/Get iPlayer Automator.app/Contents/Resources/get_iplayer/perl-darwin-2level/bin/get_iplayer
--nocopyright
-e60480000000000000
--type=tv,itv
--listformat=SearchResult|<pid>|<available>|<type>|<name>|<episode>|<channel>|<seriesnum>|<episodenum>|<desc>|<thumbnail>|<web>|<available>
--long
--nopurge
--search
van der valk
--profile-dir=/Users/zilla/Library/Application Support/Get iPlayer Automator
--hide

INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used
AppController: Starting Downloads

Downloading Show 1/1:

ITV Download (ID=2a7219a0003): Downloading Van der Valk - Sun May 10
INFO: Preparing Request for Auth Info
INFO: Requesting Metadata.

**Comment by skovatch** [comment]
Sorry, but I haven't seen any ITV issues in the past 3 days. Seems fine to me.

**Comment by raythw** [comment]
I had this problem with episode 3 of 'Flesh and Blood', another episode as well. Sometimes I've had it with other ITV shows as well, but never BBC. The download is completed perfectly, but then the programme fails to get added to the TV app and is left untagged, usually without show artwork as well. Another variation is for the programme to be added the TV application, again without artwork or tags, but added as a Home Video, presumably because the Media Type hasn't been defined. Exceptionally annoying, but I suspect impossible to repeat or fix...

**Comment by skovatch** [comment]
I have been seeing this more and more often, and I think I tracked it down. There's a lot of bad logic around tasks, pipes, and file handles, and I think there's a bad leak as a result. I was able to download multiple copies of Poirot to completion, which wasn't working before.

**Comment by skovatch** [comment]
Please check if this is still an issue in v1.21.7.
