### ISSUE TITLE
Unable to download BBC radio

### ISSUE THREAD

**Issue by petermok** [Ascoware/get-iplayer-automator#287]
It just says "problem unknown"...I was able to download last week but this week all bets seem off. Already upgraded to the latest version. Please advise. Thanks!

**Comment by skovatch** [comment]
Can you attach a log? Turn on verbose mode and see where it’s failing. Thanks!

**Comment by petermok** [comment]
Get iPlayer Automator 1.17 Initialized.
<AppController: 0x7fdf1ac64730>: Updating Programme Index Feeds...

INFO: Indexing radio programmes (concurrent)
INFO: Added 813 radio programmes to cache
<AppController: 0x7fdf1ac64730>: Index Updated.


INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used
AppController: Starting Downloads


Downloading Show 1/1:

BBC Download (ID=b008756f): Downloading Peter Bradshaw - For One Horrible Moment - Episode 3
INFO: 1 total programmes
INFO: Downloading radio: 'Peter Bradshaw - For One Horrible Moment - 03. Episode 3 (b008756f) [original]'
ERROR: Cannot write to /Volumes/VAULT/BBC DOWNLOAD/Peter Bradshaw - For One Horrible Moment/Peter Bradshaw - For One Horrible Moment - 03. Episode 3 ((hafmed)).audio.ts
BBC Download (ID=b008756f): Peter Bradshaw - For One Horrible Moment - Episode 3 Failed

Downloading Show 2/3:

BBC Download (ID=b0084ss4): Downloading Retrieving Metadata...
INFO: 1 total programmes
INFO: Downloading radio: 'Peter Bradshaw - For One Horrible Moment - 02. Episode 2 (b0084ss4) [original]'
ERROR: Cannot write to /Volumes/VAULT/BBC DOWNLOAD/Peter Bradshaw - For One Horrible Moment/Peter Bradshaw - For One Horrible Moment - 02. Episode 2 ((hafmed)).audio.ts
BBC Download (ID=b0084ss4): Peter Bradshaw - For One Horrible Moment: Episode 2 Failed

Downloading Show 3/3:

BBC Download (ID=b0082khk): Downloading Peter Bradshaw - For One Horrible Moment: Episode 1
INFO: 1 total programmes
INFO: Downloading radio: 'Peter Bradshaw - For One Horrible Moment - 01. Episode 1 (b0082khk) [original]'
ERROR: Cannot write to /Volumes/VAULT/BBC DOWNLOAD/Peter Bradshaw - For One Horrible Moment/Peter Bradshaw - For One Horrible Moment - 01. Episode 1 ((hafmed)).audio.ts
BBC Download (ID=b0082khk): Peter Bradshaw - For One Horrible Moment: Episode 1 Failed
AppController: Downloads Finished

**Comment by petermok** [comment]
Originally I thought it was a VPN issue but apparently jumping different locations did not help.

**Comment by petermok** [comment]
Oh darn, it is a storage issue. Sorry.
