### ISSUE TITLE
youtube-dl DMCA'ed by RIAA

### ISSUE THREAD

**Issue by Vangelis66** [Ascoware/get-iplayer-automator#294]
[Edited by @skovatch; see replies]

The future of youtube-dl is uncertain at best. GiA relies on it for downloading ITV content, so any problems that arise due to changes on ITV's end may or may not be fixed in youtube-dl.

We should reconsider how GiA fetches video from ITV. In the past GiA used a combination of native code and rtmpdump to do the job. Some alternatives:

- Investigate using Foundation/NSURLSession to accomplish what youtube-dl does
- Look into extracting just the ITV code from youtube-dl and include that.

**Comment by skovatch** [comment]
@Vangelis66 thanks for the heads up. I had seen hints of this on Twitter but hadn't fully paid attention to it. I kept your message but changed this issue to track concrete things we can do in this project.

I'd love to get a message board going for more discussions like these, but I don't have the spare time for it.

**Comment by Vangelis66** [comment]
> I'd love to get a message board going for more discussions like these, but I don't have the spare time for it.

If **GitHub** remains the "_place_" of choice, perhaps you should consider the `GitHub Discussions` new feature:

https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/#discussions

https://github.community/t/can-one-apply-for-github-discussions-beta/121120

https://github.com/vercel/vercel/discussions/3874

It's currently in a public beta testing stage, a repo owner has to apply/ask for it (and agree to sending feedback to GitHub...); it is mentioned somewhere that the (public) repo has to have a minimum of **3** contributors to be eligible, does GiA fulfill this?

**Comment by jefro108** [comment]
There's a fork of youtube-dl that is more up to date anyway https://github.com/blackjack4494/yt-dlc 

> youtube-dlc is a fork of youtube-dl with the intention of getting features tested by the community merged in the tool faster, since youtube-dl's development seems to be slowing down.

**Comment by skovatch** [comment]
Unfortunately, I think there has only been one other contributor since I took over the project. I'm open to fixes/other help as always but based on those criteria, no.

**Comment by skovatch** [comment]
> There's a fork of youtube-dl that is more up to date anyway https://github.com/blackjack4494/yt-dlc
Thanks, that's good to know, although there hasn't been a lot of activity specifically for ITV in some time. I keep it up to date in case of security issues, or other internals.

**Comment by skovatch** [comment]
youtube-dl has been restored, thanks to some sharp lawyering by the EFF: https://github.blog/2020-11-16-standing-up-for-developers-youtube-dl-is-back/

I'm closing this, though I'll keep the yt-dlc project in mind.

**Comment by Vangelis66** [comment]
I wrote: 

> If **GitHub** remains the "place" of choice, perhaps you should consider the **GitHub Discussions** new feature:
>
> https://github.community/t/can-one-apply-for-github-discussions-beta/121120
>
> It's currently in a (public) beta testing stage, a repo owner has to apply/ask for it (and agree to sending feedback to 
> GitHub...); it is mentioned somewhere that the (public) repo has to have a **minimum of 3 contributors** to be eligible,

@skovatch replied: 

> Unfortunately, I think there has only been **one** other contributor since I took over the project

... Well then, I have great news as the **GitHub Discussions** repo feature has been made available to **ALL public** GitHub repositories, **regardless of contributors number**...

https://github.community/t/can-one-apply-for-github-discussions-beta/121120/550

I've just checked and it's even available (via settings) in one of my forks: 

![GHD](https://user-images.githubusercontent.com/9669492/101583638-92041580-39e4-11eb-94a2-76bcfe3b825e.jpg)

@skovatch, what do you reckon? 

Kindest regards!
