### ISSUE TITLE
ITV max out at 504p

### ISSUE THREAD

**Issue by KiaN2020** [Ascoware/get-iplayer-automator#295]
ITV downloads seem to only download at 504p is there anyway to download the HD version or is this not possible due to ITV Hub using dash format for higher quality and the 504p are unprotected HLS formats?

Thank You.

**Comment by skovatch** [comment]
Here's what youtube-dl reports for the available formats:

```
$ youtube-dl https://www.itv.com/hub/dont-rock-the-boat/10a0461a0001 --list-format
[ITV] 10a0461a0001: Downloading webpage
[ITV] 10a0461a0001: Downloading XML
WARNING: Unable to download XML: HTTP Error 504: Gateway Time-out
[ITV] 10a0461a0001: Downloading JSON metadata
[ITV] 10a0461a0001: Downloading m3u8 information
[info] Available formats for 10a0461a0001:
format code  extension  resolution note
hls-136      mp4        audio only  136k , mp4a.40.2@128k
hls-633      mp4        512x288     633k , avc1.64001F@ 469k, 50.0fps, mp4a.40.2@128k
hls-834      mp4        512x288     834k , avc1.64001F@ 658k, 50.0fps, mp4a.40.2@128k
hls-1186     mp4        896x504    1186k , avc1.64001F@ 990k, 50.0fps, mp4a.40.2@128k
hls-1480     mp4        896x504    1480k , avc1.64001F@1268k, 50.0fps, mp4a.40.2@128k
hls-1777     mp4        896x504    1777k , avc1.64001F@1548k, 50.0fps, mp4a.40.2@128k (best)
```

So, the best we can get out of youtube-dl is 896x504. I don't know if there's any way to get higher resolutions. If someone has time to investigate and can provide a solution I can look into it further.

**Comment by KiaN2020** [comment]
Thank you for the reply and would be great if there was a way to get the higher resolutions but I know that those are dash streams, I am assuming that the reason that youtube-dl can grab the 896x504 streams is due to them being hls streams.

**Comment by JeremyCavanagh** [comment]
Hi,
I don't think HD downloads are possible from the ITV hub since the general broadcast programmes are not HD, those are only available via pay TV, i.e., Sky.
Regards
Jeremy

**Comment by KiaN2020** [comment]
@ JeremyCavanagh that will explain it then.

Thank you

**Comment by skovatch** [comment]
Closing this, because even if they were available it's a youtube-dl feature anyway.
