### ISSUE TITLE
Re-build for Apple M1 chip systems (universal binary)

### ISSUE THREAD

**Issue by mteller2** [Ascoware/get-iplayer-automator#296]
At your earliest convenience can you rebuild the codebase in a Universal Application form with support for the new Apple M1 based systems. This is an **enhancement** request obviously, GiA still works running under Rosetta2. Thank you, in advance.

**Comment by Sircam19** [comment]
Thanks mteller2  for flagging this and also letting us know that it still works under Rosetta 2- I really wondered it that would be the case. Cheers

**Comment by skovatch** [comment]
Done, though keep in mind that I don't build the embedded helper apps, they come from get_iplayer. I suppose AtomicParsley could be rebuilt for M1 at some point.
