### ISSUE TITLE
iTV Downloads Not Working 

### ISSUE THREAD

**Issue by Hottsy-Tottsy** [Ascoware/get-iplayer-automator#297]
Getting the following error:
Downloading Show 1/2:

ITV Download (ID=2a1166a0197): Downloading The Jonathan Ross Show - Sun Nov 29
INFO: Preparing Request for Auth Info
INFO: Requesting Metadata.
DEBUG: Metadata response status code: 200
INFO: Metadata processed.
DEBUG: youtube-dl args:["https://www.itv.com/hub/the-jonathan-ross-show/2a1166a0197", "-f", "mp4/best", "-o", "/Users/tonnysadha/Documents/iPlayer Downloads /The Jonathan Ross Show/The Jonathan Ross Show.s16e07.Episode 7.%(ext)s", "--write-sub", "--embed-subs", "--verbose"]
DEBUG: youtube-dl environment: ["PYTHONPATH": "/Applications/Get iPlayer Automator.app/Contents/Resources", "PATH": "/Applications/Get iPlayer Automator.app/Contents/MacOS:/Applications/Get iPlayer Automator.app/Contents/Resources/get_iplayer/utils/bin:/usr/bin"]
[debug] System config: []

[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'https://www.itv.com/hub/the-jonathan-ross-show/2a1166a0197', u'-f', u'mp4/best', u'-o', u'/Users/tonnysadha/Documents/iPlayer Downloads /The Jonathan Ross Show/The Jonathan Ross Show.s16e07.Episode 7.%(ext)s', u'--write-sub', u'--embed-subs', u'--verbose']

[debug] Encodings: locale US-ASCII, fs utf-8, out None, pref US-ASCII

[debug] youtube-dl version 2020.07.28

[debug] Python version 2.7.16 (CPython) - Darwin-19.6.0-x86_64-i386-64bit

[debug] exe versions: ffmpeg 4.3, rtmpdump 2.4-102-ga3a600d-get_iplayer
[debug] Proxy map: {}

[ITV] 2a1166a0197: Downloading webpage

[ITV] 2a1166a0197: Downloading XML

WARNING: Unable to download XML: HTTP Error 504: Gateway Time-out

[ITV] 2a1166a0197: Downloading JSON metadata

WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden

ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Traceback (most recent call last):
  File "/Applications/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/YoutubeDL.py", line 797, in extract_info
    ie_result = ie.extract(url)
  File "/Applications/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/extractor/common.py", line 530, in extract
    ie_result = self._real_extract(url)
  File "/Applications/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/extractor/itv.py", line 260, in _real_extract
    self._sort_formats(formats)
  File "/Applications/Get iPlayer Automator.app/Contents/Resources/youtube-dl/youtube_dl/extractor/common.py", line 1350, in _sort_formats
    raise ExtractorError('No video formats found')
ExtractorError: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by skovatch** [comment]
403 error is 'forbidden', which usually means you aren't in the UK or your VPN is failing. I should make sure this is being handled cleanly, in any event.

**Comment by Hottsy-Tottsy** [comment]
Thank you, Scott.  I’ve raised the issue with them.  Wasn’t sure as BBC downloads were working just fine.

regards
Corey

**Comment by cgareth** [comment]
Hi Scott,
I've had the same issue for a while now, thinking that still using OS Sierra is the problem. I get exactly the same error log as Corey above, but in place of "HTTP Error 403", I get 

"...

WARNING: Unable to download XML: HTTP Error 504: Gateway Time-out

[ITV] 1a5274a0013: Downloading JSON metadata

**[ITV] 1a5274a0013: Downloading m3u8 information

WARNING: Failed to download m3u8 information: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)>**

Am I able to do anything about this?

Thanks, as always.

Gareth

**Comment by skovatch** [comment]
> I've had the same issue for a while now, thinking that still using OS Sierra is the problem. I get exactly the same error log as Corey above, but in place of "HTTP Error 403", I get
> 
> WARNING: Failed to download m3u8 information: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)>**

youtube-dl uses Python, and the issue here is that Sierra has an older version of OpenSSL and Python. That combination only supports TLS v1 for secure connections but TLS v1 is no longer considered to be secure. The fix is upgrading the system Python or OpenSSL, neither of which are trivial to do.

That problem is being tracked in another bug.

**Comment by Hottsy-Tottsy** [comment]
Mine is working again after speaking with my VPN provider.

**Comment by skovatch** [comment]
OK, closing this one.
