### ISSUE TITLE
Problems Downloading Emmerdale from ITV Hub

### ISSUE THREAD

**Issue by Shadow1955** [Ascoware/get-iplayer-automator#298]
Since Monday I have problems downloading from ITV Hub. I am using a VPN to the UK and it all works fine with BBC Content. The log dhows finished but the report is failed and I only have parts downloaded. Here is the log:

Get iPlayer Automator 1.19.3 Initialized.
GetITVShows: ITV Cache Update Starting 
<AppController: 0x7fe246c82a20>: Updating Programme Index Feeds...

INFO: Indexing tv programmes (concurrent)
INFO: Added 0 tv programmes to cache
GetITVShows (Info): Episodes: 3101 Today Programmes: 314 
<AppController: 0x7fe246c82a20>: Index Updated.
GetITVShows: Update Finished

INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used
AppController: Starting Downloads

Downloading Show 1/4:

ITV Download (ID=1a8694a8909): Downloading Emmerdale - Wed Dec 09
INFO: Preparing Request for Auth Info
INFO: Metadata processed.
ITV Download (ID=1a8694a8909): youtube-dl finished downloading

Downloading Show 2/4:

ITV Download (ID=1a8694a8908): Downloading Emmerdale - Tue Dec 08
INFO: Preparing Request for Auth Info
INFO: Metadata processed.
ITV Download (ID=1a8694a8908): youtube-dl finished downloading

Downloading Show 3/4:

ITV Download (ID=1a8694a8907): Downloading Emmerdale - Mon Dec 07
INFO: Preparing Request for Auth Info
INFO: Metadata processed.
ITV Download (ID=1a8694a8907): youtube-dl finished downloading

Downloading Show 4/4:

ITV Download (ID=1a8694a8906): Downloading Emmerdale - Fri Dec 04
INFO: Preparing Request for Auth Info
INFO: Metadata processed.
ITV Download (ID=1a8694a8906): youtube-dl finished downloading
AppController: Downloads Finished

**Comment by skovatch** [comment]
I'm downloading "5 Gold Rings" right now without trouble. The Wed Dec 9 Emmerdale was rejected with a 403 error, but that may be a one-time thing. Check with your VPN provider to see if they are able to get in.

VPN issues are out of GiA and get_iplayer's control, so I'm closing this.
