### ISSUE TITLE
Feature Request: grab all available episodes from webpage (iPlayer)

### ISSUE THREAD

**Issue by ashleycox** [Ascoware/get-iplayer-automator#306]
I was recently downloading some series' using the iPlayer website and the 'user current webpage' option as the results weren't available in search. It would be great if GIA had a feature whereby it could automatically track down all available episodes on the website based on a program added to the queue. Or perhaps if one were to press the 'use current webpage' button with a page of episodes open, as opposed to a program, it could analyse the page and automatically add any episodes based on the links it finds, following the pagination as it goes. Thanks for a great app.

**Comment by skovatch** [comment]
Have you seen the PVR feature? Search for a show, click on it, then click Auto Record, and GiA will automatically look for it every time the cache is updated. If you pick up a show mid-series, "Add Available Shows to Queue" will find any other available shows for downloading. 

That said, I think that's different from what you are asking for, which is to have the "Use Current Webpage" detect that it's on a program's page, and look for all episodes of that program. It sounds like the same thing without the extra step of searching in the PVR window first. The PVR doesn't work for collections of older shows, though.

**Comment by ashleycox** [comment]
Thanks for your reply. I have seen and used the PVR feature. I'm mainly looking for something that can search the webpage for the purpose of downloading older shows. The BBC occasionally post archives of radio comedy series' for example, some of which contain large numbers of episodes but can't be found in the search.

**Comment by hugofalkman** [comment]
It's a long time since I could use "Use Current Webpage", since GiA gets confused if Safari has multiple windows in multiple desktops, each with multiple tabs. This is however not a problem, for shows not in the cache, I just copy/paste the address to a blank line in the download queue display, and then press the "Process PID" button.

So this feature request should cover both the "Use Current Webpage" and "Process PID" use cases,  for shows not in the cache. An example of a possible user interface design from Downie:
<img width="706" alt="Screenshot 2021-01-18 at 10 31 01" src="https://user-images.githubusercontent.com/10969068/104898589-1f3e7080-597a-11eb-931e-4b06af430b5e.png">

**Comment by jchhenderson** [comment]
Yes, this is the single reason I also use Downie - to download an entire season of episodes from a show that isn't searchable in GiA (I assume because it is only available on iPlayer and has not been broadcasted).

**Comment by skovatch** [comment]
After some more digging, this is related to the Series pages that capture an entire season, or multiple season, on one page. Example: https://www.bbc.co.uk/iplayer/episodes/p00yzlr0/line-of-duty?seriesId=m000tjg9

get_iplayer can get all of the PIDs with --recursive-pid-list and the 'brand ID' (here, p00yzlr0). GiA would then turn these into download lines. 

I see a way to do this, but I'm not sure when I'll get to it.

**Comment by jchhenderson** [comment]
fair enough - thanks for the reply!

**Comment by ashleycox** [comment]
Just wondered if you'd had any more thoughts on this, or whether it could be bumped up the priority queue? The BBC is celebrating its centenary at the moment and they are uploading some fantastic series', particularly radio comedy on BBC sounds which are only available for a limited time. It would be a great help to make it easier to capture them, some of them have series' in the double figures! Thanks for your continued excellent work.

**Comment by skovatch** [comment]
As luck(?) would have it, I was laid off from my last job, but I will be starting a new one in two weeks. I should have some free time to look at this some more. So no promises but check back soon.

**Comment by ashleycox** [comment]
@skovatch Sorry to hear you were laid off, but best of luck in the new job!

**Comment by skovatch** [comment]
Fixed in 1.24.3. You should be able to start with https://www.bbc.co.uk/programmes and go into the available programs and get the entire list of shows.
