### ISSUE TITLE
Manual PID entry to Download Queue

### ISSUE THREAD

**Issue by Locum7** [Ascoware/get-iplayer-automator#307]
Action: Under Download Queue add line by clicking '+'. Right click the added line.

Expected output: entry box in which to write/paste PID. Actual output: non-responsive - no entry box appears.

Version: 1.21.1 (20210228001)
No web proxy being used

**Comment by skovatch** [comment]
I genuinely did not realize this was a feature! It didn't make sense to me why the fields in the download queue should be editable, nor why there was an add button.

**Comment by skovatch** [comment]
I honestly didn't realize that was a feature! It didn't make sense to me why there was a plus button or why the columns were editable.

**Comment by Locum7** [comment]
It's linked to the main purpose, or so I've always understood, for the "Process PID" button. You manually enter the PID and then click on Process PID, which generates the detail of the programme in the columns (Status, Episode etc) alongside the PID.

**Comment by skovatch** [comment]
I see. Well, TIL in that case. :-) That's not the best name for that button, however. 'Process' is a generic verb that doesn't give give a new user any idea as to what will happen if you click on it.

**Comment by hugofalkman** [comment]
@skovatch  This is a serious limitation for those of us who can't use the "Use Current Webpage" faciity. See  my entry in the enhancement request #306 https://github.com/Ascoware/get-iplayer-automator/issues/306#issuecomment-762125807 

Especially serious for BBC, where entries only stay in the cache for 7 days

**Comment by hugofalkman** [comment]
@skovatch Thank you for fast response. Seems to work -- didn't yet do a download.

**Comment by skovatch** [comment]
Fixed in 1.21.2

**Comment by Locum7** [comment]
Sorted. Thanks Scott.
