### ISSUE TITLE
v1.21.1 & 2 = BBC episodes do not appear in (new) Episode column

### ISSUE THREAD

**Issue by jchhenderson** [Ascoware/get-iplayer-automator#308]
Every BBC show/episode I have down,oaded since v1.21.1 shows the episode in the (new) show column.

...this isn't the end of the world but it does look odd.

Recent example:
"Would I Lie to You" s14e09 displays "Would I Lie to You?: Series 14 - Episode 9" in the how column.

**Comment by jchhenderson** [comment]
So, Interestingly, with Bloodlands just now, it shows in both:
<img width="901" alt="Screenshot 2021-03-08 at 08 53 02" src="https://user-images.githubusercontent.com/34644672/110297885-d3a85a80-7feb-11eb-99ad-a085124a7f3c.png">

**Comment by skovatch** [comment]
I'm actually rewriting a good chunk of this part of the app now. Many parts of the code assumed a single column for 'Show', and this needs to be updated.

**Comment by jchhenderson** [comment]
Cheers!
