### ISSUE TITLE
Download speed incorrectly displayed

### ISSUE THREAD

**Issue by gingerbeardman** [Ascoware/get-iplayer-automator#31]
I was downloading at 30Mb/s (3.75 MB/s)

but the app displayed 3.7KB/s 

...so it seems there's a problem somewhere?

![screen shot 2017-05-16 at 15 18 10](https://cloud.githubusercontent.com/assets/49612/26110879/7c8ae61c-3a4b-11e7-882a-75035bcddac8.png)

**Comment by mutantcamel** [comment]
It might just be that K/Bs needs changing to M/Bs?  I use a VPN in China and get speeds of around 400/600 K/Bs that get reported as 0.3 or 0.6

**Comment by skovatch** [comment]
Sounds like a bug in get_iplayer... GiA just displays whatever get_iplayer sends us. I'll double-check.

**Comment by pnoguchi** [comment]
I don't think it is just a M/Bs for K/Bs. I just downloaded an episode of Red Rock at 5 megabits/s and the GIA window indicated 0.9 kilobyes/s.

**Comment by mutantcamel** [comment]
Interesting, not all of my traffic goes through the VPN either, so I can only get a general idea of my download speeds.

**Comment by gingerbeardman** [comment]
get_iplayer (via brew) on the command line for me reports as follows:

> Recording:    52.39 MiB / ~414.24 MiB  12.6%   27.9 Mibit/s 00:01:43 remaining

**Comment by naq59** [comment]
I also have the wrong speeds displayed but as it´s only a cosmetic thing and doesn´t affect the real download speed I think I´ll be able to struggle through life with this issue.

**Comment by TonyMc589** [comment]
I've also noticed that my BBC download speeds seem to be much lower than they should be. I appear to be downloading at such a low speed (0.2 KB/S!) that  a 1 hour BBC show often takes much longer than that to download! ITV downloads really quickly. 

P.S. really appreciate the work on this.

**Comment by skovatch** [comment]
Please check 1.9b7. I'm now just using get_iplayer's calculation of the download speed.

**Comment by pnoguchi** [comment]
Dear Scott,

Thank you for carrying on GetIplayerAutomater, and for the fix for the 
download speed. Seems to work correctly for me now with 1.9b7.

I noted that I need to download the sit file; trying to update from 
1.9b6 did not work for me.

Best regards,
Philip Noguchi

**Comment by hugofalkman** [comment]
The download works from 1.9b6 but then the extract crashes.

**Comment by naq59** [comment]
Hi Scott,
I´d just like to echo Philip´s comments. Great work. I also downloaded manually but no big deal.
Regards
NAQ

**Comment by skovatch** [comment]
Thank you all for the kind words! Trying to test the updater is a pain in the neck, so expect things to be unpredictable for a while.
