### ISSUE TITLE
Queue, History and PVR list deleted

### ISSUE THREAD

**Issue by MacMuser** [Ascoware/get-iplayer-automator#311]
--------

*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*

Install latest and previous update

*What is the expected output? What do you see instead?*

Update installed but wiped out all history, download queue and PVR Manager list

*What version of GiA are you using? On what version of OS X?*
1.21.4 on MacOS10.14.6

*Are you using a web proxy? DNS proxy? VPN? VPS?*
No

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *
None yet

*Please provide any additional information below.*
I tried deleting the GetIplayer folder from Application support and replacing it with the back-up but still nothing displayed in the Queue, History and PVR windows.

**Comment by MacMuser** [comment]
As I had no issues with the old version, I went back to that version and replaced the Get Iplayer folder in my Users Application Support folder. All the missing info repopulated again.

**Comment by JeremyCavanagh** [comment]
I have exactly the same problem.

GiA updated to 1.21.3 then immediately updated to 1.21.4.

Both versions cleared the download queue and no matter what I tried every restart erases the existing queue.

Unlike MacMuser I did have problems with 1.21.2. It didn't erase the download queue but every start to an age to update the caches. Instead of previously a couple of hundred were being updated 1.21.2 was updating in excess of 8000! Every time.

**Comment by LimeyGarp** [comment]
My install is doing the same thing. Had to restore 1.21.2 and all settings from Time Machine to get my PVR list back. Running on Mojave if that makes a difference. Have tried updating twice since and it keeps wiping the PVR programs when launched

**Comment by skovatch** [comment]
Sadly, I'm pretty sure I know what happened here and will work on a fix later today. I apologize for that.

**Comment by WilliamOfGaunt** [comment]
TBH I should be the one apologizing – a momentary sense of humour failure on my part caused me to neglect the sterling work you do on this invaluable app.

So instead of carping, here are my thanks.

B.

**Comment by skypalacer** [comment]
I’d like to add my thanks - what a great beast this is - invaluable indeed.

N

**Comment by skovatch** [comment]
Can someone attach their auto-record settings from an earlier version? (Queue.automatorqueue) I can't seem to recover an older copy.

**Comment by WilliamOfGaunt** [comment]
Boy, do I feel foolish now... I completely forgot that I have an earlier version (1.21.2) on an old machine – probably not the most up-to-date list of mine, but it would have been a good start! So here it is, and I hope it’s useful.

B.

**Comment by WilliamOfGaunt** [comment]
Hmm ... I can't see that the attachment actually attached - an unsupported file type.

I've added a .txt suffix; maybe it will this time
[Queue.automatorqueue.txt](https://github.com/Ascoware/get-iplayer-automator/files/6163423/Queue.automatorqueue.txt)
,

B.

**Comment by skovatch** [comment]
Well, this is frustrating. I went back to an earlier tag, created a queue, and then ran with the newest code and could read the file created by the old version, with no deleting. I hope this isn't a pre-Big Sur-only problem.  What I will do is change the code to not delete the archive if there's a problem reading it. I can't believe it was doing that in the first place.

**Comment by WilliamOfGaunt** [comment]
Sorry - should I have mentioned that the queue file came from a High Sierra machine? The machine that deleted the file is in fact running Big Sur.

**Comment by skovatch** [comment]
It's good to 

> Sorry - should I have mentioned that the queue file came from a High Sierra machine? The machine that deleted the file is in fact running Big Sur.
OK, this is good to know. I'm not sure yet if it correlates to anything yet.
Yes, when filing bugs please include your system configuration. It may or may not be relevant, but it never hurts to add it.

**Comment by skovatch** [comment]
I changed the code so that it no longer deletes the file if there was a problem decoding it, and prints the exception encountered while decoding. If this is happening to you please try this latest release and report back with the exception.

**Comment by MacMuser** [comment]
Hi Scott

I d/l and installed version 1.21.5 but still the same missing queue. However the history is populated so that is the main problem dealt wil.

Many thanks

Mark

**Comment by skovatch** [comment]
Is there an error in the log? You should see "Unable to load <filename>" with a description of the error before it.

**Comment by MacMuser** [comment]
Hi Scott

Sorry, doing ten things at once and forgot to look at the log.

Went back to old version, back came queue, etc. Reinstalled latest version but this time an error message and no PVR either:

Get iPlayer Automator 1.21.5 Initialized.
*** -[NSKeyedUnarchiver decodeBoolForKey:]: value for key (processedPID) is not a boolean
Unable to load Queue.automatorqueue. Please file a bug and mention the exception description above.
<AppController: 0x7f9d1140aa10>: Updating Programme Index Feeds...

INFO: Indexing tv programmes (concurrent)
INFO: Added 0 tv programmes to cache
INFO: Indexing radio programmes (concurrent)
INFO: Added 0 radio programmes to cache
INFO: 23210 matching programmes
<AppController: 0x7f9d1140aa10>: Index Updated.

Mark

**Comment by skovatch** [comment]
OK, exactly what I thought, then. Could you try a test fix for me? Download it from my Google Drive [here](https://drive.google.com/file/d/1DUSBPefQmTN5BnG2kwCyKsVc2OsPpGIA/view?usp=sharing) 
It should restore everything successfully.

**Comment by LimeyGarp** [comment]
I'm not MacMuser, but I downloaded the beta and upgraded and the queue survived the process this time

**Comment by MacMuser** [comment]
Hi Scott

I installed Version 1.21.6b1 (20210323001) and all the menus were populated — Queue, PVR and History. I did note that the Log Window option ⌘-L was greyed out but it was in the last version (and maybe many before). I use the >_ button in the main GetiPlayer window anyway.

Thank you for all your work.

Mark

**Comment by skovatch** [comment]
Thanks for testing it out! I will push an update out shortly.
