### ISSUE TITLE
Webpage link not working after software update

### ISSUE THREAD

**Issue by PeteSut** [Ascoware/get-iplayer-automator#312]
having just updated to Version 1.21.4 (20210316001), now clicking on "use current webpage" reports "program page not found" even on bbc iplayer pages that I downloaded from 5min earlier.

**Comment by LimeyGarp** [comment]
Mine worked if I used Safari, but not with Chrome, running on Mojave

**Comment by PeteSut** [comment]
I am using OSX Catalina, 10.15.7. 
The feature does not work on Safari, Chrome or Firefox

**Comment by skovatch** [comment]
It looks like Chrome and/or Edge had some kind of internal change that reset the option "Allow Javascript from Apple Events". That's required for Get Current Webpage to work. Make sure that's set -- in Chrome, View -> Developer -> Allow Allow Javascript from Apple Events and in Edge, Tools -> Developer -> Allow Javascript from Apple Events and see if it's still broken.

**Comment by PeteSut** [comment]
Many thanks Skovatch
That fixed it in Chrome 
(i'm on a Mac so can't comment on Edge)

**Comment by watashi49uk** [comment]
I have just updated to version 1.21.4 on an iMac running macOS 10.15.7 and I too cannot use the 'Use Current Webpage' option.
I've tried using both Chrome and Safari, but the problem remains the same.

**Comment by skovatch** [comment]
> I have just updated to version 1.21.4 on an iMac running macOS 10.15.7 and I too cannot use the 'Use Current Webpage' option.
> I've tried using both Chrome and Safari, but the problem remains the same.

See the above comment -- make sure Chrome allows you to execute JavaScript from AppleScript. The same is true for Safari -- check the Develop menu and see if Allow Javascript from AppleEvents and Allow Remote Automation are checked.

**Comment by watashi49uk** [comment]
I am having trouble finding the options to change Chrome as described, but have made the changes in Safari and changed my default browser accordingly.
Despite this, the problem remains the same.  I have tried re-starting the iMac and have checked the settings again in Safari, but still no joy.

**Comment by skovatch** [comment]
One other thing to check is whether or not Get iPlayer Automator is allowed to control Safari or Chrome via automation. In the "Security & Privacy" panel of System Preferences, click Privacy, and then scroll down to Automation. Get iPlayer Automator should show up in the list of apps that are allowed to control other apps.

**Comment by watashi49uk** [comment]
Yep, both Safari and Google Chrome are in the list and shown with a 'tick'.
Tried again after a further reboot but still get the same "Program Page Not Found" message.

**Comment by skovatch** [comment]
I'll have to add some debugging so I can see where it's going wrong. What program page are you using with this feature?

**Comment by watashi49uk** [comment]
I've tried several, but this is the main one I was trying to access:
https://www.bbc.co.uk/iplayer/episodes/m000sm37/bloodlands?seriesId=m000sm36
This is another that I tried out:
https://www.bbc.co.uk/iplayer/episodes/p00yzlr0/line-of-duty?seriesId=b01k9pm3

**Comment by skovatch** [comment]
Aha, now it makes sense. 'Get Current Webpage' doesn't know how to parse that kind of program page. If you click on the pink button next to 'Start Watching' you'll be taken to the episode's page, which can be read by GiA.

That said, it _could_ parse that kind of program page. It might be a new type of page that BBC added recently. In any event, I should be able to add support for it.

**Comment by skovatch** [comment]
This is a new issue, so I'm going to close this and track it in #315.
