### ISSUE TITLE
ITV episodes downloading with incorrect episode number

### ISSUE THREAD

**Issue by jchhenderson** [Ascoware/get-iplayer-automator#314]
*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*
Downloading episodes recently, all have an unusual format and incorrect episode number 

**What is the expected output? What do you see instead?**
**Expect:** Plebs s03.e06.Jugball.mp4
**Getting:** Plebs - Season 3.s03e21.Jugball.mp4

**What version of GiA are you using? On what version of OS X?**
GiA 1.21.4
macOS 11.2.3

**Are you using a web proxy? DNS proxy? VPN? VPS?**
No.

**What program are you attempting to download (full title, series and episode)?**
Plebs season 3, episode 6

*Please provide any additional information below.*

**Comment by skovatch** [comment]
Ah, found it... the show metadata has the correct value, and it gets parsed, but then we overwrite it with the last element of the episode ID ("2/1873/0021" in this case). Thanks for the report; this is a simple fix.

**Comment by jchhenderson** [comment]
:)

**Comment by skovatch** [comment]
Fixed in v1.21.5

**Comment by jchhenderson** [comment]
great, thanks!
