### ISSUE TITLE
'Updating Programme Indexes..." when nothing is set to be cached (1.21.b20210227001 onwards)

### ISSUE THREAD

**Issue by AbsenceJam** [Ascoware/get-iplayer-automator#319]
Since 1.21.b20210227001 the application will be 'Updating Programme Indexes..." when launched.

No items are selected to be cached and this occurs at every launch.

Reverting to the previous version (1.20.2.b20210202001) stops this.

Tested with all preference/settings files deleted, clean run.

**Comment by skovatch** [comment]
I see where it happens... the method that returns what is being cached had changed, which causes the get_iplayer cache update to always run. Thank you for the report.

**Comment by skovatch** [comment]
Fixed in v1.21.7
