### ISSUE TITLE
Sparkle.framework missing from repo

### ISSUE THREAD

**Issue by gingerbeardman** [Ascoware/get-iplayer-automator#32]
Needs to be checked in.

**Comment by skovatch** [comment]
I'm using Carthage now for these third-party dependencies. See https://github.com/Carthage/Carthage. I should document that in the README.

Basically, you need to install Carthage (usually via HomeBrew), and then run `carthage bootstrap --platform macos` in the get-iplayer-automator directory. Then, build with Xcode.

**Comment by skovatch** [comment]
Closing, because I want to avoid checking in third-party code if I can avoid it. I plan to do something similar with ASIHTTPRequest, but that probably means switching to AFNetworking.

**Comment by gingerbeardman** [comment]
No worries, makes sense.
