### ISSUE TITLE
Problem with ITV download

### ISSUE THREAD

**Issue by ChrisV56** [Ascoware/get-iplayer-automator#325]
Am in the UK. Using V1.27.1 of GIA and OS V10.13.6 with Safari as browser. 
Opened ITV webpage and selected the film to download.  Selected use Current Webpage.  The name of the show briefly appears then vanishes - Message in Failed Download Solutions indicates 'Unknown problem'  
Log shows:
Get iPlayer Automator 1.21.7 Initialized.
GetITVShows: ITV Cache Update Starting 
<AppController: 0x7fb9a540e730>: Updating Programme Index Feeds...

INFO: Indexing tv programmes (concurrent)
GetITVShows (Info): Episodes: 3360 Today Programmes: 356 
GetITVShows: Update Finished
INFO: Added 0 tv programmes to cache
INFO: 8326 matching programmes
<AppController: 0x7fb9a540e730>: Index Updated.
INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used
AppController: Starting Downloads

Downloading Show 1/1:

Downloading Carry On Abroad
 Failed
AppController: Downloads Finished

*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*

*What is the expected output? What do you see instead?*

*What version of GiA are you using? On what version of OS X?*

*Are you using a web proxy? DNS proxy? VPN? VPS?*

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *

*Please provide any additional information below.*

**Comment by skovatch** [comment]
Thanks for the report. This is a case that fell through the cracks as I was rewriting the get-current-webpage support for ITV.

**Comment by ChrisV56** [comment]
Hi Scott,

Can I just say how much I appreciate all the work and support you put into GIA. I have been using it for many years now, it’s just brilliant, so a huge thank you.

Best wishes

Chris

**Comment by skovatch** [comment]
Fixed in 1.21.9
