### ISSUE TITLE
ITV download failed, American Dad Season 16

### ISSUE THREAD

**Issue by brgphil** [Ascoware/get-iplayer-automator#327]
3 episodes of Season 16 available, added by series link, download fails for each episode.
---------------

*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*

Tried using both series link and use current webpage.
Get iPlayer Automator 1.21.7 Initialized.
GetITVShows: ITV Cache Update Starting 
<AppController: 0x14d7638c0>: Updating Programme Index Feeds...

INFO: Indexing tv programmes (concurrent)
INFO: Added 563 tv programmes to cache
INFO: 7796 matching programmes
GetITVShows (Info): Episodes: 3366 Today Programmes: 354 
<AppController: 0x14d7638c0>: Index Updated.
GetITVShows: Update Finished

INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used
AppController: Starting Downloads

Downloading Show 1/4:

Downloading American Dad!: Season 16
INFO: Preparing Request for Auth Info
INFO: Metadata processed.
youtube-dl finished downloading

Downloading Show 2/4:

Downloading American Dad!: Season 16
INFO: Preparing Request for Auth Info
INFO: Metadata processed.
youtube-dl finished downloading

Downloading Show 3/4:

Downloading American Dad!: Season 16
INFO: Preparing Request for Auth Info
INFO: Metadata processed.
youtube-dl finished downloading

Downloading Show 4/4:

Downloading American Dad!: Season 7
INFO: Preparing Request for Auth Info
INFO: Metadata processed.
*What is the expected output? What do you see instead?*
Gives Problem Unknown, log shows finished downloading, but download fails

Using Version 1.21.7 (20210330001), Mac OS 11.1

No proxy

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** * American Dad Season 16 Episodes 1, 2 &3

*Please provide any additional information below.*
Other episodes from previous series are downloading fine.

**Comment by skovatch** [comment]
This is most likely a youtube-dl issue, or an anomaly on ITV's part. I can't download it from the command line either -- it fails with the same error.

Other ITV shows seem fine.

**Comment by brgphil** [comment]
Issue has resolved with the most recent update, thanks for all your hard work.
