### ISSUE TITLE
Channel 4 (All 4) downloads

### ISSUE THREAD

**Issue by dvd403** [Ascoware/get-iplayer-automator#335]
Some time ago it was possible to download TV programmes from Channel 4. Although that option is no longer selectable Is there any work being done on restoring this facility?  Or is it just not possible

**Comment by skovatch** [comment]
Unfortunately Channel 4 changed a few years ago and now they encrypt all of their videos on All4, so nothing can download it. Even youtube-dl fails. Barring some major change in policy on their end it's not coming back.
