### ISSUE TITLE
ITV download fails repeatedly with message "youtube-dl download complete".

### ISSUE THREAD

**Issue by jbreef** [Ascoware/get-iplayer-automator#337]
I am attempting to download a series from ITV.  I am using GiA v 1.21.9 on macOS 10.15.7 and using Express VPN and a UK server.  I can begin downloading the program, however, the download will terminate with a status of Download Failed.  The solutions window displays the message "Problem Unknown: Please submit a bug report from the applications menu."  The log displays the message "youtube-dl finished downloading AppController: Downloads Finished", however the download is not complete and the resume timer starts.  It is not consistent as to how much data is downloaded between failures and the download almost always resumes (sometimes the download fails with the same messages but will successfully resume on the next attempt).  The messages in both the solutions window and the log window are always the same.  I have used GiA many times before with this VPN and have successfully downloaded programs from BBC without difficulty.  This is the first time that I attempted to download from ITV in a long time.  After many stops and restarts the program will complete.  One program to test is "Unforgotten - S4E2" as you will see in the attached files.
As a side note the "Save as Text File" button on the solutions window does not work.
Thanks for your help.

Jim Breef
![Screen Shot 2021-05-01 at 1 18 48 PM](https://user-images.githubusercontent.com/23246817/116791455-1fbdcb80-aa80-11eb-9dc2-6828e5efe4af.png)
[Get Iplayer Automater Log.txt](https://github.com/Ascoware/get-iplayer-automator/files/6410094/Get.Iplayer.Automater.Log.txt)

---------------

*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*

*What is the expected output? What do you see instead?*

*What version of GiA are you using? On what version of OS X?*

*Are you using a web proxy? DNS proxy? VPN? VPS?*

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *

*Please provide any additional information below.*

**Comment by skovatch** [comment]
There are multiple versions of this right now, so I'm marking this as a duplicate. See #336, #331.

**Comment by Iain-F** [comment]
Hi,
just to say that I'm having the same experience with ITV downloads. All fail immediately, whereas in the past I might get a failure but with repeated tries, success. No sign of this now. BBC downloads remain fine.
Mac OS 10.13.6, GiA 1.21.9
As always, very grateful for all the efforts put in to keep this app going.
Cheers
Iain

**Comment by Iain-F** [comment]
Also fails with 1.15.2 Mac OS 11.3 and 1.21.9 Mac OS 11.3. Oh and sorry no proxy in either case...

**Comment by jbreef** [comment]
Thanks for the reply, skovatch.  However, after reading the threads of the posted issues there appears to be a differently reported error.  The message I'm receiving appears to believe that the download completed successfully when in fact it terminated prematurely.  Additionally, I'd like someone watching this thread to help me understand where I can find an option to generate a bug report within the GiA application.  Thanks.
