### ISSUE TITLE
GiA crashes when Process PID is clicked

### ISSUE THREAD

**Issue by jbreef** [Ascoware/get-iplayer-automator#338]
When I copy the PID from a BBC program and add it to the download queue GiA crashes when the Process PID button is selected.  I have used this process in the past when downloading from BBC iPlayer website without issue.  I am using GiA 1.21.9 on a macOS 10.15.7 machine.  The crash report is attached below.
[Gip crash report.txt](https://github.com/Ascoware/get-iplayer-automator/files/6428010/Gip.crash.report.txt)

---------------

*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*

*What is the expected output? What do you see instead?*

*What version of GiA are you using? On what version of OS X?*

*Are you using a web proxy? DNS proxy? VPN? VPS?*

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *

*Please provide any additional information below.*

**Comment by sleaux-meaux** [comment]
Ensure you don't have a blank row selected when clicking Process PID. There is a blank row in queue when GiA starts up, which can catch you out.

**Comment by skovatch** [comment]
Thank you for the report. I'll push out an update soon.

**Comment by skovatch** [comment]
Should be fixed... if not please open a new bug.
