### ISSUE TITLE
Brave browser not supported for retrieving PIDs

### ISSUE THREAD

**Issue by hazen** [Ascoware/get-iplayer-automator#348]
*Please provide any additional information below.*

Brave https://brave.com/ is a fork of Google Chrome and as such should be simple to add as a default browser option.

I'd be happy to submit a PR, if you are open to that.  Thanks!

**Comment by skovatch** [comment]
Yes, I'd be glad to review a PR. You'd be the second ever contributor.

**Comment by hazen** [comment]
Great! Now I just have to figure out how to build this great tool. 🤔

**Comment by skovatch** [comment]
I should write up build instructions. You need Xcode for the main application and Carthage, which builds the libraries for HTML parsing, JSON parsing, and Sparkle updates.

**Comment by hazen** [comment]
Thanks, @skovatch !

**Comment by skovatch** [comment]
Fixed in v1.21.13
