### ISSUE TITLE
Use OS notifications instead of (option) Growl?

### ISSUE THREAD

**Issue by gingerbeardman** [Ascoware/get-iplayer-automator#35]
macOS style:
![ximg_54d56474ac244 png pagespeed gp jp jw pj ws js rj rp rw ri cp md ic _h1j-fnuta](https://cloud.githubusercontent.com/assets/49612/26149423/25f2e8f2-3af2-11e7-84b9-770039d572d2.png)

Grow style (requires extra software to be installed):
![screen shot 2017-05-17 at 11 12 48](https://cloud.githubusercontent.com/assets/49612/26149379/fae8f930-3af1-11e7-96c1-054b116e3975.png)

**Comment by skovatch** [comment]
I can look into this. It would be nice to not need Growl, but NSUserNotification is a 10.8+ feature. Of course, if I limit the app to 10.9 or 10.10 that's no longer a problem.

**Comment by Lordsnooty05** [comment]
I know this is probably not the place to say this but I can't find any other forum type place to say a word of Thanks to skovatch for all that he has done in rescuing this Great App from oblivian. I downloaded about 20 different programmes last night without hitch and they are all playing plus I think the app is working faster than ever before (whatever you have done) Thanks for taking the time and working on this great app and making it better.....I for one appreciate it

**Comment by skovatch** [comment]
I appreciate the kind words, but I can't take all of the credit for things like download speed. That's entirely within the realm of get_iplayer and the BBC itself. I too have noticed that my download speeds are better lately. That could be changes on the BBC's end, or switching to SmartProxy; I'm not sure which.

**Comment by skovatch** [comment]
I'm closing this as Growl is completely gone from the app now. All notifications are done through NSUserNotification. 

🎉
