### ISSUE TITLE
No programmes were found on www.itv.com/hub/shows

### ISSUE THREAD

**Issue by andyjw7** [Ascoware/get-iplayer-automator#377]
On cache update (and force cache update) the following error is displayed:

"No programmes were found on www.itv.com/hub/shows"

This worked fine for me last week but has failed consistently today. No OS or GiA updates have been installed.

*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*

Simply refresh cache and observe error.

*What is the expected output? What do you see instead?*

*What version of GiA are you using? On what version of OS X?*

GiA version = Version 1.21.13 (20220124001)
MacOS version = 11.6.2 (20G314)

*Are you using a web proxy? DNS proxy? VPN? VPS?*

No

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *

N/A - issue relates to cache refresh

*Please provide any additional information below.*

**Comment by skovatch** [comment]
Thanks for the heads up. It looks like ITV rolled out a new website this morning and it broke the link-scraping code.
