### ISSUE TITLE
Changes to BBC resolutions and get-iplayer-automator 

### ISSUE THREAD

**Issue by josephdarmi** [Ascoware/get-iplayer-automator#382]
Using another tool I noticed that the BBC is now offering 1920x1080 streams while get-iplayer-automator only downloads 1280x720 when "Best' is requested.

Steps to replicate i used Downie to view resolution options and found 1920x1080 and verified this in Quicktime player when downloaded. Added the same BBC program to get-iplayer-automator with "Best' as top option in preference and only downloaded 1280x720

i realise that it will take time to adjust to these changes from the BBC but i just wanted to alert you to this and was curious what this would mean to the Best, Better approach as get-iplayer-automator is still my go to app.

**Comment by josephdarmi** [comment]
Thanks for the info, that makes sense. I look forward to the changes.

**Comment by Mac-Man-APH** [comment]
When I used GiA Version 1.21.15 (20220207002) and it downloaded BBC programs in the file size / quality I prefer with the setting “Good” it has a file type [‘hvfhigh’](). I have tried all quality levels in the next 2 versions with Version 1.22.1 (20220216001) being the latest and none are the same previous file type or file size. Those now available, most are either twice or triple the file size = hlshd, dashfhd, hvfhd  and hvflow. When I revert to Version 1.21.15 I can still get ‘hvfhigh’ but are the BBC likely to drop this quality or should GiA consider adding this variant to the drop-down list?

**Comment by ian02054** [comment]
I found this yesterday as well.. it seems like size "web"  was similar to
the old "good"... about 700k per hour.

**Comment by Mac-Man-APH** [comment]
Yes ian02054 I can concur the 'web' file size is exactly the same as the previous 'Good'.

**Comment by ian02054** [comment]
Yep..obviously I meant 700mb not700k! 😓

**Comment by skovatch** [comment]
get_iplayer changed the name of the show quality options from 'best', 'better', 'high' etc. to 'fhd', 'hd', 'sd', 'web', and 'mobile'. These correspond to 1080p, 720p, 540p, 396p and 288p respectively. It sounds like you want to use 'sd' or 540p.

You may want to look at https://github.com/get-iplayer/get_iplayer/wiki/release320to329#release329 for more details on this change. It also explains why DASH format is used now by default. I debated adding a checkbox to continue preferring his format, but it didn't seem necessary.

**Comment by skovatch** [comment]
Also note that checking 'Use lower bitrate streams if available' tells get_iplayer to download 25 fps video if it's available. That might be a good choice too for smaller downloads.

**Comment by jchhenderson** [comment]
Can anyone tell the difference between 1080p and 720p (when enlarged to 1080p)?  I guess my question is: has the BBC simply upscaled?

**Comment by josephdarmi** [comment]
I did a quick visual A/B test on a film early on, nothing scientific, and could not tell the difference

**Comment by jchhenderson** [comment]
...so a larger file but no improvement - at least in the Ines I tested.

Curiously though, the 1080p downloads for "QI XL" are smaller than the 720p downloads - I must be going mad.

**Comment by jchhenderson** [comment]
> I did a quick visual A/B test on a film early on, nothing scientific, and could not tell the difference

So, given you could not spot the difference, are you downloading in 1080p?

**Comment by josephdarmi** [comment]
> > I did a quick visual A/B test on a film early on, nothing scientific, and could not tell the difference
> 
> So, given you could not spot the difference, are you downloading in 1080p?

Sticking with 720p for now, until the size/quality equation is worth it - I'll have another look at some point

**Comment by jchhenderson** [comment]
> Sticking with 720p for now, until the size/quality equation is worth it - I'll have another look at some point

That's my view also.  I have checked maybe 10 different shows now and can hardly spot the difference.  I am sure it will be worth it at some point but not today.

**Comment by skovatch** [comment]
FWIW, I have been downloading 1080p video, and on my big Samsung 4k TV with an AppleTV 4k attached I do see an improvement over 720p video. It's not a huge difference, but it's definitely crisper. Depending on what you are viewing shows on, it may not make a difference.

**Comment by jchhenderson** [comment]
good to know - thanks for sharing!

**Comment by skovatch** [comment]
This is working as designed, so I'm closing it as fixed in v1.23.0
