### ISSUE TITLE
v1.22 will not save changed download formats

### ISSUE THREAD

**Issue by jchhenderson** [Ascoware/get-iplayer-automator#385]
**What steps will reproduce the problem? Be specific, and provide as much detail as possible.**
- run app
- add (for example) BBC SD (540p)
- close app
- re-open app

**What is the expected output? What do you see instead?**
I expect to see BBC SD (540p) as as an added download format in the list

**What version of GiA are you using? On what version of OS X?**
GiA 1.22
MacOS 12.2.1

**Are you using a web proxy? DNS proxy? VPN? VPS?**
no

**What program are you attempting to download (full title, series and episode)?**
The Perfect Morecambe and Wise (ep 6)

**Please provide any additional information below.**
- That episode will not download without the 540p added to download format

- The edit is only lost after a restart, but the app hangs "waiting" when trying to download after adding 540p to the list i.e. either way, the episode will not download.

**Comment by sleaux-meaux** [comment]
There are a few errors in the new formats. You'll need to wait for a new release unless you build your own. These are the changes that got it working again for me:

```diff
diff --git a/AppController.m b/AppController.m
index 06758a08..4c1023da 100644
--- a/AppController.m
+++ b/AppController.m
@@ -216,9 +216,9 @@ - (void)awakeFromNib
 
     NSDictionary *newTvFormatMapping = @{
         @"Best" : @"HD (720p)",
-        @"Better" : @"Web (580p)",
-        @"Very Good" : @"Web (580p)",
-        @"Good" : @"Web (580p)",
+        @"Better" : @"SD (540p)",
+        @"Very Good" : @"SD (540p)",
+        @"Good" : @"Web (396p)",
         @"Worst" : @"Mobile (288p)"
     };
```
```diff
diff --git a/BBCDownload.m b/BBCDownload.m
index 9b40f877..a8b93c90 100644
--- a/BBCDownload.m
+++ b/BBCDownload.m
@@ -12,8 +12,8 @@
 @implementation BBCDownload
 + (void)initFormats
 {
-    NSArray *tvFormatKeys = @[@"Full HD (1080p)", @"HD (720p)", @"Web (540p)", @"Mobile (288p)"];
-    NSArray *tvFormatObjects = @[@"fhd",@"hd",@"sd", @"mobile"];
+    NSArray *tvFormatKeys = @[@"Full HD (1080p)", @"HD (720p)", @"SD (540p)", @"Web (396p)", @"Mobile (288p)"];
+    NSArray *tvFormatObjects = @[@"fhd",@"hd",@"sd",@"web",@"mobile"];
     NSArray *radioFormatKeys = @[@"High", @"Standard", @"Medium", @"Low"];
     NSArray *radioFormatObjects = @[@"high", @"std", @"med", @"low"];
```

**Comment by raythw** [comment]
I have the same problem. With 1080p and 720p selected, the 540p option actually disappears when you restart the application.

**Comment by jchhenderson** [comment]
Thanks, both!
