### ISSUE TITLE
Migration to a new Mac - what needs to be copied?

### ISSUE THREAD

**Issue by ghjimmy** [Ascoware/get-iplayer-automator#388]
I've looked and didn't find an answer to this.  I'm migrating my old Mojave build to Monterey and doing this as a fresh install of all programs to remove 6 years of un-needed cruft.  What files etc. do I need to transfer from my old build to the new one to preserve settings, history etc.? I can see

~/Library/Preferences/com.ascoware.getiPlayerAutomator.plist
~/Library/Application Support/Get iPlayer Automator
~/Library/Caches/com.ascoware.getiPlayerAutomator

Are there any others that need to be transferred?

Thanks.

**Comment by skovatch** [comment]
The contents of ~/Library/Application Support/Get iPlayer Automator is all you need. The rest is temp data used when fetching ITV data.

**Comment by ghjimmy** [comment]
Thanks. Appreciate the response.
