### ISSUE TITLE
S4C programs fail to download

### ISSUE THREAD

**Issue by franklypanky** [Ascoware/get-iplayer-automator#390]
*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*
I have a series record for Pobol y Cym which worked until Feb 16 then all subsequent downloads fail. Other BBC programs are OK so it seems to be only S4C

*What is the expected output? What do you see instead?*
Get iPlayer Automator 1.22.1 Initialized.
GetITVShows: ITV Cache Update Starting 
<AppController: 0x7fbcdd74fd20>: Updating Programme Index Feeds...

INFO: Indexing tv programmes (concurrent)
GetITVShows (Info): Programmes: 506
INFO: Added 0 tv programmes to cache
GetITVShows (Info): Episodes: 6006
GetITVShows: Update Finished
INFO: 8314 matching programmes
<AppController: 0x7fbcdd74fd20>: Index Updated.

INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used
AppController: Starting Downloads

Downloading Show 1/1:

Downloading Pobol y Cwm
Pobol y Cwm Failed
AppController: Downloads Finished

*What version of GiA are you using? On what version of OS X?*
GIA 1.22.1
MacOs 12.2.1

*Are you using a web proxy? DNS proxy? VPN? VPS?*
VPN

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *
Pobol Y Cym Wed 16 Feb 2022

*Please provide any additional information below.*
From my limited testing this problem applies to all S4C programs (these are Welsh language programs).

**Comment by skovatch** [comment]
This should be fixed once and for all in 1.25.4
