### ISSUE TITLE
Not downloading subtitles for ITV programmes

### ISSUE THREAD

**Issue by OldTrout** [Ascoware/get-iplayer-automator#393]
GiA 1.22.1
OSX 10.14.6 Mojave (I still have some 32bit apps.)
No web proxy
Tried downloading all episodes of "The Ipcress File". All downloaded OK BUT without subtitles.

Subtitles OK with BBC programmes.

**Comment by hugofalkman** [comment]
Downloaded The Ipcress File today -- the subtitles files were there, and were merged with the video files. ITV are often sloppy, and forget uploading the subtitle files, until a day or two after the video files.

ps GiA failed downloading Episode 2 repeatedly, downloaded it with Downie instead, merging the subtitle file manually with Subler.

**Comment by OldTrout** [comment]
Hi Hugo,
Thanks for reply.
I forced a cache reload and tried again. Still no subtitles.
Episode 2 is not listed.
I found before that if I brought up episode 2 on ITV Hub, set it playing with subtitles and then instructed GiA to get current web page it downloaded OK but again no subtitles.
Still puzzled!
John

**Comment by OldTrout** [comment]
Not puzzled any more. The error is mine. It is downloading embedded subtitles but using VLC as my player I have to turn them on a different way.

Thanks guys.
John

**Comment by skovatch** [comment]
I'll close this out. If you see something new please open a new bug.
