### ISSUE TITLE
Query iPlayer Downloads ((hlsfhd))

### ISSUE THREAD

**Issue by timstaton1** [Ascoware/get-iplayer-automator#395]
This is the first time I've reported an issue on here so bare with me...

I quite like the fact that Get iPlayer now supports 1080p resolution, so thank you for that.
I am currently updating all my old series to 1080p (the ones I can anyway) and have noticed that some files will download with the expected 1080p file e.g. ((dashfhd)) but some, even within the same series download as ((hlsfhd)) which comes out as just the audio file but no video file even though the file size is similar to the ((dashfhd)) files that are around the same series.

*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*
I've tried several times with the same thing. Preferences all set to download the highest quality for the Program and when downloading the episode it downloads it without the video.

*What is the expected output? What do you see instead?*
I get a file with the appendix 'xxx' ((hlsfhd).mp4 which produces a large file but only the audio
I was expected 'xxx' ((dashfhd)).mp4 which is what happens even within the same series of the program
 
*What version of GiA are you using? On what version of OS X?*
Version 1.22.1 (20220216001) on MacOS 12.3 on an M1 Mac Mini
(but the same happens with an Intel-based Mac)

*Are you using a web proxy? DNS proxy? VPN? VPS?*
No - I've never been able to use ExpressVPN with Get iPlayer (maybe this is something that someone could help me with too, please)??

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *
Death in Paradise Series 5 - 01. Episode 1 ((hlsfhd))

*Please provide any additional information below.*

**Comment by skovatch** [comment]
This is a quirk of get_iplayer. The author of get_iplayer found that the 1080p videos downloaded faster using DASH, which downloads a separate audio and video stream and then stitches them together using ffmpeg. For all other quality it uses hls streams, which are combined audio and video. It's possible that some shows don't have 1080p streams, which would explain why some of your downloads fall back to the 720p version.

It's also possible that I'm misunderstanding you and you're not getting both audio and video for some programs?

**Comment by timstaton1** [comment]
Hi Scott,

Thank you for your reply…Yes it may be that the shows do not have 1080p streams, unfortunately I do not have enough knowledge about iPlayer to know that, but the odd behaviour is that the file downloads as if it were using DASH, but comes out with only the Audio Stream in that odd format that I mentioned on the ticket - almost as if my Mac can’t understand the video stream…Even though I haven’t changed any settings…

I could understand it if the file size were say, 1GB, that would suggest that it is just downloading just the Audio Stream but it comes out at 2.5-3GB, which is the odd thing... 

Tim

**Comment by sleaux-meaux** [comment]
Those old programs aren't technically supported by get_iplayer, but it obviously has a bug in handling cases where 1080p video is not found. If you're planning to download a lot of these, switch to get_iplayer itself and use `--tv-quality=fhd --exclude-format=hls` to work around the problem. That should ensure that nothing is downloaded unless 1080p is available.

**Comment by skovatch** [comment]
As you suspected this is a bug in get_iplayer, and was fixed in 3.30. I'll have to merge it in.

**Comment by skovatch** [comment]
Fixed with v1.24.0, which had the newer version of get_iplayer.
