### ISSUE TITLE
NEW ITV issue with 1.23.0

### ISSUE THREAD

**Issue by pmhird** [Ascoware/get-iplayer-automator#401]
Hi all, downloaded latest 1.23.0 version this morning, and now I lost ITV downloads again. BBC is working fine. I understand from the release notes for this version that I should no longer need to do the steps in issue 277, so I didn't do those steps-is that my problem? Using OSX 10.11.6, here is the log for an example show:

Downloading American Dad!: Series 17
INFO: Preparing Request for Auth Info
INFO: Requesting Metadata.
DEBUG: Metadata response status code: 200
INFO: Metadata processed.
DEBUG: youtube-dl args:["https://www.itv.com/hub/american-dad/2a4263a0303", "--user-agent", "Mozilla/5.0", "-f", "mp4/best", "-o", "/Users/hirddesktop/Movies/iplayer/American Dad!/American Dad!.s17e01.Who Smarted?.%(ext)s", "--verbose"]
DEBUG: youtube-dl environment: ["SSL_CERT_FILE": "/Applications/Get iPlayer Automator-5.app/Contents/Resources/cacert.pem", "PATH": "/Applications/Get iPlayer Automator-5.app/Contents/Resources/yt-dlp_macos:/Applications/Get iPlayer Automator-5.app/Contents/Resources/get_iplayer/utils/bin"]
[debug] Command-line config: ['https://www.itv.com/hub/american-dad/2a4263a0303', '--user-agent', 'Mozilla/5.0', '-f', 'mp4/best', '-o', '/Users/hirddesktop/Movies/iplayer/American Dad!/American Dad!.s17e01.Who Smarted?.%(ext)s', '--verbose']
[debug] Encodings: locale US-ASCII, fs utf-8, out ascii (No ANSI), err ascii (No ANSI), pref US-ASCII
[debug] yt-dlp version 2021.12.27 [6223f67a8] (mac_dir)
[debug] Python version 3.9.9 (CPython 64bit) - macOS-10.11.6-x86_64-64bit
[debug] exe versions: ffmpeg 4.3.2-tessus
[debug] Optional libraries: Cryptodome, sqlite
[debug] Proxy map: {}
[debug] Using fake IP 25.216.234.205 (GB) as X-Forwarded-For
[debug] [ITV] Extracting URL: https://www.itv.com/hub/american-dad/2a4263a0303
[ITV] 2a4263a0303: Downloading webpage
[ITV] 2a4263a0303: Downloading JSON metadata
ERROR: [ITV] 2a4263a0303: Unable to download JSON metadata: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output. (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp . Make sure you are using the latest version; see  https://github.com/yt-dlp/yt-dlp  on how to update. Be sure to call yt-dlp with the --verbose flag and include its complete output.
  File "yt_dlp/extractor/common.py", line 717, in _request_webpage
  File "yt_dlp/YoutubeDL.py", line 3458, in urlopen
  File "urllib/request.py", line 523, in open
  File "urllib/request.py", line 632, in http_response
  File "urllib/request.py", line 561, in error
  File "urllib/request.py", line 494, in _call_chain
  File "urllib/request.py", line 641, in http_error_default
youtube-dl finished downloading
AppController: Downloads Finished

**Comment by pmhird** [comment]
So this is weird, I retried it and it failed 2 more times and then magically worked, i changed nothing! Not sure what's going on now. 4 in 5 attempts to download ITV work, about 1 in 5 seems to just work with no config changes at all. Oh well I guess? Any advice on the above gratefully received!

**Comment by skovatch** [comment]
A 403 error almost always means "outside the UK" in this context. If you are using VPN your provider may have had a hiccup.
