### ISSUE TITLE
Future ITV programs not yet broadcast, but available on the ITV hub, can have incomplete info, causing GiA to fail.

### ISSUE THREAD

**Issue by hugofalkman** [Ascoware/get-iplayer-automator#402]
*What version of GiA are you using? On what version of OS X?*
GiA 1.23.0 (20220328001) MacOS Big Sur 11.6.5 (20G527)
*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *
DI Ray S01 E02
*Please provide any additional information below.*
[GiAlog.txt](https://github.com/Ascoware/get-iplayer-automator/files/8610266/GiAlog.txt)

**Comment by hugofalkman** [comment]
I notice for these failing ITV episodes, the show and episode fields in the GiA download queue are blank, only the Programme Id field is filled in. Am attaching the log for Karen Pirie episode 2. Downie downloads the episode ok, with the name Series 1 - Episode 2, but it then shows up in the Apple TV app, under the correct show name Karen Pirie. Maybe GiA could do somehing similar, give it a show and episode name before invoking youtube-dl.

Downloading Show 1/3:

Downloading Retrieving Metadata...
/Applications/Get iPlayer Automator.app/Contents/Resources/get_iplayer/perl/bin/get_iplayer
--profile-dir=/Users/zilla/Library/Application Support/Get iPlayer Automator
--nocopyright
--nopurge
--atomicparsley=/Applications/Get iPlayer Automator.app/Contents/Resources/get_iplayer/utils/bin/AtomicParsley
-e604800000000
--output=/Users/zilla/Movies/TV Shows
--subdir
--logprogress
--quality=fhd
--pid
https://www.itv.com/hub/karen-pirie/10a0641a0002
--whitespace
--attempts=5
--thumbsize=640
--ffmpeg=/Applications/Get iPlayer Automator.app/Contents/Resources/get_iplayer/utils/bin/ffmpeg
--log-progress
--verbose
--subtitles
--subs-embed
--file-prefix=<nameshort><.senum><.episodeshort>
--subdir-format=<nameshort>
INFO: Start: 2022-09-28T14:28:03 (1664368083)
INFO: encodinglocale = UTF-8
INFO: encodinglocalefs = UTF-8
INFO: encodingconsoleout = UTF-8
INFO: encodingconsolein = UTF-8
INFO: ${^UNICODE} = 39
INFO: Profile dir: /Users/zilla/Library/Application Support/Get iPlayer Automator
INFO: User options file: /Users/zilla/Library/Application Support/Get iPlayer Automator/options
INFO: System options file: /etc/get_iplayer/options
-==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==-
Current options:
	atomicparsley = /Applications/Get iPlayer Automator.app/Contents/Resources/get_iplayer/utils/bin/AtomicParsley
	attempts = 5
	encodingconsolein = UTF-8
	encodingconsoleout = UTF-8
	encodinglocale = UTF-8
	encodinglocalefs = UTF-8
	expiry = 604800000000
	ffmpeg = /Applications/Get iPlayer Automator.app/Contents/Resources/get_iplayer/utils/bin/ffmpeg
	fileprefix = <nameshort><.senum><.episodeshort>
	logprogress = 1
	modes = fhd
	nocopyright = 1
	nopurge = 1
 Failed

**Comment by SOLOSAIR** [comment]
Me too - 'Tonight' ITV arrives in GiA without programme info and so, for some unknown reason does 'Peston' under the title of 'Tonight' too (no mention of Peston) - totally unrelated and unwanted. 

I'm irritated too by day of broadcast details added to the end of the title 'Coronation Street' with date details not where they should be.

Sorry to be a moan.  I really appreciate all the work you do for us Scott. 😊

**Comment by skovatch** [comment]
I think this is easily fixed by skipping over shows with a broadcast date after the current time. There are some shows that appear to not have an on-air broadcast date but are still available for viewing. 'Karen Pirie' ep. 3 is an example.

I changed the code to let yt-dlp do the metadata extraction but now I'm wondering if that was the right call. It simplified my code but if it isn't doing the right thing that doesn't help.

**Comment by skovatch** [comment]
The next version of GiA will put back the old tagging code. I didn't test the tagging done by yt-dlp well enough to realize it's not as good as what it replaced.

**Comment by skovatch** [comment]
Should be fixed with 1.24.2. Please open a new bug if you see something else.
