### ISSUE TITLE
Download fails when "download subtitles" is ticked in preferences

### ISSUE THREAD

**Issue by damndingo** [Ascoware/get-iplayer-automator#41]
Download fails when "download subtitles" is ticked in preferences. When i untick the box, download starts fast.

*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*
When i tick the box "Download Subtitles" in the preferences window. 

*What is the expected output? What do you see instead?*
Download will start is the expected outcome, but i get "Download failed"

*What version of GiA are you using? On what version of OS X?*
Version 1.9b6 (1833)
macOS Sierra (10.12.5)

*Are you using a web proxy? DNS proxy? VPN? VPS?*
No proxy, but using Unlocator.com from Germany

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *
BBC, Cardinal, Series 1, Episode 1

*Please provide any additional information below.*

**Comment by naq59** [comment]
I can´t confirm this here, also in Germany at present (Overplay). Ticking subtitles doesn´t stop anything. OSX 10.11.6 version 1.9b6
