### ISSUE TITLE
'Please ensure the frontmost browser tab is open...'

### ISSUE THREAD

**Issue by moonsong1** [Ascoware/get-iplayer-automator#411]
Getting the error message 'Please ensure the frontmost browser tab is open to an iPlayer episode page or ITV Hub episode page.' when trying to download any episode of any show on iPlayer, despite having the frontmost browser tab open on Chrome. Attempting to download 'Glastonbury 2022 - Billie Eilish' (https://www.bbc.co.uk/iplayer/episode/p0cg02h2/glastonbury-billie-eilish). Using v1.19.2 OS Monterey 12.4 from the UK with a UK VPN (Express VPN) but issue also happens without a VPN.

**Comment by SOLOSAIR** [comment]
is Chrome your default browser in GiA settings?
