### ISSUE TITLE
Episodes Missing Data - Sorting Issues

### ISSUE THREAD

**Issue by pebceb** [Ascoware/get-iplayer-automator#412]
Is anyone else having the problem where the episode and season number no longer get put into the episode properties and so the sorting on Apple TV is done alphabetically resulting in episodes being out of order?

Any way to fix this?

Thanks.

Peter

**Comment by skovatch** [comment]
Is this with ITV or BBC shows? I recently changed GiA to have yt-dlp add the show metadata, so it's possible they aren't doing something right.

**Comment by pebceb** [comment]
It is with ITV Scott. 

Thanks. 

Peter

**Comment by SOLOSAIR** [comment]
I've experienced this too on ITV. No Release date in column but instead tagged on to the end of the episode title, no episode number any more.

I watch a news magazine programme called 'Tonight' on ITV, usually aired at around 7:30pm. Recently GiA has added 'Peston' and 'ITV Evening News' instead, neither of which are wanted.  (see screenshot). Can this be fixed?

Is it possible to have the episode date and time taken away from the end of the name in Title field and have them returned to the 'release date' and 'episode' fields again please?

Thanks.
Sarah!

[image](https://user-images.githubusercontent.com/37366634/194151297-0d1a602b-22ea-42a0-a2ab-a0d5e0546d35.jpeg)

**Comment by skovatch** [comment]
Yes, the old tagging code will be back in the next release.

**Comment by skovatch** [comment]
Should be fixed in 1.24.2
