### ISSUE TITLE
New 1.9 release does not update successfully from earlier release

### ISSUE THREAD

**Issue by hugofalkman** [Ascoware/get-iplayer-automator#42]
Tried updating to 1.9 automatically both from 1.9b6 and 1.9b7. Identical behavior: Download works. When prompt to start install and relaunch is answered the install crashes. OSX 10.12.5

**Comment by skovatch** [comment]
When you say 'crashes', are you getting an actual crash or is the updater telling you there was a problem with the download?

**Comment by hugofalkman** [comment]
Yes, sorry, message from updater saying i think "try later".

**Comment by pnoguchi** [comment]
Same experience as hugofalkman. Error message says: Update Error! An error occred while extracting the archive. Please try again later.

**Comment by skovatch** [comment]
Okay. I'll update the release tag so no one gets the message again until I can figure out what happened.

**Comment by hugofalkman** [comment]
After having got the updater error message, but before hitting the Cancel Update button, I checked my  .../Application Support/Get iPlayer Automator Support/ folder.

In the Sparkle subfolder the only item was a Get iPlayer Automator 1741 folder containing a GetiPlayerAutomator_1.8.6.zip file.

I can see the download of 1.9 proceeding ok, so maybe it gets deleted after download. As you have now turned off the updater info I can't rerun the update, checking the Application Support folder after download completes but before I hit the Install and Relaunch button.

**Comment by hugofalkman** [comment]
"Thanks, everyone, for the kind words! As a daily user of this app myself, I'm plenty motivated to keep this alive as long as I can.
I really need to come up with a better announcement mechanism"

Thank you @skovatch  for providing continued support of GiA, we all appreciate your good work. Don't know if I am the only one supporting friends who never heard of Github or open source in continuing to use GiA. Anyway @skovatch, think the single most important thing you could do to support the non-sophisticated user of GiA is to fix the "Check for Updates" option.

**Comment by Sircam19** [comment]
From where I stand I can be patient about not having the update function right away. As long as the program works,I can be happy. If there are updates I just install manually...no biggie. The fact that this program has been updated and works is the single most important thing. THANK YOU Skovatch!!!

**Comment by skovatch** [comment]
This is now working starting with v1.9.4. Auto-update should continue to work as long as I build everything properly.
