### ISSUE TITLE
Feature Request: to use stv.tv to download itv programmes in HD

### ISSUE THREAD

**Issue by jefro108** [Ascoware/get-iplayer-automator#420]
stv.tv make many itv programmes available in HD. For example https://player.stv.tv/episode/4cnb/the-walk-in is downloadable using yt-dlp in 1080p25 

It would be great if this could be a feature of GiA

**Comment by skovatch** [comment]
I think I could support this with 'Get Current Webpage'. It all depends on whether or not the metadata is easily readable.

**Comment by skovatch** [comment]
Now available in v1.24.5
