### ISSUE TITLE
No Download

### ISSUE THREAD

**Issue by Dsanfor67** [Ascoware/get-iplayer-automator#432]
**This issue tracker is not a discussion forum, so don't use it as such.  If you wish to discuss the BBC, iPlayer or anything else that is not related to an actual problem with the current release of GiA, post in an appropriate forum, not in this issue tracker.**

**STOP! DO NOT submit a ticket if you are reporting that you are unable to download a program from outside the UK**.

If you need an explanation, read [this](https://github.com/Ascoware/get-iplayer-automator/wiki/No-Support-for-GiA-Outside-the-UK). If you ignore this instruction, your ticket will be closed with no further action. You can fib about your location if you like, but you will only be wasting your time. If you are using GiA within the UK, continue with the instructions below.

Before creating a new ticket, search the current open and closed tickets to see if your issue has already been reported. Use the search box at the top of the page to do so. You can also use the links below to view open and closed tickets in list form.

#### [Closed tickets](https://github.com/Ascoware/get-iplayer-automator/issues?q=is%3Aissue+is%3Aclosed)

If you create a ticket for an issue that has already been reported, your ticket will be closed with no further action. If you are certain your issue has not yet been reported, continue with the instructions below.

Create a succinct title describing your issue in the `Title` field above, then provide the information requested below. If you do not provide the requested information, your ticket will be closed with no further action.

If you cannot download a program, provide a verbose log of the attempt. See [Verbose Log](https://github.com/Ascoware/get-iplayer-automator/wiki/Verbose-Log) in wiki for instructions on posting a verbose log for your ticket. **Your verbose log should show the results from downloading ONLY ONE program. DO NOT post a massive log covering multiple multiple program downloads. IMPORTANT: DO NOT paste your verbose log into your issue report. If you do, expect it to be deleted.**

If GiA crashes, provide the OS X crash log by copying the information from Crash Reporter into a file or locating the crash log in `$HOME/Library/Logs/DiagnosticReports`. See [Verbose Log](https://github.com/Ascoware/get-iplayer-automator/wiki/Verbose-Log) in wiki for instructions on posting a crash log for your ticket. **IMPORTANT: DO NOT paste your crash log into your issue report. If you do, expect it to be deleted.**

**Delete the instructions above before submitting your ticket.**

---------------

*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*

*What is the expected output? What do you see instead?*

*What version of GiA are you using? On what version of OS X?*

*Are you using a web proxy? DNS proxy? VPN? VPS?*

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *

*Please provide any additional information below.*

**Comment by Dsanfor67** [comment]
Trying to download last two days on Get Iplayer Automator, version: 1.24.4, loads the searched programs, then when you hit the start button, nothing happens, no starting download, nothing ... just sits there and does not complete the task

INFO: Indexing tv programmes (concurrent)
INFO: Added 0 tv programmes to cache
INFO: 8403 matching programmes
<AppController: 0x7f947721e210>: Index Updated.


INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used
AppController: Starting Downloads

Says starting downloads but nothing happens ... ???

**Comment by skovatch** [comment]
Check your download queue and make sure there are no blank lines, and specifically no empty 'Programme ID' entries. I fixed a bug recently where if the program ID was blank or otherwise invalid the download queue would silently stop.

**Comment by skovatch** [comment]
If that is indeed the problem I will push an update soon since this seems to be a somewhat common problem.

**Comment by Dsanfor67** [comment]
Thanks for the suggestion Scott, not working for two days and then last night it was back working as normal …
I have no idea why ……
Thanks
Dsanfor67

**Comment by hugofalkman** [comment]
> If that is indeed the problem I will push an update soon since this seems to be a somewhat common problem.

@skovatch Maybe before you do, you could also test the case, where the queue contains an item with a valid Programme ID field, but where the Show and Episode fields are blank.

It happens that especially ITV are sloppy with new entries, and leave those two fields blank. Typically they adjust the fields  in a day or two. But it would be nice to be able to download the show, before they discover their error.
