### ISSUE TITLE
SSL Connection Failure

### ISSUE THREAD

**Issue by BadWolf001** [Ascoware/get-iplayer-automator#437]
Get iPlayer Automator Version: 1.24.4 (20221118002)
MacOS: 13.1
Issue: App was working properly then stopped working. Issue log shows the following and I am unsure how to troubleshoot. Can you please help?

Log is as follows:
Get iPlayer Automator 1.24.4 Initialized.
<AppController: 0x12e74e210>: Updating Programme Index Feeds...

INFO: Indexing tv programmes (concurrent)

ERROR: Failed to download BBC Alba schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl67/2022/w52
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC Alba schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl67/2022/w52
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC News schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl6g/2023/w01
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC News schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl6g/2023/w01
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC One Channel Islands schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl6j/2022/w51
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC One Channel Islands schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl6j/2022/w51
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC One East schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl6k/2023/w01
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC One East schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl6k/2023/w01
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC One Yorks & Lincs schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl6m/2022/w49
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC One Yorks & Lincs schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl6m/2022/w49
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC One schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl6n/2022/w52
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC One schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl6n/2022/w52
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC One London schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl6p/2023/w01
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC One London schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl6p/2023/w01
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC One North East & Cumbria schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl6r/2022/w51
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC One North East & Cumbria schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl6r/2022/w51
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC One North West schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl6s/2022/w52
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC One North West schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl6s/2022/w52
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC One Oxfordshire schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl6t/2023/w01
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC One Oxfordshire schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl6t/2023/w01
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC One South schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl6w/2022/w49
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC One South schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl6w/2022/w49
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC One South East schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl6x/2022/w51
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC One South East schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl6x/2022/w51
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC One South West schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl6y/2023/w01
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC One South West schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl6y/2023/w01
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC One West schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl70/2022/w50
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC One West schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl70/2022/w50
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC One West Midlands schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl71/2023/w01
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC One West Midlands schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl71/2023/w01
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC Parliament schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl73/2022/w49
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC Parliament schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl73/2022/w49
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC Three schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl95/2022/w51
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC Three schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl95/2022/w51
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC Two England schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl97/2022/w51
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC Two England schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl97/2022/w51
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC Two Wales schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl9d/2022/w50
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC Two Wales schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl9d/2022/w50
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download CBBC schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl9r/2022/w51
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download CBBC schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl9r/2022/w51
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download CBeebies schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl9s/2022/w51
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download CBeebies schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl9s/2022/w51
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC One Northern Ireland schedule page (3/3): https://www.bbc.co.uk/schedules/p00zskxc/2022/w51
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC One Northern Ireland schedule page (3/3): https://www.bbc.co.uk/schedules/p00zskxc/2022/w51
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC One Scotland schedule page (3/3): https://www.bbc.co.uk/schedules/p013blmc/2022/w49
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC One Scotland schedule page (3/3): https://www.bbc.co.uk/schedules/p013blmc/2022/w49
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC Two schedule page (3/3): https://www.bbc.co.uk/schedules/p015pksy/2022/w50
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC Two schedule page (3/3): https://www.bbc.co.uk/schedules/p015pksy/2022/w50
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download S4C schedule page (3/3): https://www.bbc.co.uk/schedules/p020dmkf/2022/w52
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download S4C schedule page (3/3): https://www.bbc.co.uk/schedules/p020dmkf/2022/w52
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC Two Wales schedule page (3/3): https://www.bbc.co.uk/schedules/p06ngc52/2022/w51
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC Two Wales schedule page (3/3): https://www.bbc.co.uk/schedules/p06ngc52/2022/w51
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC Two Northern Ireland schedule page (3/3): https://www.bbc.co.uk/schedules/p06ngcbm/2023/w01
ERROR: Connection error: SSL connect attempt failed

ERROR: Failed to download BBC Two Northern Ireland schedule page (3/3): https://www.bbc.co.uk/schedules/p06ngcbm/2023/w01
ERROR: Connection error: SSL connect attempt failed

INFO: Added 6879 tv programmes to cache
INFO: 6879 matching programmes
<AppController: 0x12e74e210>: Index Updated.

**Comment by skovatch** [comment]
Give it another try. In the past I've seen this happen when bbc.co.uk has gone down for some random reason. It usually goes away on its own.

**Comment by bhurte** [comment]
I encountered the same problem today (now). While it's failing SSL connections, I'm able to use the command line get_iplayer to download without issue.

**Comment by skovatch** [comment]
I haven't been able to reproduce this, but I did notice that a brew update regenerated the CA cert file, so I can update the root certificates that ship with the app.

**Comment by BadWolf001** [comment]
Thank you for investigating the issue.

Kind Regards,
Neal

Warm Regards,
Neal
________________________________

**Comment by bhurte** [comment]
Thank you Scott. I tried again today with a much shorter, mixed list and it worked. Probably just a weird coincidence yesterday.On Jan 15, 2023, at 9:44 AM, Scott Kovatch ***@***.***> wrote:﻿
I haven't been able to reproduce this, but I did notice that a brew update regenerated the CA cert file, so I can update the root certificates that ship with the app.

**Comment by skovatch** [comment]
Closing this as it's transitory, but v1.24.5 should prevent this from happening again.

**Comment by bhurte** [comment]
Thank you
