### ISSUE TITLE
Updating Programme Indexes: Using sequential indexing goes on forever .

### ISSUE THREAD

**Issue by lenn5** [Ascoware/get-iplayer-automator#44]
For the last few week after launching this app it will start updating the program indexes. But when it gets to Using sequential indexing it will go on and on and on. It never ends.  Any suggesting? 

Really like this app. Have been using it for a few years without any problems till now.

thx

**Comment by Lordsnooty05** [comment]
Yes Lenn5 that is happening to me but I am able to download the programs. I just let it run in the background and after a couple hours I look at it and it has downloaded the programs. I wonder could we have a button turn this updating off? I alos agree with you it is a great program and seems to be working faster than ever

**Comment by Lordsnooty05** [comment]
I seem to have got it working......well it's working for me. I just increased the time between updating to about 48 hrs and now it just updates very quickly and downloads very quickly. Mind you I Don't search for a program I just go to the Webpage on Safari and insert that program into the app and very quickly downloads the program. I was able to download about 15 concerts from Glastonbury in about 20 minutes. It is working a treat for me and so much thanks must go to the new developer and updater of this App

**Comment by skovatch** [comment]
@lenn5 what version of OS X are you using? It looks like get_iplayer falls back to sequential indexing if it can't find a certain Perl package.

**Comment by manderson23** [comment]
Sequential indexing is always used for me on 10.12.5. What perl package is required?

**Comment by Vangelis66** [comment]
To have concurrent indexing with GiP 3.01 (used now inside GiA), the **Mojolicious** perl module is required; 
read the [MacOS Perl requirements for GiP 3.01](https://github.com/get-iplayer/get_iplayer/wiki/osx#perl) ; hopefully a knowledgeable GiA user will chime in with more helpful details...

**Comment by skovatch** [comment]
This is now fixed with v1.9.3. You should see the faster indexing as all necessary perl files are included.
