### ISSUE TITLE
Problems downloading ITVX programmes using [Use Current Webpage] button.

### ISSUE THREAD

**Issue by Swilly6vic** [Ascoware/get-iplayer-automator#440]
I have updated my version of GIA to version 1.24.5 and tried to download an ITVX programme Doc Martin, Ep1 Set 10. On clicking the [Use Current Webpage] button. I receive a modal box saying programme page not found. I have also attached the log file below. The programme is found in the search but I understand the search for ITVX programmes can't be used at present. I would be grateful if you can investigate why this isn't working? Thanks very much Stephen W.
---------------

*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*

*What is the expected output? What do you see instead?*

*What version of GiA are you using? On what version of OS X?*

*Are you using a web proxy? DNS proxy? VPN? VPS?*

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *

*Please provide any additional information below.*
<img width="1026" alt="Screenshot 2023-01-16 at 16 21 26" src="https://user-images.githubusercontent.com/28845258/212725444-75c27179-647a-40e8-9599-d8c8278c0747.png">

**Comment by Swilly6vic** [comment]
The operating system I am using is macOS Ventura. I am not using any VPN or Proxy

**Comment by AtomicLaser** [comment]
> For Doc Martin, give stv.tv a try. https://player.stv.tv/summary/doc-martin, and then click into each episode.

is there an update which supports GIA with STV?  When I try to download anything using the Use Current Website it gives me `Please ensure the frontmost browser tab is open to an iPlayer episode page or ITV Hub episode page.`
