### ISSUE TITLE
STV - subtitles, metadata, thumbnail and bulk queuing of programmes

### ISSUE THREAD

**Issue by jefro108** [Ascoware/get-iplayer-automator#443]
Great that you've implemented STV downloads. I'm looking forward to caching! Using the latest version v1.25.0 on Monterey 12.6.1

Until you'd done that I experimented with yt-dlp and discovered that the standard subtitles for some programmes are .dfxp which won't get embedded in the mp4 with ffmpeg - so with Vera (https://player.stv.tv/summary/vera) that's an issue.

To download in a batch with yt-dlp I used Link Klipper Chrome Extension https://chrome.google.com/webstore/detail/link-klipper-extract-all/fahollcgofmpnehocdgofnhkkchiekoo to create a text file with a list of all the links from https://player.stv.tv/summary/vera selecting only those that contained 'episode' (with regex `.*episode.*`). So my yt-dlp command was 

`yt-dlp --write-sub --sub-format dfxp --convert-subtitles srt --embed-subs --add-metadata --embed-metadata --embed-thumbnail -a vera.txt`

It worked even with subtitles that weren't dfxp and converted them ready for ffmpeg to srt - it also added the STV metadata and the thumbnail. Sorry I don't know how to create a Pull Request to help you (and unfortunately I couldn't automate the kodi naming I use).

**Comment by skovatch** [comment]
Thanks, the subtitle information is helpful! I freely admit that I don't use that feature, so it tends to not get tested as thoroughly as it should.

In the past I was using `--embed-metadata` for ITV downloads, but it didn't do a good job of capturing the relevant fields in a format that was consistent with get_iplayer for BBC. I can try it again, though.

**Comment by David1494** [comment]
Thank you for all your efforts. I am frustrated, as I know you all are, at the changes to the ITV hub. I notice references in these notes to still being able to download STV programs. But STV is not present in the Download formats in Preferences. How do I make STV programs downloadable? I am on a MAC 12.6.3 Monterey.
<img width="1037" alt="Screen Shot 2023-03-25 at 11 50 28 AM" src="https://user-images.githubusercontent.com/128903867/227715840-ba45897a-5ff3-4e7c-adb3-137bee75f803.png">
<img width="1264" alt="Screen Shot 2023-03-25 at 11 50 16 AM" src="https://user-images.githubusercontent.com/128903867/227715841-64b58f9d-ee4a-4e1a-a1b1-70bbcabf52fe.png">

**Comment by skovatch** [comment]
STV shows can be added via the Use Current Webpage button. The STV/ITV Maximum Resolution popup will get the highest available resolution up to the value in the popup. Once we get ITV back when youtube-dl/yt-dlp update it will apply there as well, though you should only expect SD resolution at best with ITV.

**Comment by skovatch** [comment]
STV subtitles should now be fixed in 1.25.3, so I will close this bug.

**Comment by David1494** [comment]
Will this end it for GetiPlayer Automator?

https://www.express.co.uk/life-style/science-technology/1865709/BBC-iPlayer-block-Windows-MacBook-PCs￼
BBC iPlayer block will stop you watching on popular devices - check the list now
express.co.uk
Thanks
David L

**Comment by skovatch** [comment]
> Will this end it for GetiPlayer Automator? [https://www.express.co.uk/life-style/science-technology/1865709/BBC-iPlayer-block-Windows-MacBook-PCs￼](https://www.express.co.uk/life-style/science-technology/1865709/BBC-iPlayer-block-Windows-MacBook-PCs%EF%BF%BC)
Probably not. From that article it sounds like they are only discontinuing their desktop apps, which had the ability to save downloads for later viewing. The fact that mobile apps will still work leads me to believe that get_iplayer will continue to be able to download streams and save the output, just like it does now.

**Comment by David1494** [comment]
Super, thanks, and thanks again for your work in this.
My wife would be lost without her BBC programs since we moved to Canada!
David L
