### ISSUE TITLE
Ability to manually add BBC programs not in cache, to the queue, broken with status 'not in cache' shown

### ISSUE THREAD

**Issue by hugofalkman** [Ascoware/get-iplayer-automator#446]
For us with too complex browser setups (many browser windows on different desktops, each with many tabs), the alternative to 'use current webpage' is, to instead manually copy and paste a URL to the queue followed by pressing the process id button for that queue item.

This ability is now broken for BBC, which only carries 7 days in the cache. Instead of processing the URL, extracting the programme id, status 'not in cache' is shown -- see attached screenshot.

This test was added with the STV support, I suspect it's unnecessary also for STV.

<img width="807" alt="Screenshot 2023-02-14 at 18 35 28" src="https://user-images.githubusercontent.com/10969068/218817960-0286775f-6077-4d52-9040-595e179e7d05.png">

**Comment by cgareth** [comment]
If you reduce the url just to the programme id contained within it(the code for “Better” in your example, it works, no?

**Comment by TheChiefSmeg** [comment]
using the PID will not fix this, but if you navigate to the 'BBC Sounds' website and pick the programme from there then the programme IS in the cache and will download - it looks like we need to be able to cache BBC Sounds data too?

**Comment by hugofalkman** [comment]
For BBC, the GiA 1.25.3 Process PID button now first displays status Not in cache, thinks for about 5 seconds, and then changes the status to Available.

For STV, it would be possible to let the Process PID button invoke the same code, now used ny Use Concurrent Webpage, for the link manually copied from the browser to the GiA queue.

But that would be a nice to have, assuming the Process PID button isn't broken for ITV, once ITVX will be supported.

**Comment by skovatch** [comment]
Fixed in 1.25.3
