### ISSUE TITLE
Download failed - no specified recording quality

### ISSUE THREAD

**Issue by Iain-F** [Ascoware/get-iplayer-automator#447]
Hi
Mac mini 2018, OS Ventura 13.2.1. GIA  1.25.1 (20230118001). No web proxy, no VPN. All other recent BBC programs downloaded fine.
Failed download for a single item with following log entry (may be a one-off error at the BBC end?)

Downloading Phantom Thread
Episodes:
Phantom Thread - -, BBC Two, m000qrz4
INFO: 1 total programmes
WARNING: A UK TV licence is required to access BBC iPlayer TV content legally
INFO: Downloading tv: 'Phantom Thread - - (m000qrz4) [original]'
INFO: No specified recording quality (dashfhd,hlsfhd,hlshd,dashhd) available for this programme with version 'original'
INFO: Available qualities: sd,web,mobile
Phantom Thread failed

Cheers
Iain

---------------

*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*

*What is the expected output? What do you see instead?*

*What version of GiA are you using? On what version of OS X?*

*Are you using a web proxy? DNS proxy? VPN? VPS?*

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *

*Please provide any additional information below.*

**Comment by Mac-Man-APH** [comment]
Hi Iain

I just tried downloading this BBC programme and had no errors. The file name and quality are "Phantom Thread -  ((hlsxsd))" and it was placed in Apple TV 'Movies'.

Andrew

**Comment by skovatch** [comment]
In this case it looks like you're requesting only 720p or 1080p quality, but only SD and lower is available. For an older program that's not too surprising. I suppose the error message could be better, but in this case it's behaving correctly.
