### ISSUE TITLE
Problems with STV

### ISSUE THREAD

**Issue by robincm** [Ascoware/get-iplayer-automator#451]
STV programmes download ok but GiA fails to combine the subtitles and put the programme in to iTunes. Any help gratefully accepted.
Verbose log attached (hopefully!)
Robin
[STV.docx](https://github.com/Ascoware/get-iplayer-automator/files/11090856/STV.docx)
PS I am using GiA 1.25.1 on a Mac running 12.6.3

**Comment by skovatch** [comment]
Fixed in 1.25.3
