### ISSUE TITLE
Cache will not update with new MacBook Pro running Ventura 13.3.1

### ISSUE THREAD

**Issue by David1494** [Ascoware/get-iplayer-automator#455]
I am lucky enough to have a brand new MacBook Pro. However the updating Index feeds  just cycles endlessly. see MacBook details and Automator 
<img width="898" alt="Screenshot 2023-04-14 at 11 20 45 AM" src="https://user-images.githubusercontent.com/128903867/232085982-eaba8369-642a-4f30-9f72-1268b006370e.png">
 screenshots
<img width="285" alt="Screenshot 2023-04-14 at 11 13 36 AM" src="https://user-images.githubusercontent.com/128903867/232085808-93d1c947-9c4d-4778-9beb-8a0fd2a415b2.png">

Before creating a new ticket, search the current open and closed tickets to see if your issue has already been reported. Use the search box at the top of the page to do so. You can also use the links below to view open and closed tickets in list form.

#### [Closed tickets](https://github.com/Ascoware/get-iplayer-automator/issues?q=is%3Aissue+is%3Aclosed)

If you create a ticket for an issue that has already been reported, your ticket will be closed with no further action. If you are certain your issue has not yet been reported, continue with the instructions below.

Create a succinct title describing your issue in the `Title` field above, then provide the information requested below. If you do not provide the requested information, your ticket will be closed with no further action.

If you cannot download a program, provide a verbose log of the attempt. See [Verbose Log](https://github.com/Ascoware/get-iplayer-automator/wiki/Verbose-Log) in wiki for instructions on posting a verbose log for your ticket. **Your verbose log should show the results from downloading ONLY ONE program. DO NOT post a massive log covering multiple multiple program downloads. IMPORTANT: DO NOT paste your verbose log into your issue report. If you do, expect it to be deleted.**

If GiA crashes, provide the OS X crash log by copying the information from Crash Reporter into a file or locating the crash log in `$HOME/Library/Logs/DiagnosticReports`. See [Verbose Log](https://github.com/Ascoware/get-iplayer-automator/wiki/Verbose-Log) in wiki for instructions on posting a crash log for your ticket. **IMPORTANT: DO NOT paste your crash log into your issue report. If you do, expect it to be deleted.**

**Delete the instructions above before submitting your ticket.**

---------------

*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*

*What is the expected output? What do you see instead?*

*What version of GiA are you using? On what version of OS X?*

*Are you using a web proxy? DNS proxy? VPN? VPS?*

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *

*Please provide any additional information below.*

**Comment by David1494** [comment]
By the way, I used the MAC migration Assistant . It worked fine and even included the history file from any old MAC. But as above the index just cycles endlessly.

**Comment by skovatch** [comment]
The issue here is that the tools that actually do the downloading and cache update are still x86_64 only, even though the main application is built for both Intel and Apple architectures. This means you will need to install Rosetta 2. You can try selecting the application in the Finder, choose Get Info, and check "Open using Rosetta". Then, the next time you open it, you should be prompted to install Rosetta 2. Alternately, `/usr/sbin/softwareupdate --install-rosetta --agree-to-license` will do the job too.
