### ISSUE TITLE
Requested format is not available

### ISSUE THREAD

**Issue by shiteandstuffandcrap** [Ascoware/get-iplayer-automator#457]
---------------

*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*

Download of BBC radio show fails with 'unknown problem'

*What is the expected output? What do you see instead?*

*What version of GiA are you using? On what version of OS X?*

GiA 1.25.1

OS X 13.3.1

*Are you using a web proxy? DNS proxy? VPN? VPS?*

No

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *

https://www.bbc.co.uk/programmes/m001l9np

*Please provide any additional information below.*

Have set radio formats to high then standard, log file shows > 'ERROR: [bbc.co.uk] m001l9nn: Requested format is not available'

No changes made to the computer or GiA since successful downloads of show last week.

Downloading Show 1/1:
Downloading Gilles Peterson
ITV: Requesting Metadata
DEBUG: Metadata response status code: 200
INFO: Metadata processed.
DEBUG: youtube-dl args:["https://www.bbc.co.uk/programmes/m001l9np", "--user-agent", "Mozilla/5.0", "-o", "/Volumes/Store/iPlayer/Gilles Peterson/Gilles Peterson.s01e01.%(ext)s", "-f", "best[height<=720]", "--embed-thumbnail"]
DEBUG: youtube-dl environment: ["PATH": "/private/var/folders/3m/t6j6b9wj5tj4cltdy9sjbtkw0000gn/T/AppTranslocation/2FB22470-CC0E-40CA-9D6D-C765664BB521/d/Get iPlayer Automator.app/Contents/Resources/yt-dlp_macos:/private/var/folders/3m/t6j6b9wj5tj4cltdy9sjbtkw0000gn/T/AppTranslocation/2FB22470-CC0E-40CA-9D6D-C765664BB521/d/Get iPlayer Automator.app/Contents/Resources/get_iplayer/utils/bin", "SSL_CERT_FILE": "/private/var/folders/3m/t6j6b9wj5tj4cltdy9sjbtkw0000gn/T/AppTranslocation/2FB22470-CC0E-40CA-9D6D-C765664BB521/d/Get iPlayer Automator.app/Contents/Resources/cacert.pem"]
[bbc.co.uk] m001l9np: Downloading video page
[bbc.co.uk] m001l9np: Downloading playlist JSON
[bbc.co.uk] m001l9nn: Downloading media selection JSON
[bbc.co.uk] m001l9nn: Downloading MPD manifest
[bbc.co.uk] m001l9nn: Downloading MPD manifest
[bbc.co.uk] m001l9nn: Downloading m3u8 information
[bbc.co.uk] m001l9nn: Downloading m3u8 information
[bbc.co.uk] m001l9nn: Downloading MPD manifest
[bbc.co.uk] m001l9nn: Downloading MPD manifest
[bbc.co.uk] m001l9nn: Downloading m3u8 information
[bbc.co.uk] m001l9nn: Downloading m3u8 information
ERROR: [bbc.co.uk] m001l9nn: Requested format is not available

**Comment by shiteandstuffandcrap** [comment]
Rosetta installed and being used per #455

**Comment by skovatch** [comment]
How are you adding the show to the queue? If I follow that link and then click on 'Use Current Webpage' it will start downloading correctly.

Something didn't detect the show as coming from the BBC so it's using the ITV/STV code to download it, but that code doesn't know anything about radio programs.

**Comment by shiteandstuffandcrap** [comment]
I've always use 'Use Current Webpage'. The show in my example above doesn't appear when I search for it manually in GiA

**Comment by shiteandstuffandcrap** [comment]
Quick update, turns out that the external storage that GiA writes to had been marked as faulty with the age old 'this disk was not ejected properly' after sleep. Changing the download location got things working. So problem solved. the error message in the log was not accurate.

**Comment by skovatch** [comment]
Well, glad to know it's working again, but I'll take a look at why that would cause the ITV downloader to be used. That's a very odd bug.

**Comment by shiteandstuffandcrap** [comment]
I'd previously enabled the caching of BBC radio, searched for the show within GiA, and then tried to download directly from within GiA. I got another download failed error and a different but possibly misleaading error message in the log (will attach that when I get to the computer) Seems the error reporting got confused and should say something like 'can't write to file system'?

**Comment by shiteandstuffandcrap** [comment]
Downloads stopped working again today with the same error 'Requested format is not available'. Have stepped back through previous versions until I got to 1.24.0 which works perfectly. 

Downloading Show 1/1:
Downloading Guy Garvey's Finest Hour
ITV: Requesting Metadata
DEBUG: Metadata response status code: 200
INFO: Metadata processed.
DEBUG: youtube-dl args:["https://www.bbc.co.uk/programmes/m001lfzm", "--user-agent", "Mozilla/5.0", "-o", "/Users/ip/iPlayer/Guy Garvey\'s Finest Hour/Guy Garvey\'s Finest Hour.s01e01.%(ext)s", "-f", "best[height<=1080]", "--embed-thumbnail"]
DEBUG: youtube-dl environment: ["SSL_CERT_FILE": "/Applications/Get iPlayer Automator.app/Contents/Resources/cacert.pem", "PATH": "/Applications/Get iPlayer Automator.app/Contents/Resources/yt-dlp_macos:/Applications/Get iPlayer Automator.app/Contents/Resources/get_iplayer/utils/bin"]
[bbc.co.uk] m001lfzm: Downloading video page
[bbc.co.uk] m001lfzm: Downloading playlist JSON
[bbc.co.uk] m001lfzk: Downloading media selection JSON
[bbc.co.uk] m001lfzk: Downloading MPD manifest
[bbc.co.uk] m001lfzk: Downloading MPD manifest
[bbc.co.uk] m001lfzk: Downloading m3u8 information
[bbc.co.uk] m001lfzk: Downloading m3u8 information
[bbc.co.uk] m001lfzk: Downloading MPD manifest
[bbc.co.uk] m001lfzk: Downloading MPD manifest
[bbc.co.uk] m001lfzk: Downloading m3u8 information
[bbc.co.uk] m001lfzk: Downloading m3u8 information
ERROR: [bbc.co.uk] m001lfzk: Requested format is not available
yt-dlp finished downloading
No proxy to load
Proxy load complete.
Starting Downloads

**Comment by skovatch** [comment]
Fixed in v1.25.4
