### ISSUE TITLE
Unable to download lower bitrate formats

### ISSUE THREAD

**Issue by MistressMB** [Ascoware/get-iplayer-automator#459]
Hi all,

Posting this to ask for advice mostly as I think the issue I have may be to do with the way I've set up GiPA rather than a bug...

I've set up the App (or so I thought) to not download anything higher than 720p but it's continuing to download very high res videos which are using up my increasingly limited HD and Cloud space.

Would someone mind checking out my settings in the screenshot and let me know what, if anything, is wrong?

Many thanks in advance!

[GiPA log 2023-06-09.txt](https://github.com/Ascoware/get-iplayer-automator/files/11705789/GiPA.log.2023-06-09.txt)

<img width="1925" alt="Screenshot 2023-06-09 at 12 28 59" src="https://github.com/Ascoware/get-iplayer-automator/assets/26966420/f97758d1-8770-450c-8374-3b711707d7ec">

**Comment by sleaux-meaux** [comment]
There are no lower bitrate streams available for 720p, only for 540p and 396p.

**Comment by skovatch** [comment]
Based on what you have there, get_iplayer will *only* download 720p format video, which is not what you want. 

In the Preferences window, for BBC TV Show Formats, click the plus sign. Then click on the "Please Select" and choose the "SD (540p)" option. Then, repeat those steps, but choose the "Web (396p)" option. 

Finally, click on the "HD (720p)" option and click the minus sign to remove it. Once you do all of that get_iplayer will only look for the lower resolution formats. "Use lower bitrate streams"

**Comment by MistressMB** [comment]
Many thanks for the reply Scott. I think the 720 stream is fine, it's just that now it seems to only pick higher than that rather than lower, so I have 30 min episodes downloading at over 1Gb. I'm pretty sure that I had that before and then removed it, so I'll give it another go.

**Comment by MistressMB** [comment]
Hi again, just updating...

I've tried various configurations using the highest of 1080p down to the lowest, and various inbetween and from what I can see, there doesn't seem to be a 720p available any more, or it's weirdly huge in file size. Previously, programmes of an hour downloaded at roughly just over 1Gb. Now, they're more than double that.

On trying 1080 and then 720, the difference in file size between them is minimal. In fact, the 1080p file size seems to be lower (even allowing for the fact that it downloads the audio and video files separately).

Attaching 2 screenshots where you can see the config of the app versus the file size downloading in the log. I'm also attaching the log which shows my multiple attempts and cancellations (then deleting the partially downloaded files) in order to test various different configurations.

If you have any more thoughts/ideas, I'd be grateful, thanks!

<img width="2341" alt="Screenshot 2023-06-10 at 17 09 00" src="https://github.com/Ascoware/get-iplayer-automator/assets/26966420/0d36dbeb-ab91-4eba-99fa-7a568d230c1c">
<img width="2354" alt="Screenshot 2023-06-10 at 17 24 39" src="https://github.com/Ascoware/get-iplayer-automator/assets/26966420/68f5b393-1029-4a48-a950-6f026f22efd5">

**Comment by sleaux-meaux** [comment]
There is nothing more you can do. Lower bitrate (25fps) streams for 720p have not been available for quite a few years, so if 2 GB/hr is too big, you must select a lower resolution. 1080p bitrates vary widely, so you can't predict resulting file size with any degree of accuracy. For some programmes, 1080p files can be 50% larger, or more.

**Comment by MistressMB** [comment]
Thanks sleaux-meaux, much appreciated. Guess I have to drop the resolution in that case. Thanks for your help!
