### ISSUE TITLE
Constant 'Updating Programme Indexes' prevents use of GiA

### ISSUE THREAD

**Issue by Caliban1** [Ascoware/get-iplayer-automator#46]
![screen shot 2017-06-23 at 22 42 34](https://user-images.githubusercontent.com/29506768/27501490-a3e0e9c2-5865-11e7-94d6-3b71957b8d8e.png)

*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*
When opening GIA, the 'Updating Programme Indexes' bar at the bottom endlessly continues (20 minutes currently).

*What is the expected output? What do you see instead?*

Buttons such as 'start' are not usable while the 'Updating' bar goes on and on.

*What version of GiA are you using? On what version of OS X?*

GIA 1.9 (1841)   OS X 10.9.5

*Are you using a web proxy? DNS proxy? VPN? VPS?*

Not to my knowledge

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *

BBC Radio 3 in Concert 8 June 2017 (see attached screenshot - programme added 'using current webpage' button.

*Please provide any additional information below.*

The same repeat 'updating' issue happened with other recent Radio 3 programmes.  (I have checked 'BBC Radio' in the Preferences section)

**Comment by lenn5** [comment]
I'm having the same problems using GIA 1.9b2(1841) and MacOSX 10.12. Every time I launch GIA it takes forever to update the programming indexes. Sometimes as long as 30minutes.

**Comment by latenightlizzie** [comment]
This is interesting - for info, I'm running GiA 1.9b5 on OS X 10.11.6.  From launching the app to the completion of the concurrent indexing took 2 minutes.

**Comment by Lordsnooty05** [comment]
I seem to have got it working......well it's working for me. I just increased the time between updating to about 48 hrs and now it just updates very quickly and downloads very quickly. Mind you I Don't search for a program I just go to the Webpage on Safari and insert that program into the app and very quickly downloads the program. I was able to download about 15 concerts from Glastonbury in about 20 minutes. It is working a treat for me and so much thanks must go to the new developer and updater of this App

**Comment by MacInWin** [comment]
I, too, see the huge delay for updating. It gets the updates quickly, but then spends up to 15 minutes indexing. Once that is complete, the downloads are swift. I have it set to update each time I open the app. I may have to take the Lordsnooty05 approach.

**Comment by Lordsnooty05** [comment]
MacInWin try it....you have nothing to lose. Up the refresh cache to say  48 hrs and see if that helps with the delay to updating. Its a workaround until the app is updated

**Comment by JeremyCavanagh** [comment]
I am also experiencing this problem. I am using your so called "First Real Release" 1.9.1. However, I think you were a little premature in calling it a real release as there were many problems with the beta releases that have been flagged but have not been attended to.

**Comment by Rock-Hunter** [comment]
A little more respect please for @skovatch who's worked tirelessly on this project, I, along with many others haven't had any issues and are extremely grateful for his commitment.

**Comment by stoney27** [comment]
Yes, I have installed 1.9.1 on my wife's computer and she hasn't had any issues with this release.  And she is happy again now that she has her Eastenders. ;)

**Comment by JeremyCavanagh** [comment]
Dear Rock,

I meant no disrespect, I too am extremely grateful for the efforts of 
everyone who has contributed and is contributing to this project. I was 
simply pointing out that at the time I posted some issues that I brought 
up several months ago were still happening on this release. Along with 
that I was experiencing some new problems with GiA such as system 
throttling pushing the temperature of my laptop through the roof and GiA 
not responding when investigating what was happening via System Monitor. 
So you can see I was somewhat frustrated.

Well after I posted I tried a few things which in reality would not seem 
relevant to GiA. I installed Mac Fan Control to see if that would 
prevent overheating, which it appears to have done, restarted my 
internet modem, which needs doing occasionally anyway to maintain my 
proxy server.

Then I restarted GiA and was having the same problems, endless loading 
of the programme cache and GiA not responding. But since Mac Fan Control 
was holding the temperature down to an acceptible level I thought I 
would just leave it for an hour or so.

Well, at the moment of writing all seems well. I had intended to wait 24 
hours before reposting and withdrawing my previous post, but, given your 
response I felt it necessary to explain. I will see what tomorrow brings 
and post appropriately.

Regards

Jeremy

**Comment by Caliban1** [comment]
I've used GiA a few times in the last day or two, the "Updating Programme Indexes" wait is less than 14 days ago when I posted earlier with screenshot.  Just now, reopening the program, it was under 2 minutes.  Using the "Current Webpage" button to load the page and then hitting "Start", there is then a 5 minute pause before anything happens.  But then the selected programme downloads into iTunes with no problem.  I've just adjusted for the time being to there being those delays, compared with the instantaneous functioning of previous years - but that's no problem really!  I'm just grateful to have access again to this terrific resource, thanks to all concerned for returning it to a usable state.

**Comment by mattanorak** [comment]
For me, leaving off the option to cache BBC Radio seemed to do the trick.

**Comment by skovatch** [comment]
I have figured out what's going on here... get_iplayer wants a specific perl module installed, and if it can't find it, it falls back to the really slow 'sequential indexing'. I found a way to include the requested module in the app bundle so get_iplayer can use it -- no exotic perl installation will be necessary.

A full refresh of the BBC radio and TV cache now completes in about a minute.

**Comment by ilainftw** [comment]
Don't pretend you figured out anything. [You were told exactly what was wrong months ago](https://github.com/Ascoware/get-iplayer-automator/issues/27#issuecomment-302232859) and your response was to [profess your desire to remain ignorant about Perl](https://github.com/Ascoware/get-iplayer-automator/issues/27#issuecomment-302396737).  You were never obligated to make get_iplayer work properly, but then don't try to take credit when someone else already posted the necessary information.

**Comment by skovatch** [comment]
Sigh... had you bothered to look at my commit you'd realize how ridiculous your comment is. get_iplayer tells me every time I run it what is missing. What I figured out is how to get the additional modules into the macOS application bundle and then set the right environment variables so that they can be found.

You, sir, need to work on your anger management. Take 30 minutes after you think of something before you post anything else here. I'm not claiming credit for anything that anyone else has posted here. If you knew something about macOS application development and had posted how to do what I did, then yeah, I'd give you credit for that.

**Comment by Lordsnooty05** [comment]
ilainftw, how dare you talk like that to the guy that saved this application from going under. What a cheek. skovatch saved this application when others just talk a great talk but did nothing. This is a Great Application which like all application has it problems from time to time but Skovatch does his best to sort out to the benefit of all. Personally I hope you are banned from this forum but if not then I hope you see the errors of your way and Apologize to Skovatch.
Thanks Skovatch for all what you do to keep this application running, I for one appreciate it

**Comment by Rock-Hunter** [comment]
Agreed, DON'T ever speak to @skovatch in that way, it's because of him we anything at all, BE RESPECTFUL.

**Comment by SwaleSwimmer** [comment]
I couldn't agree more with the last two comments. skovatch has saved GIA and I use it every day and am really grateful that it is still, with a few warts, very useable. Personally I can live with a fairly long cache update as long as GIA continues to be useable. Sounds like kovatch has resolved that as well. Thanks and kudos kovatch.

**Comment by Sircam19** [comment]
Agreed this program is awesome and we are all deeply indebted to skovatch for fixing it. I really don't understand how someone can be that rude and clueless. Skovatch has done an amazing job. Thank you Skovatch.

**Comment by ian02054** [comment]
@skovatch, Just to confirm, is the 1.9 (1841) package in the release area the latest build that now includes that fix of including the requested bundles ?

**Comment by Caliban1** [comment]
As original poster on this thread, I feel I must add my heartfelt thanks to @skovatch for all his work keeping this invaluable program functional for us all, and add a voice too to the chorus of disapproval over the extraordinary post by ilainftw who I hope will consider it appropriate to apologise to skovatch...

**Comment by MacInWin** [comment]
I also appreciate skovatch's fixing the problem. But how do I get the fix? I'm not a programmer, I just want the executable application. Will the fix be incorporated in 1.9.x at some point? If not, is there a simple tutorial on how to get skovatch's fix and incorporate it in 1.9.1?

**Comment by skovatch** [comment]
@ian02054 I haven't tagged and posted a release yet. I hope to do that later today. I posted here more by way of indicating progress is being made rather than an announcement.

**Comment by ian02054** [comment]
Thanks for the clarification Scott. Thought i missed a step.. 
Thanks for all the help.. much appreciated.

**Comment by MacInWin** [comment]
Thanks for the update! I'll keep looking for the release!

**Comment by Lordsnooty05** [comment]
Hi everyone, here is the new release
https://github.com/Ascoware/get-iplayer-automator/releases/tag/1.9.2
skovatch has come the rescue again and sorted this and other issues out again and has helped to keep this great application going.
Thanks

**Comment by Sircam19** [comment]
Thank you very much Skovatch... the work you have done has made a major difference to my life (have UK citizenship but am often away)  and is greatly appreciated. Being able to use this application has been amazing, I wish I could contribute more than just my words and praise, but please know that your effort are very much welcomed.

**Comment by skovatch** [comment]
Thanks, everyone, for the kind words! As a daily user of this app myself, I'm plenty motivated to keep this alive as long as I can.

I really need to come up with a better announcement mechanism, and I am going to work on the self-updater with Sparkle, but this was enough of an update that warranted not waiting for that to get finished.

Closing as fixed.

**Comment by manderson23** [comment]
Great to see this added what a difference it makes. Thanks.
