### ISSUE TITLE
Unable to download index

### ISSUE THREAD

**Issue by freddyx844** [Ascoware/get-iplayer-automator#466]
Unable to fetch index, extract from log file below.

Get iPlayer Automator 1.26.0 Initialized.
Updating Programme Index Feeds...

INFO: Indexing tv programmes (concurrent)
ERROR: Failed to download BBC Alba schedule page (3/3): https://www.bbc.co.uk/schedules/p00fzl67/2023/w52
ERROR: Connection error: Connect timeout

**Comment by skovatch** [comment]
I'm not seeing this as of just now, so this is most likely a one-off BBC issue. If you can reproduce it add more details.
