### ISSUE TITLE
'About' text corrupted

### ISSUE THREAD

**Issue by WilliamOfGaunt** [Ascoware/get-iplayer-automator#468]
*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*

Opening the About window.

*What is the expected output? What do you see instead?*

The About text; what I see instead appears to be garbage (question marks in squares).

*What version of GiA are you using? On what version of OS X?*

GiA version 1.26.0; MacOS Sonoma 14.1.2 .

*Are you using a web proxy? DNS proxy? VPN? VPS?*

None of the above.

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *

None - GiA works well in other respects!

*Please provide any additional information below.*

When I copy the text into TextEdit it's perfectly readable as text, so it may be something screwy elsewhere and nothing to do with GiA at all - I just wonder whether I'm the only one seeing this! I attach a relevant screenshot.

![Corrupted About text in GiA 1 26](https://github.com/Ascoware/get-iplayer-automator/assets/28531006/8394e551-b31e-4f8f-9988-4ca2985329c2)

**Comment by skovatch** [comment]
Yikes, you're right -- I see this too. Thank you for the report.

**Comment by skovatch** [comment]
Something changed in macOS such that font fallback names in CSS aren't working. If I remove 'Geneva' from the font list in the CSS it works again.

**Comment by WilliamOfGaunt** [comment]
Many thanks for the clarification, Scott. I suspected it was the OS that dun it; do I need to change anything, or will it just be in the next update (for which no hurry from my point of view!).

B.

**Comment by skovatch** [comment]
No, I don't think you can work around it. It's not critical so I won't rush an update just for this.

**Comment by skovatch** [comment]
Fixed in v1.26.1
