### ISSUE TITLE
Invalid Output error on launch or cache update

### ISSUE THREAD

**Issue by mydigitalbubble** [Ascoware/get-iplayer-automator#469]
--------------
*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*
Launching GiA or performing a cache update generates an Invalid Output pop-up error (full txt in additional info below). The pop-up offers _OK_ to clear, but the pop-up repeats for as many times as there are BBC shows listed in the PVR list.

*What is the expected output? What do you see instead?*
Expect a successful cache update with zero pop-up

*What version of GiA are you using? On what version of OS X?*
1.26.0 on macOS catalina 10.15.7

*Are you using a web proxy? DNS proxy? VPN? VPS?*
No

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *
Any BBC

*Please provide any additional information below.*

Error message pop-up with the text below:

Invalid Output!
Please check your query. Your query must not alter the output format of Get_iPlayer. (getiPlayerUpdateFinished)

The error only started after the update to GiA 1.26.0.
It had been working fine up till then, although admittedly this was my first launch of GiA since 1/1/24. Downloads and updates for 31/12/23 and 1/1/24 were fine.

Possibly a manifestation of #467-  my BBC index is also reported as up to date. Not sure if the index was empty though. Not sure how to check?

**Comment by mydigitalbubble** [comment]
As suggested in the thread to #467 - downgrading to GiA 1.25.4 restores functionality in this case too.

**Comment by skovatch** [comment]
Should be fixed in v1.26.1
