### ISSUE TITLE
"Use Current Webpage" broken with episode titles containing commas

### ISSUE THREAD

**Issue by gadgetchnnel** [Ascoware/get-iplayer-automator#471]
*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*
* Go to a BBC episodes page for a show which has episode titles containing commas
* Click "Use Current Webpage" in the app

*What is the expected output? What do you see instead?*
I'd expect to see the list of episodes with correct PIDs for each episode

Instead I see the following, with the PID column containing part of the title.

![image](https://github.com/Ascoware/get-iplayer-automator/assets/2099542/d472ad0f-253e-4c52-8af5-e5e332766534)
Those episodes will then fail to download as the PIDs are invalid.

*What version of GiA are you using? On what version of OS X?* 1.26.0 on Sonoma 14.1.2 (23B92)

*Are you using a web proxy? DNS proxy? VPN? VPS?* No

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *

We Forced a Bot to Write This Show
https://www.bbc.co.uk/programmes/m001tmj6/episodes/player

*Please provide any additional information below.*
Other shows have only some episodes with commas in their names, and only those episodes will fail.

**Comment by jefro108** [comment]
There's a workaround if you go to BBC Sounds pages. It doesn't seem to add a series all at once for BBC Sounds but if you go to each individual episode eg https://www.bbc.co.uk/sounds/play/m001tj2g the page is recognised and will be added with the correct PID and the metadata is filled out before downloading

**Comment by skovatch** [comment]
Yup, I just reproduced it. Thank you for the report!

**Comment by skovatch** [comment]
Should be fixed with v1.26.1
