### ISSUE TITLE
BBC closing Desktop App soon

### ISSUE THREAD

**Issue by alphamikegc** [Ascoware/get-iplayer-automator#472]
Not an issue yet, but could it be for GIA users?

BBC statement for computer or laptop users
We have started the process of closing the Desktop Downloads App. Downloading programmes from a computer or laptop will no longer be available from Monday 11 March. You can still watch your existing downloads until Monday 8 April 2024.
You can also still download your favourite programmes on your mobile device, and add programmes to your Watchlist to return later.

**Comment by alphamikegc** [comment]
Thanks for your input Scott. Yes we will just have to wait and see and keep fingers crossed.

**Comment by skovatch** [comment]
It's March 30 and no changes as far as I can tell regarding downloads, so I'll close this.
