### ISSUE TITLE
Version 1.26.0 not downloading programmes with macOS 10.15.7

### ISSUE THREAD

**Issue by LJMason6** [Ascoware/get-iplayer-automator#474]
Any advice appreciated.

I first downloaded v1.26.0 using the built-in updater, updating from v1.25.3. The new version "just didn't work", so I downloaded a fresh copy of v1.25.3 and reverted to that. I've now installed a new copy of v1.26.0 (20240101001) and listed the exact problems I'm seeing: please see numbered points below.

I've currently got v1.25.3 and v1.26.0 installed in the main Applications folder, with the filenames "Get iPlayer Automater v1.25.3.app" and "Get iPlayer Automater v1.26.0.app" 

macOS Catalina, v10.15.7 (19H1519)
iMac (27-inch, Late 2013)
24 GB 1600 MHz DDR3
1TB HD, 111 GB available

No proxy in use, located in UK, Get iPlayer Automator v1.25.3 continues to work normally.

Problems with Get iPlayer Automater v1.26.0:

1) v1.26.0 fails to find any BBC programmes when I use its built-in search function.

I've just tested this random example which was recently broadcast, to ensure it's within the 7 day limit:

https://www.bbc.co.uk/iplayer/episode/m001wt6h/doctors-series-24-180-the-power-of-suggestion

Programme ID: m001wt6h

2) "File -> Force Cache Update" results in no report of activity at the bottom of the v1.26.0 main window.

3) If I select a programme with "Use Current Webpage", v1.26.0 displays any BBC programme with:

Status "Not Available"
Show "Retrieving Metadata"

(tested just now on https://www.bbc.co.uk/iplayer/episode/m001wt6h/doctors-series-24-180-the-power-of-suggestion)

Other points:

4) After doing the above tests, I ran v1.25.3, successfully found the above episode of Doctors which displayed with all fields correctly filled in the Get iPlayer Automator main window, quit v1.25.3, then launched v1.26.

v1.26 displayed the following alert box seven times in a row:

"Invalid Output!

Please check your query. Your query must not alter the output format of Get_iPlayer. (getiPlayerUpdateFinished)"

finishing up with a main window showing:

Programme ID: m001wt6h
Status: Not Available
Show: Retrieving Metadata
Episode: The Power of Suggestion
Last Broadcast: 29 Feb 2024

-so, the programme was all set to download with "Status: Available"  and "Episode: The Power of Suggestion" in v1.25.3, but something went wrong when I tried v1.26.0

(I tested v1.25.3 using its built-in search, removed the programme from the queue, then tried "Use Current Webpage: both methods worked)

5) I have Little Snitch installed https://www.obdev.at/products/littlesnitch/index.html.

v1.26.0 behaves the same whether I've got Little Snitch turned on or off.

I've currently got Little Snitch turned on and configured to allow all outgoing connections for both v1.25.3 and v1.26.0 - and checked now that this is the case in Little Snitch Configuration.

I've checked Little Snitch's "Network monitor". 

For v1.26.0, Little Snitch Network Monitor.app shows one network connection, to the domain github.io. Little Snitch Network Monitor.app also shows confirmation that all outgoing connections are allowed from v1.26.0.

For v1.25.3, Little Snitch Network Monitor.app shows network connections to the following domains:

bbc.co.uk
bbci.co.uk
bidi.net.uk
akamaized.net

**Comment by skovatch** [comment]
Please check v1.26.1, which should have a fix for get_iplayer not being able to run searches or perform any caching.

**Comment by LJMason6** [comment]
Thanks - so far, all working perfectly.
