### ISSUE TITLE
Doctor Who new season incorrectly numbered in Kodi naming

### ISSUE THREAD

**Issue by jefro108** [Ascoware/get-iplayer-automator#481]
*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*
Just downloading with Kodi naming selected

*What is the expected output? What do you see instead?*
Doctor Who Season 1 is being named Doctor Who Season 2 eg Doctor Who.s02e05.Dot and Bubble.mp4 instead of Doctor Who.s01e05.Dot and Bubble.mp4

*What version of GiA are you using? On what version of OS X?*
GiA Version 1.26.1 (20240329001) 
macOS 12.7.5 (21H1222)

*Are you using a web proxy? DNS proxy? VPN? VPS?*
No

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *
Doctor Who.s02e05.Dot and Bubble

*Please provide any additional information below.*
See log attached
[drwholog.txt](https://github.com/user-attachments/files/15755215/drwholog.txt)

**Comment by skovatch** [comment]
The metadata for that episode seems to disagree with you that it's Season 2:

```
get_iplayer --info --pid m001zxwj
get_iplayer 3.35.0-darwin
  Copyright (C) 2008-2010 Phil Lewis, 2010- get_iplayer contributors
  This program comes with ABSOLUTELY NO WARRANTY; for details use --warranty.
  This is free software, and you are welcome to redistribute it under certain
  conditions; use --conditions for details.


Episodes:
Doctor Who: Season 1 - Dot and Bubble, BBC One, m001zxwj
INFO: 1 total programmes

INFO: Processing tv: 'Doctor Who: Season 1 - 05. Dot and Bubble (m001zxwj)'
INFO: No versions of this programme were selected (available versions: audiodescribed,combined,original,signed)

brand:           Doctor Who
categories:      Drama,SciFi & Fantasy
category:        Drama
channel:         BBC One
credits:         /Users/skovatch/Desktop/iPlayer Recordings/Doctor_Who_Season_1_-_05._Dot_and_Bubble_m001zxwj_default.credits.txt
cuesheet:        /Users/skovatch/Desktop/iPlayer Recordings/Doctor_Who_Season_1_-_05._Dot_and_Bubble_m001zxwj_default.cue
desc:            On Finetime, the Doctor and Ruby must convince the citizens of a monstrous unseen terror.
desclong:        The world of Finetime seems happy and harmonious. But an awful terror is preying on the citizens. Can the Doctor and Ruby make them see the truth before it’s too late?
descmedium:      The world of Finetime seems happy and harmonious. But an awful terror is preying on the citizens. Can the Doctor and Ruby make them see the truth before it’s too late?
descshort:       On Finetime, the Doctor and Ruby must convince the citizens of a monstrous unseen terror.
dir:             /Users/skovatch/Desktop/iPlayer Recordings
dldate:          2024-06-09
dltime:          18:35:50
durations:       audiodescribed: 2580
durations:       combined: 2580
durations:       original: 2580
durations:       signed: 2580
episode:         05. Dot and Bubble
episodenum:      5
episodeshort:    Dot and Bubble
expires:         in 1y 12 days 16 hours (2025-06-22T18:35:10+00:00)
ext:             EXT
filename:        /Users/skovatch/Desktop/iPlayer Recordings/Doctor_Who_Season_1_-_05._Dot_and_Bubble_m001zxwj_default.EXT
filepart:        /Users/skovatch/Desktop/iPlayer Recordings/Doctor_Who_Season_1_-_05._Dot_and_Bubble_m001zxwj_default.partial.EXT
fileprefix:      Doctor_Who_Season_1_-_05._Dot_and_Bubble_m001zxwj_default
firstbcast:      2024-06-01T18:50:00+01:00
firstbcastdate:  2024-06-01
firstbcastday:   01
firstbcastmonth: 06
firstbcastrel:   8 days 7 hours ago
firstbcasttime:  18:50:00
firstbcastyear:  2024
longname:        Doctor Who: Season 1
name:            Doctor Who: Season 1
nameshort:       Doctor Who
pid:             m001zxwj
player:          https://www.bbc.co.uk/iplayer/episode/m001zxwj
qualities:       audiodescribed: sd,web,mobile
qualities:       combined: sd,web,mobile
qualities:       original: fhd,hd,sd,web,mobile
qualities:       signed: fhd,hd,sd,web,mobile
qualitysizes:    audiodescribed: sd=581MB,web=580MB,mobile=182MB [estimated sizes]
qualitysizes:    combined: sd=581MB,web=580MB,mobile=182MB [estimated sizes]
qualitysizes:    original: fhd=2814MB,hd=1777MB,sd=1005MB,web=580MB,mobile=182MB [estimated sizes]
qualitysizes:    signed: fhd=2814MB,hd=1777MB,sd=1005MB,web=580MB,mobile=182MB [estimated sizes]
releaseyear:     2024
sebcast:         202406011850
sebcastdate:     20240601
sebcasttime:     1850
senum:           s01e05
senumx:          01x05
series:          Season 1
seriesnum:       1
seriessort:      Season 1
sesort:          s01e05
sesortx:         01x05
subsfile:        /Users/skovatch/Desktop/iPlayer Recordings/Doctor_Who_Season_1_-_05._Dot_and_Bubble_m001zxwj_default.srt
subspart:        /Users/skovatch/Desktop/iPlayer Recordings/Doctor_Who_Season_1_-_05._Dot_and_Bubble_m001zxwj_default.partial.srt
subsraw:         /Users/skovatch/Desktop/iPlayer Recordings/Doctor_Who_Season_1_-_05._Dot_and_Bubble_m001zxwj_default.ttml
thumbfile:       /Users/skovatch/Desktop/iPlayer Recordings/Doctor_Who_Season_1_-_05._Dot_and_Bubble_m001zxwj_default.jpg
thumbnail:       https://ichef.bbci.co.uk/images/ic/1920x1080/p0j0qs20.jpg
title:           Doctor Who: Season 1: Dot and Bubble
tracklist:       /Users/skovatch/Desktop/iPlayer Recordings/Doctor_Who_Season_1_-_05._Dot_and_Bubble_m001zxwj_default.tracks.txt
type:            tv
verpids:         audiodescribed: p0j1kfyz
verpids:         combined: p0j1vttp
verpids:         original: m001zxwh
verpids:         signed: m001zz1y
version:         default
versions:        audiodescribed,combined,original,signed
web:             https://www.bbc.co.uk/programmes/m001zxwj
```

**Comment by skovatch** [comment]
And, the iPlayer page also says it's Season 1. So, I think this is behaving correctly/

https://www.bbc.co.uk/iplayer/episodes/p0gglvqn/doctor-who?seriesId=m001z8c2

**Comment by jefro108** [comment]
The following is a section of the log that shows that GiA is writing to a file that says s02 in the name rather than s01

`INFO: Wrote file /Users/user/media/Downloads/TV Shows/Doctor Who/Doctor Who.s02e05.Dot and Bubble.mp4
INFO: Loading recordings history
INFO: Downloading thumbnail
INFO: Downloading URL (1/3): https://ichef.bbci.co.uk/images/ic/640x360/p0j0qs20.jpg
INFO: AtomicParsley version: 0.9.7-get_iplayer.4 (utf8)
INFO: Tagging MP4
INFO: Command: "/Applications/Get iPlayer Automator.app/Contents/Resources/get_iplayer/utils/bin/AtomicParsley" "/Users/user/media/Downloads/TV Shows/Doctor Who/Doctor Who.s02e05.Dot and Bubble.mp4" --metaEnema --freefree --overWrite --stik "TV Show" --advisory remove --copyright "2024 BBC (programme data only)" --title "Dot and Bubble" --artist "BBC One" --albumArtist "BBC TV" --album "Doctor Who: Season 1" --grouping "Drama,SciFi & Fantasy" --composer "BBC iPlayer" --genre Drama --comment "On Finetime, the Doctor and Ruby must convince the citizens of a monstrous unseen terror." --year "2024-06-01T18:50:00+01:00" --tracknum 5 --disk 2 --hdvideo 1 --TVShowName "Doctor Who: Season 1" --TVEpisode m001zxwj --TVSeasonNum 2 --TVEpisodeNum 5 --TVNetwork "BBC One" --artwork "/Users/user/media/Downloads/TV Shows/Doctor Who/Doctor Who.s02e05.Dot and Bubble.jpg" --description "On Finetime, the Doctor and Ruby must convince the citizens of a monstrous unseen terror." --longdesc "The world of Finetime seems happy and harmonious. But an awful terror is preying on the citizens. Can the Doctor and Ruby make them see the truth before it's too late?
PLAY: https://www.bbc.co.uk/iplayer/episode/m001zxwj
INFO: https://www.bbc.co.uk/programmes/m001zxwj" --lyrics "The world of Finetime seems happy and harmonious. But an awful terror is preying on the citizens. Can the Doctor and Ruby make them see the truth before it's too late?
PLAY: https://www.bbc.co.uk/iplayer/episode/m001zxwj
INFO: https://www.bbc.co.uk/programmes/m001zxwj"
 Started writing to temp file. `

So clearly something is strange with GiA if it’s making a Season 1 programme into Season 2

Sorry I might have confused things by quoting “Doctor Who.s02e05.Dot and Bubble” as the programme when that was the error. The programme was as you rightly said is listed as Season 1  from https://www.bbc.co.uk/iplayer/episode/m001zxwj/doctor-who-season-1-5-dot-and-bubble?seriesId=m001z8c2
