### ISSUE TITLE
STV Use Current Webpage - 'DRM Protected'

### ISSUE THREAD

**Issue by SOLOSAIR** [Ascoware/get-iplayer-automator#482]
Screenshot I have is self explanatory.

Programme ID: 215084

Show:
Coronation Street, Fri 13 Sep

Status:
Download Failed: DRM protected

Edit:
after GiA auto-added programme after a few minutes, as in settings, it downloaded OK!  May be a sign of things to come though?

**Comment by skovatch** [comment]
I just got it with an ID of 216084, so maybe it just wasn't ready to download yet? Not sure why it reported DRM protected, though.

**Comment by skovatch** [comment]
Closing this since I'm pretty sure it was just a timing issue.
