### ISSUE TITLE
Radio cache stored at incorrect path

### ISSUE THREAD

**Issue by gingerbeardman** [Ascoware/get-iplayer-automator#5]
Looks like there are some misplaced quotes in the code, I will try to find it

This was not a problem with 1.8.7

![screen shot 2017-05-08 at 14 45 47](https://cloud.githubusercontent.com/assets/49612/25806975/117efcb8-33fd-11e7-9bcc-1a5d3dfa7e7a.png)

**Comment by skovatch** [comment]
Thanks... I was playing around with quoting as I thought it was causing problems launching the GiP task. I must have missed removing the quotes.

**Comment by gingerbeardman** [comment]
Say I cannot easily search code in your fork (GitHub limitation) so I guess that poses the question how to make this the official repo?

**Comment by skovatch** [comment]
Not sure... I feel like these things just evolve naturally? Maybe the owners of the original repo can transfer it to me at some point, but let's see what happens.

**Comment by Lordsnooty05** [comment]
Skovatch, this sounds like a lot of work hosting a Website and and updating it, plus I suppose this is going to cost you money? Maybe someone else on here with a bit of programming skill and savvy could step up to the mark and help you with that much effort. Plus will you not be out some money in hosting a Website? ......maybe some of us could join together and help pay something towards the cost of that. I am very grateful for all the work you have put in helping this Great App survive....it is much appreciated

**Comment by skovatch** [comment]
Found this... will check in soon.

**Comment by skovatch** [comment]
Fixed in 1.9b2
