### ISSUE TITLE
.zip File unzipped as damaged/corrupted

### ISSUE THREAD

**Issue by demosthien** [Ascoware/get-iplayer-automator#51]
I know it's not an issue with GIA itself but I wanted to leave a message for you to let you know.

I had to try three different unzip apps (the native OSX one, The Unarchiver, and finally Keka) in order to finally have GIA in a usable damaged/uncorrupted form that opened. Keka was the one that finally gave me a good unzip.

I don't know why this would be, maybe it's something wrong with my iMac (possible) but thought I'd give you a heads-up just in case others have had the issue.

  Model Name:	iMac
  Model Identifier:	iMac13,2
  Processor Name:	Intel Core i5
  Processor Speed:	3.2 GHz

  System Version:	OS X 10.10.5 (14F2411)
  Kernel Version:	Darwin 14.5.0

**Comment by skovatch** [comment]
I'm using tar to create a gzipped version of the app now, so no need for anything special. It should also update itself in the future.
