### ISSUE TITLE
"BBC has blocked access"

### ISSUE THREAD

**Issue by hugofalkman** [Ascoware/get-iplayer-automator#55]
Just got the following message in the GiA log after a failing download. Downloads from BBC were working this morning.

"WARNING: The BBC has blocked access to this programme because it has determined that you are using get_iplayer outside the UK.
BBC Download (ID=b091wcqx): Red Rock: Series 2: Episode 23 Failed"

Edit: My DNS Smart Server supplier has acknowledged they have a problem with iPlayer. Am closing this issue.

**Comment by tryanythingonce** [comment]
I have the same problem? How to fix this, I am using a powerful VPN, I am not sure how the BBC is knowing this?
