### ISSUE TITLE
App updater

### ISSUE THREAD

**Issue by gingerbeardman** [Ascoware/get-iplayer-automator#6]
It would be great if you could restore the ability for the app to update itself when new versions are released

**Comment by skovatch** [comment]
For this I will need to set up a web site and host the updates. I have used Sparkle before, so restoring it is just a matter of putting the correct links back into the app. I have web hosting but no actual web site. I'll try to work on that over the next month or so.

**Comment by gingerbeardman** [comment]
Maybe try this to host on GitHub

https://github.com/pierredavidbelanger/githubappcaster

**Comment by Lordsnooty05** [comment]
Skovatch, this sounds like a lot of work hosting a Website and and updating it, plus I suppose this is going to cost you money? Maybe someone else on here with a bit of programming skill and savvy could step up to the mark and help you with that much effort. Plus will you not be out some money in hosting a Website? ......maybe some of us could join together and help pay something towards the cost of that. I am very grateful for all the work you have put in helping this Great App survive....it is much appreciated

**Comment by gingerbeardman** [comment]
@Lordsnooty05 there are some ways to avoid costs, let's see how things pan out

**Comment by kiwibob** [comment]
I have a VPS server that I use to host a small number of websites and would be happy to chip in.

**Comment by jefro108** [comment]
It looks like GitHub offer their own hosting for free https://pages.github.com/

**Comment by skovatch** [comment]
Thanks, everyone, for the generous offers! I think I will investigate the githubappcaster project, as that seems to be the easiest way to do it.

My day job keeps me pretty busy, so don't expect to see much in comments/updates between 8am - 6 pm Pacific time (GMT -7 or -8). This is all coming at me pretty fast -- I didn't really expect this to be the 'new home' of the app. But I think I can work out the logistics.

**Comment by skovatch** [comment]
Finally!!! This is now working directly through github.com. From version 1.9.4 onwards, the app should automatically check for and update to new releases.

**Comment by gingerbeardman** [comment]
Great! Nice work, sounds like it was tricky

**Comment by Sircam19** [comment]
Very much appreciated skovatch... We all very much appreciate your hard work keeping GIA alive AND making it better.THANK YOU.

**Comment by Lordsnooty05** [comment]
Skovatch, Thanks a Million. This latest edition seems to have sorted out everything and is working a treat and even lets you know that you need to update. I really do appreciate the amount of work you have put into this Great App. THANKS

**Comment by kiwibob** [comment]
This is just such a great app. We really do appreciate the amount of effort required to keep it going. Many thanks (sorry about the me too but skovatch is doing a great job and needs to be thanked).
