### ISSUE TITLE
Unknown: PID Not Found

### ISSUE THREAD

**Issue by jefro108** [Ascoware/get-iplayer-automator#62]
Whenever I add a BBCIII programme via the Use Current Webpage button the details are added correctly in the Show Name - Episode Name column in the Download Queue, but at some point when the Series are added to the  Queue (I have it set to automatically add after refreshing the cache) then the Show Name - Episode Name becomes Unknown: PID Not Found.

It's not a real problem because the programme gets downloaded correctly. But it is a bit confusing and was alarming the first time it happened.

Is there any way that the programme details could be retained if the PID isn't found in the cache?

**Comment by skovatch** [comment]
This happens in other places, not just BBC 3 shows. Any show grabbed directly from a web page but not yet cached will lose the description.

**Comment by hugofalkman** [comment]
Ahhh never understood that. 😊 Would it be a reasonable design change to give a warning message allowing the user to first update the cache? It would need to be optional so the user could go ahead with the download without the description, in cases where there are problems with the cache.

**Comment by skovatch** [comment]
I'm going to close this, because I know I fixed the logic so GiA fetches the metadata if a non-cached show is selected.
