### ISSUE TITLE
None of the modes in your download format list are available for this show.

### ISSUE THREAD

**Issue by Sircam19** [Ascoware/get-iplayer-automator#7]
**This issue tracker is not a discussion forum, so don't use it as such.  If you wish to discuss the BBC, iPlayer or anything else that is not related to an actual problem with the current release of GiA, post in an appropriate forum, not in this issue tracker.**

**STOP! DO NOT submit a ticket if you are unable to download a programme from outside the UK**. 

If you need an explanation, read [this](https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/No-Support-for-GiA-Outside-the-UK). If you ignore this instruction, your ticket will be closed with no further action. You can fib about your location if you like, but you will only be wasting your time. If you are using GiA within the UK, continue with the instructions below.

Before creating a new ticket, search the current open and closed tickets to see if your issue has already been reported. Use the search box at the top of the page to do so. You can also use the links below to view open and closed tickets in list form. 

#### [Closed tickets](https://github.com/GetiPlayerAutomator/get-iplayer-automator/issues?q=is%3Aissue+is%3Aclosed)

If you create a ticket for an issue that has already been reported, your ticket will be closed with no further action. If you are certain your issue has not yet been reported, continue with the instructions below.

Create a succinct title describing your issue in the `Title` field above, then provide the information requested below. If you do not provide the requested information, your ticket will be closed with no further action.

Delete the instructions above before submitting your ticket.

---

What steps will reproduce the problem? Be specific, and provide as much detail as possible.
Tried to download the latest episode of Panorama
What is the expected output? What do you see instead?
Download to be successful was the expected result...what occurred was the following

ERROR: Failed to record 'Panorama - What Facebook Knows About You (b08qgbc3)'
REASON FOR FAILURE: None of the modes in your download format list are available for this self.show.
Try adding more modes.
What version of GiA are you using? On what version of OS X?
Version 1.9b1 (1814)

Are you using a web proxy? DNS proxy? VPN? VPS?

What programme are you attempting to download (full title, series and episode)? **Provide only ONE programme as an example. DO NOT list multiple programmes.**

If you cannot download a programme, provide a verbose log of the attempt. See [Verbose Log](https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/Verbose-Log) in wiki for instructions on posting a verbose log for your ticket. **Your verbose log should show the results from downloading ONLY ONE programme. DO NOT post a massive log covering multiple multiple programme downloads. IMPORTANT: DO NOT paste your verbose log into your issue report. If you do, expect it to be deleted.**

If GiA crashes, provide the OS X crash log by copying the information from Crash Reporter into a file or locating the crash log in `$HOME/Library/Logs/DiagnosticReports`. See [Verbose Log](https://github.com/GetiPlayerAutomator/get-iplayer-automator/wiki/Verbose-Log) in wiki for instructions on posting a crash log for your ticket. **IMPORTANT: DO NOT paste your crash log into your issue report. If you do, expect it to be deleted.**

Please provide any additional information below.

**Comment by Sircam19** [comment]
AppController: Starting Downloads

Downloading Show 1/1:

BBC Download (ID=b08qgbc3): Downloading Panorama - What Facebook Knows About You
INFO: Episode PID detected
INFO: Trying pid: b08qgbc3 using type: tv
INFO: Trying to download PID using type tv
INFO: pid not found in tv cache
INFO: 1 Matching Programmes
INFO: Checking existence of editorial version
INFO: No specified modes (dafhigh,dafstd,daflow,hlsstd) available for this programme with version 'editorial'
INFO: Try using --modes=dvfxsd,dvfhd,dvfhigh,dvfxhigh,dvfsd,dvflow,hvfxsd,hvfsd,hvfhd,hvfhigh,hvfxhigh,hvflow
ERROR: Failed to record 'Panorama - What Facebook Knows About You (b08qgbc3)'
REASON FOR FAILURE: None of the modes in your download format list are available for this self.show.
Try adding more modes.
BBC Download (ID=b08qgbc3): Panorama - What Facebook Knows About You Failed

**Comment by Sircam19** [comment]
Am really sorry got it to work...s...I have to say this app works so incredibly well and love the added functionality and the direction you have taken. THANK YOU  Mr. Developer...excellent work.

**Comment by Rock-Hunter** [comment]
@Sircam19 I'm now having the same issue, but only with radio programmes, how did you get it to work?

**Comment by gingerbeardman** [comment]
@Rock-Hunter also having this, opened a new issue for it: https://github.com/Ascoware/get-iplayer-automator/issues/15
