### ISSUE TITLE
BBC Cache not updating 

### ISSUE THREAD

**Issue by nitramlatep** [Ascoware/get-iplayer-automator#70]
BBC programs no longer being updated in cache, hence do not get found in search.
Manually adding web page still ok.
Fix was issued for windows version last night.

**Comment by botchla** [comment]
That explains the problems I'm having with the Series Link function.

**Comment by botchla** [comment]
@nitramlatep When you say the Windows version - what do you mean? I wasn't aware of a version of GiA for Windows...

**Comment by skovatch** [comment]
Looks like get_iplayer shipped a new version to deal with a server-side change. I'll try to merge it in and release a new version ASAP.

https://github.com/get-iplayer/get_iplayer/wiki/release300to309#release306

**Comment by nitramlatep** [comment]
@botchla. Thanks @skovatch, apologies I was not very clear, the Windows equivalent is get_iplayer, which is supported still by dinkypumpkin who used to support GiA as well, until luckily for us @skovatch volunteered to keep GiA going.  The core code is basically the same, but there are some differences in that since its not based on Apple OS it does not link directly into iTunes etc.

**Comment by botchla** [comment]
@nitramlatep Ah! Thanks for clearing that up - didn't want to be missing out on something!

**Comment by Vangelis66** [comment]
@skovatch wrote: 

> get_iplayer shipped a new version to deal with a server-side change. I'll try to merge it in

Hello Scott; I think it would suffice codewise to just implement https://github.com/get-iplayer/get_iplayer/commit/2a80f28ce56a52f4c6c013b5710b8265ce95fce3 into existing (inside GiA) GiP code, but, sadly, there's apparently another issue pestering GiP users on OS X: 

https://squarepenguin.co.uk/forums/thread-1547.html
https://squarepenguin.co.uk/forums/thread-1554.html

https://github.com/get-iplayer/get_iplayer/wiki/issues#get_iplayer-known-issues => 

> BBC schedule pages are now being redirected to HTTPS URLs. Systems with obsolete Perl modules, like 
> macOS (and Debian Wheezy), could have problems with that. In particular, it looks like obsolete versions  of IO::Socket::SSL cause problems for Mojolicious. New TV programmes are not added to the cache and 
> you will see error messages similar to "Mojo::Reactor::Poll: I/O watcher failed: SSL_ca_file 
> SCALAR(0x7fbcc8800178) does not exist" during cache updates. You can set up a local library for Perl 
> modules (described in the get_iplayer install docs) and install the latest versions of both Mojolicious and 
> IO::Socket:SSL to override obsolete system packages. This is not a problem with get_iplayer itself, so 
> updating to get_iplayer 3.06+ alone will have no effect. 

Have I correctly understood that GiA users will also be impacted?

@botchla wrote: 

> When you say the Windows version - what do you mean? I wasn't aware of a version of GiA for Windows...

Not a match for GiA, sadly, but on a Windows box you can install and use [get_iplayer_win32](https://github.com/get-iplayer/get_iplayer_win32/releases); it does not support ITVHub, though :disappointed: ; for that you'd have to resort to another app (e.g. youtube-dl).

**Comment by skovatch** [comment]
> Hello Scott; I think it would suffice codewise to just implement https://github.com/get-iplayer/get_iplayer/commit/2a80f28ce56a52f4c6c013b5710b8265ce95fce3 into existing (inside GiA) GiP code,

Okay, thanks for the link! I think that may be the path to least resistance for getting an update done.

> https://github.com/get-iplayer/get_iplayer/wiki/issues#get_iplayer-known-issues => 
> 
> > you will see error messages similar to "Mojo::Reactor::Poll: I/O watcher failed: SSL_ca_file 
> > SCALAR(0x7fbcc8800178) does not exist" during cache updates. You can set up a local library for Perl 
> > modules (described in the get_iplayer install docs) and install the latest versions of both Mojolicious and 
> > IO::Socket:SSL to override obsolete system packages. This is not a problem with get_iplayer itself, so 
> Have I correctly understood that GiA users will also be impacted?

I am already including a newer version of Mojolicious and SSL, so I think the answer is no, based on my testing so far.

**Comment by skovatch** [comment]
Fixed in v1.9.8
