### ISSUE TITLE
BBC weekly schedules renamed from 'this week' to 'wXX' (week no)

### ISSUE THREAD

**Issue by terrytrinder** [Ascoware/get-iplayer-automator#71]
Hi Ascoware
Starting last week, GiA is unable to  automatically download/update the BBC index files, and comes up with this warning:

WARNING: Failed to download programme schedule http://www.bbc.co.uk/radio4/programmes/schedules/fm/this_week

On checking the BBC schedules page, I can see radio schedule links for the "This Week" schedule page no longer end in 'this_week' but instead ends in the week number 

eg here is the weekly schedule page for BBC Radio 4, which ends in /w43

https://www.bbc.co.uk/schedules/p00fzl7j/2017/w43

Unless this changes, we won't be able to automate any downloads from the BBC with the PVR Manager ie nothing new will be added by the Index Feeds

Assuming this situation doesn't get corrected next week ie it is a permanent change, please can I ask that GiA calculates the week number and puts that as the suffix on every search?

Many Thanks

Terry Trinder

*What version of GiA are you using? On what version of OS X?*

I am running Mac OS Sierra, version 10.12.6 on a late 2012 27" iMac, processor 3.4 GHz Intel Core i7, 32 Gb RAM, graphics NVIDIA GeForce GTX 680MX 2048 MB

My settings for GiA are the default settings:
no proxy and 
add available Series-link programmes to the queue at startup

Here's an example of the iPlayer webpage for "Strictly Come Dancing" (the Saturday night show of 28/10/17), that should have been picked up today with an Index Feed update, but wasn't because the index isn't updating:

https://www.bbc.co.uk/iplayer/episode/b09dhrlh/strictly-come-dancing-series-15-week-6

---------------

*Are you using a web proxy? DNS proxy? VPN? VPS?*

My house gets BT Broadband Infinity, optic cable to the local cabinet, then wire to the house
I am using a BT Hub 6 modem and the iMac is ethernet cabled to that

*Please provide any additional information below.*

Here are the first few lines of today's attempt at the index file refresh:
************
Get iPlayer Automator 1.9b6 Initialized.

GetITVShows: ITV Cache Update Starting 
AppController: Updating Programme Index Feeds...

GetITVShows (Info): Merge complete B/F Programmes: 1306 C/F Programmes: 1179 Today Programmes: 166 
GetITVShows: Update Finished
INFO: Getting tv Index Feeds (this may take a few minutes)
INFO: Using sequential indexing
WARNING: Failed to download programme schedule http://www.bbc.co.uk/bbcalba/programmes/schedules/this_week

etc

***********

**Comment by skovatch** [comment]
Based on that log you need to update to the latest version, which has a fix for this and many other things, including the ability to update itself.

See https://github.com/Ascoware/get-iplayer-automator/releases/tag/v1.9.8
