### ISSUE TITLE
BBC Blue Planet not showing up 

### ISSUE THREAD

**Issue by mothyinuk** [Ascoware/get-iplayer-automator#72]
BBC Blue Planet does not show up when searching for show or when doing a searching PVR manager.
Cannot understand this as the new Series Episode 1 can be added from Safari. Not a desperate situation but would like to know that to do to correct this. Force updated cache and also restarted Mac, but made no difference. Any clues?

**Comment by craigmc79** [comment]
I've been having the same issues from last week - nothing from iPlayer has been searchable for about the last week, however I can add manually via the relevant page on iPlayer. Updated today to latest release but to no avail. ITV shows are fine.

**Comment by skovatch** [comment]
Not sure what to say, as I'm not seeing this... I can suggest quitting the application, deleting "~/Library/Application Support/Get iPlayer Automator" and then running it again. Make sure you are running v1.9.9.

**Comment by Rock-Hunter** [comment]
Working fine here thanks Scott.

**Comment by mothyinuk** [comment]
> Not sure what to say, as I'm not seeing this... I can suggest quitting the application, deleting "~/Library/Application Support/Get iPlayer Automator" and then running it again. Make sure you are running v1.9.9.

Thanks skovatch, much appreciated, but still refuses to see BBC Blue Planet II for some reason in search field and PVR search, strange!

I am using vs 1.9.9 and will try removing the Support file, but will I keep the PVR files I have already got listed that work if I do this? Or is there a way to export and then import them again saved PVR programmes?

Thanks for all the great work.

**Comment by craigmc79** [comment]
Thanks, that worked a treat! I can confirm it did delete my series links but since i only had a couple it was easy enough to re-add them. I can also confirm Blue Planet II shows up after doing that.

Thanks for your help 👍

**Comment by mothyinuk** [comment]
I can confirm too that removing the Application Support File removed the problem and can now add BBC Blue Planet to search field and PVR field and program is added.
Also I played with Application Support files and kept old Folder. I then added back to see what happened… download_history and history.gia and Queue.automatorqueue. This restored my download history and the PVR list without the effect of the previous problem with Get iPlayer Automator. Thanks for the advise and glad to be back to normal.

**Comment by Sircam19** [comment]
Mothyinuk thanks for sharing your additional approach. Worked perfectly, Blue Planet II now "appears" and history and PVR are both also intact. THANK YOU.

**Comment by skovatch** [comment]
If someone who saved their old Get iPlayer Automator folder from Application Support could make an archive of it and attach it here, I'd appreciate it. It sounds like something (get_iplayer or GiA) is finding an old version of the cache, choking on it, and failing silently. I'd like to at least understand why it's failing.

**Comment by sparkdevelopment** [comment]
@skovatch I've emailed you my archived Application Support folder

**Comment by mothyinuk** [comment]
Unfortunately I have trashed the Application Support folder but an observation might be helpful. Since GiP has rebuilt the Application Support folder when refreshing cache or force rebuild cache GiP displays the result much faster. ITV was always fast, but BBC took several minutes doing something and then displayed going through the PVR programmes. Now ITV and BBC search and display any PVR programmes for download one after the other very fast. Just as a user it looks like a cache problem. Anyway hope that may help a bits. If it happens again I will first just throw away the files identified as caches to see what happens :)

**Comment by AdamMannPro** [comment]
I followed the instructions and renamed the "~/Library/Application Support/Get iPlayer Automator" and then copied the download_history, history.gia and Queue.automatorqueue from the old folder to the new one and I can now get "Blue Planet 2" and "Gunpowder" plus I still have all my old PVR history. WELL CHUFFED now
