### ISSUE TITLE
ITV Doc Martin s8e7 Crashing GiA

### ISSUE THREAD

**Issue by mothyinuk** [Ascoware/get-iplayer-automator#74]
I have just tried to download ITV Doc Martin Season 8 Episode 7 released Wednesday 1st November and it crashes GiA. Have removed caches and restarted Mac but sill no good. Other programs download fine.
Have attached crash report below. Anyone else having same problem?

[Crash Report.pdf](https://github.com/Ascoware/get-iplayer-automator/files/1437368/Crash.Report.pdf)

**Comment by mothyinuk** [comment]
Also tried removing Application Support Folder too but did not make any difference.

**Comment by hugofalkman** [comment]
Yes, crashed GiA for me too. I notice there is no picture to go with Episode 7 on ITV Hub, so it's probably missing metadata that causes the crash.

**Comment by WilliamOfGaunt** [comment]
It crashed GiA last night here too - I noticed the lack of a picture on ITV Hub but wasn't clever enough to make the deduction that Hugo did...

**Comment by WilliamOfGaunt** [comment]
It crashed GiA last night here too - I noticed the lack of a picture on ITV Hub as well, but wasn't clever enough to make the deduction that Hugo did...

**Comment by WilliamOfGaunt** [comment]
'Sworking OK now - the picture is up on ITV Hub and GiA downloaded the file, so all seems to have been fixed at ITV's end. I think this issue can be closed.

**Comment by mothyinuk** [comment]
All of a sudden this afternoon Doc Martin is downloading! Perhaps something wrong BBC end as have not changed anything my end, strange.

**Comment by Hottsy-Tottsy** [comment]
Same thing just now.  Regardless of it being iTV or BBC file.  Crashes

**Comment by skovatch** [comment]
I'll have to try to catch this next week, or maybe with something that's just aired. I mistakenly assumed that every show has a TransmissionDate and TransmissionTime, and when it doesn't you get the crash shown.

**Comment by WilliamOfGaunt** [comment]
This may be a related issue (or it may not, but transmission time could be relevant): last night's Good Old Days episode showed up in my download queue, but it gave an error (I didn't catch the type, but I think it was unknown) when I tried to download it. Turns out that the programme was *still airing*, so presumably the PVR caught the start time but not the end time or the duration. Perhaps this relates to the BBC's streaming facility, which GiA may not be geared to.

**Comment by WilliamOfGaunt** [comment]
OK, I just tried experimentally downloading a BBC programme that was still airing. It failed, and the resulting log file is attached.

[Programme still airing - download failure report.txt](https://github.com/Ascoware/get-iplayer-automator/files/1443560/Programme.still.airing.-.download.failure.report.txt)

**Comment by skovatch** [comment]
@WilliamOfGaunt I'm not sure that's anything that either get_iplayer or Get iPlayer Automator can detect. BBC doesn't make shows available for watching on iPlayer until after they have aired, and it can't work with the live streams at all. All get_iplayer knows is that none of the requested versions (default, audiodescribed, etc.) aren't available.

**Comment by WilliamOfGaunt** [comment]
**@skovatch** Obviously I defer to your understanding of how iPlayer and GiA interact! I just thought it curious that GiA was somehow able to pick up a programme (in fact, two of them) before it had finished airing, and therefore couldn't download it.

**Comment by hugofalkman** [comment]
There still seems to be a problem with ITV's Doc Martin and downloading subtitles. S8E6 was the last episode where subtitles downloaded correctly. Subtitles do not download for S8E7 and latest S8E8. The difference between the two is that for S8E7 there are no subtitles also when you watch the episode directly on ITV hub. But for S8E8 the subtitles are there when watching directly, but GiA does not download the .srt subtitle file.

**Comment by skovatch** [comment]
The crash indicated in the original description should be fixed in 1.9.10.
