### ISSUE TITLE
Unable to download BBC

### ISSUE THREAD

**Issue by jomcf** [Ascoware/get-iplayer-automator#77]
Hi - 

I'm having incredible difficulty getting BBC downloads to work. I'm able to easily play the videos in iPlayer in Safari, but no matter how much I check for Cache Updates or Force Cache Updates, I cannot for the life of me get this working. I've even added every possible BBC TV Show Format just in case.

So - any ideas where I'm going wrong?

Downloading Show 2/4:
BBC Download (ID=b098splj): Downloading The Boss: Series 2: Episode 21
INFO: encodinglocale = UTF-8
INFO: encodinglocalefs = UTF-8
INFO: encodingconsoleout = UTF-8
INFO: encodingconsolein = UTF-8
INFO: ${^UNICODE} = 39
INFO: Profile dir: /Users/admin/Library/Application Support/Get iPlayer Automator
INFO: User options file: /Users/admin/Library/Application Support/Get iPlayer Automator/options
INFO: System options file: /etc/get_iplayer/options versionlist = default
INFO: Search args: ''
INFO: Loaded history for first check.
INFO: Loading recordings history
INFO: Programme not in history
INFO: Got 1239 file cache entries for itv
INFO: Got 3688 file cache entries for tv
INFO: No file cache exists for radio
INFO: Cleaning PID - old: 'b098splj' new: 'b098splj'
INFO: Getting URL: http://www.bbc.co.uk/programmes/b098splj.json
INFO: tv episode PID detected (b098splj)
INFO: 0 matching programmes
INFO: Programme not in history
INFO: Getting URL: http://www.bbc.co.uk/programmes/b098splj.json
INFO: Getting URL: http://open.live.bbc.co.uk/mediaselector/5/select/version/ 2.0/mediaset/iptv-all/vpid/b098spl2/transferformat/dash?cb=05413
INFO: Getting URL: http://open.live.bbc.co.uk/mediaselector/5/select/version/ 2.0/mediaset/pc/vpid/b098spl2/transferformat/dash?cb=57995
INFO: Getting URL: http://open.live.bbc.co.uk/mediaselector/5/select/version/ 2.0/mediaset/iptv-all/vpid/b098spl2/transferformat/hls?cb=43267
INFO: Getting URL: http://open.live.bbc.co.uk/mediaselector/5/select/version/ 2.0/mediaset/apple-ipad-hls/vpid/b098spl2/transferformat/hls?cb=62110
INFO: No streams available for 'original' version (b098spl2) - skipping
INFO: No streams found for 'original' version (b098spl2) - deleting
WARNING: No media streams found for requested programme versions and recording modes.
ERROR: Could not get programme metadata
BBC Download (ID=b098splj): The Boss: Series 2: Episode 21 Failed

**Comment by jomcf** [comment]
The same errors occur for _any_ BBC show, even the ones that I search within GiPA, not just this one particular file. Next to Items to Cache I've ticked "BBC TV" and "ITV TV", and ITV downloads work just fine.

**Comment by mutantcamel** [comment]
You are using the latest version of GiA - https://github.com/Ascoware/get-iplayer-automator/releases ?

**Comment by kelDommage** [comment]
Using the latest version, I was able to replicate this. 

To fix it, I first closed GPA. I then opened a Terminal window and navigated to:
`/Users/myusername/Library/Application Support/Get iPlayer Automator`

and cleaned out everything in the directory. Then I reopend GPA and let the cache refill. It's now working as expected. 

Perhaps you need a "Nuke Preferences" option in the Advanced menu. Or perhaps suggest doing so there, as this all has happened before (and will happen again).

**Comment by jomcf** [comment]
It wasn't just a new install of GiPA, it was a new install of MacOS - completely fresh (albeit in a VMWare environment on my Windows desktop). Strange thing is, a day ago it just started working - and I have no idea what changed, I didn't touch it in any way except to let it try and try again on the timer.
