### ISSUE TITLE
How to switch off HQ BBC radio?

### ISSUE THREAD

**Issue by Necktilt** [Ascoware/get-iplayer-automator#78]
I have latest 1.9.9 version, and the notes at Releases here say <<GiP 3.06 introduces the ability to get higher-quality (320k) audio for BBC shows. This is on by default, but can be disabled via a checkbox in the BBC section of the 'Download Formats' preferences.>> I don't want the BBC 320k "HQ" radio audio, but unticking the checkbox as noted seems to make no difference: still getting 320. I want 128. Am I doing something wrong?

**Comment by skovatch** [comment]
I can’t check the code at the moment but I’m pretty sure I set the get_iplayer flag to disable HQ for all downloads, not just TV. Radio downloads have a different set of quality options, so check if the highest quality

**Comment by skovatch** [comment]
.... audio isn’t in that list.

**Comment by skovatch** [comment]
Okay, that flag applies just to TV shows.

320k radio streams are downloaded if you have selected "Best" for the audio format. Make sure that isn't selected in the BBC Radio Show Formats part of Download Formats.

**Comment by Necktilt** [comment]
Scott, thanks for the info.

Good: I deleted Best and Very Good from BBC Radio Show Formats, leaving Better, and now I’m getting 128 downloads, as before.

It might be worth telling people that the 1.9.9 version will overwrite the settings in this tab. I didn’t realise until I noticed the size of one of the downloads.

Tony
