### ISSUE TITLE
How to compile and run?

### ISSUE THREAD

**Issue by Mishutochka** [Ascoware/get-iplayer-automator#8]
Ok guys, a complete newbie question, but I think I may not be alone in asking this.

I see 1.9b2 and can download it - but I have no idea how to compile it and run it on Mac OS X. Can someone point me to instructions on how to do it

Sorry :$

**Comment by skovatch** [comment]
You want [this link](https://github.com/Ascoware/get-iplayer-automator/releases/download/1.9b2/Get.iPlayer.Automator.app.zip) It's an archive of the built application.
