### ISSUE TITLE
BBC radio downloads failing in 1.9.10

### ISSUE THREAD

**Issue by prvincent** [Ascoware/get-iplayer-automator#80]
*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*

Attempting to download any BBC radio programme - example: "Andy Hamilton Sort of Remembers: Series 1 - Animals" - results in "Download Failed".

*What is the expected output? What do you see instead?*

Expected it to download and report as "Complete & In iTunes"

*What version of GiA are you using? On what version of OS X?*

Version 1.9.10 on MacOS High Sierra 10.13.1

*Are you using a web proxy? DNS proxy? VPN? VPS?*

No

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *

Andy Hamilton Sort of Remembers: Series 1 - Animals

*Please provide any additional information below.*

The log for an attempted download is below:

[log.txt](https://github.com/Ascoware/get-iplayer-automator/files/1474336/log.txt)

**Comment by skovatch** [comment]
Whoops -- my apologies. I added a newer ffmpeg but didn't realize it was pulling in a bunch of libraries. I'll send out an update later today.

**Comment by skovatch** [comment]
Fixed in 1.9.11
