### ISSUE TITLE
BBC Download Format Error

### ISSUE THREAD

**Issue by G-FOX-A** [Ascoware/get-iplayer-automator#81]
Just to report on the latest update 1.9.10 BBC TV programs are returning 'None of the download formats you specified were available for this show'. Returned to 1.9.9 and all formats are still available. Haven't checked ITV or Radio.
Thanks.

**Comment by skovatch** [comment]
Arrggh. I was afraid this might happen. I don't want to add another preference to force HLS... we need to figure out how to get ffmpeg to properly convert DASH files to mp4 so iTunes can play them.

**Comment by terrytrinder** [comment]
Hi Skovatch
I'm afraid ALL BBC downloads are failing with the latest update. TV programmes get the error "Problem Unknown" and BBC Radio gets "The show already exists in the download directory. If you would like to download it again, delete the file first" - which is nonsense as they are all new (today's programme).
Cheers Terry

**Comment by skovatch** [comment]
I just realized what's going on... this is a variant on #80. ffmpeg is broken, so the download is finishing but isn't being converted.

I'm at work for at least 5 more hours, so I'll publish a release this evening.  Sorry for the inconvenience!

**Comment by terrytrinder** [comment]
Hi Scott

 

Many thanks for the speedy response.

 

Cheers

 

Terry

**Comment by G-FOX-A** [comment]
Thanks for this update. Im sure it may fix the ffmpeg issue. I did look up the current status and noticed a release for late October with some reference to DASH. Perhaps its not very stable yet. The issue I described was that the current 1.9.10 and 1.9.11 is not scraping the full format list anymore. I did find it can see the highest quality version often. I analysed the feeds before downgrading back to 1.9.9. They are all still available in all resolutions and frame rates. I couldn't tell if they were HLS, HDS or DASH so this may be the issue. 

Thanks again for all your hard work.

**Comment by nitramlatep** [comment]
Hi Skovatch. 1.9.9 hung yesterday when downloading HQ Audio. It appears not to receive the right size file and eventually after 10 mins or so bombs out but does complete the download and puts into iTunes. Sound quality appears to be normal quality.
1.9.11 did the same today with Peaky Blinders so I turned off HQ Audio and it worked perfectly.  I assume this is related?

**Comment by skovatch** [comment]
Fixed in 1.9.11. If you see new issues here, please file a new issue.
