### ISSUE TITLE
The League of Gentlemen download fails when subtitles are enabled

### ISSUE THREAD

**Issue by jefro108** [Ascoware/get-iplayer-automator#83]
Gone back to using 1.9.9 as was never having any problems with it - all my downloads were playable.

The League of Gentlemen says it fails to download - this happened for both the episodes on iPlayer at the moment.

The download fails after completing the mp4 download. See [Verbose log](https://gist.github.com/jefro108/7b39e6cd8418960f486241cf0ce607e3) (by the way the link in the instructions for verbose log goes to a wiki article that doesn't exist). It doesn't get far enough in the process to add the metadata and thumbnail - or the subtitles.

Using MacOs Sierra 10.12.6

**Comment by jefro108** [comment]
[bUnknown-ed136775-9869-4750-8c4d-6bf408e49b8a_b09g8plb_1510777075844.xml.txt](https://github.com/Ascoware/get-iplayer-automator/files/1478369/bUnknown-ed136775-9869-4750-8c4d-6bf408e49b8a_b09g8plb_1510777075844.xml.txt)
Actually it appears that the subtitle file is the problem the link to it rendered in Chrome http://vod-sub-uk-live.bbcfmt.hs.llnwd.net/iplayer/subtitles/ng/modav/bUnknown-ed136775-9869-4750-8c4d-6bf408e49b8a_b09g8plb_1510777075844.xml?s=1510808437&e=1510851637&h=8c041a7dba7ea55f5a65ad95181ff6c7 says that 

`This page contains the following errors: error on line 7 at column 32: Char 0x0 out of allowed range` - see attached file - although when I [added it to Gist](https://gist.github.com/jefro108/01391aa6d24e599689e6b3976a45ea43) the bad characters disappeared

**Comment by jefro108** [comment]
More investigation - it appears the 0x0 character ie 00 in hex - see http://www.ltg.ed.ac.uk/~richard/utf-8.cgi?input=00&mode=hex - a NULL character is causing the problem - checking the file with Hex Dump from TextWrangler shows it as a period

**Comment by jefro108** [comment]
Update - it looks like there is an error in only the subtitle file for episode 2 now - I guess it is a BBC glitch but would be good if it could be caught 😊

**Comment by skovatch** [comment]
This is something that get_iplayer would need to address. Plus, the show is long gone, so I don't know if anyone can reproduce it at this point.
