### ISSUE TITLE
Version 1.9 (1841) will not download HD programmes from BBC website

### ISSUE THREAD

**Issue by JeremyCavanagh** [Ascoware/get-iplayer-automator#84]
For a couple of weeks now, whenever I select a programme GIA only downloads dvfxsd format. 

Also, I have looked around all the recent issues and notice that some people have been using version 1.9.10 or 1.9.11 but I cannot find any binary download options on the main website for any version. Is there an alternative site for this or has it been omitted by accident.

Regards

Jeremy Cavanagh

**Comment by hugofalkman** [comment]
https://codeload.github.com/Ascoware/get-iplayer-automator/zip/v1.9.12

**Comment by hugofalkman** [comment]
1.9.12 binary isn't available on GitHub. The binary for 1.9.11 is still pointed to as latest release and is also the release used by the GiA check for update function.

https://github.com/Ascoware/get-iplayer-automator/releases

**Comment by skovatch** [comment]
So, here’s the problem: a week or two ago, I noticed that BBC shows were downloading but weren’t playable on my Apple TV or Mac. I traced this to DVF (DASH) format downloads, so I changed the default BBC formats to force GiP to pick the other format, which still works. After some experiments I found that using some different options with ffmpeg produced an MP4 that played properly, regardless of d/l format, and I published a release (v1.9.12). Shortly afterwards, though, I noticed it took _forever_ to convert HD files, so I un-released it until I found a better solution.

**Comment by JeremyCavanagh** [comment]
Hi,
Thanks for the feedback. I have managed to upgrade to 1.9.11 and everything works fine. I must say that I am very impressed with the HQ sound, I haven't yet run it through my TV yet, but on my MacBook Air, wow what a difference.

Regards

Jeremy Cavanagh
