### ISSUE TITLE
Status 'Available: pre-watershed' download fails

### ISSUE THREAD

**Issue by approtech** [Ascoware/get-iplayer-automator#85]
*What steps will reproduce the problem? Be specific, and provide as much detail as possible.*
Try to download BBC programme 'Permission Impossible: Britain's Planners: Episode 4'

*What is the expected output? What do you see instead?*
Expect download to work, instead see 'Problem Unknown' in failed solutions window.
Status in main window says 'Available: pre-watershed'

*What version of GiA are you using? On what version of OS X?*
GiA v1.9.11, Mac OS 10.12.6

*Are you using a web proxy? DNS proxy? VPN? VPS?*
None

*What program are you attempting to download (full title, series and episode)? **Provide only ONE program as an example.** *
Permission Impossible: Britain's Planners: Episode 4
(all other episodes worked fine)

*Please provide any additional information below.*
Also tried in several earlier versions with the same result.

Log file link:
https://gist.github.com/approtech/8601e3371c41708b4435e75a3cfdd511#file-gistfile1-txt

The problem appears to be that there is no 'original' version, and GiA doesn't recognise a 'Pre-watershed' version.

**Comment by skovatch** [comment]
I think this is a bug in get_iplayer, in that it treats 'default' as a version when it's used by itself. Normally you use 'audiodescribed,default' to tell get_iplayer to prefer audiodescribed versions over 'regular' versions of a show. I'll handle this by not specifying 'default' if preferences indicate you don't want audiodescribed or signed versions.

**Comment by skovatch** [comment]
Fixed in v1.9.13

**Comment by approtech** [comment]
Many thanks for the prompt update, Scott - confirmed working!
