### ISSUE TITLE
Version 1.9.9 (20171029001) still working fine for me.

### ISSUE THREAD

**Issue by jefro108** [Ascoware/get-iplayer-automator#89]
Just wanted to let you know that I've never upgraded to the versions since there appeared to a be a problem playing the mp4 files in Quicktime Player because I didn't have any of the problems others were reporting.

All the files I've downloaded in Version 1.9.9 (20171029001) with **Get higher-quality audio** checked are working fine when I play them in Quicktime Player Version 10.4 (894.12) on macOS 10.12.6. I've not tried downloading with normal audio to see if that changes things. 

I did mention this in a previous comment but no-one responded, so I thought it worth repeating in case it can help a solution that doesn't rely on FFMPEG doing lots of work.

**Comment by raythw** [comment]
Version 1.9.13 is also working superbly, downloading hvfhd, with HQ sound and at 50FPS. Great work by all concerned!
