### ISSUE TITLE
No downloads specified for show (some shows only) 

### ISSUE THREAD

**Issue by ian02054** [Ascoware/get-iplayer-automator#9]
With 1.9b2 (it happened on 1.9b1 also) most shows download fine, but some give the error "None of the download formats you specified were available for the show." 

In the settings, all formats are specified (HD, very high, high, standard, low) and if I use Get_iplayer at the command prompt, the shows record fine with the "-good" format (I didn't try other formats..this is my default)

The show for the test was "Amazing Hotels: Life Beyond the Lobby: Series 1 - 6. ICEHOTEL, Sweden" PID: b08qf7xy
Below is the log file, the screenshot, and the get_iplayer output.

It seems there is a difference in the modes looked for between the two programs, maybe that is an issue ? (maybe it's just the way they are coded !)

**Get_iplayer looks for (and finds):**
hvfxhigh1,hvfxhigh2,hvfxhigh3,dvfxhigh1,dvfxhigh2,hvflow1,hvflow2,hvflow3,dvflow1,dvflow2

**get iplayer autopmator looks for (and fails)**
dvfxsd,dvfxhigh,dvfhd,dvfsd,dvfhigh,dvflow,hvflow,hvfxsd,hvfhigh,hvfsd,hvfxhigh,hvfhd

**get iplayer automator Log:**
BBC Download (ID=b08qf7xy): Downloading Amazing Hotels: Life Beyond the Lobby: Series 1 - ICEHOTEL
INFO: pid found in cache
INFO: 1 Matching Programmes
WARNING: Some recording modes were remapped to new values
WARNING: Input mode list remapped from 'dafhigh,dafstd,daflow,hlsvhigh,hlsstd,hlslow,hlshd,' to 'dafhigh,dafstd,daflow,hlsvhigh,hlsstd,hlsxstd,hlshd,'
WARNING: Please update your preferences
INFO: Checking existence of original version
INFO: No specified modes (dafhigh,dafstd,daflow,hlsvhigh,hlsstd,hlsxstd,hlshd) available for this programme with version 'original'
INFO: Try using --modes=dvfxsd,dvfxhigh,dvfhd,dvfsd,dvfhigh,dvflow,hvflow,hvfxsd,hvfhigh,hvfsd,hvfxhigh,hvfhd
ERROR: Failed to record 'Amazing Hotels: Life Beyond the Lobby: Series 1 - 6. ICEHOTEL, Sweden (b08qf7xy)'
REASON FOR FAILURE: None of the modes in your download format list are available for this self.show.
Try adding more modes.
BBC Download (ID=b08qf7xy): Amazing Hotels: Life Beyond the Lobby: Series 1 - ICEHOTEL Failed
__________________________________________________________
**Get_Iplayer output**:
get_iplayer --mode=good --get pid:b08qf7xy --output "/Users/ianxxx/Movies/TV Shows" --subdir --subdir-format="<nameshort>-<seriesnum>"
get_iplayer 3.00-homebrew.0, Copyright (C) 2008-2010 Phil Lewis
  This program comes with ABSOLUTELY NO WARRANTY; for details use --warranty.
  This is free software, and you are welcome to redistribute it under certain
  conditions; use --conditions for details.

  NOTE: A UK TV licence is required to legally access BBC iPlayer TV content

Matches:
157:	Amazing Hotels: Life Beyond the Lobby: Series 1 - ICEHOTEL, Sweden, BBC Two, b08qf7xy

INFO: 1 Matching Programmes
INFO: Checking existence of original version
INFO: hvfxhigh1,hvfxhigh2,hvfxhigh3,dvfxhigh1,dvfxhigh2,hvflow1,hvflow2,hvflow3,dvflow1,dvflow2 modes will be tried for version original
INFO: Trying hvfxhigh1 mode to record tv: Amazing Hotels: Life Beyond the Lobby: Series 1 - 6. ICEHOTEL, Sweden
INFO: File name prefix = Amazing_Hotels_Life_Beyond_the_Lobby_Series_1_-_6._ICEHOTEL_Sweden_b08qf7xy_original                
INFO: Begin recording file: /Users/ianxxx/Movies/TV Shows/Amazing_Hotels_Life_Beyond_the_Lobby-1/Amazing_Hotels_Life_Beyond_the_Lobby_Series_1_-_6._ICEHOTEL_Sweden_b08qf7xy_original.video.ts
INFO: Begin recording at: 0.00 MiB (00:00:00) [1]
INFO: Recorded: 130.71 MiB (00:19:04) [149] in 00:05:49 at 3.00 Mibit/s
**<note, get_iplayer continued and finished but i only copied log to this point 50% through)**

**get_iplayer automator screenshot**
![image](https://cloud.githubusercontent.com/assets/17240550/25851233/fcd93616-3492-11e7-8a0b-3db255aa2430.png)

**Comment by nitramlatep** [comment]
I have exactly the same issue.  Tried removing the formats and rein putting but made no difference.

**Comment by SwaleSwimmer** [comment]
I'm having exactly the same problem with both builds. I was attempting Amazing Hotels as well. I haven't tried downloading anything else since but I hope there is a workaround this. Otherwise delighted to have GIA again. With thanks.

**Comment by skovatch** [comment]
As a first step, I'd try moving aside "~/Library/Application Support/Get iPlayer Automator" and relaunching. I did make some changes for the new format options, and I thought I got them all, but I'll check again.

**Comment by nitramlatep** [comment]
I have been running Get iPlayer Automator fresh each time I start and thus do not even have the folder in the Application Support folder and I have the same problem still happening with certain programmes.

**Comment by Sircam19** [comment]
Hello I had the same same exact problem and opened it as a new issue 2 days back. I then closed the issue as I tried something that actually resolved it. 

At the time of this issue.... I inadvertently had both a VPN and Smart DNS running "on top of each other" Once I turned of the VPN and relied upon the Smart DNS, it magically got resolved. I purely mention this to be of assistance. I wonder if this is a connectivity issue relating to VPN etc.

**Comment by jw00d** [comment]
Hi,
Firstly thanks for your work resurrecting Gia.
I had the same issue trying to download a 6Music radio show. I saw the above comment and tried disconnecting my Vpn and it worked first time. Even though it was supposedly connected through a UK ip it kept throwing up this no formats error.

**Comment by skovatch** [comment]
I'm going to close this, because it appears to have been BBC taking their time posting it. I'm in the process of downloading it right now.
