### ISSUE TITLE
Add more columns (date & time, pid) to search results?

### ISSUE THREAD

**Issue by gingerbeardman** [Ascoware/get-iplayer-automator#90]
Currently there's no way to easily find, say, today's episode of a certain radio programme.

In fact today's episode was 2/3 of the way down the search results.

Ordering them most recent first would also be useful.

<img width="625" alt="screen shot 2017-11-28 at 17 50 33" src="https://user-images.githubusercontent.com/49612/33335384-d8cdbd24-d464-11e7-852f-f87666f7f363.png">

**Comment by skovatch** [comment]
Done in 1.10.0, though I don't recall now if newest first is the default.
