### ISSUE TITLE
Add meta data to file so that date/time, etc are encoded in the file

### ISSUE THREAD

**Issue by gingerbeardman** [Ascoware/get-iplayer-automator#91]
[jDownloader](http://jdownloader.org) does this if I use that to download a radio programme.

Also see: https://github.com/Ascoware/get-iplayer-automator/issues/90

**Comment by skovatch** [comment]
I'm not sure what you are asking for here. Do you want get_iplayer to add the date/time to the metadata? I see get_iplayer does that already via the --year option in AtomicParsley.

**Comment by gingerbeardman** [comment]
time, date, programme name, description, image from BBC

I can upload a sample of the same programme from Get iPlayer Automator and jDownloader?

**Comment by skovatch** [comment]
What are you using to verify it? iTunes? Something else?

With a verbose log, I see this:
```
INFO: Command: "/Applications/Get iPlayer Automator.app/Contents/MacOS/AtomicParsley" "/Users/skovatch/Movies/TV Shows/Just a Minute Series 80/Just a Minute Series 80 - 6. Episode 6 ((dafhigh)).m4a" "--freefree" "--overWrite" "--stik" "Normal" "--advisory" "remove" "--copyright" "2018 British Broadcasting Corporation, all rights reserved" "--title" "Episode 6" "--artist" "BBC Radio 4" "--albumArtist" "BBC Radio" "--album" "Just a Minute: Series 80" "--grouping" "Games & Quizzes,Comedy" "--composer" "BBC iPlayer" "--genre" "Games & Quizzes" "--comment" "Nicholas Parsons chairs, with Stephen Fry, Jan Ravens, Gyles Brandreth and Paul Merton." "--year" "2018-03-26T18:30:00+01:00" "--tracknum" "6" "--disk" "80" "--lyrics" "Nicholas Parsons invites Stephen Fry, Jan Ravens, Gyles Brandreth and Paul Merton to speak for 60 seconds on the subjects like Elephants and Office Politics.
```

**Comment by gingerbeardman** [comment]
I'm using Quick Look on macOS (it's a quick file preview mechanism)

I can't take screenshots right now but it was for a radio programme. I used jDownloader whilst GiA was out of action a while back, and jDownloader (at least at that time) provided a thumbnail image and description data in the audio file.

**Comment by skovatch** [comment]
Left is jDownloader 2.0, right is GiA 1.13, with tagging enabled. 
<img width="564" alt="jdownloader_get_iplayer" src="https://user-images.githubusercontent.com/329836/38166873-dde162c6-34df-11e8-94f8-e7de34b4db9c.png">

**Comment by gingerbeardman** [comment]
Oops, I did not have tagging enabled! (sorry)

:)
