### ISSUE TITLE
Unable to download ITV programme The Widower without crashing immediately

### ISSUE THREAD

**Issue by jefro108** [Ascoware/get-iplayer-automator#94]
I get a crash report from MacOS when Get iPlayer Automator crashes immediately on trying to download 'The Widower - Tues Dec 12'

Admittedly still using Version 1.9.9 (20171029001 as that wasn't causing any of the download problems for me.

See https://gist.github.com/jefro108/f24129df419570af6d44c2804d7e64f6

**Comment by jefro108** [comment]
After updating to the app doesn't crash any more trying to download what turns out to be The Widower Series 1 Episode 2 I get the following in the log:

```
Downloading Show 1/1:

ITV Download (ID=2/1391/0003#001): Downloading The Widower - Tue Dec 12
INFO: Preparing Request for Auth Info
INFO: Requesting Metadata.
ITV Download (ID=2/1391/0003#001): ERROR: None of the modes in your download format list are available for this show. Try adding more modes if possible.
AppController: Downloads Finished
/Applications/Get iPlayer Automator.app/Contents/Resources/get_iplayer
--nocopyright
-e60480000000000000
--type=tv,itv,radio
--listformat=SearchResult|<pid>|<timeadded>|<type>|<name>|<episode>|<channel>|<seriesnum>|<episodenum>|<desc>|<thumbnail>|<web>
--long
--nopurge
--search
widower
--profile-dir=/Users/upekshapriya/Library/Application Support/Get iPlayer Automator
--hide
```
Is this an issue on ITV's end?

**Comment by skovatch** [comment]
Yeah, this was happening for me, too. COuldn't find anything downloadable.

**Comment by hugofalkman** [comment]
Grantchester S1E2 has the same behavior:

ITV Download (ID=2/2958/0002#001): Downloading Grantchester - Series 1 - Episode 2 - 2/2958/0002#001
INFO: Preparing Request for Auth Info
DEBUG: Metadata URL: http://mercury.itv.com/PlaylistService.svc
INFO: Requesting Metadata.
DEBUG: Metadata response status code: 200
DEBUG: Metadata response: <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><GetPlaylistResponse xmlns="http://tempuri.org/"><GetPlaylistResult><Fault xmlns=""><faultcode>InvalidEntity</faultcode><faultstring>Video production has no renditions for DotCom platform.</faultstring></Fault></GetPlaylistResult></GetPlaylistResponse></s:Body></s:Envelope>
DEBUG: Metadata processed: seriesName=(null) dateString=(null) episodeName=(No Episode Name) episodeNumber=2 self.thumbnailURL=(null) subtitleURL=(null) authURL=(null)
DEBUG: Retrieving Playpath
DEBUG: Parsing MediaFile entries
DEBUG: Searching for itvRate match
DEBUG: Searching for bitrate match
ITV Download (ID=2/2958/0002#001): ERROR: None of the modes in your download format list are available for this show. Try adding more modes if possible.
AppController: Downloads Finished

**Comment by lucandemense** [comment]
cannot download any programmes from itvhub.Is this an issue with ITVhub ?

**Comment by skovatch** [comment]
Closing this, as I think the crash has been fixed. The "ERROR: None of the modes..." problem is documented elsewhere.
