### ISSUE TITLE
Blocked Access

### ISSUE THREAD

**Issue by Hottsy-Tottsy** [Ascoware/get-iplayer-automator#99]
I've been getting "Failed:  Blocked Access" error for the past 2 days with BBC downloads.  VPN is working fine.  IP leak check shows it's working. 

The log states below:
Get iPlayer Automator 1.9.13 Initialized.
GetITVShows: ITV Cache Update Starting 
AppController: Updating Programme Index Feeds...

INFO: Indexing tv programmes (concurrent)
GetITVShows (Info): Merge complete B/F Programmes: 1145 C/F Programmes: 1067 Today Programmes: 211 
GetITVShows: Update Finished
INFO: Added 144 tv programmes to cache
AppController: Index Updated.

INFO: Loading proxy settings...
INFO: No proxy to load
INFO: Proxy load complete.
INFO: No proxy will be used
AppController: Starting Downloads

Downloading Show 1/6:

BBC Download (ID=b09ms7g0): Downloading Antiques Road Trip: Series 16 - Episode 10
INFO: 1 matching programmes
WARNING: No media streams found for requested programme versions and recording modes.
WARNING: The BBC has blocked access to this programme because it has determined that you are using get_iplayer outside the UK.
BBC Download (ID=b09ms7g0): Antiques Road Trip: Series 16 - Episode 10 Failed

Downloading Show 2/6:

BBC Download (ID=b09m6320): Downloading The Graham Norton Show: Series 22 - Episode 13
INFO: 1 matching programmes
WARNING: No media streams found for requested programme versions and recording modes.
WARNING: The BBC has blocked access to this programme because it has determined that you are using get_iplayer outside the UK.
BBC Download (ID=b09m6320): The Graham Norton Show: Series 22 - Episode 13 Failed

Downloading Show 3/6:

BBC Download (ID=b09m0xvw): Downloading Father Brown: Series 6 - The Two Deaths of Hercule Flambeau
INFO: 1 matching programmes

**Comment by Themanwithoutaplan** [comment]
As the error message says, the BBC, as do other providers, try and block VPNs which are being used to circumvent geo-blocking. This has nothing to do with `get_iplayer`.

**Comment by hugofalkman** [comment]
https://www.fastestvpnguide.com/workaround-for-bbc-iplayer-vpn-not-working/

see discussion about blacklisting VPN IP-addresses in issue #54

**Comment by skovatch** [comment]
Shutting this down. Consistent with get_iplayer, I can't help you sort out VPN issues if you are outside the USA. Sorry.
